[STEP2] 로또(자동)
next-step/kotlin-lotto pull request #1009
Opened 2024-11-20 05:28 UTC by JwahoonKim

step2 로또 자동 구현 리뷰 요청드립니다.

step1에서 리뷰해주셨던 부분 반영하여 같이 PR 올립니다. 

감사합니다!

2024-11-20 13:28 UTC, pci2676 requested changes
조금 더 개선해볼만한 부분에 코멘트를 남겨두었으니 개선한 뒤 다시 요청 부탁드리겠습니다. 😄

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/calulator/Numbers.kt
> +            throw RuntimeException("음수는 입력할 수 없습니다.")
조금 더 명확히 하려면 numbers를 메세지에 담거나

문제가 된 음수를 메세지에 담아주면 좋을것 같습니다 😄

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/calulator/delimiterParser/CustomDelimiterStrategy.kt
> +        val matchResult = Regex("//(.)\n(.*)").find(text)
Regex는 내부적으로 compile하는 작업이 있는것으로 알고 있는데요. 해당 작업의 비용이 조금 있는것으로 알고 있습니다.

그래서 한번만 선언해두고 재사용하는것이 더 나을수 있으니 참고해주세요~

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/calulator/delimiterParser/DefaultDelimiterStrategy.kt
> +class DefaultDelimiterStrategy : DelimiterStrategy {
👍

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/calulator/delimiterParser/DelimiterStrategy.kt
> +interface DelimiterStrategy {
👍 👍

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/LottoMain.kt
> +    }
InputView와 ResultView가 입/출력에 대한 역할과 책임을 가지고 있다면

main 로직은 어떠한 역할을 가지고 있나요?

이러한 for-loop가 main에 구현되어야만 할까요??

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/LottoMain.kt
> +    val lottoList = mutableListOf<List<Int>>()
collection의 원소로 collection을 가지고 있는것은 코드를 읽을때 부담이될 수 있습니다.

일급컬렉션이라는 개념을 활용해보시면 좋을것 같습니다. 😄

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/LottoMain.kt
> +    for (i in 1..purchaseAmount / 1000) {
상수로 표현해볼만한 값들이 보이는것 같군요 🤔

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/LottoMain.kt
> +    )
정적 메서드를 사용하지 않고 객체들의 상호작용을 통해 값을 구해보면 좋을것 같습니다!

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoResultAnalyzer.kt
> +    )
Lotto의 일치 할 수 있는 번호가 6개라서 이정도인데

100개 1000개 10000개의 숫자가 있을때도 이렇게 멤버변수를 늘려가며 해결할 수 있을까요?

다른 자료형을 고려해보시면 좋을것 같습니다 😄

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/view/ResultView.kt
> +        println("6개 일치 (2000000000원)- ${lottoResult.firstCount}개")
이러한 값들은 로또 애플리케이션의 '정책'으로 보입니다.

그리고 view에서 이러한 정책을 하드코딩해서 관리하게되는것 같습니다.

view는 변경에 잦은편인데 정책을 이곳에서 관리하지 않고 다른 객체에게 넘겨보는것은 어떨까요?

2024-11-20 13:28 UTC, pci2676 commented on src/main/kotlin/lotto/view/ResultView.kt
> +        val isProfitable = rateOfReturn > 1.0
이곳 또한 마찬가지 입니다.

2024-11-20 13:28 UTC, pci2676 commented on src/test/kotlin/lotto/domain/LottoResultAnalyzerTest.kt
> +    }
테스트를 꼼꼼히 작성해주셨네요~ 👍 

다만 비슷한 테스트들이 많이 보이는 것 같습니다.

이러한 테스트들을 하나의 테스트로 묶어서 관리해보면 어떨까요?

중복되는 부분이 많아 하나의 테스트로 표현해볼 수 있을것 같습니다.

Junit의 ParameteriezedTest를 참고해보시면 좋을것 같습니다. 😄

2024-11-20 13:28 UTC, pci2676 commented on src/test/kotlin/lotto/domain/LottoResultAnalyzerTest.kt
> +            listOf(1, 2, 3, 4, 5, 6),
Int로 관리하고 있어 로또 번호가 1~45가 아닌 다른숫자가 들어가도 애플리케이션이 동작하는데 문제가 없을것 같습니다.

정책에 대해 모르는 사람이 엉뚱한 값을 넣으면 엉뚱한 기능을 하는 개발이 가능하다는 것과 같아보이는데 이를 방어해줄수 있는 '값 객체'를 만들어 보면 어떨까요?

2024-11-20 16:18 UTC, pci2676 approved these changes
조금 더 개선할 수 있는 부분에 comment를 남겨두었으니

꼭 확인해서 다음 단계 진행전에 먼저 commit으로 먼저 남겨주세요.

미션 진행을 위해 merge하겠습니다~ 🚀

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
view 로직이 domain의 책임으로 볼 수 있을까요?

지금은 console 형태의 view만 있지만 web이나 다른 형태의 view가 추가된다면 toString을 계속해서 사용할 수 있을까요?

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +            else -> LottoRank.NONE
LottoRank에게 의미있는 값을 부여되어 있는데요.

LottoRank로 부터 위와 같은 로직을 녹여내볼수 있지 않을까요?

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +            .let { Lotto(it) }
generate를 할때마다 새로운 Lotto를 생성해야하는것으로 보이는데요.

Lotto객체를 계속해서 새롭게 만들어야 할 필요가 있을까요? 🤔

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        require(value in 1..45) { "로또 번호는 1부터 45 사이여야 합니다." }
메세지에는 원인이 된 값을 함께 넘겨주는것도 좋을것 같습니다. 😄

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +enum class LottoRank(val matchCount: Int?, val winningMoney: Int) {
👍

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoResults.kt
> +    fun isProfitable(): Boolean {
이 메서드는 상태를 나타내나요 행동을 나타내나요?

그에 따라 fun과 val을 적절히 구분지어 사용해보시는것을 권장드립니다. 😄 

이 메서드를 비롯해 다른 부분들도 함께 봐주세요~

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/service/LottoService.kt
> +        val buyingLottoQuantity = purchaseAmount / LOTTO_COST
이 부분과 LOTTO_COST를 하나의 객체에서 표현해보는것도 좋은 시도가 될 수 있을것 같습니다.

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/controller/LottoController.kt
> +}
꼭 반영하실 필요는 없는데요~

지금은 service의 단편적 기능만 테스트가 가능한 구조로 보이는데요~

더 나아가서 전체적인 비즈니스 흐름을 테스트할 수 있는 구조도 한번 고민해보시면 좋을것 같습니다. 😄

2024-11-20 16:18 UTC, pci2676 commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +        assertThat(lotto.match(winningLotto3)).isEqualTo(LottoRank.THIRD)
하나의 테스트 메서드에는 하나의 케이스만 존재하는것이 좋습니다.

지금은 여러 케이스가 하나의 메서드에서 검증이 되고 있는것 같습니다.

[이전에 드린 코멘트](https://github.com/next-step/kotlin-lotto/pull/1009#discussion_r1850315134)를 참고하시어 꼭 개선해주세요.

2024-11-20 16:18 UTC, pci2676 commented on src/main/kotlin/lotto/service/LottoService.kt
> +class LottoService {
service에 대한 테스트 코드가 없네요!

반드시 테스트 코드를 추가해주세요.

2024-11-20 16:18 UTC, merged

2024-11-21 01:18 UTC, JwahoonKim commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +        assertThat(lotto.match(winningLotto3)).isEqualTo(LottoRank.THIRD)
```
@ParameterizedTest
    @CsvSource(
        "1,2,3,4,5,6:FIRST",
        "1,2,3,4,5,7:SECOND",
        "1,2,3,4,8,9:THIRD",
        "1,2,3,10,11,12:FOURTH",
        "7,8,9,10,11,12:NONE",
        delimiter = ':'
    )
    fun `match 메서드는 일치하는 번호 개수에 따라 적절한 LottoRank를 반환한다`(
        winningNumbers: String,
        expectedRank: LottoRank
    ) {
        val lotto = Lotto(
            listOf(
                LottoNumber(1),
                LottoNumber(2),
                LottoNumber(3),
                LottoNumber(4),
                LottoNumber(5),
                LottoNumber(6)
            )
        )

        val winningLotto = Lotto(
            winningNumbers.split(",").map { LottoNumber(it.toInt()) }
        )

        assertThat(lotto.match(winningLotto)).isEqualTo(expectedRank)
    }

```

이런식으로 변경해보았는데 이렇게 작성하고 나니 이전 버전에 비해 테스트 코드에 로직이 들어가게 되었습니다.(winningLotto를 map, split으로 만드는 과정) 이전 버전의 경우 그냥 flat 하게 써져있어서 코드를 바로 이해할 수 있는 구조였는데 
 parameterizedTest를 하니 코드는 짧아졌어도 좀 더 복잡하게 느껴질 수도 있나? 라는 생각이 드는 것 같아요. 하나의 테스트 메서드에서는 하나의 케이스만 존재하는 것이 좋다고 말씀해주셨는데 parameterizedTest도 사실 여러개의 케이스를 테스트하는 경우가 아닌가? 라는 생각이 들기도 하고.. 🤔 어떤 방식이 더 좋은지 고민이 되는 것 같은데 어떻게 생각하실까요? 애초에 뭔가 구조가 잘못되어서 테스트가 이쁘게 안나오는 걸까요?

2024-11-21 01:20 UTC, JwahoonKim commented on src/main/kotlin/lotto/controller/LottoController.kt
> +}
요 부분 제가 이해를 잘 못했는데 조금만 더 설명해주실 수 있으실까요?

controller의 main의 전체적인 흐름을 테스트할 수 있는 구조가 뭔지 감이 잘 안오는 것 같습니다. 그리고 현재 상황이 service의 단편적 기능만 테스트 가능한 구조로 보인다는 것도 왜 그런지 잘 이해를 못했습니다ㅠㅠ

input, output을 받는 쪽을 interface로 만들고 테스트에서 테스트용 구현체를 만드는 방식을 말씀해주신걸까요?

2024-11-21 01:23 UTC, JwahoonKim commented on src/main/kotlin/lotto/service/LottoService.kt
> +        val buyingLottoQuantity = purchaseAmount / LOTTO_COST
요 부분 감을 잘 못잡았는데..

```
object LottoCost {
    const val COST = 1000

    fun calculateQuantity(purchaseAmount: Int): Int {
        return purchaseAmount / COST
    }
}

// 사용 예
val buyingLottoQuantity = LottoCost.calculateQuantity(purchaseAmount)

```

요런 느낌을 말씀해주신게 맞으실까요?

2024-11-21 01:28 UTC, JwahoonKim commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +            .let { Lotto(it) }
헛 요거는 Lotto 객체를 계속 만들어야한다고 생각하는데 캐싱하는 방법이 있을까요? 로또 경우의 수가 많아서 그건 안될 것 같고.. 혹시 어떤 부분 좀 더 고민하면 될지 힌트주실 수 있으실까요?

Lotto는 LottoNumber를 새로 만드는 것처럼 매번 만들어야한다고 생각했습니다! 아니면 LottoNumber를 캐싱하는걸 말씀해주신건가요?

2024-11-21 07:17 UTC, pci2676 commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +            .let { Lotto(it) }
아 제가 잘못 적어두었네요 LottoNumber를 말슴드린것이었습니다~ 😅

2024-11-21 07:18 UTC, pci2676 commented on src/main/kotlin/lotto/service/LottoService.kt
> +        val buyingLottoQuantity = purchaseAmount / LOTTO_COST
"로또를 구매하려는 돈" 을 나타낸 객체를 생각해볼 수 있을것 같습니다.

```kotlin
val lottoMonery = LottoMoney(2300)
val count = lottoMoney.caculateQuantity()
```

2024-11-21 07:21 UTC, pci2676 commented on src/main/kotlin/lotto/controller/LottoController.kt
> +}
비즈니스의 "요구사항은 돈을 입력하면 로또가 사지고 당첨금액을 알 수 있다" 라는 일련의 흐름인데요

이 일련의 흐름을 한번에 테스트할 수 있으면 좋을것 같은 의미였습니다. 

지금은 service를 순차적으로 호출하는 형태이기에 테스트하기 쉽지 않은 모양새로 보이네요.

아래와 같은 형태면 좀 더 큰 범위의 테스트가 가능하지 않을까요?

```kotlin
fun main() {
  LottoApplication(InputView(), OutputView()).run()
}

2024-11-21 07:26 UTC, pci2676 commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +        assertThat(lotto.match(winningLotto3)).isEqualTo(LottoRank.THIRD)
> 이런식으로 변경해보았는데 이렇게 작성하고 나니 이전 버전에 비해 테스트 코드에 로직이 들어가게 되었습니다.(winningLotto를 map, split으로 만드는 과정)

이러한 과정이 테스트에서 수반되어야 한다는것은 어쩌면 테스트하기에 좋은 구조가 아닐지도 모른다는 신호로 볼 수 도 있습니다~!

> parameterizedTest를 하니 코드는 짧아졌어도 좀 더 복잡하게 느껴질 수도 있나? 라는 생각이 드는 것 같아요.

오 날카롭고 좋은 생각이네요~!

그러한 경우가 있습니다! 그래서 언제나 위와 같은 테스트가 좋은것은 아닙니다.

오히려 가독성이 떨어진다고 판단되는 경우에는 별개의 테스트 메서드로 구분짓는것이 나을때도 있습니다.

>하나의 케이스만 존재하는 것이 좋다고 말씀해주셨는데 parameterizedTest도 사실 여러개의 케이스를 테스트하는 경우가 아닌가? 라는 생각이 들기도 하고.. 🤔

이전 케이스들은 사실 입력값과 검증값만 다르지 검증하고자 하는 행위는 모두 같은것이지 않았나 싶습니다.

행위는 같은데 입력 출력이 다른 경우에 대해 테스트한다면 하나의 테스트로 묶어서 테스트하는것이 더 낫지 않을까요?

테스트를 하고자 하는 대상이, 기능이 무엇인지에 초점을 둔다면 지금의 경우에는 저는 하나로 묶는것이 더 좋다고 생각하는 편 입니다. 😄