feat: 문자열 덧셈 계산기 개발
next-step/kotlin-lotto pull request #1017
Opened 2024-11-21 05:19 UTC by ddoriya-dev

문자열 덧셈 계산기 개발 구현 진행하였습니다~

2024-11-21 14:52 UTC, Wordbe requested changes
상준님 안녕하세요 😀
두번째 미션에 벌써오셨네요. 앞으로 잘부탁드리고
리뷰 확인 부탁드립니다!

2024-11-21 14:52 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        }
좀 극단적이긴한데, 여기 depth 가 2인 것 같아 README에 적어주신 프로그래밍 요구사항에 맞지 않네요 😀😮

2024-11-21 14:52 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        return Expression("[,:]", text)
regex 처음보는 개발자도 알기쉽도록 이런 문자열을 상수로 만들고 명명해보면 어떨까요?

2024-11-21 14:52 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        val tokens = expression.numberText.split(expression.delimiter.toRegex())
이것을 뭔가 Expression 객체가 할 수도 있을 것 같다는 생각이드네요 🧐

2024-11-21 14:52 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        if (text.isNullOrEmpty()) return 0
코틀린이 제공하는 require 등을 써보시는게 어떠신가요?

2024-11-22 00:56 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        if (text.isNullOrEmpty()) return 0
안녕하세요~ 
혹시 require 를 사용하면 예외가 발생해서 return 0 조건이 될까요?

2024-11-22 00:58 UTC, ddoriya-dev reviewed
안녕하세요~
부족한 부분이 많지만 잘 부탁드립니다~

2024-11-22 00:58 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        val tokens = expression.numberText.split(expression.delimiter.toRegex())
잠시 고민해봤는데 해당 부분으로 뺴는게 더 코드가 좋아 보이겠군요!

2024-11-22 00:58 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        }
네네 ㅠㅠ 어떻게 예외를 뺄지 또 loop를 돌리고싶지않아.. 고민이였습니다

2024-11-22 00:58 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        return Expression("[,:]", text)
네~ 상수로 빼는 부분이 더 좋겠네요!

2024-11-22 15:07 UTC, Wordbe requested changes
리뷰 한번 반영해주세요! 🙇

2024-11-22 15:07 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        if (text.isNullOrEmpty()) return 0
아아~ return 0 이었군요. 잘못 생각했었어요 제가..! 무시해주기 바랍니다 😊

2024-11-22 15:07 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        }
그래도 한번 해보시죠 depth 1로! 
여기서 require 을 사용하면 될것같아요 :)

2024-11-22 16:15 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        }
넵 수정진행해서 올려드렸어요~

2024-11-22 16:15 UTC, ddoriya-dev commented
혹시 어떤걸 반영하면 될까요~?

2024-11-23 13:43 UTC, Wordbe approved these changes
코멘트 드린 부분은 옵션이라, 다음 스텝에 반영해주셔도 됩니다.
머지하고 다음 스텝으로 가시죠! 😀

2024-11-23 13:43 UTC, Wordbe commented on src/main/kotlin/study/calculator/StringAddCalculator.kt
> +        }
아 이부분을 코틀린 예외처리 스럽게 하면 어떨가 제안드렸어요!

2024-11-23 13:43 UTC, merged