[Step1] 문자열 계산기 구현
next-step/kotlin-lotto pull request #1019
Opened 2024-11-21 10:57 UTC by Seokho-Ham

안녕하세요 리뷰어님! 
이번에 로또 미션에 대해 리뷰를 받게 된 함석호입니다! 잘부탁드립니다:)

2024-11-21 18:10 UTC, namjackson requested changes
안녕하세요 함석호님! 
로또 미션을 함께하게된 조남재라고 합니다! 
잘부탁드립니다 :)
미션을 잘구현해주셨지만 몇가지 고민할법한 코멘트 남겼으니, 확인해주세요 :)

2024-11-21 18:10 UTC, namjackson commented on README.md
> +  - [ ] 숫자 이외의 값 혹은 음수를 전달할 경우 런타임 예외를 반환한다.
완성된 기능은 체크 표시해보면 어떨까요 :)

2024-11-21 18:10 UTC, namjackson commented on src/main/kotlin/stringcalculator/StringCalculator.kt
> +class StringCalculator {
StringCalculator 클래스의 책임이 너무 많은건 아닐까요?
Separator를 분리하는 작업과 계산로직에 대한 책임을 분리해보면 어떨까요?

2024-11-21 18:10 UTC, namjackson commented on src/main/kotlin/stringcalculator/StringCalculator.kt
> +            ?: throw RuntimeException()
어떤 에러를 던지는지 메세지를 포함하면 디버깅할때 도움이 될거같네요!

2024-11-21 18:10 UTC, namjackson commented on src/main/kotlin/stringcalculator/StringCalculator.kt
> +                token.toIntOrNull()?.takeIf { it >= 0 } ?: throw RuntimeException()
0보다 큰수에 대한 책임도 분리해볼수 있을거 같아요!

2024-11-21 18:10 UTC, namjackson commented on src/test/kotlin/stringcalculator/StringCalculatorTest.kt
> +class StringCalculatorTest : StringSpec({
테스트 코드를 잘 작성해주셨네요! 
현재 테스트 베이스에서, 
추가로 책임을 분리하는 리팩터링을 진행해보면 어떨까요? :)

2024-11-22 05:27 UTC, Seokho-Ham commented on README.md
> +  - [ ] 숫자 이외의 값 혹은 음수를 전달할 경우 런타임 예외를 반환한다.
앗 이부분은 제가 놓쳤네요! 수정해두겠습니다!

2024-11-22 06:30 UTC, Seokho-Ham commented
말씀해주신 내용들 바탕으로 개선하였습니다!

- `StringCalculator` 클래스는 계산의 역할만 담당하도록 수정하였습니다.
- 구분자로 분리하는 역할은 `TokenSplitter`라는 클래스로 분리하였습니다.

2024-11-22 13:04 UTC, namjackson approved these changes
안녕하세요 석호님! 
피드백 적용 잘해주셨네요!  👍 
이제 본격적으로 로또 미션 진행해주시면 좋을거 같아요 !

2024-11-22 13:04 UTC, namjackson commented on src/main/kotlin/stringcalculator/StringCalculator.kt
> +    private fun isPositiveInt(it: Int) = it >= 0
원시값을 포장한다면 0보다 큰수를 검증하는 책임 또한 분리할수 있을거 같아요 :)

2024-11-22 13:04 UTC, namjackson commented on src/test/kotlin/stringcalculator/StringCalculatorTest.kt
> +class StringCalculatorTest : StringSpec({
StringCalculatorTest 테스트 케이스들이 작성되어있어서 
리팩터링 과정에서 안정성을 유지할수 있었을거 같아요 👍

2024-11-22 13:04 UTC, namjackson commented on src/test/kotlin/stringcalculator/TokenSplitterTest.kt
> +class TokenSplitterTest : StringSpec({
StringCalculatorTest 와 중복된 테스트 라고 느껴질수 있지만,
조금 더 독립적인 테스트를 작성해주셔서, 더 안정성있는 코드가 되었네요 👍

2024-11-22 13:04 UTC, merged