2단계 - 로또(자동)
next-step/kotlin-lotto pull request #1035
Opened 2024-11-22 10:25 UTC by giwankim

이전 단계에서 리뷰해 주신 부분을 반영하고 자동 로또 게임을 MVC 패턴으로 구현해봤습니다.

앞으로 두 단계가 남아 있는 것을 감안하여 책임 분리와 확장성을 확보하기 위해 노력했습니다.

프로그래밍 요구 사항에

> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.

라고 하는데 조금 찜찜한 부분이 있습니다. 여기서 TDD라고 하면 켄트 벡 [정석 TDD](https://tidyfirst.substack.com/p/canon-tdd)를 명시하는 것 같은데, 개인적으로 연습용 kata에서도 정석 TDD로 구현하는 것이 어색한 것 같습니다. catsbi 님은 실무에서 테스트 코드/구현을 어떻게 하시는지 여쭤보고 싶습니다.

개인적으로 테스트 코드 작성을 매우 중요시하기는 하지만, 아무 설계 없이 순수하게 TDD로 구조를 찾아가는 과정에 대해서는 의문이 생깁니다. 저는 일반적으로 클래스의 속성이나 어떤 클래스들이 필요할지 정도는 클래스 다이어그램이나 main에 테스트 코드 없이 구현하다가 비즈니스 로직을 작성해야 하면 그때부터 TDD로 전환하는 편입니다.

컨설턴트분이 정석 TDD 를 구현하면서 "자연스럽게" MVC 패턴을 재발견하는 일종의 공연도 본 적이 있고, 요구 사항이나 유즈케이스부터 순차적으로 구조를 만들어가는 outside-in 방식도 있는 것으로 알고 있습니다 (몇 달 전에 catsbi 님이 ATDD 강의 미션 리뷰어였습니다 😄).

LottoService는 LottoLineGenerator 컴포넌트에 의존성을 갖고 있어서 단위 테스트를 위해 mock이나 fake를 사용할지 잠시 고민하다가 별 문제 없을 것 같아 그냥 통으로 SpringBootTest라는 느낌으로 테스트를 작성했습니다.

2024-11-23 10:20 UTC, catsbi requested changes
지완님, 2단계 미션도 잘 진행해주셨습니다 👍 
몇 가지 추가 피드백 남겨드렸으니 확인 해주시면 좋을 것 같구요! 

질문 주신부분 중 TDD에 대해 말씀 주셨는데, 지완님이 말씀해주신 방법들 중 클래스 다이어그램이나 테스트 케이스를 추리는건 개발시작 전 요구사항 분석및 설계에 해당될 수 있기에 이것들을 먼저하는건 상관이 없을 것 같아요. 

그리고, 지완님이 말씀해주신 방법이 top-down방식의 TDD인데, 어찌되었든 테스트를 작성한다는 측면에서는 안하는 것 보다는 낫다고 생각하고 결과론적으로는 테스트가 다 작성되었으니 같을수도 있습니다. 

다만, 해당 과정은 TDD '학습' 과정이니만큼 정석대로 해보는것을 권장드려요. 
저는 기본적으로 알고 있고, 할 줄 알지만 트레이드오프를 계산해 더 적절한 방식을 선택하는 것과 할 줄 모르지만 다른 방식도 있다고 했으니 다른 방식을 선택하는 것에는 차이가 있다고 생각하거든요. 

그리고 실무에서 테스트가 아닌 기능 작성 이후 테스트를 작성하다보면, 지금 이미 잘 돌아가고 QA검증도 통과하는데 테스트를 작성하기엔 시간이 아깝다는 생각과 다음 기능 개발하기에 벅차다는 느낌을 받고 테스트 작성이 스킵되는 경우가 상당히 잦습니다. 

그렇기에 차후 실무에서는 top-down방식이나 다른 방식을 사용하더라도 학습과정내에서는 bottom-up도 시도해보면 어떨까 하네요 ㅎㅎ

SpringBootTest 애노테이션은 전체 컴포넌트 스캔을 해버리기 때문에, 테스트 규모가 작을 수록 불필요한 스캐닝 비용이 소비될 수 있기에 여유가된다면 이 부분도 리팩터링 고려해보면 좋을 것 같네요. 

그럼 리뷰 확인 후 다시 리뷰요청 부탁드립니다!

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/application/LottoService.kt
> +) {
객체구조가 서비스 계층에 맞게 적절한 의존성 주입만 되고 상태를 갖지 않는 상태로 잘 설계된 것 같네요 👍

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/application/LottoService.kt
> +    }
코틀린에서는 행위에 대해 표현식(Expression)과 문(Statement)로 표현을 할 수 있습니다. 
사용하는 측면에선 모두 동일한 것 같지만, 지완님이 함수를 식으로 혹은 문으로 작성하는 선택의 기준이 있으실까요? 

코틀린은 표현식 지향적 특성을 가지고 있어 간단한 로직의 경우 표현식을 권장하는 편입니다. 
다만, 같은 혹은 비슷한 행위들에 대해 언제는 식, 언제는 문으로 표현된다면 가독성이 오히려 떨어지지 않을까? 라는 생각으로 팀내에서도 컨벤션 회의때 많은 얘기가 나오기도 했는데요. 저는 지금은 간단한 순수 함수 표현식일 경우에만 고차함수 개념으로 표현식을 사용하는 편입니다.

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    private val rankToCount: Map<Rank, Int>,
열거타입을 활용하는 Map자료구조라면 EnumMap을 활용해보는건 어떨까요?

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        fun from(value: Int): LottoNumber = NUMBERS[value] ?: throw IllegalArgumentException("로또 번호는 ${MIN_VALUE}부터 ${MAX_VALUE}까지 가능합니다.")
동반객체를 통해 캐싱과 정적팩토리 함수 패턴까지 잘 활용해주셨네요 👍

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    override fun compareTo(other: LottoNumber): Int = value.compareTo(other.value)
compareTo는 infix함수이기에 dot(.) 없이도 표현이 가능하죠 ㅎㅎ

```suggestion
    override fun compareTo(other: LottoNumber): Int = value compareTo other.value
```

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/domain/Payment.kt
> +        val PRICE_PER_LINE: BigInteger = BigInteger.valueOf(1000)
객체명은 Payment로 좀 범용적인 네이밍인데 내부 값은 로또에 의존하는 가격 정보가 있는 것 같네요. 
이런 도메인 상수 정보들을 어떤식? 혹은 어떤 위치에 관리하는게 좋을까요?

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/domain/Rank.kt
> +    }
when절로 Rank 인스턴스들을 하나하나 분기하기엔 확장성이 너무 떨어지지 않을까 싶습니다. 각각이 자신에 해당하는지 여부는 각각의 인스턴스(FIRST, SECOND, ...) 가 책임지는게 맞지 않을까요?

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/ui/InputView.kt
> +object InputView {
재사용가능한 object 클래스로 잘 만들어주셨네요

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/ui/InputView.kt
> +    private val LINE_PATTERN = """^\s*(\d+\s*,\s*){5}\d+\s*$""".toRegex()
Pattern 객체도 미리 상수로 선언해두셨네요 👍

2024-11-23 10:20 UTC, catsbi commented on src/main/kotlin/lotto/ui/ResultView.kt
> +        println("\n당첨 통계\n---------")
println()함수는 내부적으로 System.out을 사용하기 때문에 너무 잦은 호출은 권장되지 않습니다. 
System.out은 내부적으로 synchronized 키워드를 사용하는 동기화 함수이거든요. 그렇기에 성능이슈가 있을 수 있습니다. 

buildString이나 StringBuilder를 활용해봐도 좋을 것 같고 List 구조는 joinToString 확장함수를 사용해봐도 좋을 것 같네요!

2024-11-24 06:14 UTC, giwankim commented on src/main/kotlin/lotto/domain/Payment.kt
> +        val PRICE_PER_LINE: BigInteger = BigInteger.valueOf(1000)
도메인 상수 정보는 Constants.kt 같은 파일을 도메인 패키지에 만들어서 관리해도 괜찮을 것 같습니다.

제 의도는 Payment는 로또 게임을 위해 Money 클래스를 래핑하는 것이었습니다. 그래서 도메인 패키지에 구현하기는 했는데, 조금 더 그 의도를 명확하게 하기 위해서 클래스 명칭을 LottoPayment로 변경했습니다. 따로 BigDecimal 같은 클래스를 래핑해서 Money 클래스 만들고 하는 것이 kata 의 핵심에서 멀어지는 것 같아서 고민을 했었는데 약간 죽도 밥도 아니게 된 것 같기는 합니다. 😭 

혹시 실무에서 금전을 표현할 때 많이 사용하는 라이브러리가 있나요? 전에 [JavaMoney](https://javamoney.github.io/)라는 라이브러리를 이런 용도로 사용할까 생각했었는데, 국제화 필요성도 없고 해서 BigDecimal/BigInteger 정도 사용했던 것 같습니다.

2024-11-24 09:13 UTC, giwankim commented on src/main/kotlin/lotto/application/LottoService.kt
> +    }
이런 컨벤션에 대한 고민은 미처 생각해보지 못했습니다. 바디가 한 줄이면 ktlint 디폴트가 단일 표현식을 사용하게 되어 있어서 그게 모범 사례라 생각하고 있었습니다.

"간단한 순수 함수 표현식일 경우"에만 표현식을 사용하신다고 했는데, 그럼 LottoService에 있는 두 메서드 모두 사이드 이펙트가 없는 순수 함수라는 생각이 듭니다.

```kotlin
fun play(
      lotto: Lotto,
      winner: LottoLine,
): LottoResult = lotto.match(winner)

fun generateRandom(numberOfLines: Int): Lotto =
        Lotto.from(
            (1..numberOfLines).map { lineGenerator.generate() },
        )
```

제 나름대로의 기준도 결국 (주관적인) 가독성인데

- 가능하다면 단일 표현식으로 줄수를 최소화합니다.
    - 함수들을 볼 때 선언부 위주로 보다 보니 표현식과 문이 섞여 있는 것이 가독성을 저해하는 것에 대해 크게 느껴지지는 않았습니다. 클래스의 크기가 커지고 비즈니스 로직이 더 복잡해지면 어떨지는 잘 모르겠습니다. 아직은 자바에 비해 줄수가 주는 쪽에 더 무게를 두고 있는 것 같습니다.
    - 단지 단일 표현식을 사용하면 생성자나 팩토리 메서드가 아닌 이상 리턴 타입을 표기하고 있습니다.
- 아직 고민 중인 부분은 컬렉션에 스트림 오퍼레이션을 적용할 때 중간 결과값 변수를 추출하는 기준입니다.

2024-11-25 05:02 UTC, catsbi approved these changes
지완님 피드백 반영 잘 해주셨어요 👍 

크게 더 문제될 부분은 없어보여서 머지하도록 하겠습니다. 3단계 진행해주세요!

2024-11-25 05:02 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoPayment.kt
> +class LottoPayment(
시그니처가 좀 더 명확해진 것 같네요 👍

2024-11-25 05:02 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    private val rankToCount: EnumMap<Rank, Int>,
피드백 반영 👍

2024-11-25 05:02 UTC, catsbi commented on src/main/kotlin/lotto/ui/ResultView.kt
> +            .forEach { sb.append(formatLine(it)) }
joinToString함수를 사용해봐도 좋을 것 같네요!

2024-11-25 05:02 UTC, merged