🚀 1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #1049
Opened 2024-11-23 13:00 UTC by SeolYoungKim

안녕하세요 현구님!! 이번 미션 잘 부탁드립니다~! 

ps. 현구막 블로그 주인분이 맞는것 같아서, 최근에 하이버네이트 조회 쿼리 데드락에 관한 글을 인상깊게 읽었다는 말씀 전해드리고 싶습니다 ㅎㅎ 리뷰 잘부탁드립니다 👍

2024-11-25 03:10 UTC, Hyeon9mak requested changes
안녕하세요 설영님, 로또 미션 리뷰를 맡게된 최현구입니다. 🙇‍♂️ 
1단계 완성도 높게 잘 진행해주셨어요! 아주 간단한 코멘트 몇 개만 남겼습니다.
궁금하신 점 편하게 질문 주세요~
(블로그 좋게 봐주셔서 감사합니다 ㅎㅎ 🙇‍♂️ )

2024-11-25 03:10 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/README.md
> +  - [x] 리스트 안의 숫자를 모두 더한다
기능 목록을 꼼꼼히 작성해주셨네요 💯 👍

2024-11-25 03:10 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/NumbersExtractor.kt
> +
객체가 따로 상태값을 갖지 않는다면 object 로 선언하여 "싱글톤 느낌으로 사용하면 좋아~" 라는 의도를 전달해주는게 좋죠 👍

2024-11-25 03:10 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/NumbersExtractor.kt
> +
Regex 객체들도 미리 선언해서 인스턴스 중복 생성을 방어해주셨군요 👍 💯

2024-11-25 03:10 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +        }
문자열계산기 또한 상태값이 없으므로 object 를 활용해줄 수 있겠네요 👍

2024-11-25 03:10 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +    }
저는 클래스 명칭을 보고 "NumberExtractor? 숫자와 관련된 로직은 여기에 모두 담겨있겠군." 라고 기대했는데요,
실제로는 숫자 추출기에서 구분자(연산자)를 검증하고, 계산기에서 피연산자를 검증하고 있더라구요.
클래스 명칭을 통해 기대하는 로직을 바로 찾아낼 수 있게끔, 명칭을 다듬거나 검증 로직의 위치를 이동시켜보는 건 어떨까요?

2024-11-25 03:10 UTC, Hyeon9mak commented on src/test/kotlin/stringaddcalculator/NumbersExtractorTest.kt
> +    }
꼼꼼한 테스트 👍 👍 
다음 단계부터는 kotest 를 활용해보시는 것도 좋을거 같아요.
가장 접하기 쉬운 StringSpec 부터 활용해보는 건 어떨까요?
https://kotest.io/docs/framework/testing-styles.html

2024-11-26 13:26 UTC, SeolYoungKim commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +        }
오, 그게 좋겠네요! object 라는 클래스가 아직 익숙치 않아서 그런지, 써보기도, 안써보기도 하면서 장단점을 느껴보고 있는데요! 

object로 선언하면 확실히 사용이 편하기도 하지만, 뭔가 무분별하게 참조될 가능성도 있어보여요. 마치 obejct가 자바의 Util 클래스(static 필드/메서드만 존재하는)를 쓰는 느낌이 나서 그런 것 같아요!

제가 실무에서 무분별한 Util 클래스 사용으로 인해 유지보수가 매우 힘들었던 경험이 있는데요 😓 

혹시 현구님 께서는 이런 부분은 걱정하지 않고 사용하는 편이실까요? 혹은, 실무에서 object를 어떻게 잘(?) 활용하고 계신지 궁금합니다! 
(참고로, 저는 코틀린을 처음 써봅니다! <- 혹시 대답하시는데 도움이 되실까 하여 같이 작성드려요 ㅎㅎ )

2024-11-26 13:52 UTC, SeolYoungKim commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +    }
해당 클래스는 "문자열에서 숫자를 추출해낸다"라는 것이 제 의도였는데, 그렇게 해석될 여지가 있어보이네요..!

아무래도 계산기에 피연산자 검증 로직이 있는것이 문제인 것 같아서, 검증 로직들을 모두 NumberExtractor로 옮겨보았습니다!

2024-11-26 13:53 UTC, SeolYoungKim commented on src/test/kotlin/stringaddcalculator/NumbersExtractorTest.kt
> +    }
오 넵 다음미션때 한번 써보겠습니다 ㅎㅎ

2024-11-27 02:34 UTC, Hyeon9mak approved these changes
설영님 피드백 잘 반영해주셨습니다!
질문 주신 사항에 대한 답변 남겼습니다.
다음 단계 진행에 도움이 되면 좋겠네요!
다음 단계에서 뵙겠습니다!

2024-11-27 02:34 UTC, Hyeon9mak commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +    }
> 현구님 께서는 이런 부분은 걱정하지 않고 사용하는 편이실까요? 혹은, 실무에서 object를 어떻게 잘(?) 활용하고 계신지 궁금합니다!

어떤 개발 상황이건 common, util 과 같은 성격을 띄는 클래스는
항상 빅보이가 되기 쉽기 때문에 유지보수에 어려움을 겪게 만들었던거 같아요.
때문에 "어디서든 쓰이는 만능 클래스" 를 만들지 않으려는 의식이 중요하다고 생각합니다 ㅎㅎ 👍 

개인적으로는 object 를 간단하게 검증 로직을 모아주는 형태로 자주 활용하는데요,
가령 service 계층에서 domain 계층으로 내리기 애매한, 사소한 검증 로직이 포함되어 있다고 가정해볼게요.

```kotlin
@Service
class SeolYoungService(
  private val seolYoungRepository: SeolYoungRepository,
  private val hyeon9makRepository: Hyeon9makRepository,
  private val jasonRepository: JasonRepository,
) {
  fun something(value: String) {
    // .. 이전 로직 ..

    require(value.isNotBlank()) { " ... " }

    // .. 이후 로직 ..
  }
}
```

`SeolYoungService` 서비스 내부 검증 로직에 대한 테스트 코드 작성이 매우 귀찮겠죠.
이 때 저는 object 로 해당 검증 로직을 분리하여 간단한 테스트 코드를 작성합니다.

```kotlin
object SomeThingValidator {

  fun validate(value: String) {
    require(value.isNotBlank()) { " ... " }
  }
}

class SeolYoungService(
  private val seolYoungRepository: SeolYoungRepository,
  private val hyeon9makRepository: Hyeon9makRepository,
  private val jasonRepository: JasonRepository,
) {
  fun something(value: String) {
    // .. 이전 로직 ..

    SomeThingValidator.validate(value = value)

    // .. 이후 로직 ..
  }
}
```

그럼 `SomeThingValidator` 로 테스트 코드 작성이 엄청 간결해지고,
service 계층에서 검증할게 생길 때마다 `SomeThingValidator` 에 메서드를 하나씩만 더 추가하면 되겠죠. 동료 개발자는 `SomeThingValidator` 만 확인해도 어떤 비즈니스 요청들이 있었는지 한눈에 파악할 수 있구요.
더 나아가 최종적으로는 규모가 커진 `SomeThingValidator` 를 domain 계층으로 이동시키면서 하나의 domain model 로 만들어 우리 도메인으로 변경해볼 수도 있겠구요.

2024-11-27 02:34 UTC, merged

2024-11-30 00:08 UTC, SeolYoungKim commented on src/main/kotlin/stringaddcalculator/StringAddCalculator.kt
> +    }
오오..!! 상세한 설명 감사합니다!! 말씀주신 부분들을 생각하면서 잘 적용해봐야곘어요 👍