Step2-로또(자동)
next-step/kotlin-lotto pull request #1063
Opened 2024-11-24 14:31 UTC by janghomoon

안녕하세요 작업 완료되어 PR 드립니다.

2024-11-25 12:06 UTC, pci2676 requested changes
조금 더 개선해보면 좋을 부분에 리뷰를 남겨두었으니 개선 후 다시 요청해주세요!

2024-11-25 12:06 UTC, pci2676 commented on src/main/kotlin/autolotto/AutoLottoApplication.kt
> +    OutPutView.printLottoResults(lottoWinnerResult, amount)
빈 공백 또한 코드를 읽는데 중요한 요소가 되니 적절히 맥락에 따라 빈공간을 넣어주시면 좋을것 같습니다. 😄

2024-11-25 12:06 UTC, pci2676 commented on src/main/kotlin/autolotto/calculator/LottoCalculator.kt
> +    }
이 부분을 enum을 활용하여 개선해보시면 좋을것 같습니다. 😄

2024-11-25 12:06 UTC, pci2676 commented on src/main/kotlin/autolotto/configuration/AutoLottoConfiguration.kt
> +    }
이렇게 설정해서 사용하시는 의도가 있으실까요? 🤔

2024-11-25 12:06 UTC, pci2676 commented on src/main/kotlin/autolotto/valid/Valid.kt
> +object Valid {
방어 로직만을 위한 util성 정적메서드만 모여있는 클래스 없이

객체 내부에서 검증을 하도록 모두 변경해보시면 좋을것 같습니다.

2024-11-25 12:06 UTC, pci2676 commented on src/main/kotlin/autolotto/entity/Lotto.kt
> +}
이 로또에서는 1미만 45이상의 값들이 들어갈 수 있을것 같습니다.

값 객체에 대해 알아보시고 개선해보시면 좋을것 같습니다. 😄

2024-11-29 04:18 UTC, pci2676 requested changes
이전에 남긴 리뷰중 중요한 부분이 개선되지 않은것 같습니다.

다시 개선해서 PR 부탁드리겠습니다.

혹시 코드를 작성함에 어려움이 있다면 정리해서 PR에 남겨주시거나 DM을 주셔도 좋습니다. 😄

2024-11-29 04:18 UTC, pci2676 commented on README.md
> +  * 수익률 계산
코드를 객체 지향적으로 작성해보는 연습을 위해

애플리케이션에서 필요한 역할과 책임을 분류해보시는건 어떨까요?

가령 양수를 다루는 클래스가 필요하다면

PositiveNumber
- 양수만 가지고 있을 수 있다.
- 양수가 아니면 exception을 발생시킨다.

와 같이 정책의 작은 부분을 쪼개어 작성해보시고 그에따라 객체를 구현해보시면 좋을것 같습니다.

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/configuration/AutoLottoConfiguration.kt
> +    }
지난 질문에 대한 답변이 없는것 같습니다.

지금 이렇게 configuration을 작성해야하는 이유가 있을까요?

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/calculator/LottoCalculator.kt
> +        lotto: Map<Int, Int>
Map의 key, value인 Int가 정확히 무엇을 의미하는지 명시적이지 않습니다.

모든 것을 대체하도록 말씀드리는것은 아니지만   
조금 더 명확한 의미를 띌 수 있도록 객체로 대체해보시는것이 좋을것 같습니다.

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/calculator/LottoCalculator.kt
> +        return prize?.calculatePrize(count) ?: 0
아래 글을 참조하여 상수로 변환할 수 있는 값들을 모두 찾아 개선해주세요.

https://javabom.tistory.com/28

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/enums/prize/Prize.kt
> +            return (count * prizeMoney) + 1000 // 예: 추가 보너스 계산
정책상 존재하는 로직을 구현해주세요. 이러한 정책은 없는것 같습니다. 🤔

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/entity/Lotto.kt
> +class Lotto(val lottoGame: Set<Int>) {
클래스의 이름이 Lotto인데 멤버변수의 이름을 lottoGame이라고 지은 이유가 있으실까요?

조금 더 적절한 이름은 없을까요?

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/entity/Lotto.kt
> +class Lotto(val lottoGame: Set<Int>) {
Lotto 클래스를 만들때 어떠한 역할과 책임을 기대하고 설계하셨을까요?

Lotto에는 지정된 수의 번호들만 들어올 수 있고 지정된 갯수만 갖고있어야할것 같은데

이러한 보장이 될 수 있도록 개선해보면 어떨까요?

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/valid/Valid.kt
> +object Valid {
이 클래스에 집약적으로 작성된 validation 로직을 모두 다른 객체에 분산해보도록 해보겠습니다.

반드시 개선해주세요.

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/view/OutPutView.kt
> +    private val FIRST_PRIZE_MONEY = 2000000000
이 값은 view에서 관리해야하나요?

관리하기에 더 어울리는 객체가 domain 영역에 있을것 같습니다.

2024-11-29 04:18 UTC, pci2676 commented on src/main/kotlin/autolotto/entity/Lotto.kt
> +class Lotto(val lottoGame: Set<Int>) {
이와 더불어 값 객체의 개념을 찾아보시고 이번 미션에서 적용해보시면 좋을것 같습니다.

2024-11-30 12:37 UTC, pci2676 requested changes
질문에 대한 답변을 부탁드린 부분들이 있습니다. 해당 부분에 답변을 부탁드립니다.

추가로 개선해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/calculator/LottoCalculator.kt
> +        return prize?.calculatePrize(count) ?: ZERO
0을 ZERO로 표현하는것은 상수로 변환하는 의미가 크게 있지 않을것 같습니다.

0이 의미하는 바를 변수명으로 표현하는것은 어떨까요?

이를테면 `NONE_MATCH_PRIZE`와 같은 이름이 될 수 있을것 같습니다.

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/calculator/LottoCalculator.kt
> +                    (totalPrize - amount).toDouble() * ONE_HUNDRED
`ZERO`와 관련된 리뷰와 동일합니다.

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/valid/ValidatorStrategy.kt
> +interface ValidatorStrategy<T> {
지난번 리뷰와 동일합니다.

이러한 별도의 검증 로직만을 담당하는 객체는 이번 단계에서 불필요해보입니다.

이 인터페이스와 구현체들은 모두 '제거'해주세요.

그리고 객체에 검증하는 책임을 구현해주시면 좋을것 같습니다.

양수를 나타내는 객체라면

```kotlin
class PositiveNumber(val value: Long) {
  init {
    require(value >= 0) { "양수가 아닙니다. value=$value" }
  }
}
```

위와 같이 객체 내에 검증 로직이 위치한다면 일반 Long 혹은 Int를 사용하는것 보다 PositiveNumber를 이용하면서 양수라는 값이 보장된 상태를 계속해서 이어나갈 수 있습니다.

이러한 식으로 도메인 객체 내에 검증 로직을 자연스럽게 녹여봐주세요.

지금 적용해볼 수 있는것으로 보이는 것은

로또 번호 (1~45), 로또 티켓(로또 번호 6개를 갖고 있는) 등이 있을것 같습니다.

위 두개 말고도 여러방면에 적용해 볼 수 있습니다.  

더 찾아서 적용해주세요! 궁금한 점이 있다면 편하게 질문주세요. 제가 드리는 질문에 대한 답변도 궁금한 점에 대한 질문도 없다면 리뷰를 이어가며 도움드릴수 있는 부분이 적어질 것 같습니다. 😢

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/view/InputView.kt
> +            if (!numberValidatorStrategy.isValid(e)) {
이렇게 별도의 validation 로직이 절차적으로 존재하게 되면 어떠한 문제점이 생길까요?

여기서 검증한 Int, Long값들은 안전하다는 것=(정책에서 요구하는 사항을 준수한다는 것)을 보장받을 수 있을지 모르지만

다른 객체에서 전달받는 Int, Long과 같은 부분에서는 그에 대한 요구사항이 보장되었다는 확신을 가질 수 없습니다.

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/view/OutPutView.kt
> +        println("총 수익률은 ${lottoResultResponse.getProfit()}입니다.${if (lottoResultResponse.getProfit() < 1) "(기준이 1이기 때문에 결과적으로 손해라는 의미임)" else ""}")
dto에는 별도의 로직을 구현하지 않는것이 좋습니다.

dto는 data transfer object 입니다. 말 그대로 값을 전달하는 것이 주된 목적인 객체입니다.

별도의 view전용 로직이 필요하다면 view에서 구현하는게 더 좋을것 같습니다.

단일 책임 원칙을 준수하여 구현해보시면 좋을것 같습니다.

2024-11-30 12:37 UTC, pci2676 commented on src/main/kotlin/autolotto/enums/prize/Prize.kt
> +            return (count * prizeMoney) + 1000 // 예: 추가 보너스 계산
이 부분에 대한 피드백이 없는것 같습니다.

2024-12-01 11:50 UTC, janghomoon commented on src/main/kotlin/autolotto/view/InputView.kt
> +            if (!numberValidatorStrategy.isValid(e)) {
사실 말씀하신 절자척으로 존재할떄 문제점이 있다는 말을 이해는 잘가지 않습니다;; 
저의 경우에는 API 를 작성할때 꼭 requet 객체의 valid를 절차적으로 의무화 해서 하는데 그럼 이런 부분도 문제가 생긴다는 것일까요??  

 혹시  이부분을 어떻게 수정하면 좋을지 자세하게 알려주시면 감사합니다.

2024-12-02 18:28 UTC, pci2676 commented on src/main/kotlin/autolotto/view/InputView.kt
> +            if (!numberValidatorStrategy.isValid(e)) {
request를 거치고 나온뒤 사용하는 값의 타입이 전부 Int, String과 같은 기본형인것이 문제가 될 수 있습니다.

이러한 값을 앞에서 validation 해서 뒤에서 사용할때 안전해 보일 수 있지만 그렇지 않습니다.

가령 A에서 0보다 커야 한다는 조건을 가진 validation을 거치고 나온뒤 B에서 사용되는 Int가 있다고 해보겠습니다.

우리가 작성한 애플리케이션은 A에서 validation이 거쳐진 Int를 B에서 사용하도록 작성하였기 때문에 문제가 되지 않습니다.

하지만 다른 개발자가 B를 사용할때 전달받을수 있는 파라미터가 단순히 Int인 경우 0보다 작거나 같은 값을 전달할 수 있습니다. 이러한 경우 정책에서 어긋나는 값이 전달되어 예상치 못한 동작을 할 수 있습니다.

따라서 별도의 의미를 가지는 객체를 사용하시기를 권장드리는 것 입니다.

금액을 전달하는 경우 Int가 아닌 Money와 같은 객체를 전달해보면 어떨까요?

LottoMachine이라는 로또를 판매하는 기계가 있고 이러한 기계의 메서드로 buy가 있을때

buy(Integer money)와 buy(Money money)는 안정성의 수준이 달라 보이시지 않으실까요?

그리고 Money를 계속해서 재활용할 수 있고 buy를 다른 곳에서 사용할때도 Money라는 규약이 생겨 더 안정적으로 메서드를 운용할 수 있게 됩니다.

2024-12-02 18:31 UTC, pci2676 approved these changes
미션 진행을 위해 merge하겠습니다.

질문에 대한 답변을 남겨두었습니다.

추가로 질문에 대한 답변을 아직 하지 않으신 부분이 있으신것 같은데 답변 부탁드리겠습니다. 😄

2024-12-02 18:31 UTC, pci2676 commented on src/main/kotlin/autolotto/enums/prize/Prize.kt
> +        fun fromMatchCount(matchCount: Int): Prize? {
👍

2024-12-02 18:31 UTC, pci2676 commented on src/main/kotlin/autolotto/dto/LottoResultResponse.kt
> +class LottoResultResponse() { // private val winnerResults: Map<Prize, Int>
사용하지 않으면 제거해주세요~

2024-12-02 18:31 UTC, pci2676 commented on src/main/kotlin/autolotto/configuration/AutoLottoConfiguration.kt
> +    }
이 부분에 대한 답변을 기다리고 있습니다~

2024-12-02 18:31 UTC, merged