Step2
next-step/kotlin-lotto pull request #1064
Opened 2024-11-24 14:33 UTC by ddoriya-dev

로또 자동 미션 구현진행하였습니다~

2024-11-24 15:38 UTC, Wordbe requested changes
고생하셨습니다!
코멘트 드린 부분 확인 부탁드려요 🙏

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/model/LottePrize.kt
> +    FIRST(6, 2000000000),
자릿수가 큰 숫자는 _ 로 구분해보는 건 어떨까요? 😀

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteController.kt
> +    private val lotteService = LotteService()
생성자로 받아서 외부에서 주입하는 방식이면 어떨까요? 😀
필드에 주입하는 것과는 무슨 장단점이 있을까요?

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteController.kt
> +    LotteController()
컨트롤러의 생성이 곧 run 인 것 같은데, controller.run() 으로 하면 역할이 더 명시적으로 드러나지 않을까 생각이듭니다!

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteController.kt
> +                winLottoStatMap[prize] = winLottoStatMap[prize]!!.plus(1)
맵 대신 객체로 만들어보면 어떨까요? 그랬을 경우 장점은 뭘까요? 😀
그리고 !! 은 정말확신하는 경우가 아니라면 지양하는게 좋아보여서 변경이 가능할까요?

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteService.kt
> +        return (0 until money / LOTTO_PRICE).map { Lotto(randomLotto()) }
`..<` 이라는 문법도 직관적이니 한번 도입해봐도 좋을 것 같아요!

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteService.kt
> +        return (0 until money / LOTTO_PRICE).map { Lotto(randomLotto()) }
money 에 대한 검증은 있으면 좋을 것 같네요 😀

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteService.kt
> +        return winLotto.lotteNumbers.intersect(lotto.lotteNumbers).size
Lotto 속성이 밖으로 드러나는 것 같은데, Lotto 안에 만들어 보면 어떨까요? 😀

2024-11-24 15:38 UTC, Wordbe commented on src/main/kotlin/study/lotto/LotteService.kt
> +    }
직접명시된건 없지만 일반적으로 private 메소드는 맨 아래에 많이 놓는 것 같아요. 어떠신가요?

2024-11-25 00:38 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteController.kt
> +    private val lotteService = LotteService()
해당 컨트롤러가 inputView 클래스 등 변경할일이 없다고 판단하여 진행 했었어요..
하지만 service, view 로직은 외부로 빼는부분이 더좋곘군요 ㅠ 감사합니다.

2024-11-25 00:46 UTC, ddoriya-dev reviewed
안녕하세요~ 해당 리뷰에 대해 부족한 부분 확인했습니다~
아무래도 고민이 많았던 부분들은 딱딱 알려주신것같아요~ 
감사합니다.

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteController.kt
> +    LotteController()
네네~ 꼼꼼한 확인 감사합니다.

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteController.kt
> +                winLottoStatMap[prize] = winLottoStatMap[prize]!!.plus(1)
MAP 과 객체 고민을 많이 하긴했는데 ㅠㅠ 아무래도 객체가 조금더 유연하게 할수있을것 같습니다~
그리고 !!는 지양하도록 하겠습니다 ㅠ

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteService.kt
> +        return (0 until money / LOTTO_PRICE).map { Lotto(randomLotto()) }
넵~ 알겠습니다

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteService.kt
> +        return winLotto.lotteNumbers.intersect(lotto.lotteNumbers).size
넵~ 이부분에 대해 고민좀 했는데 감사합니다.

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/LotteService.kt
> +    }
네 좋습니다~

2024-11-25 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/lotto/model/LottePrize.kt
> +    FIRST(6, 2000000000),
아 _ 이런기능이 있었군요!

2024-11-25 15:14 UTC, Wordbe approved these changes
리뷰반영 감사합니다 ☺️ 고생많으셨어요
다음스텝으로 가시죠!! 🚀🔥

2024-11-25 15:14 UTC, merged