[Step4] 🚀 4단계 - 로또(수동)
next-step/kotlin-lotto pull request #1076
Opened 2024-11-25 14:39 UTC by kyuwon53

안녕하세요 . 플라님! 
4단계 로또 (수동) 미션 리뷰 요청 드립니다. 🚀

이번 미션도 잘 부탁드립니다~

2024-11-26 13:19 UTC, Flamme1004K requested changes
안녕하세요!

4단계 미션 매우 잘 해주셨습니다! 몇 가지 코멘트 남겼으니, 확인 후 다시 리뷰 요청 부탁드립니다!

화이팅입니다!

2024-11-26 13:19 UTC, Flamme1004K commented on README.md
> +- [x] 수동으로 입력한 로또 번호와 지난 주 당첨 번호를 비교하여 당첨 통계를 계산한다.
요구 사항 정리 좋아요! 항상 명확한 요구 사항을 정리해 주셔서 기능 구현 파악하기 좋네요! 

감사합니다.

2024-11-26 13:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Amount.kt
> +value class Amount(private val value: Int) {
Amount도 value class로 해주셨네요~👍

2024-11-26 13:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return Lotto.from(generator.generate())
private val generator: LottoNumberGenerator의 generate()를 Int로 반환하지 않고, 미리 만들어 놓은 LottoNumber를 반환하는 건 어떨까요?

그러면, 객체 생성 비용 개선 및 LottoNumberGenerator에 의미가 더 명확해질듯합니다. 😄

2024-11-26 13:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +value class LottoNumber(val value: Int) : Comparable<LottoNumber> {
원시값 포장 잘하셨어요! 👍

2024-11-26 13:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        lottoCount: Int,
lottoCount를 구매한 로또의 수에 뜻을 가진 이름으로 변경하는 건 어떨까요?

2024-11-26 13:19 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +class LottoNumberTest : BehaviorSpec({
예외 테스트 👍 생성 테스트도 있으면 좋겠네요~

2024-11-26 13:19 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoStoreTest.kt
> +            }
테스트가 명확하니 좋네요!

2024-11-26 14:25 UTC, kyuwon53 commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return Lotto.from(generator.generate())
💡 아! 저녀석을 빼먹었네요!

2024-11-26 14:27 UTC, kyuwon53 commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        lottoCount: Int,
좋습니다 👍

2024-11-27 13:34 UTC, Flamme1004K approved these changes
안녕하세요!

이만 로또 미션 끝내도록 하겠습니다!

너무나도 잘 해주셨고, 끝까지 로또 미션 진행해 주셔서 너무나도 감사드립니다.

다음 블랙잭 미션 파이팅 하시길 바랍니다! 파이팅!

2024-11-27 13:34 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +    Given("유효한 로또 번호가 주어졌을 때") {
생성에 대한 테스트 케이스 굳!

2024-11-27 13:34 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +                ?: throw IllegalArgumentException("로또 번호는 ${LOTTO_NUMBER_MIN}부터 $LOTTO_NUMBER_MAX 사이여야 합니다.")
잘하셨어요! 👍

2024-11-27 13:35 UTC, merged