4단계 - 로또(수동)
next-step/kotlin-lotto pull request #1094
Opened 2024-11-28 04:18 UTC by wooobo

안녕하세요 수현리뷰어님!

4단계 구현해보았습니다! 
이번 리뷰도 잘 부탁드립니다! 😄

2024-11-28 09:02 UTC, wisemuji requested changes
안녕하세요 태화님!

이전 단계에서 구조를 잘 설계해주셔서 이번 단계는 크게 드릴 피드백이 많지 않았는데요!
마지막 단계인 만큼 몇 가지 고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요!

2024-11-28 09:02 UTC, wisemuji commented on src/main/kotlin/lotto/InputView.kt
> +        )
외부에서 수동으로 구매하여 Lottos에 넘겨주는 것이 아닌, Lottos가 알아서 생성하도록 부 생성자나 팩토리 함수를 활용해보는건 어떠세요?

2024-11-28 09:02 UTC, wisemuji commented on src/main/kotlin/lotto/InputView.kt
>  object InputView {
마지막 단계인 만큼 고민해보면 좋을 내용인데요! (정답이 없습니다)

현재는 InputView에서 직접적으로 도메인 객체를 잘 알고 있고, 함수도 호출하고 있어요.

![image](https://github.com/user-attachments/assets/f23955c6-65bb-4662-ba25-5e351a936143)

MVC 구조에서는 뷰가 도메인 객체를 어느 정도로 알고 있어야 할까요? 🤔

2024-11-28 09:02 UTC, wisemuji commented on src/main/kotlin/lotto/InputView.kt
> +        }
책 엘레강트 오브젝트의 [인자의 값으로 NULL을 절대 허용하지 마세요](https://github.com/Coveong/reading-books-for-programmers/blob/74830435409c0a5000c8b7eb3639c5d63e9e47a5/%EC%97%98%EB%A0%88%EA%B0%95%ED%8A%B8%20%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8/3%EC%9E%A5.%20%EC%B7%A8%EC%97%85/wisemuji.md?plain=1#L49) 파트를 참고해보셔도 좋을 것 같아요!
(다소 워딩이 세게 표현되어 있긴 합니다 😂 )

2024-11-28 09:02 UTC, wisemuji commented on src/main/kotlin/lotto/Rank.kt
> +    SECOND(matchCount = 5, prize = Amount(BigDecimal(30_000_000)), isBonus = true),
named arguments를 활용해주셨군요 👍

2024-11-28 09:02 UTC, wisemuji commented on README.md
다음 요구 사항 처리가 누락된 것 같아요! 

> 예외 처리를 통해 에러가 발생하지 않도록 한다.

2024-11-28 09:02 UTC, wisemuji commented on src/test/kotlin/lotto/UserTest.kt
> +        user.buyManualLottos(manualLottos)
장기적으로 프로그램이 커질수록 픽스쳐로 관리하고 싶은 샘플 코드들이 생길텐데요, 이러한 픽스쳐는 어떻게 관리하면 좋을지 스스로 고민해보셔도 좋을 것 같아요.

고민에 도움이 되도록 관련 예시를 첨부합니다.
- https://thalals.tistory.com/375
- https://github.com/woowacourse/service-apply/blob/master/src/test/kotlin/apply/JudgmentFixtures.kt

2024-11-28 09:02 UTC, wisemuji commented on src/test/kotlin/lotto/LottoNumberTest.kt
> +}
의미 있는 시나리오 테스트 👍 
LottoNumber를 단순히 Wrapper class로만 생각한 것이 아니라 적절한 역할과 책임을 부여해서 좋았습니다 👍 
단순히 Wrapper class로만 만든다면, typealias등을 활용하여 원시값을 포장할 수도 있을 것 같아서 이전 단계에서 피드백을 드렸습니다. 이 또한 User 객체에서 너무 잘 활용해주셨어요 👍

2024-11-28 14:32 UTC, wooobo commented on src/test/kotlin/lotto/UserTest.kt
> +        user.buyManualLottos(manualLottos)
감사합니다~

2024-11-28 14:32 UTC, wooobo commented on README.md
그렇네요! Step개념을 도입 해봤습니다~^^

2024-11-28 14:40 UTC, wooobo commented on src/main/kotlin/lotto/LottoViewStep.kt
> +typealias ViewBonusNumber = Int
[comment](https://github.com/next-step/kotlin-lotto/pull/1094#discussion_r1861758540)

Domain 레이어를 View 레이어에서 과도하게 알게 되면, 의존성으로 인해 Domain 변경이 어려워질 수 있다고 생각해요!
이를 해결하기 위해 View와 Domain 사이를 연결해주는 프로토콜 변환 매개체나 아키텍처적 접근 방식이 필요할것 같아요 🤔  

View에서 사용하는 타입은 DTO 개념 대신 **typealias**를 활용해 가독성을 높이고, 불필요한 객체 의존성을 줄여보았습니다~
또한, Domain에 대한 의존성을 중앙화하기 위해 **GameContext**를 도입하여, 도메인 접근을 단일화하고 변경에 유연하게 대응할 수 있도록 설계하려고 해보았습니다 😄

2024-11-28 14:46 UTC, wooobo commented on src/main/kotlin/lotto/InputView.kt
> +        )
네!

2024-11-29 07:54 UTC, wisemuji approved these changes
안녕하세요 태화님! 리뷰 반영을 너무너무 잘 해주셨습니다 👍 

태화님이 작성하신 코드 구조를 보며 저 또한 좋은 인사이트를 얻어가는 시간이였습니다!
개발자로 성장하는 과정에 도움이 되었길 바라며 로또 미션은 마무리하겠습니다.
나머지 미션도 꼭 완주하시길 응원하겠습니다 💪

2024-11-29 07:54 UTC, wisemuji commented on src/main/kotlin/lotto/LottoMachine.kt
> +            throw IllegalArgumentException("숫자가 아닙니다.")
[requireNotNull](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/require-not-null.html)을 활용할 수도 있을 것 같네요 🙂

2024-11-29 07:54 UTC, wisemuji commented on src/main/kotlin/lotto/Lottos.kt
> +        }
좋습니다 👍  이제 Lottos 생성에 대한 책임 또한 Lottos 안에서 관리할 수 있게 되었어요.

팩토리 함수와 부생성자에 대한 다음과 같은 시각이 있으니 참고차 읽어보시면 좋을 것 같아요 ㅎㅎ
- https://kt.academy/article/ek-factory-functions

2024-11-29 07:54 UTC, wisemuji commented on src/main/kotlin/lotto/LottoViewStep.kt
> +typealias ViewBonusNumber = Int
호오 흥미로운 구조를 설계해주셨네요 👍 
특히나 게임 구조 상 순서가 명확하게 존재하고, 각각의 순서별 동작이 명시적으로 수행되어야 하는 경우 더욱 의미있을 것 같아요.
하지만 만약 로또 게임이 매우 복잡해진다면 GameContext이 관리 책임으로 인해 다소 비대해질 수 있어서, 이 부분은 나중에라도 고민이 필요할 것 같아요!

태화님의 코드를 보고 저 또한 인사이트를 많이 얻어갑니다!

2024-11-29 07:54 UTC, merged

2024-11-29 09:02 UTC, wooobo commented on src/main/kotlin/lotto/LottoMachine.kt
> +            throw IllegalArgumentException("숫자가 아닙니다.")
좋은 리뷰 감사합니다~