Step4 로또(수동)
next-step/kotlin-lotto pull request #1097
Opened 2024-11-28 16:28 UTC by DuhanMo

안녕하세요 범준님!
이전스텝에서 말씀주신 피드백을 반영해보았어요 😀
항상 좋은 인사이트 주셔서 감사해요

이번 스텝에서는 
Set<Int> 형태로 로또넘버를 도메인끼리 주고받던 부분을 수정했어요, LottoApplication 에서 Set<Int> -> LottoNumbers로 변환하여 객체들에게 전달하도록 했어요.

그러면 이번리뷰도 잘부탁드립니다🙇‍♂️

2024-11-28 16:30 UTC, DuhanMo commented on src/main/kotlin/lotto/domain/RankReward.kt
> +            else -> this.matchedCount == matchedCount && this.matchBonus == matchBonus
이 부분을 말씀주신 방향으로 해보려고 했어요.
단순 `this.matchedCount == matchedCount && this.matchBonus == matchBonus` 해당 조건식을 리턴하게 되면 this.matchedCount 가 null 일때 의도했던 동작을 하지 않더라구요🥲 그래서 위와같이 `when`으로 분기처리해보았습니다🙂

2024-11-29 05:18 UTC, ddaaac requested changes
안녕하세요 두한님 👋 

리뷰를 남겨보려고 이것저것 고민해봤는데 이전 단계에서 구조를 잘 잡아주셔서 크게 남길 코멘트가 없네요.

혹시 더 궁금하신 점이나 얘기해보고 싶은 것들이 있다면 코멘트 남겨주시고 아니면 바로 재요청 주시면 머지하겠습니다!

2024-11-29 05:18 UTC, ddaaac commented on src/main/kotlin/lotto/domain/RankReward.kt
> +            else -> this.matchedCount == matchedCount && this.matchBonus == matchBonus
아... 죄송합니다. 착각했네요 😅
깔끔하게 원하는 바를 잘 표현하게 구현한 것 같습니다!

2024-11-29 05:18 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
>              return Lotto(LottoNumbers.create())
여기도 LottoNumbers.random() 정도가 적당한 네이밍일 것 같네요!

2024-11-29 06:20 UTC, DuhanMo commented on src/main/kotlin/lotto/domain/Lotto.kt
>              return Lotto(LottoNumbers.create())
네! random이 적당해보여요 ㅎㅎ 반영하도록 할게요🙂

2024-11-29 13:33 UTC, DuhanMo commented
범준님 이번 미션 리뷰해주시느라 고생많으셨습니다🙇‍♂️ 궁금하거나 고민 생기면 따로 여쭤볼게요!😄 감사합니다~!

2024-12-01 10:49 UTC, ddaaac approved these changes
안녕하세요 두한님 👋 

로또 미션동안 정말 고생 많으셨습니다!

다음 단계도 화이팅하세요 💪

2024-12-01 10:50 UTC, merged