[Step3] 로또(2등)
next-step/kotlin-lotto pull request #1101
Opened 2024-11-29 08:35 UTC by kimihiqq

안녕하세요 남재님!
꼼꼼한 코드리뷰 감사합니다! 🙇 
이전 리뷰해주셨던 부분들 중 Step2 리팩토링을 포함해, 새로 Step3 의 기능들을 새로 구현해 추가했습니다.
이번 단계도 잘 부탁드립니다! 🙂

2024-11-30 08:08 UTC, namjackson requested changes
안녕하세요 성현님 
3단계 고생하셨습니다! 
몇가지 추가적으로 고민할법한 코멘트 남겼으니, 확인해주세요!

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/WinningCategory.kt
> +                else -> NONE
WinningCategory 에서 가지고 있는 matchCount를 활용하면 어떨까요?
 ```
    SECOND(5, 30000000),
    FIRST(6, 2000000000),
```
이미 정의 되어있는 매직넘버네요 :)

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoGameManager.kt
> +        return WinningStatistics(statistics)
LottoGameManager은 어떤 책임이 있을까요?
playLottoGame는 어떤 책임이 있을까요?
tickets, lottoMatcher 객체를 받아서 객체의 데이터를 사용해서 객체를 실행하는 구조네요
그렇다면 tickets, lottoMatcher의 책임이라고 볼수 있지는 않을까요?
이부분 고민해보면 좋을거같아요!

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +        val matchBonus = ticket.getNumbers().contains(bonusNumber)
ticket의 getNumbers를 받아와서 연산해주고 있어요,
ticket에게 메세지를 던져서 책임을 위임해보면 어떨까요?

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/ProfitCalculator.kt
> +class ProfitCalculator {
비슷한 류의 코드들이 많은거 같아요, ( DefaultLottoPurchaseCalculator, LottoGameManager ... 등등 )
ProfitCalculator는 어떤 책임이 있을까요?
ProfitCalculator는 데이터와 행위가 분리되어있는 구조같아요,
필요한 데이터는 함수의 파라미터를 통해 외부에서 전달되고, 클래스내에서는 받아온 외부의 데이터를 연산을 해주고 있어요,
동일한 관심사의 데이터와 연산이 분리된건 아닐까요?
데이터와 행위를 하나의 책임으로 묶어보는 구조를 고민해보면 좋을거같아요

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/WinningStatistics.kt
> +    }
도메인 로직에 View요소가 포함되어있네요
View 관련 로직은 분리해주세요!

2024-11-30 08:08 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoGameManager.kt
> +                .mapValues { it.value.size }
playLottoGame 이라는 로직은 로또의 결과를 반환하는 로직같아요,

하지만 결과를 반환하는것 뿐아니라, 
등수별로 그룹화하는 로직도 포함되어이있네요.

등수별로 그룹화하는 책임은 게임 결과를 필요에 따라서 연산한다고 볼수 있지않을까요?
결과를 반환하는 책임과, 결과를 연산하는 책임을 분리해보면 어떨까요?
로또의 결과를 항상 그룹화해서 보여줄 필요는 없다는 생각이 들어요 :)

2024-11-30 11:31 UTC, kimihiqq commented on src/main/kotlin/lotto/domain/LottoGameManager.kt
> +        return WinningStatistics(statistics)
감사합니다! 말씀주신대로 tickets와 lottoMatcher가  실제 로직을 처리애햐 할 책임을 가지는게 맞는것같아 해당 로직을 옮기는 쪽으로 수정했습니다! 🙂

2024-11-30 11:33 UTC, kimihiqq commented on src/main/kotlin/lotto/domain/ProfitCalculator.kt
> +class ProfitCalculator {
데이터를 가진 객체에 데이터를 활용한 행위를 포함시키는 방향으로 수정해보았습니다!

2024-12-01 02:13 UTC, namjackson approved these changes
안녕하세요 성현님! 
피드백 적용 잘해주셨네요! 
몇가지 고민할법한 코멘트 남겼으니, 확인해주세요! 
다음단계 진행하시면서 참고해주세요 :)

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +class LottoMatcher(private val winningLotto: Lotto, private val bonusNumber: LottoNumber) {
LottoMatcher라는 네이밍도 좋지만 WinningLotto가 좀더 어울리는 객체네이밍은 아닐까요? ( 이부분은 개인적인 의견입니다!)

bonusNumber와 winningLotto와 중첩된 번호를 가지고 있는 케이스도 고려해볼거 같아요 :)

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
>      fun match(ticket: Lotto): WinningCategory {
match 함수는 테스트 이외에서는 외부에서 사용되지 않고 있는 코드네요 :)
테스트가 실코드에 영향을 주는건 지양하는게 좋을거같아요

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/StatisticsFormatter.kt
> +package lotto.domain
domain영역 보다는 View영역이라고 볼수 있을거 같아요 :)

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/WinningCategory.kt
> +                count == FIFTH.matchCount -> FIFTH
매번 등수가 추가될때마다 여기가 추가되는 코드인거같아요 :) 
```
entries.find { it.matchCount ...
```
처럼 활용할수 있을거같아요 :)

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +        return WinningStatistics(statistics)
결과를 분석하는 책임이있는 WinningStatistics를 만들어주고있네요
하지만 WinningCategory를 그룹화한것조차 분석의 영역은 아닐까요?

LottoMatcher의 관심사인 당첨 결과를 결정하는것과는 다른 책임이라고 볼수도 있을거 같아요 :)

2024-12-01 02:13 UTC, namjackson commented on src/main/kotlin/lotto/domain/WinningCategory.kt
> +    FIRST(6, 2000000000),
```suggestion
    SECOND(5, 30_000_000),
    FIRST(6, 2_000_000_000),
```
가독성을 위해 큰 숫자에는 , 대신 _ 를 이용해 단위를 표기해주기도 합니다 :)

2024-12-01 02:13 UTC, merged