3단계 - 로또(2등)
next-step/kotlin-lotto pull request #1114
Opened 2024-12-03 15:42 UTC by eshc123

## 주요 내용
- 로또(2등) 추가 구현 하였습니다.
- step-2 피드백에 대해 step-2 PR 코멘트에 커밋 아이디 남겨두었습니다.

2024-12-04 13:26 UTC, BeokBeok requested changes
이전 단계 피드백과 로또(2등) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        val matchingBonus = lottoNumbers.numbers.contains(bonusNumber)
Lotto는 LottoNumbers에 대해 너무 잘 알고 있습니다.
LottoNumbers에 메시지를 보내도록 개선해보면 어떨까요?

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/LottoVendor.kt
> +object LottoVendor {
네이밍이 훨씬 좋아졌네요! 👍

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        val LOTTO_NUMBER_RANGE = 1..45
프로그래밍 요구사항에는 아래와 같은 항목이 있습니다.
> 일급 컬렉션을 쓴다.

하나의 로또번호와 관련된 일급 컬렉션을 만들어보면 어떨까요?

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
로또 번호가 중복으로 만들어질수는 없을까요? 🤔

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/view/ResultView.kt
> +                lotto.lottoNumbers.numbers.joinToString(
ResultView는 Lotto와 LottoNumbers에 대해서 너무 잘 알고 있습니다.
Lotto에 메시지를 보내도록 개선해보면 어떨까요?

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/view/ResultView.kt
> +            val matchBonusText = if (rank == LottoRank.SECOND) TEXT_MATCH_BONUS_NUMBER else TEXT_EMPTY
LottoRank에 값이 추가 또는 변경되었을 때 변경사항을 인지하기가 어려워보입니다.
변경사항을 쉽게 인지할 수 있도록 enum 비교를 exhausitive하게 개선해보면 어떨까요?

2024-12-04 13:26 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun from(
from 함수를 만들어주셨네요. 👍 
다만, 함수명만 보고서는 LottoRank가 어떤 방식으로 만들어지는지 이해가 잘 되지 않는데요.
함수명에 의도가 드러나도록 개선해보면 어떨까요?

2024-12-09 14:08 UTC, eshc123 commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
로또 번호가 중복으로 만들어 질 수 있다는 의미가 정확히 어떤 의미인지 궁금합니다! 현재 코드가 로또 번호가 중복으로 만들어 질 수 있다는 의미인지, 로또 번호가 중복으로 만들어질 수 있어야한다는 의미인지 궁금합니다!

2024-12-10 00:17 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
@eshc123 
제가 설명이 자세하지 못했네요 😅 
로또 번호가 중복으로 만들어질 수 있다는 의미입니다!
1에서 45까지의 숫자를 랜덤으로 섞어서 추출하고 있지만 로또 번호가 중복될 가능성이 있지 않을까요? 🤔

2024-12-11 00:32 UTC, eshc123 commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
중복도 가능하지 않을까 해서 따로 처리를 하지는 않았습니다! 로또 구매 시 자동으로 번호를 선택했을 때 똑같은 6개의 번호가 나올 수도 있을 것 같다고 생각은 하였는데, 똑같은 6개 번호 묶음이 나오지 않도록 하는게 맞을 것 같네요!

2024-12-12 13:16 UTC, eshc123 commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
다시 보니 로또 번호를 클래스로 만들 때 중복해서 인스턴스가 만들어질 수 있다는 뜻으로 말씀해주신 것 같아 강의와 강의 자료 참고해서 수정해보도록 하겠습니다!

2024-12-17 02:03 UTC, eshc123 commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +    override fun generate(): LottoNumbers = LottoNumbers(LOTTO_NUMBER_RANGE.shuffled().subList(START_INDEX, LOTTO_NUMBER_COUNT).sorted())
[6899fd1](https://github.com/next-step/kotlin-lotto/pull/1114/commits/6899fd14ab38a443f15d09cc229c241a54aeb321) 으로 수정하였습니다!

2024-12-17 02:04 UTC, eshc123 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        val matchingBonus = lottoNumbers.numbers.contains(bonusNumber)
[1a379a1](https://github.com/next-step/kotlin-lotto/pull/1114/commits/1a379a15c245afa7db8d641b428155c27caa31a1) 로 수정하였습니다!

2024-12-17 02:04 UTC, eshc123 commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        val LOTTO_NUMBER_RANGE = 1..45
[6899fd1](https://github.com/next-step/kotlin-lotto/pull/1114/commits/6899fd14ab38a443f15d09cc229c241a54aeb321) 으로 수정하였습니다!

2024-12-17 02:05 UTC, eshc123 commented on src/main/kotlin/lotto/view/ResultView.kt
> +                lotto.lottoNumbers.numbers.joinToString(
[da47d8e](https://github.com/next-step/kotlin-lotto/pull/1114/commits/da47d8e8ce9d117c8426e7466ade60b793b2f2e2)

2024-12-17 02:05 UTC, eshc123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun from(
[785295d](https://github.com/next-step/kotlin-lotto/pull/1114/commits/785295d70acf86ab8404d46630eb4b13e95ef6e6) 로 수정하였습니다!

2024-12-17 02:05 UTC, eshc123 commented on src/main/kotlin/lotto/view/ResultView.kt
> +            val matchBonusText = if (rank == LottoRank.SECOND) TEXT_MATCH_BONUS_NUMBER else TEXT_EMPTY
[9556443](https://github.com/next-step/kotlin-lotto/pull/1114/commits/95564437dab50bdc9592ae60c8f35a27e94cc2ce) 로 수정하였습니다!

2024-12-17 13:58 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2024-12-17 13:58 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private const val MAXIMUM_NUMBER = 45
init 블럭을 활용하여 유효성체크를 하도록 개선해보면 어떨까요?

2024-12-17 13:58 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/lottonumber/RandomLottoNumbersGenerator.kt
> +        val LOTTO_NUMBER_RANGE = 1..45
로또를 생성하는 곳에서 로또의 숫자범위와 로또의 개수를 알고 있습니다.
로또의 숫자범위와 로또의 개수를 알고 있는 곳을 최대한 활용하여 생성하도록 개선해보면 어떨까요?

2024-12-17 13:58 UTC, BeokBeok commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    ): String = lottoNumbers.numbers.joinToString(separator, prefix, postfix)
이 함수가 호출되는 곳을 살펴보니 ResultView에서 사용이 되네요.
출력과 관련된 로직은 ResultView에서 관리하도록 개선해보면 어떨까요?

2024-12-17 13:58 UTC, BeokBeok commented on src/main/kotlin/lotto/view/ResultView.kt
> +            val matchBonusText = if (rank == LottoRank.SECOND) TEXT_MATCH_BONUS_NUMBER else TEXT_EMPTY
@eshc123 
부연 설명을 드리겠습니다. 😅 
현재 구조에서는 LottoRank의 타입이 추가가 되면 추가된 타입은 else문의 로직이 호출되게 됩니다.
이는 예상치못한 오류를 발생시키게 됩니다.
enum 타입이 추가가 되더라도 빌드타임에 인지할 수 있도록 개선해보면 어떨까요?

ref. https://play.kotlinlang.org/byExample/03_special_classes/02_Enum

2024-12-17 13:58 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoNumbersTest.kt
> +    fun `로또 번호 개수가 6개가 아니면 예외를 발생한다`() {
테스트는 경계값을 기준으로 테스트하는 것을 권장합니다.
로또 번호 개수가 6개라면, 5개 혹은 7개에 대한 테스트를 작성해보면 어떨까요?

2024-12-17 13:58 UTC, merged