[STEP2] 로또 (자동)(1)
next-step/kotlin-lotto pull request #1125
Opened 2024-12-10 11:29 UTC by Hyojae-Park

view
- InputView : 구매 / 당첨번호 입력
- ResultView : 결과 확인

domain
- LottoTicket : 로또 정보 및 당첨 확인 로직
- LottoResult : 사용자의 전체 결과 확인 로직

controller
- GeneratorRandomNumbers : 랜덤 숫자 생성 기

2024-12-11 10:02 UTC, Flamme1004K requested changes
안녕하세요~ 리뷰 늦어서 죄송해요!

문자열 합 계산기 피드백 반영 및 로또 미션 잘 해주셨어요.

문자열 합 계산기 개선사항이 아직 남아있는 상태라, 로또 미션은 다음 리뷰 요청 때 리뷰하도록 하겠습니다.

감사합니다.

2024-12-11 10:02 UTC, Flamme1004K commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        val tokenizer = InputTokenizer(userInput ?: "0")
```suggestion
        if(userInput) {
               return 0;
        }
```

으로 빠른 반환을 해주면 더 좋지 않을까하네요~

2024-12-11 10:02 UTC, Flamme1004K commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +
tokenizer.getTokens()를 Int 값으로 변경하고, list 함수인 sum()을 사용해보는 건 어떨까요?

> for 문으로 사용하기 위해서 iterator 를 사용하였어요.
이번 교육에 참여하면 list api 에 훨씬 편한 api 들을 공부하고 있어요 :)

코틀린의 list 함수에는 유용한 함수들이 매우 많아요. 요번 기회에 kotlin에서 제공해 주는 list 함수들에 대해 학습하셨으면 좋겠어요 :) 그 안에는 sum() 함수도 있고, 교집합 함수을 구하는 함수도 있고 많은 부분이 있습니다.

2024-12-11 10:02 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
```suggestion
    private val delimiter: String
    private val tokens: List<String>

```

가변인 var보다는 val로 선언하는 게 더 안전하지 않을까하네요~

2024-12-11 10:02 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
>          if (result?.groupValues?.size == 3) { // 커스텀 구분자
https://github.com/next-step/kotlin-lotto/pull/1117#discussion_r1877456136

코멘트에 대해서 수정하기 어려운 이유를 좀 더 자세히 말해주실 수 있으실까요?

```kotlin
init {
        val result = Regex(DELIMITER_FILTER_EXPRESS).find(inputString)
        if (result != null) { // 커스텀 구분자
            delimiter = result.groupValues[1]
            tokens = result.groupValues[2].split(delimiter)
        } else {
            delimiter = DEFAULT_DELIMITER
            tokens = inputString.split(delimiter.toRegex())
        }
}
```

size == 3을 제거하고도 테스트 케이스에서 통과가 되고 있어서요~

<img width="310" alt="스크린샷 2024-12-11 오후 1 30 47" src="https://github.com/user-attachments/assets/b16d2dfb-ce6f-410b-a9ae-27075fcc9dda">

2024-12-11 10:02 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
>          val result = Regex(DELIMITER_FILTER_EXPRESS).find(inputString)
https://github.com/next-step/kotlin-lotto/pull/1117#discussion_r1877457312

상수로 관리하면 변경에 대한 유지보수도 좋아지죠. 하지만 Regex를 상수로 빼면 더 큰 장점이 있습니다. 아래의 글을 통하여 장점을 찾고 개선해보세요.

https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-6.-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%ED%94%BC%ED%95%98%EB%9D%BC

2024-12-11 10:03 UTC, Flamme1004K commented
커밋 로그도, 다음에는 기능에 따라 나누어 커밋을 해보셨으면 좋겠어요~ 😊

2024-12-12 05:57 UTC, Hyojae-Park commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
>          if (result?.groupValues?.size == 3) { // 커스텀 구분자
제가 잘못 이해 했어요. 조건문이 필요 없어 보인다는 의미로 해석하였어요

2024-12-12 06:10 UTC, Hyojae-Park commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
>          val result = Regex(DELIMITER_FILTER_EXPRESS).find(inputString)
```suggestion
    companion object {
        val REGEX_FILTER_OBJECT = Regex("//(.)\\n(.*)")
    }
```

이렇게 수정해 보았습니다.

2024-12-12 06:18 UTC, Hyojae-Park commented
리뷰 주신 내용 참고하여 수정 하였어요.
수정 중 불필요한 부분도 제거 하였습니다~
리뷰 부탁 드려요~ :)

2024-12-12 13:24 UTC, Flamme1004K requested changes
안녕하세요~

1단계 미션 피드백 매우 잘 해주셨어요! 2단계 미션 코멘트 남겼으니, 반영 후 다시 리뷰요청 부탁드립니다.

감사합니다!

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/InputTokenizer.kt
> +        val REGEX_FILTER_OBJECT = Regex("//(.)\\n(.*)")
피드백 반영 잘 해주셨어요!

2024-12-12 13:24 UTC, Flamme1004K commented on README.md
> +[13, 14, 16, 38, 42, 45]
기능 요구사항 정리 잘 해주셨습니다!

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/LottoApp.kt
> +
해당 로직은 resultView의 메소드로 넣는 건 어떨까요?

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +                val number = (1..45).random()
1..45 숫자를 미리 만들어 놓을 수는 없으려나요?

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +            }
코틀린의 list 함수에는 shuffle과 take 함수가 있어요. 이 함수를 사용하여 좀 더 간결하게 코드를 리팩토링해보세요.

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +class GeneratorRandomNumbers {
companion object에 들어가는 함수만 있다면 class 가 아닌 object class를 사용해보는 건 어떨까하네요~

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +}
toString과 equals, hashcode를 오버라이드 하셨군요! 이 부분에 대해서는 kotlin의 data class에 대해서 한번 적용해보면 어떨까요? 

그리고 data class에 대해서 설명해주시겠어요?

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    }
"이익" , "손해" 보다는, enum 값으로 의미있게 만들어보는 건 어떨까요?

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +        const val TICKET_PRICE = 1000
```suggestion
        const val TICKET_PRICE = 1_000
```

이 부분은 _바로 보기 쉽게 만드는 것도 좋겠죠~?

2024-12-12 13:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
LottoTicket의 lottoNumbers는 가변이 아닌, 불변으로 관리해도 좋아보이네요~ 로또는 한번 생성되면 변하면 안된다고 생각해요~

2024-12-13 01:47 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +}
data class 는 equal 과 hashcode 를 자동 생성해 주는 것으로 알고 있어요.
int 로 로또 번호를 생성하고 비교 기능까지 지원하고 싶어서 class 로 만들었는데,
현재는 data class 로 전환해도 될것 같습니다. :)

2024-12-13 02:20 UTC, Hyojae-Park commented
좋은 의견 감사 드립니다.
제가 작성한 코드에 대해 더 심사숙고 하게 되는 시간인것 같아요.
수정 사항 반영하였어요. 리뷰 부탁드립니다~

2024-12-13 13:30 UTC, Flamme1004K requested changes
안녕하세요~

2단계 로또 미션 피드백 잘 해주셨습니다. 몇 가지 코멘트 남겼으니 코멘트 반영 후 다시 리뷰 요청 부탁드립니다.

하루하루 빠짐없이 열심히 해주시는 모습은 매우 훌륭합니다. 다만, 미션을 빠르게 진행하는 것보다 미션의 요구사항과 피드백을 보고 더 많은 고민을 하고, 자신이 만족할 정도로 코드를 리팩토링하여 리뷰 요청을 해주셨으면 좋겠습니다.

추가적인 피드백으로 지금 현재 진행하고 있는 미션 요구사항을 README.MD에 정리하고, 도메인에 맞는 시나리오를 TODO로 정리한 다음 기능을 개선하거나, 테스트를 만드는 방향으로 진행해 보시면 좋을 것 같아요.

다음 리뷰 요청 기대하겠습니다.

화이팅입니다.

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
GeneratorRandomNumbers 클래스 위치를 controller한 이유를 알 수 있을까요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +    }
둘 다 같은 메소드로 보이는데요~ 하나로 합쳐보는 건 어떨까요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
자동차 미션에서도 경험해보셨겠지만, 랜덤한 요소인 GeneratorRandomNumbers를 LottoTicket에서는 어떻게 테스트를 해야할까요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val LOTTO_NUMBERS: MutableMap<Int, LottoNumber> = mutableMapOf()
LOTTO_NUMBERS를 가변 상수로 관리하면 어떠한 단점이 있을까요? LOTTO_NUMBERS가 필요한 이유는 무엇인가요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +            require(value in 1..45)
해당 검증 로직은 정적팩토리메서드의 검증 로직이 아닌 LottoNumber 클래스의 검증 로직이 아닐까하네요~

2024-12-13 13:30 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +            return tickets.toList()
적절한 Kotlin List API의 함수를 찾아 리팩토링 해보시겠어요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +    }
해당 테스트는 등수에 대한 테스트가 아닌 일치에 대한 테스트가 아닐까하네요~ 적절한 테스트 명을 짓고, `@CsvSource` 테스트를 통해서 하나의 테스트 케이스에 대해서 다양한 파라미터를 입력하여 테스트할 수 있도록 개선해보세요.

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +        val tickets = LottoTicket.generateLottoTickets(1)
랜덤 생성에 대한 부분은 GeneratorRandomNumber의 테스트라고 생각해요. GeneratorRandomNumber 테스트로 분리해  보시고,

Readme에 현재 선언해놓은 도메인 클래스에 대해 검증할 수 있는 테스트가 무엇이 있는지 정리하고 정리한 내용으로 테스트 케이스를 만들어보세요.

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoResultTest.kt
> +class LottoResultTest {
등수에 대한 테스트 케이스도 만들어 볼까요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +    }
두 테스트 케이스의 차이는 무엇인가요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +    }
해당 테스트 케이스가 LottoNumber에 대한 테스트 케이스인가요?

2024-12-13 13:30 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +        println(ticket)
대부분 테스트 케이스마다 println이 있네요. 지우는게 좋지 않을까요?

2024-12-14 00:50 UTC, Hyojae-Park commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
랜덤한 사항에 대해서 테스트 하기 어렵기 때문에 domain 과 분리 하여 controller 로 위치 시켰어요

2024-12-14 00:56 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val LOTTO_NUMBERS: MutableMap<Int, LottoNumber> = mutableMapOf()
이전 리뷰에서 상수로 관리 하는게 좋다고 하셔서 수정했어요.
다만 가변으로 정의 한것은, 모든 번호 (1~45)를 정의 해 두는 것보다 필요 시 getOrPut 으로 추가 하도록 적용했어요.

2024-12-14 01:10 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +    }
제거 하였어요

2024-12-14 01:14 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +    }
객체 비교 라는 점에서 동일하다고 볼 수 있을것 같아요.

2024-12-14 03:09 UTC, Hyojae-Park commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
interface 로 선언하여 테스트 케이스 작성하였어요.

2024-12-14 06:33 UTC, Flamme1004K requested changes
안녕하세요! 

2단계 미션 피드백 반영 감사합니다. 추가 코멘트가 있으니 확인 후 다시 리뷰요청 부탁드립니다.

감사합니다.

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
효재님이 학습하신 controller와 domain의 개념은 무엇인가요~? controller와 doamin의 개념을 다시 한번 새겨보고 GeneratorRandomNumbers가 과연 controller에 해당하는 요소인지 생각해 보시겠어요?

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val LOTTO_NUMBERS: MutableMap<Int, LottoNumber> = mutableMapOf()
https://github.com/next-step/kotlin-lotto/pull/1125#discussion_r1879318344

혹시 이 리뷰에 대한 피드백이라면, LOTTO_NUMBERS getOrPut으로 하는 것보다는, GeneratorLottoNumbers 에서 generateNumbers에 대한 반환 값을 Int가 아닌 LottoNumber로 반환하도록 만들면 피드백에 대해 적용하기 좋을거에요.

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
전 해당 두 메서드가 합쳐져도 좋을 것 같네요~

constructor(vararg elements: Int)의 테스트 코드에 대해서 constructor(elements: List<Int>)도 충분히 표현이 가능해보여요!

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        println("$ticket equal number count $numberCount")
println은 제거해줘도 좋겠죠?

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
해당 LottoTicket도 변경이 이루어지지 않고 불변으로 관리된다면 data class로 사용해도 좋아보이네요~

2024-12-14 06:33 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoResultTest.kt
> +    }
> 해당 테스트는 등수에 대한 테스트가 아닌 일치에 대한 테스트가 아닐까하네요~ 적절한 테스트 명을 짓고, `@CsvSource` 테스트를 통해서 하나의 테스트 케이스에 대해서 다양한 파라미터를 입력하여 테스트할 수 있도록 개선해보세요.

지난번 피드백에 대한 반영이 안된 부분이 있네요. 반영 부탁드릴게요~

2024-12-14 06:33 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +class LottoNumberTest {
LottoNumber의 생성자 테스트와 생성 시 예외에 대한 테스트도 추가 가능해보이네요~

2024-12-14 06:33 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +class LottoTicket {
LottoTicket에도 생성자에 대한 유효성 검증이 있으면 좋겠네요!

2024-12-14 06:45 UTC, Flamme1004K commented
11월 27일날 재성님이 공유해주신 글과 영상이 있는데요. 이 글과 영상을 보고, 앞으로의 로또 미션을 어떻게 수행할지 고민해보셨으면 좋겠어요 :) 

- https://codingnuri.com/seven-virtues-of-good-object/
- https://www.youtube.com/watch?v=dJ5C4qRqAgA

추가로, 현재 미션은 MVC 패턴만으로도 controller, model(domain), view에 대해서 나눌 수가 있습니다.
- https://velog.io/@langoustine/%EC%97%AC%EA%B8%B0%EB%8F%84-MVC-%EC%A0%80%EA%B8%B0%EB%8F%84-MVC-MVC-%ED%8C%A8%ED%84%B4%EC%9D%B4-%EB%AD%90%EC%95%BC

를 읽고, 현재 패키지 구조가 MVC에 맞는지도 한번 고민해 보세요.

2024-12-14 16:00 UTC, Hyojae-Park commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
도메인은 데이터를 구현하고, 컨트롤러는 뷰와 모델을 연결해 주는 것으로 이해 하고 있어요.
다만, GeneratorRandomNumber 의 경우 테스트 하기 어려운 부분으로 별도롤 분리 하였는데, 가볍게 controller 로 넣는것으로 고려 하였어요.
그런데, 생각해 봐도 다른 대안은 떠오르지 않아요.

2024-12-14 16:10 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val LOTTO_NUMBERS: MutableMap<Int, LottoNumber> = mutableMapOf()
말씀 하신 내용을 고려 안했던건 아닌데, 어떤 장점이 있는지 잘 모르겠어요.
사용가능한 번호의 범위도 generator 에서 관리 해야하고, generator 가 너무 많은 일을 하는것 같아요.

2024-12-14 16:19 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
lottoNumber 를 생성자로 사용한다면 data class 로 변경은 가능 할것 같아요.
제가 굳이 int 배열을 매개변수로 사용 중인데..
바꾸는게 좋을까요 :)

2024-12-14 16:25 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoResultTest.kt
> +    }
지난번엔 결과 하나(1등)만 확인한 테스트였고, 피드백에 따라 테스트 케이스를 추가하였어요.
언급 하신 대로 테스트 파라미터를  추가하도록 하겠습니다.

2024-12-15 06:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val LOTTO_NUMBERS: MutableMap<Int, LottoNumber> = mutableMapOf()
너무 많은 일이라는게 무슨 의미인지는 잘 모르겠네요. 현재 generator가 하는 일은 단순히 1~45 안에서 6개의 숫자를 뽑아주는 것인데, 이게 정말 많은 일을 하는 것일까요?

그리고, GeneratorLottoNumbers인데, LottoNumber를 반환하지 않고, Int 자료형을 반환하는 것도 또한 어색해 보여요~

2024-12-15 06:09 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorRandomNumbers.kt
> +object GeneratorRandomNumbers {
GeneratorRandomNumber 또한 도메인에 한 부분입니다.

자동 로또는 6개의 랜덤한 숫자를 이용하여 로또를 만든다.에 대한 시나리오만 생각을 했을 때 이 경우가 도메인 로직과 같이 포함되어야지, 도메인과 뷰를 연결해주는 컨트롤러에 포함되는 부분은 매우 어색하다고 생각해요.

랜덤 한 사항에 대해서 테스트가 어렵기 때문에 domain과 분리하여 컨트롤러에 위치시킨다는 생각보다는 도메인과 함께 두어 도메인의 랜덤 한 사항에 대해서 테스트를 쉽게 하기 위해 인터페이스를 사용하여 좀 더 테스트를 용이하게 만든다는 표현이 더 옳지 않을까 하네요~

2024-12-15 06:21 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
코틀린 언어는 간결함부터 시작합니다. 그 간결함을 표현해주기 위해 코틀린 언어 자체에서도 다양한 클래스를 제공해주죠. 그래서 위와 같은 피드백을 드린 부분이 있습니다.

Int 배열을 매개변수로 한정지어 LottoTicket 클래스를 사용해야하는 이유는 무엇인가요? LottoTicket은 LottoNumber로 만들어질텐데 말이죠. 

제가 생각하기에는 Int 배열을 써야 테스트 코드 짜기가 쉬워지고, GeneratorLottoNumbers의 반환 값에 대해서 연결시켜주기 위해서 밖에 안 보이네요.

2024-12-15 09:42 UTC, Flamme1004K commented on README.md
> +  - 1~45 숫자 중 번호 생성
다음 리뷰 요청에는 작성한 디자인 설계를 그동안 만든 클래스를 통해 정리해서 README.md 작성해 주시겠어요?

ex ) 

로또번호(LottoNumber)
       - 1 ~ 45의 값을 가진다. [ ] 
       - 1 ~ 45 사이 외의 값이 들어오면 예외를 일으킨다. [ ]
       - 숫자 자료형 하나만 가진다. [ ]

로또티켓(LottoTicket)
        - ....

2024-12-16 05:48 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
생성자 수정하였어요.

2024-12-16 05:49 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        println("$ticket equal number count $numberCount")
print 문제거 했습니다~

2024-12-16 08:10 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoResultTest.kt
> +    }
list 형태로 MethodSource 적용하였습니다~

2024-12-16 08:12 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
말씀 하신 사항을 의도하였습니다. 그런 점이 객체간 느슨한 연결이 구현하였다고 생각하였고요.
리뷰 주신데로 코틀린의 간결함을 위해서 LottoNumber 로 수정 하였습니다~

2024-12-16 08:29 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +class LottoNumberTest {
예외 케이스 테스트 추가 하였습니다

2024-12-16 08:50 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +class LottoTicket {
유효성 검사 및 테스트 케이스 추가하였어요

2024-12-16 10:21 UTC, Hyojae-Park commented on README.md
> +  - 1~45 숫자 중 번호 생성
README 파일 업데이트 하였어요

2024-12-16 11:00 UTC, Hyojae-Park commented
안녕하세요. 좋은 의견 감사 드립니다.
링크 주신 글과 영상도 잘 시청하였어요.
generator 는 controller 에 있으면 안되며, class 로 구현하는 것은 바람직하지 않다는... 의미 인건지요?
명확하게 집어 주시면 좋을것 같아요.
그렇게 방향을 잡고 수정해 보려 했으나, 접근이 어려운 상태에요.
1. generator 는 controller 인가? -> LottoNumber / LottoTicket 을 사용하는 controller 라고 생각되요
2. generator 가 꼭 별도 class 로 구현해야 할까? -> LottoTicket or LottoNumber 에 포함되는 것도 어색한것 같아요.

하여, 해당 부분은 많은 고민을 했으나, 특별한 조치를 취하지 못했어요..
의견 부탁 드립니다.

2024-12-16 14:04 UTC, Flamme1004K approved these changes
안녕하세요.

2단계 미션 피드백 고생하셨습니다. 이만 머지하도록 하겠습니다.

추가 코멘트는 3단계 미션과 함께 반영해주세요~

3단계 미션 화이팅입니다!

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorLottoNumbers.kt
> +}
> 안녕하세요. 좋은 의견 감사 드립니다.
> 링크 주신 글과 영상도 잘 시청하였어요.
> generator 는 controller 에 있으면 안되며, class 로 구현하는 것은 바람직하지 않다는... 의미 인건지요?
> 명확하게 집어 주시면 좋을것 같아요.
> 그렇게 방향을 잡고 수정해 보려 했으나, 접근이 어려운 상태에요.
> 
> generator 는 controller 인가? -> LottoNumber / LottoTicket 을 사용하는 controller 라고 생각되요
> generator 가 꼭 별도 class 로 구현해야 할까? -> LottoTicket or LottoNumber 에 포함되는 것도 어색한것 같아요.
> 하여, 해당 부분은 많은 고민을 했으나, 특별한 조치를 취하지 못했어요..
> 의견 부탁 드립니다.

명확하게 말하자면, 도메인이죠. generator는 controller 인가? generator 가 꼭 별도 class로 구현되어야 할까?라는 방향보다는 로또(자동)이라는 도메인 하나만 봤을 때 자동 로또 번호를 만들어주는 generator가 없으면 과연 로또(자동)일까?라는 생각을 한번 해보시면 이게 도메인인지, 컨트롤러인지 방향성이 잡힐 거예요.

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/GeneratorLottoNumbers.kt
> +    private val LOTTO_NUMBERS = (1..45).map { LottoNumber(it) }
LottoTicket의 6 / LottoNumber의 범위인 1..45 가 각 클래스마다 중복으로 선언되어 있네요. 이를 한 곳에다가 모아줄 수 없으려나요~?

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    }
```suggestion
    private enum class RateResult(val koreanText: String) {
        WIN("이익"),
        LOSS("손해"),
    }
```

RateResult가 더 어울리지 않을까요? 

```
val rateResult: RateResult
        get() = if (returnRate > 1) WIN else LOSS
```

또한 RateResult 객체를 넘겨주고, ResultView에서 해당 객체의 text를 사용할 수는 없으려나요?

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        require(lottoNumbers.size == 6)
예외를 만들 때는 메시지가 있어야되겠죠?

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        return numberCount
List API에 대해 학습하고 있다고 했죠? 해당 코드를 kotlin의 List API로 더 간결하게 만들어보세요.

2024-12-16 14:04 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +            return tickets.toList()
https://www.baeldung.com/kotlin/initialize-list#list-builders

List-builders를 통해서 로직을 개선해 보세요.

2024-12-16 14:04 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +            )
테스트가 두 개나 들어가 있네요. assertThatExceptionOfType를 했을 경우 첫 번째 케이스에 대해서 익셉션이 걸릴 것 같은데요.

이 경우에는 두 번째 케이스에 대해서 검증하지 못하는 게 아닐까요? 두 경우를 검증할 수 있도록 변경해 보세요.

2024-12-16 14:04 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +    }
1등 / 3등 확인에 대한 테스트는 LottoResult의 시나리오라고 생각해요.

6개가 일치한다 /  4개가 일치한다가 더 적절한 LottoTicketTest의 시나리오가 아닐까요?

2024-12-16 14:04 UTC, Flamme1004K commented on README.md
> +  - 1~45 숫자 중 번호 생성
6개의 숫자를 자동으로 추출한다 라는 시나리오는 없을까요?

좀 더 디자인 설계에 대해서 명확하게 정리해보세요.

2024-12-16 14:04 UTC, merged

2024-12-17 01:24 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +            )
케이스를 분리하였어요

2024-12-17 01:26 UTC, Hyojae-Park commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +    }
케이스 명이 명확하지 않아서 그런것 같아요.
동일한 번호의 갯수를 테스트 하고 있는데, 의도를 명확하게 하기 위해 이름을 변경했어요.

2024-12-17 01:32 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    }
RateResult 를 감추고 싶었던것 같아요. 그러다 보니 네이밍이 어긋 난것 같네요..
리뷰 주신대로 RateResult 를 사용하도록 변경했어요.

2024-12-17 01:33 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        require(lottoNumbers.size == 6)
네 :)

2024-12-17 01:38 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        return numberCount
filter 를 사용했어요.

2024-12-17 02:32 UTC, Hyojae-Park commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +            return tickets.toList()
buildList 를 사용했어요.

2024-12-17 06:02 UTC, Hyojae-Park commented on src/main/kotlin/lotto/controller/GeneratorLottoNumbers.kt
> +    private val LOTTO_NUMBERS = (1..45).map { LottoNumber(it) }
선언한 상수들에 대해 역할을 검토해 보고 위치해야할 클래스로 이동하였습니다.
- LottoNumber :  가질수 있는 숫자의 범위 (최소/최대)
- LottoTicket : 필요한 번호의 갯수

2024-12-17 06:03 UTC, Hyojae-Park commented on README.md
> +  - 1~45 숫자 중 번호 생성
랜덤 생성에 대해서 더 고민해 보고, 숫자를 생성하는건 내부로 숨기고
한장의 티켓(6개의 숫자)를 추출하여 티켓을 생성하는 형태로 수정하였어요.

2024-12-17 06:08 UTC, Hyojae-Park commented on src/main/kotlin/lotto/controller/GeneratorLottoNumbers.kt
> +}
~er 이 필요한가.. 라는 언급도 있다보니 어디에 붙여야하나 라는 것까지 고려하다보니 방향을 잡기 쉽지 않았어요. :)
로또(자동) 에 대해 generator 를 domain 으로 변경하여 숫자 범위를 입력 받아 로또 티켓을 생성하는 클래스로 수정하였습니다.  훨씬 정돈되고 명확해진것 같아요~