🚀 3단계 - 로또(2등)
next-step/kotlin-lotto pull request #1127
Opened 2024-12-12 12:34 UTC by Aimbe

안녕하세요 경록님! 저번 단계 피드백부터 위주로 진행하면서 2등 보너스볼도 추가했습니다! 
저번 피드백때 여러 레퍼런스 주셔서 도움이 많이 됐습니다 ㅎㅎ 나머지는 4단계 진행하면서 더 해보겠습니다!

2024-12-13 08:58 UTC, Rok93 requested changes
정호님 3단계 잘 구현해주셨습니다. 👍
몇몇 코멘트 남겨두었으니 확인해서 반영 부탁드릴게요.

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +        return winningStatistics[rank] ?: 0
이전 단계에도 이 부분에 코멘트를 달았었던 것 같은데, 혹시 놓치셨나 싶어 추가로 코멘트 달아두겠습니다. 

0의 의미를 한눈에 파악하기가 어려울 것 같은데, 상수로 추출해보면 어떨까요? 

[의미가 불분명한 매직 넘버를 상수로 선언하라.](https://javabom.tistory.com/28)

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/Rank.kt
> +            }
enum 요소가 추가되더라도 해당 로직을 수정할 수 없도록 변경해볼 수는 없을까요? 

`Rank.entries`를 적절히 사용해보면 수정이 가능할 것 같습니다. 😉

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +            rank.prize * count
[이전 코멘트](https://github.com/next-step/kotlin-lotto/pull/1102#discussion_r1864099891)로 말씀드렸던 부분인데, 
[rank 객체에게 메지시를 보내](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)보면 어떨까요? 
 
```suggestion
            rank.xxxx(count)
```

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +            .map { (matchCount, matchBonus) -> Rank.from(matchCount, matchBonus) }
Lotto.match의 결과로 `Rank`를 반환하면 더 깔끔할 것 같은데, 어떻게 생각하시나요? 😃

```suggestion
            .map { it.match(winningNumber, bonusBall) }
```

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +    // Lottos 라는 객체는 구입한 로또들의 집합.
로직이 복잡해서 주석의 설명이 필요한 경우도있지만, 지금의 경우에는 네이밍으로도 충분히 의도가 파악되는 것 같아서
굳이 주석 설명까지 추가해야하나? 라는 생각이 들어요. 😃

불필요한 주석은 제거해주시면 좋을 것 같습니다. 😃

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +class PurchasedLottos(private val tickets: List<Lotto>) {
`Lotto`의  `일급 컬렉션`이니 `Lottos`가 조금 더 직관적이라고 생각됩니다. 😃

접두사로 `Purchased`가 붙어버리니 Lotto와 다른 성질을 가지고있는건가...? 라는 생각을 가지고 코드를 살펴봤는데 크게 다른 성질을 가졌다고 생각되지는 않았어요. 😃

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +    fun size(): Int = tickets.size
size도 lottos처럼 프로퍼티로 정의해보면 어떨까요? 🤔

2024-12-13 08:58 UTC, Rok93 commented on src/main/kotlin/lotto/service/LottoService.kt
>  class LottoService {
LottoService가 가지고있는 두 puchase, checkWinning 역할은 새로운 도메인 객체들에게 위임해볼 수 있을 것 같은데요. 

로또를 생성해주는 `LottoFactory`를 만들어보시면 어떨까 싶어요. 

당첨을 확인하는 역할은 winningNumbers, bonusBall을 가진 새로운 객체에게 위임해볼 수 있을 것 같아요. 😃

2024-12-13 10:31 UTC, Aimbe commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +            .map { (matchCount, matchBonus) -> Rank.from(matchCount, matchBonus) }
여기서 좀 더 세분화해서 결과에 대한 data클래스를 나누려고 MatchResult 객체를 빼서 뒀는데, 말씀하신 내용 생각해보니 
해당 부분에 대한 책임을 rank로 대신할 수 있을것 같다는 생각이 드네요!

2024-12-13 10:38 UTC, Aimbe commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +        return winningStatistics[rank] ?: 0
이부분 놓쳤네요 ㅎㅎ 추가해 놓겠습니다.

2024-12-13 11:28 UTC, Aimbe commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +            rank.prize * count
아 ㅎㅎ 사실 이부분 calculatePrize라는 금액 계산 함수를 rank에 넣어 놨었는데,
생각해보니 Rank가 가격 계산을 담당하는 형태가 되서 간단한 계산은 외부에서 보는게 더 직관적일것 같아서 빼놨습니다!
해당 메소드의 이름이 calculateTotalPrize이라 현재에는 보기에도 좀 더 명확해보여서,
좀 더 복잡한 함수가 들어가면 객체 책임 분리하면서 빼놓을까 생각했는데, 어떻게 생각하실까요~~?

2024-12-13 11:30 UTC, Aimbe commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +            rank.prize * count
Rank같은 enum 객체는 팩토리처럼 해당 enum의 값을 생성/선택하는 책임을 주로 가지고, 단순한 데이터 제공은 외부에 노출하는 게 더 자연스러울 수 있다고 생각이 들어서요!

2024-12-13 11:35 UTC, Aimbe commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +class PurchasedLottos(private val tickets: List<Lotto>) {
ㅋㅋㅋ 뭔가 Lottos라고 해버리니까 제가 헷갈리더라구요. 이 로또의 집합은 유저가 산 ticket개념 아닌가? 싶어서
제가 생각하기에 더 명확한 Purchased 접두어를 넣어 변경했는데.. 성질을 생각하니 경록님 의견이 더 맞아보이네요 ㅎㅎ!!

2024-12-13 12:00 UTC, Aimbe commented on src/main/kotlin/lotto/service/LottoService.kt
>  class LottoService {
넵 service는 추상화 계층으로만 쓰고, 도메인에 대한 책임을 조금 더 위임해보겠습니다~

2024-12-14 10:13 UTC, Rok93 commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +            rank.prize * count
질문 주신부분에대한 제 의견을 남겨보자면

 전 enum객체는 팩토리처럼 해당 객체의 값을 생성/선택 하는 책임을 주로 가지고, 비즈니스에 대한 계산은 해당 클래스에서 하기 애매하는 생각이 들어서요!

전 enum 객체로 단순히 하나의 객체라고 생각해요 : )
자신의 역할과 책임을 가지고 다른 객체와 협력하는 하나의 객체라고 생각합니다.

비즈니스에 대한 계산은 해당 클래스에서하기 애매하다는 의견에는 조금 반대되는 생각을 하고있습니다. :thinking_face:

2024-12-14 11:11 UTC, Rok93 approved these changes
정호님 피드백 반영 잘해주셨습니다! 👍👍
3단계는 이정도면 충분한 것 같아서 이만 머지하도록하겠습니다. 😃
추가적으로 간단한 코멘트 남겨뒀는데, 다음 미션 진행전에 같이 확인해주세요. 😉

다음 단계에서 뵙겠습니다. 🙏

2024-12-14 11:11 UTC, Rok93 commented on src/main/kotlin/lotto/domain/Lottos.kt
> +            .mapValues { it.value.size }
`grounpingBy`를 활용하도록 변경해볼 수 있을 것 같네요. 😃
```suggestion
        return tickets
            .map { it.match(winningNumber, bonusBall) }
            .groupingBy { it }
            .eachCount()
```

2024-12-14 11:11 UTC, Rok93 commented on src/main/kotlin/lotto/domain/Rank.kt
> +        fun from(
from에 대한 테스트 코드를 추가해주시면 좋을 것 같아요. 😃

해당 로직은 한눈에 파악하기가 어려운 것 같은데, 

먼저 bonus number가 일치하는 케이스를 우선적으로 확인하고  그 다음에 match number와 상관없이 전체에 관련된 

예를들면 저는 `partition` 확장함수를 활용해서 아래와 같이 변경해볼 수도 있겠다고 생각했어요.
```kotlin
    return entries.partition(Rank::hasBonus)
            .let { (ranksWithBonus, ranksWithoutBonus) ->
                ranksWithBonus.find { it.matchCount == matchCount && it.hasBonus }
                    ?: ranksWithoutBonus.find { it.matchCount == matchCount }
                    ?: NONE
            }
```

2024-12-14 11:11 UTC, merged

2024-12-16 12:00 UTC, Rok93 commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +class PurchasedLottos(private val tickets: List<Lotto>) {
아! 그런 의도시라면 충분히 `Purchased`의 네이밍의 이유는 이해가 됩니다. 😃
저의 생각은 Lotto와 일급 컬렉션이 네이밍의 결을 동일하게 맞춰주는게 좋겠다는 이야기였어요!

2024-12-20 00:15 UTC, Aimbe commented on src/main/kotlin/lotto/domain/Lottos.kt
> +            .mapValues { it.value.size }
groupping by를 사용하니 더 깔끔하고 가독성이 좋아진것 같습니다! ㅎㅎ 감사합니다.

2024-12-20 00:21 UTC, Aimbe commented on src/main/kotlin/lotto/domain/Rank.kt
> +        fun from(
넵 ㅎㅎ 다시 봐도 해당 코드는 테스트 코드가 없으면 한눈에 보기 힘들어 보이네요. 
제안해주신 partition 사용하주시는 방법이 가독성이 더 좋은것 같아 해당 방법으로 진행해볼게요!

2024-12-20 11:42 UTC, Aimbe commented on src/main/kotlin/lotto/domain/Rank.kt
> +        fun from(
덕분에 partition사용법도 스터디 하게됐습니다!ㅎㅎ감사합니다.

지금은 from 객체를 만드는것에 있어서 bonusNumber에 유무가 파라미터로 필요해서
```
return entries.partition(Rank::hasBonus)
        .let { (ranksWithBonus, ranksWithoutBonus) ->
            if (matchBonus) {
                ranksWithBonus.find { it.matchCount == matchCount }
            } else {
                ranksWithoutBonus.find { it.matchCount == matchCount }
            } ?: NONE
        }
```

이런식으로 변경했는데 어떨까요?