[STEP4] 로또(수정) 리뷰 요청 드립니다.
next-step/kotlin-lotto pull request #1136
Opened 2024-12-20 09:07 UTC by Hyojae-Park

안녕하세요.
좋은 의견 감사 드립니다.
드디어 마지막 단계까지 왔어요 :)
리뷰 요청 드립니다~

2024-12-21 03:54 UTC, Flamme1004K requested changes
안녕하세요~

4단계 미션 고생하셨어요! 몇 가지 코멘트 남겼으니, 반영 후 리뷰 요청 부탁드릴게요.

감사합니다!

2024-12-21 03:54 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +        }.sum()
피드백 반영 잘 해주셨어요~ rankMap도 LottoResult 클래스 내에서만 수정할 수 있도록 변경해보세요!

2024-12-21 03:54 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/LottoApp.kt
> +        val tickets = GeneratorLottoNumbers.generateRandomLottoTickets(autoTicketCount)
```suggestion
        val manualTickets = inputView.inputManualTickets()
        val autoTicketCount = count - manualTickets.size
        val autoTickets = GeneratorLottoNumbers.generateRandomLottoTickets(autoTicketCount)
```

tickets보다 autoTickets이 더 알맞는 네이밍으로 보이네요~

2024-12-21 03:54 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/LottoApp.kt
> +        val manualTickets = inputView.inputManualTickets()
manualTickets이 생겼다면, LottoResult도 manualTickets도 포함시켜야하지 않을까요?

2024-12-21 03:54 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +        println(rank)
println은 지워주는 게 좋겠죠~?

2024-12-21 07:38 UTC, Hyojae-Park commented
안녕하세요. 꼼꼼한 리뷰 감사 드립니다~
외부 변경 불가하도록 private set 을 적용하였습니다
결과 오류 및 테스트 오류 수정했어요
리뷰 부탁 드립니다

2024-12-22 06:20 UTC, Flamme1004K approved these changes
안녕하세요!

4단계 미션 고생하셨습니다! 이만 머지하도록 하겠습니다.

앞으로 남은 미션 화이팅입니다!

감사합니다!

2024-12-22 06:20 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/LottoApp.kt
> +        val totalTickets = manualTickets + autoTickets
피드백 반영 잘 해주셨어요!

2024-12-22 06:20 UTC, merged