3단계 - 로또(2등)
next-step/kotlin-lotto pull request #133
Opened 2021-03-14 16:12 UTC by SeoJinHyuk14

2등에 보너스 번호도 매칭되도록 수정

2021-03-15 14:04 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다

2021-03-15 14:04 UTC, kyucumber commented on src/main/kotlin/LottoCard.kt
> -    fun getMatchCount(winningLottoCard: LottoCard): Int {
이 부분을 제거하신 이유가 있을까요?
입력 단계에서 validation을 수행하는게 아니라 `LottoCard`라는 도메인 객체 자체에 validation이 추가되어 있어야 하지 않을까요?

```kotlin
LottoCard(listOf(1, 2, 3, 4, 5, 6, 7, 8, 9))
```

위 코드는 아무런 예외없이 잘 동작할 것 같네요.

2021-03-15 14:04 UTC, kyucumber commented on src/test/kotlin/LottoTest.kt
> +            lotto.validateLottoCard("")
`@ParameterizedTest`의 `@NullSource` `@EmptySource`를 사용할 수 있지 않을까요?

2021-03-16 16:09 UTC, SeoJinHyuk14 commented on src/main/kotlin/LottoCard.kt
>      var cards: List<LottoCard> = (1..cnt).map { LottoCard() }
@kyucumber
안녕하세요!
해당 클래스는 생성자가 두개 있는데요.
하나는 숫자를 자동으로 생성하는 케이스와, 수동으로 입력받는 케이스 2개로 사용하고 있어요.
해당 3단계에서는 당첨번호를 입력받을때 사용하고 있어요.

말씀해주신 내용인 4단계 문제를 확인하고 왔는데요.
수동으로 번호를 입력 받는 것도 동일하게 번호를 생성자로 전달하면 될것 같아서 문제가 될거 같지는 않아요 :)

ps. 저는 로또 번호를 생성하는것은 LottoCards가 아닌 LottoCard의 역할이라고 생각했어요!
감사합니다! 👍  다른 의견이 있다면 말씀주세요!

2021-03-16 16:22 UTC, SeoJinHyuk14 commented on src/main/kotlin/Winning.kt
> +    }
저는 보너스볼에 따라 출력할 텍스트가 바뀌기 때문에 상태가 있는 도메인 로직이라고 생각을 했어요..
출력을 시키는 부분만 뷰라고 생각을 했네요.

그런데 다시 생각해보니, 리뷰어님 말씀대로 뷰쪽으로 이동하는것도 좋을것 같다고 생각이 들었어요 :)
반영토록 하겠습니다. 감사합니다!

2021-03-16 16:34 UTC, SeoJinHyuk14 commented on src/main/kotlin/Lotto.kt
> +        require(!numberLine.isNullOrBlank()) { "로또 번호를 반드시 입력해야 합니다." }
@kyucumber

로또 숫자를 입력 받는것은 InputView에 해당하고,
로또 번호가 6개이어야하고, 입력된 숫자의 범위가 1~45이어야 한다는것은 
도메인 로직이라고 저는 생각을 해서 다음과 같이 배치를 한것 같아요.

리뷰어님의 의견도 맞다고 생각하는데요. 저는 이대로도 괜찮지 않을까? 라고 생각이 들었어요.
리뷰어님의 생각은 어떠신가요? :)

2021-03-16 16:37 UTC, SeoJinHyuk14 commented on src/main/kotlin/LottoCard.kt
> -    fun getMatchCount(winningLottoCard: LottoCard): Int {
앗 해당 로직은 LottoCard -> Lotto로 이동되었습니다!

2021-03-16 16:46 UTC, SeoJinHyuk14 commented on src/test/kotlin/LottoTest.kt
> +            lotto.validateLottoCard("")
앗! 이런게 있었군요!
감사합니다 👍 👍

2021-03-17 12:25 UTC, kyucumber commented on src/main/kotlin/LottoCard.kt
>      var cards: List<LottoCard> = (1..cnt).map { LottoCard() }
```
안녕하세요!
해당 클래스는 생성자가 두개 있는데요.
하나는 숫자를 자동으로 생성하는 케이스와, 수동으로 입력받는 케이스 2개로 사용하고 있어요.
```

이 부분은 `LottoCard`에 대한 내용을 말씀해주신 것 같아요.

저는 `LottoCards`가 `List<LottoCard>`를 가지기에 수동과 자동을 구분하지 않고 담아줄 목적으로 선언하신 것으로 이해했어요.
그래서 해당 내용에 대한 코멘트를 남겨두었습니다.

2021-03-17 12:25 UTC, kyucumber commented on src/main/kotlin/Lotto.kt
> +        require(!numberLine.isNullOrBlank()) { "로또 번호를 반드시 입력해야 합니다." }
이 부분은 크게 중요한 부분은 아니라서 그대로 유지해주셔도 괜찮습니다 😄

2021-03-17 12:27 UTC, kyucumber commented on src/main/kotlin/LottoCard.kt
> -    fun getMatchCount(winningLottoCard: LottoCard): Int {
`Lotto`로 이동하신 부분은 확인했어요.

다만 `Lotto`에서 검증하는 경우 `LottoCard`라는 도메인 객체에 아래와 같이 아무렇게나 값을 넣어 생성할 수 있는 문제가 있습니다.

```kotlin
LottoCard(listOf(1, 2, 3, 4, 5, 6, 7, 8, 9))
```

`LottoCard`는 6개의 숫자만 가져야 하지 않을까요?

2021-03-17 12:28 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

아래 두가지 코멘트는 추가로 확인 부탁드릴게요!

https://github.com/next-step/kotlin-lotto/pull/133#discussion_r595966775
https://github.com/next-step/kotlin-lotto/pull/133#discussion_r595968189

혹시 제가 잘못 이해했거나, 잘 이해가 안되시는 부분이 있다면 메시지 남겨주세요

다음 단계 진행을 위해 머지하겠습니다. 남겨둔 코멘트는 다음 단계에 반영해주세요

2021-03-17 12:28 UTC, merged

2021-03-20 16:02 UTC, SeoJinHyuk14 commented on src/main/kotlin/LottoCard.kt
> -    fun getMatchCount(winningLottoCard: LottoCard): Int {
말씀해주신 부분을 이해했습니다!

해당 validation은 LottoCard로 이동해야겠군요!