[Step4] 로또(수동)
next-step/kotlin-lotto pull request #141
Opened 2021-03-16 17:28 UTC by hyunssooo

2021-03-17 15:33 UTC, galcyurio requested changes
드디어 마지막 단계네요.
이번 단계도 잘해주셨어요!
로또 번호 생성기를 interface로 선언하고 수동, 자동 번호 생성을 다형성을 통해 구현해주신 부분이 인상깊네요.
코멘트 남겨두었으니 확인부탁드립니다!

2021-03-17 15:33 UTC, galcyurio commented on src/test/kotlin/lotto/domain/lottogenerator/ManualLottoGeneratorTest.kt
> +        )
테스트 코드에서는 `~ 하면, ~ 된다` 부분이 중요한데 아래와 같이 주석으로 나누어 주기도 합니다.
when, then 부분을 아래와 같이 짧게 만들어주면 가독성있는 테스트 코드를 만들 수 있습니다.

```kotlin
// given
val elements = listOf(1, 2, 3, 4, 5, 6)
val expected = Lotto(elements.map { LottoNumber.of(it) }.toSet())
val generator = ManualLottoGenerator(elements)

// when
val actual = generator.generate()

// then
assertThat(actual).isEqualTo(expected)
```

반드시 위와 같은 코드처럼 작성하라는 것은 아닙니다.
가독성만 좋으면 어떻게 쓰든 상관없습니다.

2021-03-17 15:33 UTC, galcyurio commented on src/test/kotlin/lotto/domain/LottosMachineTest.kt
> +    fun `입력 금액보다 수동 로또 구매 금액이 더 큰 경우 예외 처리`() {
테스트 케이스 이름에 `예외 처리`라는 단어를 쓰셔서 오해하시는 것 같아서 말씀드려요~
현재 프로그램은 예외를 던지는 것으로 예외를 처리했다고 할 수는 없습니다.
제대로 예외 처리를 한다면 프로그램이 강제 종료되는게 아니라 유저에게 에러메세지를 보여주고 다시 입력을 받아야 하지 않을까요?
코틀린에서도 자바에서 처럼 `try-catch`를 통해 예외 처리를 해주실 수 있습니다.

-----
다음은 코틀린에서의 예외처리 방식입니다.
당장은 바로 적응하기 힘들겠지만 장기적으로는 아래의 방식을 고려해주세요.

- [논리 오류](https://ko.wikipedia.org/wiki/%EB%85%BC%EB%A6%AC_%EC%98%A4%EB%A5%98)일 때만 예외를 던지세요.
- 논리 오류가 아니면 예외를 던지지 말고 null을 반환하세요.
- 실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환하세요.
- 일반적인 코틀린 코드에서 `try-catch`를 사용하지 마세요.

위 사항들의 자세한 설명은 아래 글을 읽어보세요.
https://medium.com/@elizarov/kotlin-and-exceptions-8062f589d07

2021-03-17 15:33 UTC, galcyurio commented on src/main/kotlin/lotto/view/InputView.kt
> +}
잘못된 입력이 들어오면 아래와 같이 다시 입력을 받아보는 방식은 어떨까요?
`tailrec`은 꼬리재귀 최적화를 위한 키워드입니다.

```kotlin
tailrec fun inputMoney(): Int {
    println("구입금액을 입력해 주세요.")
    return readLine()?.toIntOrNull() ?: inputMoney()
}
```

2021-03-18 18:26 UTC, hyunssooo commented on src/test/kotlin/lotto/domain/lottogenerator/ManualLottoGeneratorTest.kt
> +        )
항상 읽기 좋은 코드가 좋은 코드라고 생각했는데 정작 제 코드가 가독성이 떨어졌군요🙄 감사합니다! 👍

2021-03-20 02:56 UTC, galcyurio requested changes
안녕하세요! 현수님!
마지막으로 코드를 전체적으로 살펴봤는데 아쉬운 점이 하나 있어서 코멘트 남겨놓았습니다.
확인 부탁드립니다.

2021-03-20 02:56 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottosMachine.kt
> +    private val manualCount = manualLottoGenerators.size
LottosMachine에서 금액과 수동 로또 생성기를 생성자로 받고 totalCount, manualCount의 상태도 초기화한 뒤 내부에 상태를 보존하고 있습니다.
그런데 4개의 변수 모두 '굳이 멤버변수로 가지고 있을 필요가 있을까?'와 같은 생각이 들어요.
마치 init 영역에서 유효성 검사를 해주기 위해 억지로 멤버변수로 추가한 것처럼 보입니다.

또한 LottosMachine에서 `List<LottoGenerator>`를 받는데 반드시 수동 로또 생성기만 넘겨주어야 합니다.
협업하는 동료가 이 부분에 대해 잘 모르는 경우 실수로 다른 LottoGenerator 구현체를 넘겨버리면 프로그램이 잘못 동작하게 될 수 있습니다.

2021-03-21 08:05 UTC, galcyurio approved these changes
피드백 잘 반영해주셨네요 👍 
다른 방식으로도 가능할 것 같아서 코멘트 남겨두었습니다.
로또 미션 고생하셨습니다.

2021-03-21 08:05 UTC, merged