[Step3] 로또(2등)
next-step/kotlin-lotto pull request #142
Opened 2021-03-17 13:33 UTC by thxwelchs

#130  에서 마무리 하지 못한 피드백 반영이 포함된 PR입니다..!

이번 리뷰도 잘 부탁드립니다 :)

2021-03-18 00:17 UTC, vsh123 requested changes
안녕하세요!!
지난 단계에서 피드백을 잘 반영해주셨군요!! 👍 

이번 단계에서는 테스트 코드 작성이 누락된 부분과 toString에 대하 부분을 집중적으로 피드백 드렸습니다!
한번 확인 및 수정하신 후 재요청 부탁드려요~!!

궁금하거나 모르시는건 언제나 DM주시구요!

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +    override fun toString(): String {
Lotto와 마찬가지로 `toString`에 대해서 고민해보시길 바랄게요!

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    fun isBonusNumberMatch(bonusNumber: LottoNumber): Boolean {
테스트코드가 없는 것 같아요~!

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoStatistics.kt
> +        val matchBonus = lottoTicket.isBonusNumberMatch(winningLottoNumbers.bonusLotto)
`winningLottoNumbers.bonusLotto`를 넣어주고 있지만 함수에서는 `bonusNumber`로 받고 있는데요!! 이름을 맞춰주면 가독성이 좀 더 증가하지 않을까요?

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        return lottoTicket.lotto.count(this.lotto)
`lottoTicket.lotto`와 같이 lotto를 get하지 않고 작성할 수 없을까요?

2021-03-18 00:17 UTC, vsh123 commented on src/test/kotlin/lotto/domain/WinningLottoNumbersTest.kt
> +    fun `중복 번호 검증`(stringWinningLottoNumbers: String, bonusNumber: Int) {
ParameterizedTest 💯

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/view/Application.kt
>  fun main() {
해당 메인은 view와 도메인을 이어주는 역할을 하는 것 같은데요!! 패키지위치에 대해서 고려해보면 어떨까요?

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        fun of(stringWinningLottoNumbers: String, bonusNumber: Int): WinningLottoNumbers {
* `bonusNumber`를 Int로 받는다면, `stringWinningLottoNumbers`도 List<Int>로 받을 수 있지 않을까요??
* view에서 입력 받은 값을 도메인에 필요한 형식으로 바꾸어주는(여기서는 String -> List<Int>가 되겠네요) 역할은 어디에서 수행하는 것이 좋을까요??

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun selectByMatchCount(matchCount: Int, matchBonus: Boolean): LottoRank? {
* 테스트를 만들어보면 어떨까요?
* LottoRank를 notNull하게 넘겨주기 위해서는 어떻게 하면 좋을까요??

2021-03-18 00:17 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +            if (matchCount == 5) {
매직넘버가 보이면 우선 상수화 하는 습관을 가지면 좋을 것 같아요!!
상황에 따라서는 상수화를 하지 않을 때가 더 직관적이라고 이야기하는 분들도 계시지만, 보통은 상수화를 하면 더 직관적으로 보이게 되더라구요!

2021-03-18 14:06 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/Lotto.kt
> +class Lotto constructor(
private constructor를 고민하다가, private만 지우고 누락된 것 같습니다;;

`Lotto`(LottoNumber 컬렉션을 들고 있는 일급 컬렉션)
`LottoTicket`(Lotto 한장을 의미하는 객체)
로 생각했었는데요, Lotto 일급 컬렉션만 사용하는게 더 좋았을까요?

2021-03-18 14:07 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    fun contains(lottoNumber: LottoNumber): Boolean {
반영했습니다!

2021-03-18 14:07 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    fun count(lotto: Lotto): Int {
반영했습니다!

2021-03-18 14:07 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        return this.numbers.filter {
count가 있는줄 몰랐네요 ㅜㅜ 코틀린은 자바에 비해 정말 많은 기능이 지원되는 것 같군요

2021-03-18 14:09 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    override fun toString(): String {
피드백 주신대로 고민해보니, 해당 toString 함수는 특정 뷰에 의존되는 형태인 것 같습니다..!

특정 뷰에 의존하지 않기 위해서 일단 toString은 재정의 하지 않도록 하고, View에서 처리해주었는데요 제가 생각한대로 구현하는게 좋은 방법일까요?

2021-03-18 14:11 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val cache: Map<Int, LottoNumber> = (MINIMUM_LOTTO_NUMBER..MAXIMUM_LOTTO_NUMBER).map {
map을 활용한 초기화도 충분히 좋았는데, 더 깔끔한 방법이 있었네요!

덕분에 이번 반영에 한번 활용해보았습니다.

2021-03-18 14:12 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +    override fun toString(): String {
위 Lotto와 마찬가지로 뷰에서 처리하도록 해봤습니다

2021-03-18 14:16 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun selectByMatchCount(matchCount: Int, matchBonus: Boolean): LottoRank? {
- 테스트가 누락되어 있어 작성해보았습니다..!
- 이 부분에 대해서는 고민이 있는데요, LottoRank를 nullable한 타입으로 반환하는 이유는, `WinningLottoStatistics` 에서 로또티켓에 대한 당첨순위를 구할 때, 당첨 순위에 해당하는 않은 부분을 `LottoRank` Enum에서 찾지 못한 값(`null`)으로 처리 할려고 했었는데요 혹시 더 깔끔하고 좋은 방법은 무엇일까요?

2021-03-18 14:18 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +            if (matchCount == 5) {
매직넘버 상수화에 대한 부분 적극 동의하지만 꼭 누락되는 부분이 있는 것 같습니다 ㅜ (반영해보았는데, Enum의 프로퍼티에도 반영해줘야 할지.. 조금 헷갈리더라구요 일단 프로퍼티에도 반영을 했지만, 리뷰어님은 어떻게 생각하실까요?)

2021-03-18 14:26 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    fun isBonusNumberMatch(bonusNumber: LottoNumber): Boolean {
LottoTicket은 랜덤한 로또번호로만 인스턴스가 생성되는 객체라서 `isBonusNumberMatch`에 대한 부분을 고민하다 테스트하기 어렵고, 굳이 테스트하지 않아도 contains api를 사용하기 때문에 테스트 필요성을 느끼지 못하다고 판단하여 테스트작성은 하지않았습니다.

Jason님이 강의해주신 내용대로, 랜덤의 의존을 상위 레벨로 올려서 테스트하는게 더 좋았을까요? (또한 여기서 랜덤의 의존을 객체 그래프의 상위로 올린다는 것은 LottoTicket에서 랜덤으로 로또번호를 생성하는 것이 아니라, 상위 객체로부터 이미 랜덤으로 생성된 로또번호를 전달받아 생성하는 구조가 되는 것이 맞을까요? )

2021-03-18 14:29 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        return lottoTicket.lotto.count(this.lotto)
lotto를 get하지 않고 lottoTicket에게 바로 count를 구하도록 시키고 값을 반환받는 방식으로 해보았습니다.

count를 구하는 개념의 기능이 `WinningLottoNumbers`, `LottoTicket`, `Lotto` 에 전부 존재한다는게 조금 걸리는데 이것을 객체의 캡슐화를 지키면서 올바르게 구현하는 방향은 어떤게 있을까요..?

2021-03-18 14:30 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        fun of(stringWinningLottoNumbers: String, bonusNumber: Int): WinningLottoNumbers {
`List<Int>` 형태의 인자로 받도록 반영해보았습니다.
String -> List 로 바꾸어주는 역할은 별도의 클래스가 필요할 것 같아 `LottoNumberTokenizer`를 구현했는데요 이것이 적절했을지 긴가민가합니다.

2021-03-18 14:31 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/WinningLottoStatistics.kt
> +        val matchBonus = lottoTicket.isBonusNumberMatch(winningLottoNumbers.bonusLotto)
LottoTicket 쪽 인자명을 변경하여 가독성이 증가하도록 해보았습니다.

2021-03-18 14:36 UTC, thxwelchs commented on src/main/kotlin/lotto/view/Application.kt
>  fun main() {
이 부분에 대해서도 고민이 있는데요..!

저는 개인적으로 메인 함수가 작성된 클래스 혹은 파일은 그 해당 애플리케이션 루트 위치에 있는것이 적절하다고 생각하고 있는데요(여기서는 `main/kotlin/lotto`) 저번 step2때 또한 패키지위치에 대한 고려 피드백을 주셔서 긴가민가하면서 view의 위치로 변경을 했던 것 같습니다 ㅜ 

혹시 리뷰어님이 생각하시는 적절한 위치는 어느곳인지 의견주시면 제가 고민하는데에 많은 도움이 될 것 같습니다!

2021-03-19 09:14 UTC, vsh123 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +class Lotto constructor(
두개의 객체를 분리했을 때 서로 다른 책임(역할)이 있나요??
만약 있다면 분리하고, 그렇지 않다면 합치는게 좋을 것 같아요!

2021-03-19 09:14 UTC, vsh123 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    override fun toString(): String {
넵! 도메인로직을 짤때는 특정 View에 의존되지 않게 짜면 좋을 것 같아요!

2021-03-19 09:20 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    fun isBonusNumberMatch(bonusNumber: LottoNumber): Boolean {
`랜덤의 의존을 상위 레벨로 올려서 테스트`를 했을 때의 이점이 무엇이 있을까요??
만약 현재 작성한 코드의 양을 100이라고 했을 때 랜덤 의존을 현재 위치에 두는 것과, 상위로 올렸을 때 커버할 수 있는 test coverage가 어떻게 될까요?

2021-03-19 09:23 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        return lottoTicket.lotto.count(this.lotto)
* 위에 말씀드렸던 것과 같이 Lottoticket과 Lotto의 책임(역할)의 차이가 무엇이 있을지 생각해보면 좋을 것 같아요!
* WinningLottoNumbers와 Lotto의 `count`는 같다고 봐야할까요?

2021-03-19 09:25 UTC, vsh123 commented on src/main/kotlin/lotto/view/Application.kt
>  fun main() {
저는 이 파일이 일종의 controller라고 생각해요(view와 domain을 이어주니까요!)
그렇다면 domain모듈과 view모듈이 아닌 다른 곳에 위치하면 좋을 것 같은데, 현재구조에서는 controller가 하나뿐이니 lotto패키지 바로 아래 있어도 괜찮겠네요 :)

2021-03-19 09:27 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun selectByMatchCount(matchCount: Int, matchBonus: Boolean): LottoRank? {
LottoRank에 미당첨이라는 값을 추가해보면 어떨까요?

2021-03-19 09:28 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +            if (matchCount == 5) {
저는 Enum은 값 자체로 추측이 가능해서 프로퍼티들은 따로 상수화를 해주지 않습니다!

2021-03-19 09:29 UTC, vsh123 approved these changes
태훈님 안녕하세요!
미션과 피드백을 적용하면서 많은 고민을 하신게 느껴졌습니다!!

질문주신 내용에 대해서 코멘트 남겼으니 확인부탁드릴게요!
이번단계는 머지하도록 하겠습니다 :)

2021-03-19 09:30 UTC, merged

2021-03-19 10:20 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun selectByMatchCount(matchCount: Int, matchBonus: Boolean): LottoRank? {
엇 그런방법이..!