[Step4] 로또(수동)
next-step/kotlin-lotto pull request #152
Opened 2021-03-20 10:39 UTC by thxwelchs

안녕하세요..! #142 의 마무리하지못했던 피드백 반영이 포함되어있습니다. https://github.com/next-step/kotlin-lotto/commit/696031aa9fe3f06d22d368ed7af087d98ffc99ef https://github.com/next-step/kotlin-lotto/commit/122c0a67f6fbafd262d0e380d9d3647a4acb54ec

이번에는 전보다 원시값을 포장하는 클래스를 더 많이 구현 하면서 자연스레 도메인 모델을 좀 더 상세하게 나누고 자연스레 책임을 부여할 수 있었던 것 같아 뜻깊은 경험이었습니다.

바쁘시겠지만 이번 리뷰도 잘 부탁드리겠습니다..!

2021-03-22 10:29 UTC, vsh123 requested changes
태훈님 안녕하세요!!
마지막 단계까지 고생많으셨습니다!! 👍 

몇가지 코멘트를 남겼습니다.
확인부탁드릴게요!

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/Application.kt
>  package lotto.view
패키지 위치 확인해주세요~

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/view/InputView.kt
> +        require(buyingPrice.isGreaterThanEqualsByCount(manualLottoCount)) {
View에서 도메인 로직을 호출하는게 맞을지 생각해보면 좋을 것 같아요!

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoPrice.kt
> +    fun isGreaterThanEqualsByCount(count: Int): Boolean {
해당 함수의 역할(개수만큼 수동 로또 구매가 가능한지 여부)을 생각했을 때 조금 더 명확한 네이밍을 해주는 건 어떨까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/BuyingLotto.kt
> +    val automaticCount: Int = price.calculateAutomaticCount(manualLotto.size)
* 수동로또가 만들어지는 시점에 자동로또도 만들어지는게 더 괜찮지 않을까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/BuyingLotto.kt
> +    val manualLotto: List<Lotto> = manualLottoNumbers.toLottos()
* LottoMachine의 `buy`함수의 역할을 이곳에서 하는 느낌이에요!! 어떻게 생각하시나요~?
* 복수형의 네이밍이 알맞지 않을까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        return (1..count).map { Lotto.create() }
자동로또는 `Lotto.create()`를 통한 Lotto에 생성의 책임이 있는데, 수동로또는 외부에 존재하는 것 같아요!!
생성에 대한 책임을 한군데로 모을 수 없을까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoPrice.kt
> +        return this >= convertCountToLottoPrice(count)
Comparable을 없애기 위해 해당 로직을 변경해보면 어떨까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/ResultLottoStatistics.kt
> +package lotto.domain
* 해당 클래스는 별도 도메인 로직이 없는데요!! 과연 이게 도메인이 맞을까요?
* 추가적으로 도메인 로직이 없는 다른 클래스들에 대해서도 고려해보면 좋을 것 같아요!

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoStatistics.kt
> +        val matchBonus = lotto.contains(winningLottoNumbers.bonusLotto)
네이밍을 다시 변경하신 이유가 있을까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoProfitRate.kt
> +    val value: Double = total / buyingPrice.value.toDouble()
네이밍을 다시한번 생각해보며 좋을 것 같아요!

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun valuesNotIncludeNotPlace(): List<LottoRank> {
`valuesExcludeNotPlace`라는 네이밍은 어떨까요?

2021-03-22 10:29 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoRank.kt
>              if (matchCount == SECOND_OR_THIRD_PLACE_MATCH_COUNT) {
if문 안에 2등이 맞는지를 검사하는 로직이 들어가면 더 깔끔해질 수 있을 것 같아요~

2021-03-22 10:29 UTC, vsh123 commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +    @ParameterizedTest
ParameterizedTest 👍

2021-03-22 10:48 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/WinningLottoStatistics.kt
> +        val matchBonus = lotto.contains(winningLottoNumbers.bonusLotto)
LottoTicket이 현재의 LottoTicket과는 다른 역할을 하던 객체일 때의 기능이 isBonusNumberMatch 였으나, Lotto로 변경됨에 따라서 Lotto의 contains 라는 함수를 이용하게 되었습니다. (contains는 다른 객체에서도 범용적인 LottoNumber 맞는지 확인하는 용도로 사용하는 기능이라 contains 그대로 쓰는 것이 더 적합하다고 생각했었습니다.)

2021-03-23 02:02 UTC, thxwelchs commented on src/main/kotlin/lotto/Application.kt
>  package lotto.view
반영했습니다.

2021-03-23 02:02 UTC, thxwelchs commented on src/main/kotlin/lotto/view/InputView.kt
> +        require(buyingPrice.isGreaterThanEqualsByCount(manualLottoCount)) {
도메인(`LottoMachine`) 에서 역할을 수행하도록 수정했습니다.

2021-03-23 02:03 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoPrice.kt
> +    fun isGreaterThanEqualsByCount(count: Int): Boolean {
좀 더 어울리는 이름으로 리네이밍 해봤습니다. `isExceedPriceByCount()`

2021-03-23 02:04 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/BuyingLotto.kt
> +    val automaticCount: Int = price.calculateAutomaticCount(manualLotto.size)
수동로또가 만들어지는 시점인 `LottoMachine.buy` 에서 만들어지도록 변경했습니다.

2021-03-23 02:05 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/BuyingLotto.kt
> +    val manualLotto: List<Lotto> = manualLottoNumbers.toLottos()
buy함수로 해당 역할들을 옮기기 시작하다보니 BuyingLotto의 존재가 무의미해지는 것 같아 buy 함수가 좀 더 제역할을 하게끔 수정하고 BuyingLotto를 제거했습니다.

2021-03-23 02:05 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoProfitRate.kt
> +    val value: Double = total / buyingPrice.value.toDouble()
value -> profitRate 로 변경했습니다.

2021-03-23 02:06 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +        fun valuesNotIncludeNotPlace(): List<LottoRank> {
제안해주신 `valuesExcludeNotPlace` 가  더 적합한 것 같다고 생각되어 변경했습니다..!

2021-03-23 02:06 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoRank.kt
>              if (matchCount == SECOND_OR_THIRD_PLACE_MATCH_COUNT) {
if문 안에 2등이 맞는지 검사하는 `isSecondOrThirdPlaceMatchCount` 프라이빗 함수를 만들고 호출하도록 변경했습니다.

2021-03-24 12:58 UTC, vsh123 requested changes
태훈님 안녕하세요!
DM으로 주고받은 피드백을 잘 적용해주셨네요!!

몇가지 수정하면 더 좋은 내용들이 있을 것 같아 코멘트를 남겼습니다! :) 
확인 부탁드릴게요!

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +            lottoMachine.setGenerator(ManualLottoGenerator(it))
객체의 프로퍼티를 외부에서 변경하지 못하도록하면 어떨까요?
이 경우에는 자동로또머신과 수동로또머신을 각각 생성할 수 있을 것 같아요!!

[setter를 피해야하는 이유](https://www.infoworld.com/article/2073723/why-getter-and-setter-methods-are-evil.html)를 참고해보셔도 좋을 것 같아요~ :)

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    private fun validateLottoCount(price: LottoPrice, lottoTicket: LottoTicket) {
해당 validation을 수행할 수 있는 책임을 가진 객체가 있지 않을까요?

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/domain/generator/LottoGenerator.kt
> +interface LottoGenerator {
good!! 💯

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    fun start(price: LottoPrice, manualLottoCount: Int): LottoTicket {
저희 요구사항 중에
```
- 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.
    - 함수(또는 메서드)가 한 가지 일만 잘 하도록 구현한다.
```
와 같은 조건이 있었는데요! 해당 함수가 요구사항에 충족하는지 생각을 해보면 좋을 것 같아요!

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +        validateLottoCount(price, lottoTicket)
validation이 로또티켓 구매 이전시점에 이루어져야하지 않을까요?

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoPrice.kt
> +    private fun convertCountToLottoPrice(count: Int): LottoPrice {
미사용 함수는 제거 부탁드려요!

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val manuals: List<Lotto>,
수동로또와 자동로또는 분리되서 보관되는게 맞을까요?
생성 이후에서는 두가지 종류의 로또가 구분이 필요할까요?

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    fun getTickets(): List<Lotto> {
아래의 두개를 참고하여 조금 더 간단하게 만들어볼까요?

* [List.plus](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/plus.html)를 활용
* [property를 만들고 getter/setter를 구현하는 방법](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/plus.html)

2021-03-24 12:58 UTC, vsh123 commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
>      companion object {
winningLottoInstance를 생성하는 로직을 generator를 이용해보면 어떨까요?

2021-03-24 14:28 UTC, thxwelchs commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +            lottoMachine.setGenerator(ManualLottoGenerator(it))
전략패턴을 구현 할 때 setter 주입 방식이 더 접근성이 좋을 것 같아 구현했었는데, 현재 상황에서는 오히려 캡슐화를 깨는 상황으로 보이는 것 같아 말씀하신대로 반영했습니다.

2021-03-24 14:29 UTC, thxwelchs commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    private fun validateLottoCount(price: LottoPrice, lottoTicket: LottoTicket) {
LottoTicket에게 책임을 넘겨보았습니다.

2021-03-24 14:29 UTC, thxwelchs commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    fun start(price: LottoPrice, manualLottoCount: Int): LottoTicket {
함수를 분리해보았습니다.

2021-03-24 14:30 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoPrice.kt
> +    private fun convertCountToLottoPrice(count: Int): LottoPrice {
반영했습니다.

2021-03-24 14:32 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val manuals: List<Lotto>,
ResultView 에서 LottoTicket을 인자로 받아 출력해주는 부분에서 각각의 장 수를 표현해줄 때 사용해주고 있었는데, 
LottoTicket의 프로퍼티로는 수동로또, 자동로또 구분없이 List<Lotto> 로 가지게 하고, count를 별도로 보관하는 형태로 반영해봤습니다.

2021-03-24 14:32 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    fun getTickets(): List<Lotto> {
LottoTicket이 수동, 자동 구분이 없어짐에 따라 제거되었습니다.

2021-03-24 14:33 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
>      companion object {
반영해보았습니다.

2021-03-25 00:21 UTC, vsh123 requested changes
태훈님 안녕하세요~!
피드백 반영 💯 

몇가지 수정을 하면 좋을 부분을 코멘트 드렸습니다!!
마지막으로 한번만 더 확인 부탁드릴게요~ :)

2021-03-25 00:21 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val lottos: List<Lotto> = manualLottos + automaticLottos,
외부에서 인자로 받지 않는 프로퍼티들은 주 생성자가 아닌 클래스 안에 선언해주시면 좋을 것 같아요!

2021-03-25 00:21 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        require(price.isExceedPriceByCount(lottos.size)) {
validation이 이관되면서 테스트가 추가되면 좋을 것 같아요~~!!

2021-03-25 00:21 UTC, vsh123 commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +        val stringLottoNumbers = InputView.enterLastWeekWinningLottoNumbers()
Input을 받는 위치를 Application.kt나 이곳 중에 하나로 통일하면 좋을 것 같아요!

2021-03-26 10:09 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val lottos: List<Lotto> = manualLottos + automaticLottos,
반영했습니다..!

2021-03-26 10:09 UTC, thxwelchs commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +        require(price.isExceedPriceByCount(lottos.size)) {
반영했습니다

2021-03-26 10:09 UTC, thxwelchs commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +        val stringLottoNumbers = InputView.enterLastWeekWinningLottoNumbers()
반영했습니다

2021-03-27 03:29 UTC, vsh123 approved these changes
태훈님 안녕하세요~!!
로또 마지막 미션까지 정말 수고하셨습니다!!

이번에 진행한 미션이 앞으로의 과정에서도 많은 도움이 되셨길 바랍니다 :)
머지할게요!! 고생많으셨습니다~~!

2021-03-27 03:30 UTC, merged