[step4] 수동 로또
next-step/kotlin-lotto pull request #163
Opened 2021-03-25 14:06 UTC by chldbtjd2272

- 기존 수동로또 생성기능을 이용해 수동로또생성
- step1 보너스볼 없는 게임 지원

2021-03-26 13:42 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

확인 후 재 요청 주시면 머지하도록 할게요~

2021-03-26 13:42 UTC, kyucumber commented on src/main/kotlin/lotto/store/LottoStore.kt
> +    private fun issueManualLotto(issueCount: Long, txManualLottos: List<String>): MutableList<LottoTicket> {
큰 차이는 없지만 불변으로 처리할 수 있는 경우는 불변으로 처리하면 어떨까요?

여기서는 `Mutable`을 사용하지 않아도 괜찮을 것 같네요.

```kotlin
        val tickets = issueManualLotto(issueCount = issueCount, txManualLottos = request.txManualLottoTickets)

        val autoTickets = (0..autoCount).map { LottoTicket.ofAuto() }

        return IssuedLottoTickets(tickets.plus(autoTickets))
    }
    
    private fun issueManualLotto(issueCount: Long, txManualLottos: List<String>): List<LottoTicket> {
```

2021-03-26 13:42 UTC, kyucumber commented on src/main/kotlin/lotto/ticket/WinningTicket.kt
> +    private val bonusBall: LottoNumber? = null
`ofTxNumbers` 정적 팩토리 메소드만을 이용해서 생성되고 있는 것 같네요.

아래처럼 생성자를 `private`으로 지정하면 어떨까요?

```kotlin
class WinningTicket private constructor(
```

2021-03-26 13:42 UTC, kyucumber commented on src/main/kotlin/lotto/ticket/WinningTicket.kt
> +    private val bonusBall: LottoNumber? = null
정적 팩토리 메소드에서 bonusBall 파라미터에 아래와 같이 값을 넘겨주고 있습니다.

```kotlin
bonusBall = LottoNumber.drawNumber(number = txBonusBall.toInt())
```
위 `drawNumber`는 Null을 반환하는게 아닌 예외를 던지고 있으므로 정적 팩토리 메소드를 이용하는 경우 bonusBall에 값이 들어가지 않는 케이스는 없을 것 같네요.

nullable이 아닌 non null 타입으로 정의하면 어떨까요?

2021-03-27 07:48 UTC, chldbtjd2272 commented on src/main/kotlin/lotto/ticket/WinningTicket.kt
> +    private val bonusBall: LottoNumber? = null
step1/step2 모두 지원하기 위해 열어놓은 생성자입니다.
보너스볼이 존재하는 게임, 보너스볼이 없는게임을 다 지원하기 위해 열어두었습니다:)

2021-03-27 07:48 UTC, chldbtjd2272 commented on src/main/kotlin/lotto/ticket/WinningTicket.kt
> +    private val bonusBall: LottoNumber? = null
https://github.com/next-step/kotlin-lotto/pull/163#discussion_r602685744

2021-03-27 15:24 UTC, kyucumber approved these changes
4단계 미션까지 진행하시느라 고생 많으셨습니다.

다음 단계 진행을 위해 머지할게요

2021-03-27 15:24 UTC, merged