Step1 문자열계산기
next-step/kotlin-lotto pull request #194
Opened 2021-10-31 11:12 UTC by sinoso

코드리뷰 잘 부탁드리겠습니다.
많은 가르침 주셨으면합니다.

2021-10-31 16:02 UTC, vagabond95 requested changes
안녕하세요! 미션 진행동안 잘 부탁드립니다. ㅎㅎ

구현해주신 내용에 대하여 간단한 코멘트 남기었는데요, 확인 후 리뷰요청 부탁드립니다!

2021-10-31 16:02 UTC, vagabond95 commented on src/main/kotlin/calculator/Formula.kt
> +        var customDelimiter: String? = null
customDelimiter 를 구하는 함수를 따로 분리해보는 것은 어떨까요?

2021-11-01 01:23 UTC, sinoso commented on src/main/kotlin/calculator/Formula.kt
> +    }
>",", ":" 와 같은 문자열은 하드코딩 하기보다 상수로 관리해보는 것은 어떨까요?

상수로 분리했습니다.

2021-11-01 15:05 UTC, vagabond95 approved these changes
빠르게 코멘트 잘 반영해주셨네요 👍 
1단계는 머지하도록 하겠습니다!

2021-11-01 15:05 UTC, vagabond95 commented on src/main/kotlin/calculator/Formula.kt
> +        val customDelimiter: String? = getCustomDelimiter(customDelimiterAndOperands)
```suggestion
        val customDelimiter = getCustomDelimiter(customDelimiterAndOperands)
```
타입은 생략되어도 괜찮을 것 같습니다!

2021-11-01 15:06 UTC, merged