[3단계 - 로또(2등)] 리뷰 부탁드립니다.
next-step/kotlin-lotto pull request #202
Opened 2021-11-02 13:19 UTC by kwj1270

안녕하세요 리뷰어님 빠르게 PR 드립니다 ㅎㅎㅎ    
3단계는 2단계에 비해 크게 구현할 점은 없었고,    
WinningLotto 라는 클래스를 만들어서 도메인에서 최대한 로직을 처리하도록 했습니다.    
        
* [x] WinningLotto (상속 대신 컴포지션 방식)    
    * Lotto -> 당첨 로또 
    * LottoNumber -> 보너스 로또 
    * 입력시 당첨 로또에 보너스 로또 있는지 검증 처리(있으면 안됨!)  
    * 기능 :   
       * 그냥 로또가 보너스 볼 맞추었는지 여부 반환  
       * 그냥 로또가 당첨 로또랑 몇개 맞는지 숫자 반환        

리뷰해주셔서 감사드리고, 이번 PR도 잘 부탁드리겠습니다!! 🙇

2021-11-03 01:47 UTC, vagabond95 requested changes
요구사항에 맞게 잘 구현해주셨네요 👍 👍 

구현해주신 내용에 대하여 코멘트 남겼는데요, 확인 후 리뷰요청 부탁드립니다!

2021-11-03 01:47 UTC, vagabond95 commented on src/main/kotlin/domain/lotto/LottoApplication.kt
> +            ConsoleOutputStrategy.output(e.message.toString())
이전단계에서는 제가 못보고 지나갔던 부분인데요!

ConsoleOutputStrategy 보다 LottoResultView 를 활용해보는 것은 어떨까요?
View 에 대한 추상화 레벨이 같으면 좋을 것 같아요!

2021-11-03 01:47 UTC, vagabond95 commented on src/main/kotlin/domain/lotto/LottoApplication.kt
> +            ConsoleOutputStrategy.output(e.message.toString())
이전단계에서는 제가 못보고 지나갔던 부분인데요!

ConsoleOutputStrategy 보다 LottoResultView 를 활용해보는 것은 어떨까요?
View 에 대한 추상화 레벨이 같으면 좋을 것 같아요!

2021-11-03 01:47 UTC, vagabond95 commented on src/main/kotlin/domain/lotto/domain/WinningLotto.kt
> +data class WinningLotto private constructor(private val winningLotto: Lotto, private val bonusBall: LottoNumber) {
Lotto 를 상속받는 것이 아니라 주입하여 처리하는 부분 좋은 것 같습니다 👍

2021-11-03 01:47 UTC, vagabond95 commented on src/main/kotlin/domain/lotto/domain/MatchBoard.kt
> +            if (numberOfMatch == SECOND.numberOfMatch && isMatchBonus) {
이렇게 특정 등수에 대한 조건문이 있을 경우, 보너스번호를 가지는 등수가 늘어날때마다 if 문이 추가될 것 같아요!
특정 등수에 의존하지 않는 로직으로 바꿔볼 수 있을까요?

hitn : 보너스 번호를 가지고 있는 등수 유무를 나타내는 값을 가져보는 것은 어떨까요?

2021-11-03 01:47 UTC, vagabond95 commented on src/main/kotlin/domain/lotto/ui/LottoResultView.kt
> +        if (it.key == MatchBoard.SECOND) {
MatchBoard 와 같은 맥락으로 특정 등수에 의존하지 않는 로직으로 구현 되면 좋을 것 같아요!

2021-11-03 10:57 UTC, kwj1270 commented on src/main/kotlin/domain/lotto/LottoApplication.kt
> +            ConsoleOutputStrategy.output(e.message.toString())
View에 대한 추상화 레벨을 고려하지 않았는데 적극 공감이 되네요!! 👍
사실, Result라는 이름이 예외처리에 대한 메시지를 출력하는게 안맞다고 생각해서 따로 뺐었습니다.   
추상화를 맞게 하려면, 이름을 변경하거나 예외를 출력하는 View를 만들어서 처리하면 될 것 같네요

2021-11-03 11:02 UTC, kwj1270 commented on src/main/kotlin/domain/lotto/domain/MatchBoard.kt
> +            if (numberOfMatch == SECOND.numberOfMatch && isMatchBonus) {
이 부분에 대해서 고민할 거리가 많은 것 같네요!!   
리뷰어님의 말씀을 듣고 `when`으로 처리할까도 생각했지만, 문제가 동일히 발생할 것 같다는 생각도 드네요  
enum에 true/false 를 넣는건 가능하지만, 보다 좋은 구조가 있을지 고민해보겠습니다!!

2021-11-03 16:24 UTC, kwj1270 commented
# 1차 피드백 이후

안녕하세요 리뷰어님!!  우선, 저번 리뷰 너무 감사드립니다. 🙇        
피드백 주신 내용을 통해서 `추상화 레벨을 동일하게 가져가야 된다`는 점을 상기시킬 수 있었고   
Lotto를 하면서 `if()`한 개는 어쩔 수 없이 넣어야된다는 생각이었는데,   
고민해보고 이를 해결함으로써 조금 더 성장한 것 같습니다 :)   
  
우선 피드백 주신 내용에 대해서 정리해보면 아래와 같습니다.   

**피드백1, 추상화 수준 동일하게**
* global 패키지에 예외처리 출력용 ExceptionVuiew 를 정의해서 출력을 하는 형태로 변경했습니다.    
    * ResultView는 이름 그대로 결과를 출력한다고 생각이 들어서 별도의 전역 클래스로 만들었습니다.  
    ```kt
    class ExceptionView(private val outputStrategy: OutputStrategy) {
        fun showErrorMessage(message: String) = outputStrategy.output(message)
    } 
    ```
**피드백2, MatchBoard에서 상수 값 찾을 때 OCP 지키도록 구현**   
* 문제를 어떻게 해결하지 해결하지 고민하다가 아래와 같은 생각을 했습니다.  
    * 보너스볼이 필요하지 않다면? -> 전부다 하나의 값으로 통일 -> false  
    * 보너스볼이 필요하다면? -> 들어온 값, 그대로 내보내면 되지 않나? -> true/false 가지고 알아서 계산할 듯  
    ```kt
    class Rank(val numberOfMatch: Int, val necessityOfBonus: Boolean = false) {
        init {
            if (!(Lotto.MINIMUM_SIZE..Lotto.MAXIMUM_SIZE).contains(numberOfMatch)) {
                throw InvalidNumberOfMatchException(numberOfMatch)
            }
        }

        fun isEqualToNumberOfMatch(otherNumberOfMatch: Int): Boolean =
            (numberOfMatch == otherNumberOfMatch)

        fun isEqualToNecessityOfBonus(isMatchBonus: Boolean): Boolean =
            (necessityOfBonus == calculateNecessity(isMatchBonus))
        
        private fun calculateNecessity(isMatchBonus: Boolean): Boolean {
            if (necessityOfBonus) {
                return isMatchBonus
            }
            return false
        }
    }
    ```
* 그리고 앞서 제가 언급했듯이, MatchBoard에 필드가 3개 이상되면 너무 많은 책임을 가진다고 생각해서 클래스로 분리했습니다.

미션을 진행할때 마다, 너무 좋은 리뷰를 해주셔서 꾸준히 성장하고 있다는 느낌이 들고 있습니다.  
리뷰 맡아주셔서 정말 감사드리고 이번 PR도 잘 부탁드리겠습니다 :) 😊

2021-11-04 13:16 UTC, vagabond95 approved these changes
피드백 의도대로 잘 반영해주셔서 추가 코멘트 드릴 부분이 없습니다!

사실 실제 개발에서는 2등 케이스와 같은 상황이 있을 때 if 문을 사용하는 것이 나쁘다고 생각되지는 않습니다. 다만 의도하지 않고 무의식적으로 반복할 경우 절차지향적인 코드가 되기 쉬워 중점적으로 코멘트를 남겼습니다 ㅎㅎ

3단계는 머지하도록 하겠습니다!

2021-11-04 13:16 UTC, merged