Step3 - 로또(2등)
next-step/kotlin-lotto pull request #206
Opened 2021-11-03 12:33 UTC by leesohyun13

안녕하세요! step2 리뷰 해주신 사항도 반영해서 구현해보았습니다. step2 리뷰도 너무 감사드립니다.

2021-11-03 13:18 UTC, BeokBeok requested changes
로또(2등) 미션하시느라 고생하셨습니다!
동작을 해보니, 5개 일치하면서 보너스볼 하나 일치하는 조건을 기입했을 때 체크가 안되는 것 같아요.
구현을 다 하시고나서 테스트코드를 작성하신 것 같은데요.
테스트코드를 먼저 작성하시고나서 구현을 해보시면 어떨까요?

추가로 아래 두 가지 요구사항을 충족해주시면 좋을 것 같아요
- 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외 
- 커밋 시에 ktlint 체크 (https://edu.nextstep.camp/s/iuYIJ06v/ls/swXsTkH9)

2021-11-03 13:18 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
> +    }
보너스 넘버를 가지고 있는지 아닌지에 대해서는 Lotto 객체에 위임하는 것은 어떨까요?

2021-11-03 13:18 UTC, BeokBeok commented on src/main/kotlin/lotto/view/OutputView.kt
>      }
이 함수는 없어도 될 것 같아요
해당 문구에 "이득", "손해" 에 대한 출력은 요구사항에 없습니다!

2021-11-03 13:18 UTC, BeokBeok commented on src/main/kotlin/lotto/view/OutputView.kt
> +            .sortedBy { it.winningMoney }
이 역할은 OutputView의 역할이 아닌 것 같아요
해당 기능을 LottoRank 객체에서 할 수 있도록 위임하면 어떨까요?

2021-11-03 13:18 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +    @DisplayName("구매 금액에 null이 입려된 경우")
```suggestion
    @DisplayName("구매 금액에 null이 입력된 경우")
```

2021-11-03 13:18 UTC, BeokBeok commented on src/test/kotlin/lotto/model/GenerationNumberTest.kt
> +    }
이 테스트코드는 의미가 없는 것 같아요.
마치 테스트를 통과하기 위해서 작성된 코드같아요.

로또 번호를 생성하고, 그 로또 번호가 내가 만든 로또 번호인지 확인할 수 있는 테스트코드로 변경하면 어떨까요?

2021-11-03 13:18 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottosTest.kt
> +    @DisplayName("보너스 숫자가 같아 2등하는 경우")
2등하는 경우에 대해서 구체적으로 작성해주시면 좋을 것 같아요
2등은 숫자가 5개 일치하면서 보너스 숫자가 일치해야 2등인데, 작성하신 테스트코드에는 4개 일치하면서 보너스 숫자가 일치해야 2등인 것으로 보여요

2021-11-03 13:54 UTC, leesohyun13 commented
제가 잠시 보너스볼 2등 산출하는 방법이 헷갈려서 로직을 잘못 구현 했었습니다. 해당 부분 수정했습니다. 다음부터 TDD로 구현해보겠습니다 ㅎㅎ 리뷰 감사드립니다 :)

2021-11-03 13:55 UTC, leesohyun13 commented
그리고 린트는 설정을 해놨는데 지금 프로젝트에서 될때가 있고 안될때가 있어서 다시 설정해보겠습니다!

2021-11-05 14:07 UTC, leesohyun13 commented
안녕하세요! 지난 번에 리뷰 해주신 내용 바탕으로 random으로 숫자 생성하는 메소드 이동 및 private function들도 object로 변경하여 테스트 코드를 더 추가해보았습니다 ㅎㅎ 덕분에 재밌게 미션 진행해보았습니다! 감사합니다!!

2021-11-05 15:00 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
> +            bonusNumber: Int?,
같은 number인데 하나는 String타입이고 하나는 Int타입이라 햇갈리는 것 같아요
LottoNumber 객체를 활용해서 일관성있게 타입을 사용하면 어떨까요?

2021-11-05 15:00 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
> +            require(!list.map { it.number }.contains(bonusNumber)) { EXCEPTION_BONUS_NUMBER }
Lottos객체가 Lotto객체에 대해서 너무 잘 알고 있는 것 같아요
contains를 Lottos에서 하는 것 보다는, Lotto 객체에 해당 기능에 대해 정의하고 Lottos 객체에서 Lotto 객체에 메시지를 보내서 확인하게 하면 어떨까요?

2021-11-05 15:02 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +    @DisplayName("구매 금액의 범위에 맞지 않는 숫자가 입력된 경우")
구매 금액의 범위라는 것이 애매한 것 같아요
`천원 단위가 아닌 금액을 입력한 경우` 와 같이 작성해보면 어떨까요?

2021-11-05 15:03 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottoRankTest.kt
> +    @DisplayName("일치한 숫자에 맞는 등수 찾기(일반)")
해당 테스트 케이스가 몇등인지도 적어주면 좋을 것 같아요
가령, 몇 개의 숫자가 일치하면 몇등입니다의 뉘앙스이면 좋을 것 같아요

2021-11-05 15:04 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottoRankTest.kt
> +    @DisplayName("일치한 숫자에 맞는 등수 찾기(보너스 숫자도 일치하는 경우)")
해당 케이스가 몇등인지에 대한 문구가 있으면 좋을 것 같아요

2021-11-05 15:04 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottoRankTest.kt
> +    @DisplayName("일치한 숫자에 맞는 등수 찾기(일반)")
모든 등수에 대한 케이스가 테스트 코드로 전부 검증해보면 좋을 것 같아요

2021-11-05 15:15 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottoStatisticTest.kt
> +    @DisplayName("로또 당첨된 사람이 있는 경우의 수익률 계산")
로또 당첨된 사람이 없는 경우인 것 같아요 😅

2021-11-05 15:16 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottosTest.kt
> +    @DisplayName("로또 번호가 모두 같지 않는 경우")
```suggestion
    @DisplayName("로또 번호가 모두 같지 않은 경우")
```

2021-11-05 15:16 UTC, BeokBeok commented on src/test/kotlin/lotto/model/LottosTest.kt
> +    @DisplayName("당첨 번호와 로또 숫자 비교")
`당첨 번호와 로또 숫자를 비교해서 몇 개가 일치하는지 확인합니다` 의 뉘앙스로 적어주시면 좀 더 좋을 것 같아요

2021-11-05 15:17 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoStatisticFormat.kt
> +
미사용 import는 제거해주세요

2021-11-06 09:51 UTC, BeokBeok requested changes
피드백을 반영해주시느라 고생하셨습니다 👍 
확인해보니 일부 중요한 피드백이 반영이 안되어 있는 것 같습니다 😭 
궁금하신 부분이 있으시다면 언제든지 DM주세요! 🙏

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lotto.kt
> +
Lotto 객체가 LottoNumbers 객체에 대해서 너무 잘 알고 있는 것 같아요
해당 로직을 LottoNumbers 객체에 메시지를 보내서 확인해보면 어떨까요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +        get() = value ?: MIN_NUMBER
value가 null일 때 예외처리를 하고 있지만, 이 로직만 봤을 때에는 null일때 1이라는 값으로 초기화하는 것으로 보입니다
1이라는 값은 유호한 로또 번호이기 때문에 유효하지 않은 값(가령 음수)으로 초기화해보면 어떨까요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoNumberListGenerator.kt
> +            }
이 함수를 테스트하실 때 로또 생성 개수 확인이 아니라, 내가 원하는 로또 번호로 생성되었는지 확인하는 테스트를 작성해보면 어떨까요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoRank.kt
> +                .sortedBy { it.winningMoney }
이 변수를 테스트하려면 어떻게 하면 좋을까요?
해당 변수에는 비즈니스 로직이 들어간 것으로 보이는데요
비즈니스 로직을 함수로 분리해서 테스트해보면 어떨까요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoRank.kt
> +            if (isBonusNumber) SECOND else THIRD
테스트를 위해서 public 함수로 만든 느낌이 들고, 함수 자체가 의존성이 있어보여요
보너스볼이 일치하면 반드시 2등이고 일치하지 않으면 3등인 로직으로 보이는데요
보너스볼이 일치하지 않으면 무조건 3등일까요? 🤔 
만약에 공이 1개 일치하고 보너스볼이 일치하는 경우에는 어떻게 되는건가요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/LottoStatisticFormat.kt
> +        fun getRankProfit(list: HashMap<LottoRank, Int>, rank: LottoRank): Int = (getRankCount(list, rank) * rank.winningMoney)
함수명만 봤을 때에는 LottoStatisticFormat 객체에서 하는 일이 하니라, LottoRank 객체에서 해야하는 일인 것 같아요

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
> +                    if (lastWinNumber.numbers.contains(lottoNumber)) ++number
@leesohyun13 
확인 부탁드려요!

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
> +    private val bonusNumber: LottoNumber,
생성자에 프로퍼티가 계속 추가되고 있는 것 같아요
처음에는 일급 객체로 시작했지만, 지금은 하나의 클래스에서 여러 가지 책임을 갖게 되는 것 같아요
price, lastWinNumber, bonusNumber는 compareLottoResult 함수에서만 필요한 것으로 보이는데요
불필요한 캡슐화를 개선하여 compareLottoResult 함수에서 필요한 데이터를 파라미터로 받는 것은 어떨까요?

2021-11-06 09:51 UTC, BeokBeok commented on src/main/kotlin/lotto/model/Lottos.kt
>          ): Lottos {
하나의 함수에서 많은 파라미터를 전달받는다는 것은, 그만큼 하나의 함수에서 두 가지 이상의 일을 하고 있다고 봐도 될 것 같아요
이 함수가 어떤 역할을 하는 것일까요?
함수명으로만 봤을 때 지난주 당첨 번호를 입력받는 함수로 보이지만, 실제로는 부가적인 역할도 하고 있는 것 같아요
이 함수를 개선해보면 어떨까요?

2021-11-08 12:52 UTC, BeokBeok approved these changes
피드백을 적극적으로 반영해주시느라 고생하셨습니다 👍 
점점 테스트가 가능해지는 코드가 보기 좋았습니다 💯 
마지막 미션도 화이팅입니다 💪

2021-11-08 12:52 UTC, BeokBeok commented on src/main/kotlin/lotto/model/WinNumber.kt
> +    private val _bonusNumber: LottoNumber
프로퍼티에는 언더바를 붙이지 않는 것이 좋습니다!
private setter public getter를 활용할 때 주로 사용합니다!
```suggestion
    private val lastWinNumber: Lotto,
    private val bonusNumber: LottoNumber
```

2021-11-08 12:52 UTC, BeokBeok commented on src/main/kotlin/lotto/model/WinNumber.kt
> +        get() = _bonusNumber
```suggestion
class WinNumber private constructor(
    lastWinNumber: Lotto,
    bonusNumber: LottoNumber
) {

    init {
        require(!lastWinNumber.hasNumber(bonusNumber)) { EXCEPTION_BONUS_NUMBER }
    }

    var lastWinNumber: Lotto = lastWinNumber
        private set

    var bonusNumber: LottoNumber = bonusNumber
        private set
```
이렇게 쓰시면 될 것 같아요

2021-11-08 12:52 UTC, BeokBeok commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val purchasedLotto = LottoNumberListGenerator(price).generateLottoList(LottoNumber.getLottoNumberRange().shuffled())
외부에서 랜덤 값 주입 👍 💯 🥇

2021-11-08 12:52 UTC, BeokBeok commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val purchasedLotto = LottoNumberListGenerator(price).generateLottoList(LottoNumber.getLottoNumberRange().shuffled())
```suggestion
        val purchasedLotto = LottoNumberListGenerator(price)
            .generateLottoList(
                LottoNumber
                    .getLottoNumberRange()
                    .shuffled()
            )
```
함수 체이닝 컨벤션을 적용하면 좋을 것 같아요

2021-11-08 12:52 UTC, merged