[Step4] : 로또(수동)
next-step/kotlin-lotto pull request #218
Opened 2021-11-06 11:33 UTC by Flamme1004K

안녕하세요. 리뷰어님~ 산뜻한 토요일 저녁이네요 😁

STEP4 로또(수동) 구현하고 리뷰요청 합니다!

요번에도 잘 부탁드립니다😁

2021-11-06 11:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResults.kt
리뷰어님, 요번에 해당 부분은 변경을 고민이 되서 변경은 일단 하지는 않았는데요.
`fun matchingWinningNumber(
            winningNumber: List<Int>,
            bonusNumber: Int,
            purchasedLottos: List<Lotto>
        ): LottoResults {`

위와 같이 winningNumber, bonusNumber, purchasedLottos를 controller 단에서 받도록 구현을 해놨습니다.

그런데, 요번 미션 힌트 중에 '모든 원시값과 문자열을 포장한다.' 라는 부분이 있는데,

controller 단에서 값이 넘어올때부터 원시값과 문자열을 모두 포장을 시켜주고 넘겨줘야하나요?

궁금하네요 🤔

2021-11-06 16:11 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoResults.kt
>          ): LottoResults {
컨트롤러단에서도 값을 넘겨줄 때 포장되어야한다고 생각이 들어서, 바로 수정하여 푸시 하였습니다😁

2021-11-08 13:59 UTC, galcyurio requested changes
로또 마지막 단계까지 잘 구현해주셨습니다 👍 
래퍼 클래스와 일급 컬렉션으로 모두 포장해주신 부분 아주 좋았습니다.

다만 대부분 값을 가지고 있다가 외부로 전달해주고만 있습니다.
한 단계 더 나아가서 내부에서 값을 처리하고 외부로 처리된 값을 반환하도록 리팩터링을 시도해보세요.

2021-11-08 13:59 UTC, galcyurio commented on src/test/kotlin/lotto/LottoStoreTest.kt
> +    fun `수동 로또와 자동 로또의 갯수가 맞는지 테스트`() {
조금 더 무엇을 테스트하고자 하는지 함수명에 드러나면 좋겠어요.
예를 들면, `14000원으로 3개의 수동 로또를 구매하면 3개의 수동로또와 자동 로또 11개가 구매되어야 한다`는 어떨까요?

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottoResults.kt
어디서부터 포장할지 정답은 없지만 개인적으로는 UI에서 domain으로 넘기기 전에 포장해서 domain으로 넘기는게 깔끔하다고 생각합니다.
이렇게 하면 domain 관련 클래스의 함수 시그니쳐에 원시타입을 사용하지 않고 모두 wrapper class로 선언할 수 있기 때문입니다.

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/MatchingWinningNumber.kt
> +            val winningNumberCount = lottoNumbers.toInts().intersect(winningLotto.toInts()).count()
lottoNumbers와 winningNumbers의 내부 값을 꺼내서 사용하고 있습니다.
두 객체 모두 LottoNumbers이므로 LottoNumbers 클래스에서 처리하고 값을 반환하는 식으로 만들 수 있지 않을까요?

```kotlin
val winningNumberCount = lottoNumbers.countOfMatches(winningLotto)
```

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/MatchingWinningNumber.kt
> +            val isBonus = lottoNumbers.toInts().contains(bonusNumber.toInt())
위와 마찬가지로 LottoNumbers에서 LottoNumber를 받아서 가지고 있는지 확인하는 방식으로 바꾸어보세요.

```kotlin
val isBonus = bonusNumber in lottoNumbers
```

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    fun toInts() = lottoNumbers.map { it.toInt() }
`MatchingWinningNumber.of()` 함수의 피드백을 반영하면 이 함수는 필요없어지겠네요.

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottoResults.kt
>              }
toList()를 통해 바깥으로 값을 꺼내서 사용하기보다는 Lottos 클래스에 메시지를 전달해서 Lottos 내부에서 처리를 한 다음에 값을 반환하도록 만들어보세요.

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    fun getAllLottos(): Lottos = Lottos.from(manualLottos.toList() + autoLottos.toList())
아래와 같이 작성되도록 Lottos 클래스를 개선해보세요.

```kotlin
fun getAllLottos(): Lottos = manualLottos + autoLottos
```

2021-11-08 13:59 UTC, galcyurio commented on src/main/kotlin/lotto/domain/ManualLottoNumbers.kt
> +value class ManualLottoNumbers(private val lottoNumbers: List<LottoNumbers>) {
이 래퍼 클래스는 단순히 값을 보관하는 용도로만 쓰이고 있습니다.
toList()를 호출해서 단순히 내부의 값을 반환하는 용도만이 아니라 ManualLottoNumbers로 메시지를 전달하여 해당 메시지에 따라 내부에서 처리한 뒤에 외부에 처리된 값을 반환해보세요.

2021-11-08 16:52 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    fun isBonusNumber(bonusNumber: LottoNumber) = bonusNumber in lottoNumbers
요번에 Lotto 4단계를 짜면서 내부 값에 대해서 꺼내고 쓰고 있어서 이걸 계속 꺼내써도 되는가에 대해 가장 고민이 되었습니다.

하지만 리뷰어님께서 바로 꼭 집어서 알려주셔서 고민이 해소됐습니다.

역시 리뷰어님 짱입니다👍👍

2021-11-08 16:54 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lottos.kt
> +
`fun getAllLottos(): Lottos = manualLottos + autoLottos` 에 대한 부분을 연산자 오버로딩을 통하여 변경을 하였습니다.

처음으로 연산자 오버로딩을 통하여 구현을 해보니, 코틀린 인 액션에서도 왜 연산자 오버로딩을 강조하는지 알겠네요.

그만큼 코드가 간결해지고 강력한 기능인 것 같습니다 😁

2021-11-08 17:07 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    fun isBonusNumber(bonusNumber: LottoNumber) = bonusNumber in lottoNumbers
여기서 질문이 있습니다.

처음에 변경하고나서 테스트를 돌려본 결과, 결과값이 전부 0이나와서 놀랬습니다.

하지만, 제가 생각하기로는 LottoNumber라는 클래스가 일반 클래스이고, 다 각각의 주소값을 가지고 있기 때문에

오류가 난 것이다라고 생각하여 LottoNumber를 data class로 만들어 줌으로써 해당 부분을 해결을 했습니다.

intersect()나 in이나 모두 값을 비교할 때 equals 비교를 해서 그런건가요?

2021-11-08 17:09 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/ManualLottoNumbers.kt
> +    fun buyLottos(): List<Lotto> = lottoNumbers.map { Lotto.from(it) }
리뷰어님 피드백을 읽고, ManualLottoNumbers에게 메시지를 전달하여 내부 처리를 하도록 만들기 위해서 

getSize와 buyLottos 메서드를 만들었는데, 이렇게 하는게 맞는걸까요?

아니면 리뷰어님의 다른 의도가 숨겨져 있으신건가요? 궁금합니다!

2021-11-08 17:14 UTC, Flamme1004K commented
<img width="1012" alt="스크린샷 2021-11-09 오전 1 34 39" src="https://user-images.githubusercontent.com/50702723/140786914-57e4d170-874f-488e-8c50-a712a3470632.png">

TotalRate class에서 위의 메서드를 보면 getResult()를 공통으로 사용을 하고 있습니다.

그런데 getResult()를 공통으로 쓰게 된다는 점이 내부의 값을 꺼내서 외부에서 처리를 하는 것과 같은데,

일단, 이 getResult()를 포함한 sumLottoCount , sumPrize 모두 LottoResults 클래스에 옮겨야 하나 의문이 듭니다.

왜냐하면 totalRate라는 클래스는 총 비율을 만들어주는 클래스인데, sumLottoCount나 SumPrize가 모두 LottoResults에 들어가 버리면,

totalRate의 역할이 모호해지고, LottoResults에게 너무 많은 책임을 주는게 아닌가 라는 생각을 하게 되더라구요.

리뷰어님의 의견을 듣고 싶습니다🤔

2021-11-09 14:52 UTC, galcyurio requested changes
피드백 반영 고생하셨습니다! 👏 
마지막으로 피드백 드린 부분들 한 번 더 리팩터링을 진행해보면 좋겠습니다.

2021-11-09 14:52 UTC, galcyurio commented on src/main/kotlin/lotto/domain/ManualLottoNumbers.kt
> +    fun buyLottos(): List<Lotto> = lottoNumbers.map { Lotto.from(it) }
제가 생각했던 방향과 조금 다르게 구현된 것 같습니다.
전체적으로 아래와 같이 수정해보는 건 어떨까요?

로또 판매점(LottoStore)에 지갑(Wallet)을 들고 돈(money)을 지불하여 로또 티켓들(Lottos)을 구매하는 방식으로 만들어보세요.

현재 구현은 로또를 산 다음에서야 로또 판매점을 만들 수 있어서 무언가 역전된 느낌이 듭니다.

```kotlin
fun purchaseLotto(wallet: Wallet, manualLottoNumberTexts: List<String> = emptyList()): LottoStore {
    val manualLottoNumbers = ManualLottoNumbers.generateManualLottoNumbers(manualLottoNumberTexts)
    wallet.buyManualLotto(manualLottoNumbers.getSize())
    return LottoStore(Lottos.buyManualLottos(manualLottoNumbers), Lottos.buyAutoLottos(wallet))
}
```

2021-11-09 14:52 UTC, galcyurio commented on src/main/kotlin/lotto/domain/Lotto.kt
> TotalRate class에서 위의 메서드를 보면 getResult()를 공통으로 사용을 하고 있습니다.
> 
> 그런데 getResult()를 공통으로 쓰게 된다는 점이 내부의 값을 꺼내서 외부에서 처리를 하는 것과 같은데,
> 
> 일단, 이 getResult()를 포함한 sumLottoCount , sumPrize 모두 LottoResults 클래스에 옮겨야 하나 의문이 듭니다.
> 
> 왜냐하면 totalRate라는 클래스는 총 비율을 만들어주는 클래스인데, sumLottoCount나 SumPrize가 모두 LottoResults에 들어가 버리면,
> 
> totalRate의 역할이 모호해지고, LottoResults에게 너무 많은 책임을 주는게 아닌가 라는 생각을 하게 되더라구요.
> 
> 리뷰어님의 의견을 듣고 싶습니다🤔

개인적으로는 LottoResults가 관련된 모든 정보를 가지고 있으므로 LottoResults에서 처리하는게 더 좋다고 생각합니다.
그렇게 구현했을 때 TotalRate의 역할이 모호한 이유는 TotalRate를 구한뒤에 더 이상 처리할 것 없이 출력해주면 되기 때문이 아닐까요?

2021-11-10 15:43 UTC, Flamme1004K commented
항상 저에게 많은 가르침을 주시는 리뷰어님 :)

피드백 주신 부분에 대해 수정하고 리뷰 요청 합니다!

요번에도 잘 부탁드립니다😁

2021-11-10 15:43 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    fun isBonusNumber(bonusNumber: LottoNumber) = bonusNumber in lottoNumbers
헉.. 지금 해보니깐 잘 되네요!!

그때 잠깐 다른 에러가 있었나봅니다 😭😭😭

2021-11-10 15:47 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +
LottoStore에 대해서 기본 생성자를 wallet으로 변경하면서 manualLottos와 autoLottos를 변수로 내렸습니다 

그런데, 원래대로라면, lateinit var를 이용하여 변수 선언을 하려고 했는데, Lottos라는 클래스가 value class라서 불가능하더라구요.

혹시, 이런 경우에는 value class를 일반 class로 만드나요?

아니면 다른 방법이 있을까요?🤔

2021-11-10 15:50 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
이 부분이 순서가 매우 중요하게 되버렸습니다..

purchaseAutoLottos를 purchaseManualLottos보다 먼저 실행 시켜버리면

14000원을 넣었을 경우 manualLottos를 3장을 사고, 나머지를 autoLottos를 사는 경우에 

autoLottos를 14장사고, ManualLottos를 3장 사게되는 오류가 발생을 하는데,

이런 경우를 대비해서, 더 세분화를 해야할까요?? 🤔

2021-11-11 15:03 UTC, galcyurio requested changes
제 피드백이 잘못 전달된 것 같네요.
코드 예시를 남겨두었으니 참고해주세요!

2021-11-11 15:03 UTC, galcyurio commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
구매할 로또의 개수를 미리 정해서 parameter로 넘기는식으로 변경해보세요.
이 부분은 현재 Wallet을 불변 클래스로 만들고 각 함수에서 side effect를 제거하여 [순수 함수](https://zladnrms.tistory.com/117)로 만들어보면 자연스럽게 해결될 것으로 기대됩니다.

2021-11-13 18:04 UTC, Flamme1004K commented
안녕하세요. 리뷰어님!

리뷰어님 피드백 받고나서, 다시 변경하여 리뷰 요청 합니다 😊

확실히, lotto Store 부분을 모두 순수함수로 변경하니, 로직이 클린해지네요. 역시 리뷰어님 짱입니다👍

리뷰어님 말씀하신데로 클래스를 만들고, 필드를 추가할 때 과연 필요한 필드인가에 대해서 꼭 생각을 해봐야되겠다는 생각하게 되었습니다.🤔

많은 경험을 주셔서 감사합니다 리뷰어님 🙇🏻

2021-11-15 12:14 UTC, galcyurio approved these changes
피드백 잘 반영되었네요 👍 
지금까지 로또 미션 고생하셨습니다.
다음 미션도 힘내세요!

2021-11-15 12:14 UTC, merged