[Step4] 로또 (수동)
next-step/kotlin-lotto pull request #234
Opened 2021-11-16 17:32 UTC by ssibongee

리뷰어님 안녕하세요 🙇 
리뷰 요청 드리는게 많이 늦었네요 ㅠㅠ 마지막 미션까지 잘 부탁드립니다 🙏

2021-11-17 08:08 UTC, vsh123 requested changes
안녕하세요!!
Step3까지 너무 잘구현해주셨구, 수동 로또도 기존 로직에 잘 녹여내셨네요! 💯 

몇가지 코멘트를 남겼으니 확인 부탁드리겠습니다 :) 
혹시 추가적으로 고민이 있는 부분이 있다면 말씀주세요!

2021-11-17 08:08 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
>              .map { generator.generate() }
수동생성이 추가되니까 `generator`라는 프로퍼티명이 어색해보이는데요! 어떻게 생각하시나요?

2021-11-17 08:08 UTC, vsh123 commented on src/main/kotlin/lotto/LotteryApplication.kt
> +
run()함수도 10줄이 넘어갔는데요!! 함수의 길이를 줄여볼 수 있을까요?

2021-11-17 08:08 UTC, vsh123 commented on src/main/kotlin/lotto/LotteryApplication.kt
> +        val manual = view.inputManualCountPrompt()
manual보다는 manualLotteryCount와 같이 조금 더 명확한 네이밍은 어떨까요?

2021-11-20 04:57 UTC, ssibongee commented on src/main/kotlin/lotto/domain/Order.kt
> +class Order(val manual: Int, val auto: Int, val selected: List<LottoNumbers> = listOf()) {
Order클래스는 도메인 클래스는 아니고 DTO의 느낌으로 정의하였는데요. 

Application에서 LottoMachine에 수동으로 선택한 번호, 수동으로 선택한 번호 목록, 자동으로 선택한 개수를 각각 넘겨주는 과정에서 
- 전체 구매 가능한 개수에서 수동으로 선택한 번호를 빼서 자동으로 선택 가능한 번호를 구해주는 것을 Application에서 감추고 싶었고 
- 이들을 묶어서 한번에 넘겨줄 수 있는 클래스가 있으면 좋겠다고 생각했습니다.

2021-11-20 05:11 UTC, ssibongee commented on src/main/kotlin/lotto/ui/LottoView.kt
> +            .map { inputManualLottoNumbers() }
피드백 주신 부분을 확인해보니 굳이 해당 메서드에서 다시 `LottoNumbers.of(it)` 형식으로 다시 만들어줄 필요 없이 LottoNumbers를 바로 만들어서 넘겨줄 수 있겠네요! 🙏

2021-11-20 05:19 UTC, ssibongee commented on src/main/kotlin/lotto/domain/LottoMachine.kt
>              .map { generator.generate() }
이 부분에 대한 네이밍을 많이 고민했었는데 로또 번호 수동 생성같은 경우에는 LottoNumberGenerator가 아닌 사용자가 입력한 번호를 가지고 생성되기 때문에 굳이 Generator를 거칠 필요가 없고 이에 따라서 `generator`라는 프로퍼티명을 사용하더라도 혼란이 생기지 않을 것이라고 판단했습니다.

고민해보니 좀 더 정확하게는 LottoNumberGenerator의 경우에도 자동생성 전략에 대한것이기 때문에 LottoNumberAutoGenerator와 같은 네이밍이 되어야 할 것 같고 이에 대한 구현체들은 다양한 자동 생성 방식들에 대한 구현체 클래스가 되는 방향이 바람직할 것 같네요..! 🙏

2021-11-20 12:32 UTC, vsh123 commented on src/main/kotlin/lotto/domain/Order.kt
> +class Order(val manual: Int, val auto: Int, val selected: List<LottoNumbers> = listOf()) {
DTO의 느낌이라면 data class로 선언해주는 건 어떨까요?

2021-11-20 12:40 UTC, vsh123 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
>              .map { generator.generate() }
> 고민해보니 좀 더 정확하게는 LottoNumberGenerator의 경우에도 자동생성 전략에 대한것이기 때문에 LottoNumberAutoGenerator와 같은 네이밍이 되어야 할 것 같고

이부분 동의합니다!! 말씀주신 방향으로 수정해보면 어떨까요~?

2021-11-20 12:41 UTC, vsh123 requested changes
안녕하세요!
피드백 반영 잘해주셨네요!! 💯 

코멘트 남겨주신 부분에 추가 의견을 달았습니다! 
확인 부탁드릴게요~~ :) 

궁금하신 부분은 디엠주세요!

2021-11-21 00:06 UTC, vsh123 approved these changes
안녕하세요!!
피드백 반영 감사합니다 💯 

로또 미션은 여기서 마무리 하도록 할게요!
미션 수행하시느라 고생하셨습니다~~!!

다음 미션도 화이팅하세요!! :)

2021-11-21 00:06 UTC, merged