[ 1단계 ] 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #277
Opened 2022-05-21 06:37 UTC by YooInKeun

안녕하세요 리뷰어님~ 
클래스의 역할을 고민해보면서 문자열 덧셈 계산기 기능을 구현해봤는데, 리뷰 부탁드립니다 ㅎㅎ
로또 미션 동안 잘 부탁드립니다~! 👍

2022-05-21 07:56 UTC, pci2676 requested changes
안녕하세요~ 로또 미션 리뷰를 담당하게 된 박찬인이라고 합니다!
아주 깔끔하게 문자열 덧셈 계산기를 구현해주셨네요!

조금 더 수정해보면 좋을 부분에 리뷰를 남겨두었습니다!
고민해서 수정해보시고 이해가 안되는 부분이 있으시다면 편하게 DM주셔도 됩니다!

즐거운 주말 보내세요~

2022-05-21 07:56 UTC, pci2676 commented on src/main/kotlin/calculator/model/Number.kt
> +value class Number private constructor(
크 인라인 클래스를 이용해서 값 객체를 표현하셨군요! 멋집니다! 👍 

조오금 아쉬운 부분이 있는데요 해당 값 객체는 양수만을 나타내기 때문에 클래스의 이름이 `Number` 보다는 양수를 나타낼수 있도록 변경하는건 어떨까요?

추가로 기본 생성자를 `private`으로 막아두고 동반객체(companion object)를 이용해서 객체를 생성하게 하고 계시는데 값객체의 값을 검증하는 부분이 `from` 에 있는것이 가장 좋은 위치일지 고민해보시면 좋을것 같습니다.

만약 동반객체에서 이 객체를 생성하는 방법이 추가로 구현이 된다면 매번 `validateNumber`를 추가해줘야하지 않을까요?
이 부분은 사람이 충분히 실수하기 쉬운 부분일것 같습니다!

2022-05-21 07:56 UTC, pci2676 commented on src/main/kotlin/calculator/model/AddCalculator.kt
> +        return splitAndSum(tokens = input)
지금은 사용자 정의 구분자를 구분하는 정규표현식이 하나이기 때문에 `AddCalculator`에 정규표현식을 몰아넣어서 관리하고 분기문을 이용해서 식의 분리, 계산을 처리하고 있는데요.

사용자 정의 구분자를 구분하는 정규표현식이 늘어나게 됐을때 지금같이 구현하게 된다면 더 복잡해질 수 있을것 같습니다!
전략패턴을 이용해보는것도 좋은 방법이 될것 같네요!

`AddCalculator`에는 더하는 책임만, 다른 곳에 분리하는 책임을 나눠보면 좋을것 같습니다!

2022-05-21 07:56 UTC, pci2676 commented on src/main/kotlin/calculator/model/Numbers.kt
> +    }
이 부분에 코틀린 감수성을 조금 추가해보는건 어떨까요!
Numbers의 sum() 메서드는 결국 Numbers의 총 합이라는 상태를 나타내는것으로 보입니다!
코틀린에서 val는 상태를 나타내는 프로퍼티인데요 지금 Numbers는 불변객체이기도 하니 아래와 같이 표현하는 방식이 있을 것 같습니다!

불변객체라면
```suggestion
    val sum: Int = numbers.sumOf { it.number }
```

가변객체라면
```suggestion
    val sum: Int
        get() = numbers.sumOf { it.number }
```

2022-05-21 07:56 UTC, pci2676 commented on src/test/kotlin/calculator/model/AddCalculatorTest.kt
> +        assertEquals(AddCalculator.calculate(input), 6)
위 리뷰에서 말씀드렸듯 커스텀 구분자, 기본 구분자가 정상적으로 작동하는지 수식을 넣고 그 결과를 확인하기 보단
구분자를 가지고 수식을 분리하는 객체에게 '수식을 분리해줘!' 라고 하거나 '이 수식 분리할 수 있어?'라고 묻는 구조로 테스트를 할 수 있는게 더 좋아보입니다!

`AddCalculator`에게 우리가 던지는 메세지는 '이 수식 더해줘' 니까요~!

2022-05-21 07:56 UTC, pci2676 commented on src/test/kotlin/calculator/model/AddCalculatorTest.kt
> +    }
크 `@ParameterizedTest`를 활용해서 꼼꼼한 테스트를 작성해주셨군요! 👍 
`delimiter` 를 활용한것 까지 굉장히 인상깊었습니다!

2022-05-25 05:11 UTC, YooInKeun commented on src/main/kotlin/calculator/model/Number.kt
> +value class Number private constructor(
> 추가로 기본 생성자를 private으로 막아두고 동반객체(companion object)를 이용해서 객체를 생성하게 하고 계시는데 값객체의 값을 검증하는 부분이 from 에 있는것이 가장 좋은 위치일지 고민해보시면 좋을것 같습니다.
> 
> 만약 동반객체에서 이 객체를 생성하는 방법이 추가로 구현이 된다면 매번 validateNumber를 추가해줘야하지 않을까요?

말씀 주신 부분에 대해 동의하고, 짚어주셔서 감사합니다 👍  ㅎㅎ

하지만 `Number` 를 생성하기 위한 파라미터를 string 으로 받고 있는 상황에서 number(string)를 검증하기 위한 `validateNumber` 를 한 곳에서 처리할 방법이 떠오르지 않는데 조언 부탁드립니다~!

2022-05-25 05:13 UTC, YooInKeun commented on src/main/kotlin/calculator/model/AddCalculator.kt
> +        return splitAndSum(tokens = input)
좋은 인사이트 진심으로 감사드려요~ 👍  👍
말씀 주신대로 책임을 분리하는 것이 깔끔하고 좋아보입니다!
해당 작업 확인 부탁드려요~

2022-05-25 10:49 UTC, pci2676 commented on src/main/kotlin/calculator/model/Number.kt
> +value class Number private constructor(
아 이거는 양수인지를 검증하는 부분은 `init`에 옮기는게 좋지 않을까 하는 의견이었습니다.
이 객체를 생성하는 방법이 문자열 이외에 
바로 정수를 사용하여 생성해야하는 요구사항이 생겼을 때 

매번 `String` 으로 변환해서 넣는것 보다는 
바로 정수를 이용해서 객체를 생성할 수 있도록 해주는 것이 좋을것 같다고 생각했거든요~!

그래서 문자열을 입력 받았을 때는 숫자 형태인지 검사해주면 되고 양수인지 검사는 최후로 미루는 것이 좋지 않을까? 라는 의견이었습니다~!

2022-05-25 10:52 UTC, pci2676 commented on src/main/kotlin/calculator/model/AddCalculator.kt
> +        return splitAndSum(tokens = input)
리뷰 반영하신것 확인했습니다 `object`의 활용부터 인터페이스 분리까지 아주 완벽하게 작성해주셨네요! 💯

2022-05-25 10:56 UTC, pci2676 approved these changes
안녕하세요! 리뷰 반영해주신 것 잘 봤습니다!
인터페이스 분리와 전략 패턴 적용까지 아주 깔끔하게 해주셨네요!
고민하신 부분은 제가 코멘트로 답장을 남겨두었습니다. (제가 기존에 설명을 조금 애매하게 한 것 같네요😅)
이번 미션은머지하도록록 하겠습니다!
수고하셨습니다!

2022-05-25 10:56 UTC, merged