4단계 - 로또(수동)
next-step/kotlin-lotto pull request #294
Opened 2022-05-22 23:29 UTC by revfactory

지난 PR Merge 시 추가 피드백도 적용 했습니다.
https://github.com/next-step/kotlin-lotto/pull/274

2022-05-23 13:10 UTC, laco-dev requested changes
4단계 미션 잘 해주셨습니다 💯 

지난번 주셨던 질문 포함해서 고민하고 도전 해볼만한 내용을 피드백 남겨드렸습니다!

2022-05-23 13:10 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    val numbers: List<LottoNumber> = numbers.toList().map { LottoNumber(it) }
LottoNumber가 1부터 45까지라는 값을 가지고 이 값은 변하지 않는 45개의 인스턴스라고도 볼 수 있는데요.
LottoNumbers가 만들어 질 때마다 같은 숫자를 가진 로또 번호라도 매번 새로운 인스턴스가 만들어 지고 있어요.

이 내용을 한번 고민 해 보시고 적절하게 재활용할 수 있는 방법이 없을지 개선 해보면 좋겠습니다.

2022-05-23 13:10 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
LottoNumberGenerator라는 인터페이스를 이용해서 같은 역할을 하는 제너레이터를 만들어 볼 수 있을 것 같아요!

2022-05-23 14:55 UTC, revfactory commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    constructor(lottoNumberGenerator: LottoNumberGenerator = RandomLottoNumberGenerator) : this(lottoNumberGenerator.generate(), true)
@laco-dev
```
Lotto(RandomLottoNumberGenerator.generate(), true).isAutoPick shouldBe true
```
위 처럼 이미 자동 생성된 번호 목록을 전달하고 있는데 다시 자동 유무를 같이 넘기는 게 어색해서 고민했네요.
NumberGenerator 는 이름 그대로 숫자를 생성하는 것이니 자동으로 볼 수 있을 것 같아요.
다만, LottoNumberGenerator 인터페이스로 생성기를 보장하려고 했는데 어색한 부분이 있긴 하군요.
기존대로 LottoMachine 이 결정하도록 돌려야 겠네요.

2022-05-26 13:06 UTC, laco-dev requested changes
피드백 반영 확인했습니다. 👍 
바로 답글을 남겨주셨는데 확인이 늦었군요ㅠ 😭 

로또 미션의 마지막 단계라서 추가적으로 개선해 보면 좋을만한 내용들에 의견을 남겨보았습니다.

2022-05-26 13:10 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
아하, 제 의도는 LottoNumberGenerator를 통해 LottoNumbers를 반환하고 있어서요.
내부 구현은 어떻게 되는지 관심없이 LottoNumbers만 받아오는 것만 신경쓰면 되지 않을까 생각을 헀습니다.

아래와 같은 느낌으로요!

```kotlin
fun interface LottoNumberGenerator {
    fun generate(): LottoNumbers
}

class RandomLottoNumberGenerator: LottoNumberGenerator { ... }

class SimpleLotoNumberGenerator(numbers: LottoNumbers): LottoNumberGenerator {
   fun generate() = numbers
}
```

2022-05-26 13:51 UTC, revfactory commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
로또　숫자　생성기　인터페이스로　설계한　의도는　확장성을　염두에　둔　것이고，　단순히　숫자를　전달하는　용도로는　숫자　생성기를　이용할　필요는　없을　것　같습니다．

제　생각에는　이런　케이스가　확장될　수　있지　않을까　싶어요　＾＾
｀｀｀
－　반자동　로또　숫자　생성기　：　５개　이하로　숫자를　지정하고　나머지　숫자는　자동으로　생성
－　지난　로또　결과를　토대로　가중치가　부여된　랜덤　생성기
｀｀｀

2022-05-26 16:17 UTC, revfactory commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +        class Builder(private val lottoNumbers: LottoNumbers) {
전체적으로 static factory method 를 적용했습니다.
builder 관련해서는 이견 없습니다.
vararg 를 사용하는 것은 listOf( ) 를 사용처에서 매번 써야 하는가? 하는 고민에서 시작한 것인데, WinningLotto 에서 걸림돌이 되었네요. 이 부분은 리뷰어분 의견에 따라 과감히 정리했습니다.

2022-05-28 01:09 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
네! LottoMachine의 역할은 Lotto를 반환하는 책임은 유지하고 있으니, 말씀주신 내용도 맞을 것 같습니다. 🙏

2022-05-28 01:13 UTC, laco-dev approved these changes
피드백 반영 확인 헀습니다.

기본적인 실력도 상당히 좋으셨는데도 고민 해 볼만한 내용들을 잘 따라와 주셔서 감사합니다.
덕분에 저도 같이 성장할 수 있는 좋은 기회가 되었습니다.

다음 미션도 화이팅입니다. 🙏

2022-05-28 01:13 UTC, merged