step1 : 문자열 더하기 계산기
next-step/kotlin-lotto pull request #295
Opened 2022-05-23 09:35 UTC by jngcii

리뷰 부탁드립니다.
lotto 미션 구현 잘 부탁드립니다 :)

2022-05-23 12:42 UTC, hyunniiii requested changes
안녕하세요 형수님!
몇가지 코멘트 남겼으니 확인 부탁드립니다 🙏

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val calculator = Calculator()
상태를 가지지 않는 클래스들은 `Object`로 선언해주면 코드가 조금 더 간결해질 것 같아요 :)

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val numbers = inputView.getNumbers()
커스텀 구분자로 이루어진 값을 입력하면 제대로 동작하지 않는 것 같아요!
확인 한번 부탁드립니다 😄

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputParser.kt
> +    private val defaultDelimiterRegex = Regex("$COMMA|$COLON")
```suggestion
    private const val delimiterParseRegex = Regex("//(\\D)\n(.*)")
    private const val defaultDelimiterRegex = Regex("$COMMA|$COLON")
```
이걸 의도하신 걸까요? 😄

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputParser.kt
> +    }
`RuntimeException`보다는 어떠한 exception인지 명확하게 알려주는게 디버깅할 때 더 좋을 것 같아요 :) 

또한 이 exception들에 대한 테스트도 작성할 수 있을 것 같습니다 : )

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +        }
>빈 문자열 또는 null을 입력할 경우 0을 반환해야 한다. (예 : “” => 0, null => 0)

`[0]`과 `0`은 다르지 않을까요? 😄 

또한 이 부분에 대한 테스트도  추가할 수 있을 것 같네요 :)

2022-05-23 12:42 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/README.md
> +## TODO-LIST
TODO-LIST를 기능 요구 사항 내용을 참고해서 조금 더 자세하게 적어보는건 어떨까요?

2022-05-24 02:53 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputParser.kt
> +    private val defaultDelimiterRegex = Regex("$COMMA|$COLON")
`const`는 primitive 타입에만 붙일수 있어서 regex에는 붙일수 없는걸로 알고있어요~ 맞을까요??

2022-05-24 02:54 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val numbers = inputView.getNumbers()
테트스코드는 잘 동작하는데, 실행하면 안되네요 ㅠㅠ
요구사항의 \n이 개행을 말하는건지 문자열 `"\n"`을 말하는건지 잘 모르겠어요!

2022-05-24 02:54 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val calculator = Calculator()
[refactor : 상태를 가지지 않는 클래스를 object로 변경](https://github.com/next-step/kotlin-lotto/pull/295/commits/84d2b1969e6280cbb4b05a4eee490194e65ff696)
오 몰랐던 기능이에요! 알려주셔서 감사합니다 :)

2022-05-24 02:55 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputParser.kt
> +    }
요구사항에 `RuntimeException`을 던지라고 명시되어 있어서 이렇게 구현했는데, `RuntimeException`을 상속하는 예외도 가능한거였군요 ^^;;
수정했습니다! [refactor : 잘못된 입력에 대한 예외 수정 및 테스트 추가](https://github.com/next-step/kotlin-lotto/pull/295/commits/fdfa68f74ccf60efa1715e3309176c52c8ad37dc)

2022-05-24 02:57 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +        }
요구사항의 `0을 반환한다`는 `계산 결과값이 0을 반환한다`로 이해하고 있어요.
그리고 이부분은 입력값을 반환하는 함수입니다!

`readLine`이 있는 함수도 테스트가 가능한가요?!

2022-05-24 02:57 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/README.md
> +## TODO-LIST
네! step2부터 조금 더 자세히 기록하고 진행해보겠습니다 😭

2022-05-25 08:22 UTC, hyunniiii requested changes
안녕하세요~!
리뷰 반영 잘 해주셨네요 👍 
몇가지 코멘트 남겼으니 확인 부탁드립니다!

2022-05-25 08:22 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    resultView.print(result)
```suggestion
    val numbers = InputView.getNumbers()
    val result = Calculator.run(numbers)
    ResultView.print(result)
```

2022-05-25 08:22 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +        return inputParser.parseExpression(expression, delimiter)
```suggestion
        val (expression, delimiter) = InputParser.parseDelimiter(input)

        return InputParser.parseExpression(expression, delimiter)
```

2022-05-25 10:24 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    resultView.print(result)
[refactor : 불필요 변수 제거](https://github.com/next-step/kotlin-lotto/pull/295/commits/206f0c8d7422c9f8a0e43b6728bc2742d7c6af65)

수정했습니다! 리뷰 감사합니다 :)

2022-05-25 10:25 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +        }
좋아요!
[refactor : InputView::getNumbers 함수 리팩터링 및 테스트](https://github.com/next-step/kotlin-lotto/pull/295/commits/b5d6d955059cbc7b42fc5b94a73ca88ca06d60c7)

위처럼 바꿔봤어요 :)

2022-05-25 10:26 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputParser.kt
> +    private val defaultDelimiterRegex = Regex("$COMMA|$COLON")
InputParser는 object라서 내부에 companion object를 사용할수 없네요 😭
불필요한 상수는 제거했습니다! [refactor : 불필요한 상수 제거](https://github.com/next-step/kotlin-lotto/pull/295/commits/6a52cd4d9300da6666768c8eb500e5914d08896c)

2022-05-25 10:34 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val numbers = inputView.getNumbers()
[refactor : 구분자 파싱 정규식 수정](https://github.com/next-step/kotlin-lotto/pull/295/commits/1f1ae7a03378379d9535cc8220925b43430e5acf)
`\n` 말고 `₩n`를 찾도록 하니 잘되네요 ㅎㅎ 수정했습니다

2022-05-25 10:36 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val numbers = inputView.getNumbers()
앗, https://github.com/next-step/kotlin-lotto/pull/295#discussion_r881195273 이 댓글을 늦게 발견해서 다시 수정했습니다 ^^;; 감사합니다 :)
[refactor : 구분자 파싱 정규식 수정](https://github.com/next-step/kotlin-lotto/pull/295/commits/04eaab3ad082f2ead9f44b59f18668816a1de99d)

2022-05-25 10:36 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +        return inputParser.parseExpression(expression, delimiter)
inputParser는 class라서 제안해주신대로 수정 못했습니다 😭

2022-05-25 13:02 UTC, hyunniiii approved these changes
안녕하세요 형수님~!
피드백 반영 잘해주셨네요 :)
다음 미션을 위해 머지하겠습니다 👍

2022-05-25 13:02 UTC, merged

2022-05-25 23:55 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/InputView.kt
> +}
오 그러네요? 리뷰 감사합니다!

2022-05-25 23:55 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/calculator/Application.kt
> +    val numbers = inputView.getNumbers { readLine() }
오호 감사합니다~!