Step1 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #297
Opened 2022-05-23 12:13 UTC by D000L

리뷰 부탁드립니다~!

2022-05-24 12:03 UTC, laco-dev requested changes
안녕하세요. 
로또 미션동안 잘 부탁드립니다.

기능 단위로 커밋을 잘 나눠 주신 점 정말 좋았습니다.
역할에 맞게 객체도 분리를 해 주셨는데 몇 가지 고민 해 볼만한 내용들과 수정사항을 피드백으로 남겼습니다. 🙏

2022-05-24 12:03 UTC, laco-dev commented on src/main/kotlin/calculator/Numbers.kt
> +    }
Numbers의 기능에 대한 테스트도 추가 해 보면 좋겠습니다.

2022-05-25 10:17 UTC, D000L commented on src/main/kotlin/calculator/Parser.kt
> +            else delimiter to expression
넵 커스텀 구분자 유무에 상관없이 해당로직을 돌리고 있어서 커스텀 구분자가 없는 경우에는 나타날수가 있습니다.

2022-05-25 10:23 UTC, D000L commented on src/test/kotlin/calculator/StringCalculatorTest.kt
> +    }
Calculator 로 보는 편이 더 좋을 거 같습니다.
의견감사합니다.~!

2022-05-26 12:19 UTC, laco-dev approved these changes
피드백 잘 반영 해주셨습니다. 👏 

Fake 생성자를 이용한 방법에 관련해서 한 가지 의견을 남겨드렸는데,
고민 해 보시고 다음 단계에 같이 수정 해 주시면 됩니다.

1단계 미션 수고하셨습니다. 👍

2022-05-26 12:19 UTC, laco-dev commented on src/main/kotlin/calculator/Numbers.kt
> +fun Numbers(strings: List<String>) = Numbers(strings.map(String::toInt))
Fake Constructor 동작을 시도 해 보신 것 같아요!
그런데 이 방법은 특수한 경우에 사용되고는 합니다.

예를 들어 MutableList는 인터페이스 타입인데요.
하지만 우리는 MutableList(...) 라는 함수로 실제 값을 생성할 수 있습니다.

실제 생성은 할 수 없지만 생성을 할 수 있게 만드는 것처럼 패턴화를 할 때 정하는 상당히 마이너한 방법이기는 합니다.
MutableList(...) 함수 구현체를 한번 살펴보세요!

지금 구조에서는 부 생성자나 정적 팩토리 메소드를 활용 해 보는게 더욱 좋을 것 같아요!

2022-05-26 12:19 UTC, merged