Step2 : 로또(자동)
next-step/kotlin-lotto pull request #333
Opened 2022-05-27 03:14 UTC by jngcii

커밋 단위를 TDD에 따라 구현해봤습니다. 리뷰부탁드려요~! (첫 커밋은 [step1에서 리뷰주신것](https://github.com/next-step/kotlin-lotto/pull/295#pullrequestreview-984767244) 반영한 커밋입니다!)

2022-05-28 14:57 UTC, hyunniiii requested changes
안녕하세요 ″̮
로또 미션 잘 구현해주셨네요 👍 
몇가지 코멘트 남겼으니 확인 부탁드립니다 ″̮

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/README.md
> +- [x] 출력기능 구현
기능 요구 사항을 잘 적어주셨네요!
여기서 조금 더 디테일한 부분을 추가해주면 어떨까요?
예시)
- [ ] 등수를 계산하는 기능 구현
    - [ ] 6개가 모두 일치하면 1등이다.
    - [ ] 5개가 일치하고 보너스 볼이 일치하면 2등이다.
    - [ ]  5개가 일치하면 3등이다.

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Lotto.kt
> +    }
```suggestion
    fun getSameCount(comparison: Lotto): Int {
            return numbers.intersect(comparison.numbers.toSet()).count()
    }
```

이렇게 한번에 표현이 가능할 것 같습니다 ″̮

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/truncate.html

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Lotto.kt
> +    }
숫자가 `1~45` 사이인 경우에 대한 검증은 `숫자를 6개 가진 로또` 보다는 `하나의 숫자`를 의미하는 객체에서 검증하는게 좋을 것 같아요 ″̮

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/InputView.kt
> +    }
이런 경우 `exception`을 던지기 보다는 사용자가 바로 재입력을 할수 있도록 해보면 어떨까요?

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +    }
입력을 받는 부분에 관련된 문구 같아요. 
`InputView`에 포함시켜주면 어떨까요?

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +        get() = "[${this.numbers.joinToString(", ")}]"
복잡한 로직이 아니니 메서드를 따로 분리하지 않아도 좋을 것 같습니다 : )

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +    private fun List<Rank>.count(rank: Rank) = this.count { rank == it }
이 부분은 비즈니스 로직으로 보이네요.
`view`가 가져야할 책임인지 한번 고민해보면 좋을 것 같아요 ″̮

2022-05-28 14:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/Controller.kt
> +fun main() {
중요한 부분은 아니지만 클래스 이름을 `Controller.kt` 보다는 `Application.kt`로 해주면 어떨까요  ″̮

2022-05-29 15:45 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Lotto.kt
> +    }
[refactor : Lotto의 numbers 타입을 Set으로 변경 및 sameCount 로직 리팩터링](https://github.com/next-step/kotlin-lotto/pull/333/commits/f1b2cd444ebeeab62e7189422bfe75a872f67b25)
반영했습니다! :)

2022-05-29 15:45 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Lotto.kt
> +    }
[refactor : 개별 숫자를 가진 LottoNumber 객체 생성](https://github.com/next-step/kotlin-lotto/pull/333/commits/33769a8e4b494c5148c032724d2d6c6ada490810)

반영했습니다! :)

2022-05-29 15:45 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +    }
[refactor : 입력 관련 print문 재위치](https://github.com/next-step/kotlin-lotto/pull/333/commits/3feaaa16a923078820cd5fcb6f444aea023f56b4)

반영했습니다! :)

2022-05-29 15:46 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/InputView.kt
> +    }
[refactor : 부적절한 값 입력시 다시 입력하도록 로직 변경](https://github.com/next-step/kotlin-lotto/pull/333/commits/fd71fd2d9f7d9be79a8c1360b7b2f357f76c6e0d)

반영 완료했습니다!

2022-05-29 15:46 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +        get() = "[${this.numbers.joinToString(", ")}]"
[refactor : 간단한 함수 제거하고 inline 구현](https://github.com/next-step/kotlin-lotto/pull/333/commits/e452c43829e5a2546e9c34e9521d29aee6e871c2)

네! 반영했습니다!

2022-05-29 15:47 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/ResultView.kt
> +    private fun List<Rank>.count(rank: Rank) = this.count { rank == it }
[refactor : rank list를 Ranks 일급객체로 묶음](https://github.com/next-step/kotlin-lotto/pull/333/commits/c8db16b434511138d38be30e99fcbd048f6c371d)

ranks 일급컬렉션 만들어서 반영했습니다!

2022-05-29 15:47 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/Controller.kt
> +fun main() {
[refactor : Controller -> Application rename](https://github.com/next-step/kotlin-lotto/pull/333/commits/c5b97670efdff41e84cbef7ed4b15186cbc1e7fc)

반영했습니다! :)

2022-05-29 15:51 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/README.md
> +- [x] 출력기능 구현
네 ^^; 다음부터 이렇게 작성할겠습니다!

한가지 궁금한점이 있는데, 디테일한 부분을 추가한다면 커밋도 디테일한 단위로 나눠서 하면 좋을까요?
그리고 더해서, 테스트도 하나의 테스트를 만들때마다 하나의 디테일에 체크를 하고 만들어야할까요?

예를들어 `6개가 모두 일치하면 1등`에 대한 테스트 하나를 추가하고 커밋한개, `5개가 일치하고 보너스 볼이 일치하면 2등`에 대한 테스트를 추가하고 커밋한개, 각 기능을 구현하고 각 커밋 한개 추가해야하나요??

요구사항에 `git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.` 요 문구가 있었어서 궁금해서요!

2022-05-31 13:28 UTC, hyunniiii approved these changes
안녕하세요 형수님!
리뷰가 늦어서 죄송합니다 😭 
몇가지 코멘트 남겼으니 다음 미션에 반영 부탁드립니다 :)

2022-05-31 13:28 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/README.md
> +- [x] 출력기능 구현
요구사항처럼 기능 목록 단위로 추가하는게 좋습니다. :)

요구 사항을 기능 목록 단위로 추가하면, 커밋 내역을 통해서 어떤 코드가 변화되었는지 쉽게 확인할 수 있다는 장점이 있겠죠?

어느정도는 커밋 단위를 쪼개는게 좋을 것 같습니다 :)

2022-05-31 13:28 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Lotto.kt
> +class Lotto(_numbers: List<Int>) {
`List<Int>`를 `List<LottoNumber>`로 변경해보는건 어떨까요?

2022-05-31 13:28 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Ranks.kt
> +    fun countOf(rank: Rank) = ranks.count { it == rank }
`it == rank` 는 `rank`에게 책임을 위임해보는건 어떨까요?
`Ranks` 에서는 `rank` 가 넘겨준 결과를 받아서 이용하도록 하면 될 것 같습니다 :)

2022-05-31 13:28 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Record.kt
> +    }.let { Ranks(it) }
이 부분은 `Ranks` 에게 책임을 위임해주는건 어떨까요?

또한 `List<Lotto>`를 상태로 가지고 있는 객체의 네이밍은 `Record` 보다는 `lottos` 같은 이름을 붙여주는건 어떨까요?
이럴경우 어떠한 상태를 가지고 어떤 책임을 지니고 있어야할 지 조금 더 명확하게 알 수 있을 것 같습니다 :)

2022-05-31 13:28 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/view/InputValidator.kt
> +    fun validateInputCount(input: String?): Int? {
입력을 반복으로 받는 부분은 `tailrec` 을 이용해보는건 어떨까요?

https://codechacha.com/ko/kotlin-tailrect/

2022-05-31 13:28 UTC, merged

2022-06-01 07:28 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Record.kt
> +    }.let { Ranks(it) }
Record보다 Lottos가 훨씬 좋은 네이밍 같네요! 반영했습니다.

그런데
> 이 부분은 `Ranks` 에게 책임을 위임해주는건 어떨까요?
이 커멘트에서 `이 부분`이 무엇인지이해못했어요! getResult 메서드를 말씀하시는걸까요??
만약 그게 맞다면 Lotto들의 결과물들을 도출해 Ranks를 만드는것인데 Lottos보다 Ranks가 더 어울릴까요?
getResult 메서드를 언급하신게 아니라면 어떤부분인지 궁금합니다 :)

2022-06-01 07:31 UTC, jngcii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Ranks.kt
> +    fun countOf(rank: Rank) = ranks.count { it == rank }
Rank에 메서드를 구현한다면, 아래처럼될것같은데요
```kotlin
enum class Rank {
    FIRST, ... , FIFTH;
    fun isSame(rank: Rank) = rank == this
}

// 호출부
it.isSame(rank)
```
`it == rank`를 `is.isSame(rank)`로 래핑하는것의 의미를 잘 모르겠어요 ㅜㅜ
enum을 사용하는 것이 이러한 동등비교에서도 이점을 얻을수 있기때문이라 생각되어서요!
제가 놓치고 있는 부분이 있을까요?

2022-06-02 11:57 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Ranks.kt
> +    fun countOf(rank: Rank) = ranks.count { it == rank }
하나의 객체에서 다른 객체의 값을 가져와서 연산을 하는 것 보다는 그 객체에게 메시지를 던져주는 것 입니다.
`Ranks`에서 `ranks.count{ it == rank }` 를 해주면 `Ranks`는 `Rank` 객체의 구조를 알 수 있습니다.
이렇게 되면 캡슐화를 해주는 의미가 사라질 것이라고 생각합니다 :) 

이렇게 메시지를 던져 주도록 하면 다른 객체에서 그 값에 접근하는 것을 막고 자기 자신의 상태를 객체가 스스로 관리할 수 있는 장점이 있습니다.

https://skyblue300a.tistory.com/18

2022-06-02 12:00 UTC, hyunniiii commented on src/main/kotlin/com/nextstep/jngcii/lotto/model/Record.kt
> +    }.let { Ranks(it) }
`Lottos`들의 결과물을 도출해 `Ranks`를 생성하지만, 
로또도 로또 종이가 결과를 도출하는 것이 아닌, 기계를 이용해서 결과를 도출하는 것 처럼
`Lottos`는 번호 여러개를 가진 한장의 로또를 의미하도록 하고,
`Ranks`는 `Lottos`의 값을 이용해서 결과를 도출하는 책임을 가지고 있는 것이 좋을 것 같습니다 :)