Step2 - 로또(자동)
next-step/kotlin-lotto pull request #346
Opened 2022-05-28 15:16 UTC by mygoaway

안녕하세요 !

Step2 - 로또(자동) 리뷰 요청 부탁드립니다.
감사합니다!

2022-05-29 16:19 UTC, ddaaac requested changes
안녕하세요 👋 

2단계 구현 잘 해주셨습니다 💯 

몇 가지 코멘트 남겼으니 확인 부탁드려요!

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoBuyer.kt
> +        get() = _lottoNumbers
저번 수업 때 학습했던 backing property를 사용해주셨군요 💯 

다만, 앞의 코멘트와 동일하게 여기서도 한 번에 초기화해준다면 불변 객체를 만들어줄 수 있을 거 같아요. 광재님은 가변으로 만들었을 때의 이점이 더 크다고 생각하시나요?

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoBuyer.kt
> +        for (i in 1..count) {
단순 반복을 위한 for문은 repeat로 대체할 수 있습니다 😄

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +class Lotto {
Lotto가 가져야할 몇 가지 규칙들이 있는데요, 이 규칙들에 대한 검증을 추가해보는 건 어떨까요?

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    fun calculateWinningTotalMoney(lottoNumbers: List<Lotto>, winningLottoNumbers: List<Int>): Int {
만약 winningLottoNumbers로 5개 또는 7개의 숫자가 온다면 어떻게 될까요? 😄

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/LottoApplication.kt
> +    ResultView.printWinningStatistics(lottoBuyer.lottoNumbers, printWinningLottoNumber, earningRate)
LottoStatistics라는 유틸리티 클래스 성격을 지닌 객체에서 통계 관련된 로직을 갖고, Application에서 하나씩 실행해주고 있어요.
만약 LottoStatistics가 로또 번호와 당첨 번호를 받아서 결과를 Map으로 갖고 있다면 통계나 수익률에 대한 로직을 스스로 처리할 수 있을 것 같은데 광재님의 생각은 어떠신가요?

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/LottoApplication.kt
> +    ResultView.printBuyLottoCount(buyMoney / 1000)
1000 이란 숫자를 main 함수에서 알고 있어요.
돈을 관리하는 값 객체를 만들면 적절하게 처리할 수 있지 않을까요? 🤔

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        private const val ELSE_COUNT_MONEY = 0
상수들의 네이밍 패턴이 반복되네요! enum으로 분리해도 좋을 것 같아요 :)

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        private const val SIX_COUNT_MONEY = 2000000000
```suggestion
        private const val SIX_COUNT_MONEY = 2_000_000_000
```
숫자가 길어지면 underscore를 통해서 가독성을 향상시킬 수 있습니다!

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/view/InputView.kt
> +        return readLine()!!.toInt()
```suggestion
        return readln().toInt()
```
코틀린 1.6부터는 향상된 읽기 함수를 제공합니다!

2022-05-29 16:19 UTC, ddaaac commented on src/main/kotlin/lotto/view/ResultView.kt
> +        val countToMoneyMap = mapOf(3 to 5000, 4 to 50000, 5 to 150000, 6 to 2000000000)
3 - 5000 등의 숫자가 중복으로 등장하네요. 이 부분의 앞의 코멘트를 반영하면 해결할 수 있을 것 같아요!

2022-05-30 14:01 UTC, mygoaway commented on src/main/kotlin/lotto/LottoApplication.kt
> +    ResultView.printWinningStatistics(lottoBuyer.lottoNumbers, printWinningLottoNumber, earningRate)
넵, 말씀주신것처럼 LottoStatistics가 로또 번호와 당첨 번호를 받아서 통계나 수익률에 대한 로직을 스스로 처리하는게 좋을것 같네요 ㅎㅎ 말씀주신대로 진행해보도록 하겠습니다^^

2022-05-30 16:22 UTC, ddaaac approved these changes
안녕하세요 👋 

리뷰 반영 잘해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주시고, 다음 단계에서 함께 반영부탁드려요!

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        get() = _lottoNumber
```suggestion
class Lotto(val lottoNumber: List<Int>) {
```
Lotto가 불변 컬렉션이 되면서 backing property 없이 구현해도 될 것 같습니다.
[방어적 복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)를 생각하신 거라면 아래와 같이 구현할 수도 있겠네요 :)

```kotlin
class Lotto(lottoNumber: List<Int>) {
    private val lottoNumber = lottoNumber.toList()
```

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
로또 번호는 1~45 사이의 숫자여야한다는 검증도 필요할 것 같아요.
여기서 검증할 수도 있겠지만 Int 대신 LottoNumber라는 [VO](https://kotlinlang.org/docs/inline-classes.html)를 사용할 수도 있겠네요.

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        }
이 로직도 LottoMatch 안으로 넣을 수 있을 것 같아요.
enum의 `values()`를 활용하면 조금 더 깔끔하게 구현할 수 있을 것 같네요 :)

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        fun random(): Lotto {
상수와 함수는 한 줄 분리해주면 보기 더 좋을 것 같습니다!

2022-05-30 16:22 UTC, ddaaac commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
예외 테스트 잘 구현해주셨어요 💯

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoBuyer.kt
> +class LottoBuyer(lottoNumbers: ArrayList<Lotto>) {
```suggestion
class LottoBuyer(lottoNumbers: List<Lotto>) {
```
꼭 ArrayList를 받을 필요 없이 List 인터페이스의 구현체라면 모두 허용해도 될 것 같아요 😄

2022-05-30 16:22 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    private val winningLottoNumbers: List<Int>
당첨 번호 역시 검증이 필요할 텐데요, 여기도 한 번 객체로 감싸보면 좋을 것 같아요.
다음 단계 미션을 진행할 때도 이렇게 만든 객체가 도움이 될 것 같습니다 😄

2022-05-30 16:22 UTC, merged