Step4 - 로또(수동) 리뷰요청 드립니다.
next-step/kotlin-lotto pull request #354
Opened 2022-05-29 10:41 UTC by sah3122

안녕하세요 현석님 😄 

마지막 미션 리뷰 요청 드립니다. 
마찬가지로 이번 미션도 최대한 간결하게 작성하기 위해 노력하였습니다. 😄 
잘부탁드립니다 👍

2022-05-29 13:52 UTC, BeokBeok requested changes
이전 단계 피드백과 로또(수동) 미션하시느라 고생하셨습니다. 👍 
코드를 잘 작성해주셔서 피드백 드릴 것이 적네요. 💯 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2022-05-29 13:52 UTC, BeokBeok commented on src/main/kotlin/lotto/application/LottoMachine.kt
> +    }
하나의 함수에서 두 가지 이상의 일을 하고 있네요. (자동 구매, 수동 구매)
하나의 함수에서는 하나의 일만 하도록 해보면 어떨까요?
개인적으로는 buy 함수 대신에 buyAuto, buyManual 함수를 각각 호출하게 하면 될 것 같아요.
그래야 코드를 분석하는 입장에서, main함수를 봤을 때 buy 함수를 타고가지 않아도 어떻게 구매하는지 파악하기 쉬울 것 같아요.

2022-05-29 13:52 UTC, BeokBeok commented on src/main/kotlin/lotto/application/vo/Purchase.kt
> +class Purchase(
data class를 일반 class로 변경해주셨네요.
추측건데, 내부 변수값을 초기화하기 위해 변경한 것으로 보이는데요.
성격상 data class가 적합하지 않을까요?

2022-05-30 03:43 UTC, sah3122 commented on src/main/kotlin/lotto/application/vo/Purchase.kt
> +class Purchase(
성격상 data class의 성격을 띄고 있는것이 맞아요. 
고민되는 부분은 `구입 금액`과 `수동 로또 구입수`를 활용하여 자동, 수동 로또 구입 수를 계산해야 하는데, 
data class로 선언시 주 생성자에서 프로퍼티만 정의해야하는 제약이 있어 자동, 수동 로또 구입 로직이 외부로 노출되는 단점이 있더라구요. 
저도 고민을 많이 했던 부분인데 우선 Purchase 객체를 만들기 위한 팩토리 클래스를 추가해볼게요 ! 
그에따른 피드백도 부탁드립니다 😄

2022-05-30 03:43 UTC, sah3122 commented on src/main/kotlin/lotto/application/LottoMachine.kt
> +    }
로또 구입이라는 행동을 하나의 행동으로 보았는데, 이야기 해주신것 보니 분리하는것이 명확하게 정의할수 있는 방법인것 같네요 😄 
분리해보겠습니다 !

2022-05-30 13:09 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
동철님과 미션하면서 저 또한 성장하게 된 것 같습니다. 😄 
좋은 개발자가 되기 위한 소중한 경험이 되었길 바랍니다. 💪

2022-05-30 13:09 UTC, BeokBeok commented on src/main/kotlin/lotto/application/PurchaseFactory.kt
> +object PurchaseFactory {
코틀린에서는 companion object를 활용하여 factory method를 만들 수 있습니다.

2022-05-30 13:09 UTC, merged