4단계 - 로또(수동)
next-step/kotlin-lotto pull request #357
Opened 2022-05-29 15:33 UTC by haejungunderthetable

```
킷! 주말 잘 보내셨나요?

전 금요일에 배포하고 주말에 간간히 모니링하면서 과제를 했습니다. 🤣
마지막 과제 리뷰 부탁드립니다.
```

### Summary
* TDD를 이용해서 로또 자동 + 수동 구매가 가능한 프로그램을 만들어 본다.

### Changes
* 3단계 - 로또(2등) 리뷰 반영
  * `LottoTicket`에서 `LottoMatch`를 획득하도록 변경
  * `LottoStatistics`에서 `LottoMatch`를 이용해서 계산
  * 빠진 `LastLottoNumbers` 테스트 추가
* Primitive 타입을 클래스로 Wrapping
  * PurchaseMoney
  * LottoNumber  
* 로또 수동 구매 기능 추가
  * 수동 구매 횟수 입력
  * 수동 구매 번호 입력
* 기타
  * 예외로 인해 프로그램이 종료되지 않도록 수정

2022-05-30 13:13 UTC, karian7 requested changes
4단계 구현 잘 하셨습니다. 👍 
이제 마지막까지 왔네요. (리뷰이 중에 일등이십니다.ㅋㅋ) 빨리 리뷰의견 남기고 싶었는데 오늘 시간이 잘 안나서 늦게 의견 드려요. 
좀더 고민해보면 좋을만한 의견 남겨놓았으니 고민해보시고 도전해 보시면 좋겠습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요. 😀

2022-05-30 13:13 UTC, karian7 commented on src/main/kotlin/lotto/LottoMain.kt
> +    val countOfManual = inputView.readCountOfManualLotto()
"수동입력은 구매금액 이내여야 한다."라는 요구 사항을 코드로 표현해 보면 어떨까요?

2022-05-30 13:13 UTC, karian7 commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +            }
아래 코드로 개선해 보면 어떨까요?
```suggestion
            manualTickets + LottoTicketMachine.generate(countOfAutoLotto)
```

2022-05-31 10:52 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoTicketMachine.kt
> +                .sorted()
정렬에 대해서 책임을 가지고 구별해서 sort를 나누지는 않았습니다.
그냥 단편적으로는 intersect() 내부에서 sort가 되어 있다면 더 빠르게 교집합을 계산하지 않을까 하는 생각으로 접근했습니다.

View로 책임을 가져가도록 수정해보겠습니다.

2022-05-31 10:56 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoTicketMachine.kt
> +                .map { LottoNumber(it) }
1. 45개 인것 같습니다.
2. 네 미리 LUT 형식으로 LottoNumber를 45개 만들어두고 거기서 take 할 수 있을거 같습니다.
3. (7 * x) < 45 일때는 LUT로 만둘어둔 LottoNumber의 생성비용 보다 적을거 같습니다.
단 그 이상이라면 비용이 더 크게 될거 같습니다.

2022-05-31 10:58 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +                .toMap()
음... 컬렉션 복사가 생성비용이 많을거 같습니다. 

groupingBy docs 참조해서 최적화 해볼께요

2022-05-31 11:01 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoMatch.kt
> +            return values().find { it.count == count && it.withBonus == withBonus } ?: ZERO
제가 로또 규칙을 잘못이해한걸까요?

1등은 추첨번호 중 5개 일치
2등은 추첨번호 중 4개 일치 + 보너스 번호 1개 일치
3등은 추첨번호 중 4개 일치 + 보너스 번호 미일치
4등은 추첨번호 중 3개 일치 + 보너스 번호 미일치

라고 이해하고 있는데요. 호옥시 규칙이 다른가요?

2022-05-31 11:04 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +sealed class LottoTicket(numbers: Set<LottoNumber>) : Set<LottoNumber> by numbers {
네 부생성자를 활요하도록 수정해보겠습니다.

추가로:
sealed 클래스를 사용한 이유는 테스트를 위한게 아니고 자동/수동 구매를 구별하기 위한 주 목적이 있고 이후에 로또 번호 표시할 때 count를 filter하기 위한 용도로 사용했습니다.

2022-05-31 11:08 UTC, karian7 commented on src/main/kotlin/lotto/domain/LottoMatch.kt
> +            return values().find { it.count == count && it.withBonus == withBonus } ?: ZERO
아래와 같습니다.
```
1등: 6개 일치
2등: 5개 + 보너스 일치
3등: 5개 일치
4등: 4개 일치 (보너스 상관없음)
5등: 3개 일치 (보너스 상관없음)
```

2022-05-31 11:12 UTC, haejungunderthetable commented on src/main/kotlin/lotto/view/InputView.kt
> +                    null
입력 번호가 유효하지 않을때 재입력을 유도한는 표시를 위해서 getOrElse()를 사용하게 되었는데요. getOrNull()로 하게 된다면 외부에서 한번더 체크를 위한 비교를 하게 될거 같은데요. null을 없에는게 맞는건지 잘 모르겠습니다.

2022-05-31 11:17 UTC, karian7 commented on src/main/kotlin/lotto/view/InputView.kt
> +                    null
이 피드백을 남길 당시에는 다음과 같은 코드를 염두하고 드렸었습니다.
```kotlin
lottoNumbers = kotlin
                .runCatching { value?.tokenize()?.toInt()?.toSet()?.toLottoNumber() }
                .onFailure { printInputLottoNumberAgain() }
                .getOrNull()
```
while 조건에 에서 `lottoNumbers` 에 대한 널 체크를 하고 있기때문에 괜찮다고 생각했습니다.
그런데 이보다 아래 내용이 더 중요한 부분인것 같습니다.

https://edu.nextstep.camp/s/MFvxefXA/ls/DK1opD8g

![Capture 2022-05-31 오후 8 16 32](https://user-images.githubusercontent.com/247208/171161333-8117aa90-42a3-4ee3-a3f8-b5f4093ccb46.jpg)

이부분을 고려했을 때 InputView 전체적으로 개선할 부분이 있을지 논의해 보면 좋겠습니다. 의견 부탁드립니다!

2022-05-31 11:18 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +            }
LottoTicketMachine.generate()에서 생성하는 LottoTickets의 규칙에 0개의 LottoTicket을 소유할 수 없다는 규칙이 있다보니 돌아돌아 왔네요.
다시 생각해보니 해당 규칙이 필요한지 의문이 됩니다. 0개도 포함할 수 있다! 라고 다시 규칙을 정하고 그에 맞게 수정해볼께요.

그러면 여기도 간단하게 바뀔수 있게 될거 같습니다.

2022-05-31 11:39 UTC, haejungunderthetable commented on src/main/kotlin/lotto/view/InputView.kt
> +                    null
runCatching {}을 열심히 쓰고 있네요.

2022-05-31 17:03 UTC, haejungunderthetable commented on src/main/kotlin/lotto/domain/LottoMatch.kt
> +            return values().find { it.count == count && it.withBonus == withBonus } ?: ZERO
뜨헉..😱

그럼 로또 당첨 번호가 1,2,3,4,5,6 보너스 7 일때
4등은 보너스 번호를 포함해서 1,2,4,7,20,21 이게 성립한다는건가요?

카메라로 찍어서 확인만 했지...잘 몰랐네요 ㅋ

2025-08-13 14:29 UTC, closed without merging