3단계 - 로또(2등)
next-step/kotlin-lotto pull request #359
Opened 2022-05-30 03:36 UTC by Jaesungchi

잘부탁드립니다 ㅎㅎ!

2022-05-30 10:57 UTC, Flamme1004K commented
재성님, 도메인과 모델 패키지 잘 합쳐주셨습니다! 😊

본격적으로 리팩토링을 들어가기전에 리팩토링이 어떻게 진행될 것인지에 대한 방향성을 소개하려고 합니다.

일단, 재성님이 생각하신 모델과 도메인은 데이터를 저장하는 클래스의 집합, 비즈니스 로직 클래스의 집합이에요.

이러한 각각의 역할이 있기 때문에 모델에 있는 클래스는 데이터를 저장하는 구조이기 때문에, 가벼워지고, 비즈니스 로직은 계속 무거워지는 것을 확인할 수가 있습니다.

하지만, 도메인 패키지로 다 넣음으로써 이제 도메인 안에 있는 클래스의 관계가 형성되고, 기존의 모델 클래스들에게 계속해서 무거워지는 비즈니스 로직을 나눠줄 수 있는 구조가 되었습니다. 기존의 모델에 있는 클래스에게 비즈니스 로직을 나눠준다면? 무슨 장점이 있을까요? 저는 모델에 대해 행위가 추가된다고 생각하며, 이 행위를 통하여, 역할, 책임, 협력의 관계를 가질 수 있는 객체지향 프로그래밍을 할 수 있다고 생각합니다.

네 맞아요. 앞으로 좀 더 객체지향적으로 로또를 리팩토링 할 예정이에요.

요번에 한번 같이 객체지향 프로그래밍을 즐겨보는 시간을 가집시다! 

일단, 저는 해당 글을 꼭 읽어보길 바래요!

- [좋은 객체의 7가지 덕목](https://codingnuri.com/seven-virtues-of-good-object/) 

앞으로 화이팅입니다! 😊

2022-05-30 11:35 UTC, Flamme1004K requested changes
안녕하세요!

피드백 반영 감사합니다. 💯

로또(2등) 게임 구현 잘 해주셨습니다! 👍👍

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

화이팅입니다! 🙌

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoCompany.kt
> +        require(!winningTicket.numbers.contains(bonusNumber)) { ErrorMessages.BONUS_IS_DUPLICATE_WITH_WINNINGS }
```suggestion
        require(!winningTicket.contains(bonusNumber)) { ErrorMessages.BONUS_IS_DUPLICATE_WITH_WINNINGS }
```

winningTicket의 number를 꺼내서 bonusNumber를 포함되어있는지 확인하는게 아닌, winningTicket에게 number가 포함되어 있는지에 대해 물어보는건 어떨까요? 🤔

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoCompany.kt
> +    fun convertTicketsToLottoResults(tickets: List<LottoTicket>): LottoResults {
```suggestion
    fun convertTicketsToLottoResults(tickets: LottoTickets): LottoResults {
```

로또 티켓들의 집합을 뜻하는 LottoTickets를 만들어보는건 어떨까요? 🤔

만들어보고, LottoTickets이 가져야할 책임과 역할을 생각해보고 리팩토링을 한번 해보셨으면 합니다!

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoCompany.kt
> +        return LottoResults(prizes.groupBy { it }.map { LottoResult(it.key, it.value.size) })
피드백 반영 훌륭합니다 👍👍

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoCompany.kt
> +        return LottoResults(prizes.groupBy { it }.map { LottoResult(it.key, it.value.size) })
제가 생각하기로는 LottoResults가 만약 List<LottoResult>가 아닌, List<Prize>를 가지고 있다면 prizes의 그룹화하는 역할을 LottoCompany가 아닌 LottoResult가 할 수 있다고 봐요.

LottoResult가 가지고 있다면, LottoCompany에서 상품을 어떻게 그룹화시키는지에 대한 로직을 알 수 없어도 되기 때문입니다.

좋은 의견이 있으실까요?

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Prize.kt
> +    FIRST(6, 2000000000)
```suggestion
    LOSER(0, 0),
    FIFTH(3, 5_000),
    FOURTH(4, 500_000),
    THIRD(5, 1_500_000),
    SECOND(5, 30_000_000),
    FIRST(6, 2_000_000_000)
```

이렇게 하면 더 가독성 있어 보일 것 같아요!

2022-05-30 11:35 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Prize.kt
> +            return values().find { it.matchCount == matchCount } ?: LOSER
2등 로직 좋습니다! 👍👍

```kotlin
fun of(matchCount: Int, isCorrectBonus: Boolean): Prize {
            return values().find {
                if (isCorrectBonus && matchCount == SECOND.matchCount) {
                    return SECOND
                }
                it.matchCount == matchCount
            } ?: LOSER
        }
```

저도 한번 개선해봤습니다!

2022-05-31 15:34 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        return LottoTickets(List(ticketCount) { LottoTicketFactory.getRandomLottoTicket() })
`LottoStore`에서 `RandomLottoTicket`를 ticketCount를 통하여 List를 만드는 게 아닌, LottoTicketFactory에게 ticketCount를 줌으로써, LottoTickets를 만들어오게 시키는 게 어떨까요?🤔

마치, 실생활에 있는 로또 기계처럼요!

2022-05-31 15:39 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoCompanyTest.kt
>  class LottoCompanyTest {
우와....... 테스트 코드에 대한 수정과 추가에 대해 진짜 감동했습니다!  👍👍

앞으로도 좋은 테스트 기대하겠습니다!! 🤩

2022-05-31 15:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/InputView.kt
>          println(Messages.WRITE_WINNING_NUMBER)
<img width="920" alt="스크린샷 2022-06-01 오전 12 40 58" src="https://user-images.githubusercontent.com/50702723/171214028-bb330c9c-5d4a-40a1-8d49-0ea3c2161a82.png">

지난 주 당첨 번호 입력에 7개 이상 숫자가 들어가네요! 수정 부탁드립니다! ☺️

2022-05-31 15:47 UTC, merged

2022-05-31 15:55 UTC, Flamme1004K commented
`LottoTicket에 어처피 변수가 하나 밖에 없어서, 이걸 일급 컬렉션으로 해야하나? 라는 생각에 처음에 일급컬렉션으로 감싸지 않았는데. (오히려 포장된애를 다른 쓰임새가 없는데 한번더 포장한 느낌..?!)
혹시 실무에서도 이런 변수가 하나인 경우에도 일급컬렉션으로 만들어 쓰는 경우가 있나요 ??`

에 대해서 저도 답변을 드리자면, 실무에서도 요즘 많이 사용하고 있는 중에 있어요! 나중에 컬렉션에 대해 액션이 있을 경우, 그리고 변경점이 있을 경우, 새로운 값을 추가해줘야 할 경우에 대비해서 항상 사용하고 있습니다 😆

주위 개발자 분(계속 사용하는 분과 사용하지 않고 일급 컬렉션을 사용하지 않지만, 자주 보는 분)들에게 일급 컬렉션에 대해 몇몇 분들에게 물어봤는데, `처음에 써야 할 때 생소하다고 느껴지지만, 사용하다 보면 도메인적인 로직에 대해 구현 및 개선할 때 좋다`과 `서비스 로직에서 표현하는 게 더 좋기 때문에 생각을 해봐야 되겠다.`라는 의견이 나왔네요. ☺️

2022-06-03 23:44 UTC, Jaesungchi commented on src/main/kotlin/lotto/domain/LottoResults.kt
> +}
와 이거 일급컬렉션의 중요성이네요... 리팩토링해도 이쪽만 손대도 되니깐 너무 편리하네요 ...ㅋㅋ
살짝 충격입니다 허허허