3단계 - 로또(2등)
next-step/kotlin-lotto pull request #361
Opened 2022-05-30 09:27 UTC by sue26

안녕하세요! 
크게 달라진 점은 아래와 같습니다.

- 일급컬렉션을 사용해 generator 를 대체했습니다. 
    - LottoNumbers 라는 일급컬렉션을 만들었고, 번호 6개가 랜덤 생성인지, 사용자 지정인지, 그리고 유효한 로또 번호인지 검증하는 로직은 다 이 클래스안에 들어있습니다.
    - `LottoNumbersGenerator`, `RandomNumbersGenerator`, `CustomNumbersGenerator` 는 삭제되었습니다.

리뷰 부탁드립니다! 감사합니다 (_ _)

2022-05-30 10:45 UTC, pci2676 requested changes
안녕하세요~! 
이미 구현을 잘해주셔서 3단계는 무리없이 진행하신것 같아보입니다~!
소소한 리뷰를 남겨두었으니 확인하시고 반영해주시면 좋을것 같습니다~!

2022-05-30 10:45 UTC, pci2676 commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +class WinningLotto(winningNumbers: List<Int>, val bonusNumber: Int) {
`bonusNumber`는 1~45 범위 바깥으로 입력해도 게임이 진행이 되는것 같네요!

2022-05-30 10:45 UTC, pci2676 commented on src/main/kotlin/lotto/domain/numbers/LottoNumbers.kt
> +        } ?: throw IllegalArgumentException("로또 번호는 총 6개이고 1과 45사이의 숫자여야 합니다.")
이전까지는 `Lotto` 번호에 대한 검증 로직이 이곳에만 있어도 문제가 되지 않았는데요.
`bonus` 번호의 등장으로 이 로직이 다른 곳에 위치하는것이 더 좋을것 같이 보입니다~!

`LottoNumbers`는 컬렉션 객체로서 컬렉션의 상태에 대해서만 검증하고 구성요소에 대한 검증은 구성요소 자신이 할 수 있도록 해보시는건 어떨까요?

2022-05-30 10:45 UTC, pci2676 commented on src/main/kotlin/lotto/domain/prize/LottoPrizeResult.kt
> +class LottoPrizeResult(winningLotto: WinningLotto, lottoBought: List<Lotto>) {
`LottoPrizeResult`를 `WinningLotto`에게 `lottoBought`를 메세지로 넘기면서 생성해보는건 어떨까요?
먼저 `prizes` 자체를 사용하는 곳은 내부와 테스트뿐인것 같아보이기도 하고
`LottoPrizeResult`에서 주요관심사는 `LottoPrizeResult`가 가지고 있는`prize`에서 총 상금이 얼마인지', '`prize`가 몇개씩 있는지'인것 같아 보여서요!

다시 말하자면 이 객체를 사용하는 입장에서는 `prize`가 어떻게 생성되는지는 그렇게 궁금해하지 않을것 같습니다!

다만 이 부분은 여러 견해어서 고민해보시고 수정하셔도 되고 안하셔도 됩니다! (저라면 이렇게 코멘트 남겨드린 대로 했을것 같아서요~!)
[좋은 블로그 글](https://bb-library.tistory.com/272)이 있어서 한번 보시면 좋을것 같아요!

2022-05-30 10:45 UTC, pci2676 commented on src/main/kotlin/lotto/LottoStore.kt
> +            val winningLotto = WinningLotto(InputView.readWinningNumbers(), InputView.readBonusBallNumber())
우승번호를 잘못입력 (ex. 한개의 숫자만 입력) 한 경우에도 보너스 번호를 입력하기 위한 단계까지는 무조건 실행이 되고 있는것 같아보입니다.
빠르게 exception을 발생시키는건 어떨까요?

입력단도 역할에 부합하는 검증 로직을 가지고 있어주면 좋을것 같습니다!

2022-05-30 10:45 UTC, pci2676 commented on src/test/kotlin/lotto/domain/prize/LottoPrizeTest.kt
>      @ParameterizedTest
소소한 팁인데요~
```suggestion
        @ParameterizedTest(name = "{0}개 일치하고 보너스 번호 일치여부가 {1}라면 당첨금액은 {2} 이다.")
```

이렇게 사용하면 아래와 같은 결과물을 얻을수 있습니다~!

<img width="553" alt="image" src="https://user-images.githubusercontent.com/13347548/170975963-9f3e0176-4327-47cd-9d36-e5beb35dc1c4.png">

2022-05-31 03:12 UTC, sue26 commented on src/test/kotlin/lotto/domain/prize/LottoPrizeTest.kt
>      @ParameterizedTest
훨씬 보기 명확하고 좋네용 ㅎㅎ 감사합니다!
[9d37e0c](https://github.com/next-step/kotlin-lotto/pull/361/commits/9d37e0cc2f9a29745e31721dba5e61f0936413a9) 에 반영했습니다

2022-05-31 03:12 UTC, sue26 commented on src/main/kotlin/lotto/LottoStore.kt
> +            val winningLotto = WinningLotto(InputView.readWinningNumbers(), InputView.readBonusBallNumber())
[6806581](https://github.com/next-step/kotlin-lotto/pull/361/commits/6806581cfcf7bb7ce71277f204a6b2f96258abad) 에 반영했습니다

2022-05-31 03:14 UTC, sue26 commented on src/main/kotlin/lotto/domain/prize/LottoPrizeResult.kt
> +class LottoPrizeResult(winningLotto: WinningLotto, lottoBought: List<Lotto>) {
말씀 해주신 부분에 동의합니다!! 알려주셔서 감사합니다
LottoPrize 를 가져오는 로직을 WinningLotto 로 옮겼습니다.
[14d9758](https://github.com/next-step/kotlin-lotto/pull/361/commits/14d97581dec8aa3cd3afe5276804c84a1c61d7b5) 에 반영했습니다

2022-05-31 03:15 UTC, sue26 commented on src/main/kotlin/lotto/domain/numbers/LottoNumbers.kt
> +        } ?: throw IllegalArgumentException("로또 번호는 총 6개이고 1과 45사이의 숫자여야 합니다.")
[9e28024](https://github.com/next-step/kotlin-lotto/pull/361/commits/9e28024fa54d4455172ab8f97fdb549ec8f6ddeb)
lottoNumber 를 감싸주는 `LottoNumber` inline class 를 만들었습니다.
리스트 사이즈 검증은 LottoNumbers 에서, 로또 번호 검증은 LottoNumber 에서 행해지도록 변경했습니다!

2022-05-31 03:16 UTC, sue26 commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +class WinningLotto(winningNumbers: List<Int>, val bonusNumber: Int) {
[9e28024](https://github.com/next-step/kotlin-lotto/pull/361/commits/9e28024fa54d4455172ab8f97fdb549ec8f6ddeb)
lottoNumber 를 감싸주는 LottoNumber inline class 를 만들었고, 로또 번호 검증은 LottoNumber 에서 행해지도록 변경했습니다.
bonusNumber 도 LottoNumber 로 변경해서 1~45 범위 바깥일 경우 에러가 발생하도록 변경했습니다!

2022-05-31 14:35 UTC, pci2676 commented on src/main/kotlin/lotto/domain/numbers/LottoNumber.kt
> +value class LottoNumber(private val number: Int) {
인라인클래스를 사용하면서 성능상의 이점을 얻었지만 List와 같은 컬렉션에서 사용할때는 언박싱이 발생하게됩니다~!
그래서 `LottoNumber`는 총 45개니까 이 45개의 `LottoNumber`를 미리 생성해두고(캐시의 개념으로) Generator가 미리 생성되어있는 `LottoNumber`를 사용하는 방식을 사용하면 좋습니다~!

2022-05-31 14:38 UTC, merged