Step2 - 로또(자동)
next-step/kotlin-lotto pull request #363
Opened 2022-05-30 13:14 UTC by D000L

리뷰 부탁드립니다.~

2022-06-01 04:39 UTC, laco-dev requested changes
리뷰 확인이 늦었습니다. 🙏 

2단계 미션 잘 해 주셨네요.
최대한 객체를 만들고 분리 해 보려는 시도가 좋았습니다.

열심히 하신 만큼 보다 개선해보면 더욱 좋은 구조가 될 것 같아서 다소 피드백을 많이 남기게 되었습니다. 😅 

고민 해 보시고 천천히 도전 해보세요.

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Grade.kt
> +    None(0, 0);
마이너한 내용인데 코틀린에서는 숫자 타입에 `_` 를 사용해서 표현할 수도 있어요.
```kotlin
First(6, 2_000_000_000)
```

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Grade.kt
> +        }
valueOf는 주어진 값을 이용해 생성할 때 주로 사용되는 표현이라 이 경우에는 일치하는지 찾는 역할이기 때문에 동일하게 `find`로 지어보면 어떨까요?

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/GradeInfo.kt
> +data class GradeInfo(val grade: Grade, val count: Int)
`count`가 의미하는게 무엇일까요?
클래스 이름으로도 프로퍼티 이름으로도 예측이 되지 않아요
Info라는 범용적인 이름 대신 구체적으로 이름을 지어주면 어떨까요?

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoList.kt
> +    fun calculateLottoResult(winningNumbers: WinningNumbers): LottoResult {
모든 함수에서 calculate 라는 표현을 사용 해 주고 계신데요.
단순히 무엇을 계산하는거지? 라는 의문을 가질 수 있어요.

match(...) 같은 표현을 사용 해 보면 어떨까요?

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    const val LottoCost = 1000
명확한 상수인 경우 이전처럼 LOTTO_COST 형태로 대문자 형식으로 작성해야 합니다.
https://kotlinlang.org/docs/coding-conventions.html#property-names

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
로또 머신이 두 가지 역할을 하고 있어요.
```
1. 로또를 주어진 가격만큼 파는 것
2. 로또를 생성 하는 것
```

로또 판매원과 로또 머신으로 역할을 나눠 보면 어떨까요?
```
Client -> LotterSeller -> LotterMachine -> LotterSeller -> Client (로또 !)
```

2022-06-01 04:39 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    val numbers = numbers.sorted().map(::LottoNumber)
`numbers: List<Int>`는 인스턴스가 생성된 이후 아무런 역할을 하지 않는데요.
`List<LottoNumber>`를 주 생성자로 만들어 보면 어떨까요?

2022-06-01 04:39 UTC, laco-dev commented on src/test/kotlin/lotto/LottoResultTest.kt
> +    }
구입한 로또의 개수를 리턴한다. 처럼 코드 친화적인 표현 보다는 도메인 개념에 맞게 만들어 보면 더욱 좋을 것 같아요
"로또 결과는 당첨 등수들 만큼의 개수를 가진다"

2022-06-01 04:39 UTC, laco-dev commented on src/test/kotlin/lotto/LottoResultTest.kt
> +    }
테스트 코드에는 로직을 포함하는 것을 피해야 합니다.
reward가 얼마이지? 2를 나누고 곱하면 몇이지..? 라는 계산을 직접 해야 합니다.

그래서 가급적 하드 코딩으로 기댓값을 명시 해 주는 것을 선호합니다.
```
1등과 2등에 당첨되면 총 상금은 000다.
2천원을 사용해 4등에 두번 당첨되면 수익률은 000다.
```

2022-06-01 04:39 UTC, laco-dev commented on src/test/kotlin/lotto/WinningNumbersTest.kt
> +    }
이 로직은 `LottoNumbers`에서 이미 검증을 했는데 WinningNumbers가 다른 타입을 가지게 되서 중복으로 작성된 것 같네요.

2022-06-02 09:57 UTC, D000L commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
이건 잘 생각이 다른것 같습니다.
LottoMachine 이 하는 역할은 주어진 금액만큼 로또를 전달하는 역할뿐이고, 
생성 로직은 LottoNumbers 가 가졌다고 생각하고 있습니다.

어떤 부분에서 로또를 생성하는 역할을 가졌다고 보시는지 잘 이해가 가지 않습니다. ㅠ

2022-06-02 12:20 UTC, D000L commented on src/test/kotlin/lotto/LottoListTest.kt
> +        }
1을 보고 오해하신거 같습니다. 1등이 아니라 전체 등수가 하나씩 나왔는지를 확인하고 싶었습니다.
더 명확하게 바꿔봐야겠네요.

2022-06-02 12:36 UTC, D000L commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +    }
GradeInfo 가 애매한거 같아서 제거하는 방향으로 변경해보았습니다.

2022-06-03 13:18 UTC, laco-dev approved these changes
피드백 잘 반영 해주셨네요 👍 
구조적으로도 더욱 좋아 진 것 같아요.

간단한 의견 남겼습니다~
다음 미션 진행하시면서 가볍게 확인 한번 해 주세요 🙏

2022-06-03 13:18 UTC, merged

2022-06-03 13:43 UTC, D000L commented on src/main/kotlin/lotto/domain/LottoSeller.kt
> +    private val LOTTO_COST = Money(1000)
object 의 val property 의 경우에 SNAKE_CASE 형태로 네이밍을 해도 되는걸로 아는데, 아닌가요???

2022-06-04 14:30 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoSeller.kt
> +    private val LOTTO_COST = Money(1000)
```
object val properties with no custom get function that hold deeply immutable data)
```
이 내용인 것 같네요.
네, 저도 살짝 놓치고 있던 개념 같기는 합니다.
항상 불변으로서의 구조를 가진다면 스네이크 케이스로 작성을 할 수도 있네요

안드로이드 공식문서의 컨벤션에 보다 설명이 잘 나와 있는 것 같아요.
https://developer.android.com/kotlin/style-guide#constant_names