Step4 - 로또(수동)
next-step/kotlin-lotto pull request #379
Opened 2022-06-02 04:54 UTC by Inpyo-Jeon

마지막 단계네요 리뷰어님!
PR 올렸는데, 확인 부탁드리겠습니다-!

2022-06-04 02:14 UTC, malibinYun requested changes
로또 미션 고생 많으셨습니다!
객체를 잘 분리해주셔서 크게 피드백 드릴 부분이 없었네요. 👍👍
코멘트 확인해주시고 리뷰 요청해주세요. 미션을 마무리 하고 싶으시다면 DM 주세요! 바로 머지하겠습니다 🙂

2022-06-04 02:14 UTC, malibinYun commented on src/test/kotlin/lotto/seller/LottoSellerTest.kt
> +        }
테스트에서 for 관련 로직을 사용하는 것은 지양해야합니다.
for, if 등의 로직을 사용하면 한 번 해석해야하기 때문이에요.
for문을 돌리는 것 보다는, 1개를 직접 꺼내와서 테스트하는 것이 좀 더 바람직합니다.

2022-06-04 02:14 UTC, malibinYun commented on src/test/kotlin/lotto/seller/LottoSellerTest.kt
> +        val randomNumbers = RandomNumberFixture(setOf(1, 6, 23, 5, 2, 7))
픽스처 클래스를 만들어서 활용하기 보다, 테스트 코드 내부에서 바로 object를 만들어서 사용하는 것이 좀 더 좋습니다.
Fixture가 뭔지 한 번 들어갔다 나와서 테스트 코드 읽는 흐름을 깨기 때문이에요.
해당 내용을 잘 설명한 블로그 글을 공유드립니다 :) https://jojoldu.tistory.com/611

2022-06-04 02:14 UTC, malibinYun commented on src/main/kotlin/lotto/agency/LottoTicket.kt
> +    constructor(vararg numbers: Int, bonus: Int) : this(numbers.toSet(), bonus)
로또 티켓과 당첨 티켓의 역할이 분리되면 좋을 것 같아요.
로또 티켓은 6개의 숫자만 들고 있고, 당첨 티켓은 로또 티켓과 보너스 볼을 들고 있게 한다면 좀 더 역할을 분리해볼 수 있을겁니다.
실제 로또 티켓에는 보너스볼을 적는 항목이 없기 때문에 더 현실 세계를 반영할 수 있다고 생각이 드네요 :)

2022-06-05 02:55 UTC, Inpyo-Jeon commented on src/main/kotlin/lotto/agency/LottoTicket.kt
> -    }
헛?! 중간에 머지 컨플릭이 나서, github 웹 툴로 머지하는 경우에서 잘못 머지가 되었나보네요.
해당 부분 수정했습니다.

2022-06-05 02:55 UTC, Inpyo-Jeon commented on src/test/kotlin/lotto/seller/LottoSellerTest.kt
> +        val randomNumbers = RandomNumberFixture(setOf(1, 6, 23, 5, 2, 7))
테스트를 위한 입력 값을 전달 할 수 있도록 인터페이스를 재구현한 클래스이고,
이를 공통으로 사용할 경우를 생각해서 테스트 패키지 내에 픽스쳐 형태로 만들어두었던 케이스입니다.
실상 지금 사용하는 부분은 아직 한 곳 밖에 없어서 나누는 것이 무의미 할 수는 있지만,
다른 테스트에 사용할 때를 위해 필요할 수 있다고 생각이 되는 부분입니다.

말씀주시고 링크 주신 내용을 읽어보았고, 충분히 공감가는 좋은 내용이어서 공유주신 점 감사합니다!
실무나 차후 다른 과제에서 더욱 고민하면서 진행해보겠습니다 :)

2022-06-05 02:55 UTC, Inpyo-Jeon commented on src/test/kotlin/lotto/seller/LottoSellerTest.kt
> +        }
내가 지정한 로또 숫자와 입력된 로또 숫자가 같은지 판단하기 위해 작성했었는데요.
말씀 주신 부분을 포함해서 고민해보다보니,
루프를 돌리기 보다는 테스트 라이브러리의 containsAll() 메서드를 사용하는 것이 더 나은 방향일 거 같다는 생각이 들어,
요 메서드를 사용해서 테스트하도록 수정했습니다.

2022-06-05 02:55 UTC, Inpyo-Jeon commented on src/main/kotlin/lotto/agency/LottoTicket.kt
>          private set
네 그 부분은 인지하고 있긴 했지만,
`private set` 이 부분을 사용하려다 보니, 코틀린에서는 var로 가이드를 주고 있어서, 이와 같은 형태로 사용하게 되었습니다.
더구나,
보너스 또한 한 번 할당 되면 변경되지 않아야 할 것으로 판단해서 로또 숫자와 마찬가지로 불변이 되도록 했던 측면이 있습니다.

2022-06-05 02:55 UTC, Inpyo-Jeon commented on src/main/kotlin/lotto/agency/LottoTicket.kt
> +    constructor(vararg numbers: Int, bonus: Int) : this(numbers.toSet(), bonus)
동작에는 문제가 없지만, 말씀처럼 `현실 세계 반영`이라는 측면에선 아주 조금 아쉬운 부분이네요 😅
다만, 다른 과제들이 계속 진행되다보니 지금은 같이 챙기기 쉽지 않아, 여유가 되는 상황에서 고민해보도록 하겠습니다-!

2022-06-06 14:04 UTC, malibinYun approved these changes
로또 미션 완주 고생 많으셨습니다!
반영하지 못한 피드백은 나중이라도 다시 구현 해보시길 바랍니다.
아니면, 아예 처음부터 다시 구현해보는 것도 좋은 방법입니다. 이전과는 아예 다른 프로젝트가 만들어지기도 하기에 스스로 큰 변화점을 느끼실 겁니다 🙂

로또 미션은 이만 머지하도록 하겠습니다. 다른 미션들도 응원하겠습니다!! 💪

2022-06-06 14:04 UTC, malibinYun commented on src/main/kotlin/lotto/agency/LottoTicket.kt
>          private set
val로 선언하시면 private set을 할 필요가 없어집니다. 아예 set을 할 수 없기 때문이에요 :)
var은 변수를 다른 변수로 할당할 수 있지만 val은 한 번 할당하면 다시 재할당은 불가능해지는 키워드입니다!

2022-06-06 14:05 UTC, merged