2단계 - 로또(자동)
next-step/kotlin-lotto pull request #384
Opened 2022-06-03 01:56 UTC by Hyeon9mak

안녕하세요 영직님~
객체의 책임을 최대한 잘게 나눠보고자 했습니다.
이번 리뷰도 잘 부탁드립니다! 🙇‍♂️

2022-06-04 12:16 UTC, laco-dev requested changes
로또 미션 고생하셨습니다! 👍 

전체적으로 설계나 객체로 분리를 잘 해주셔서 좋았습니다.
코틀린의 value class 라는 개념을 읽어보시고 나중에 적용 해 보셔도 좋습니다.
https://kotlinlang.org/docs/inline-classes.html

코틀린의 함수들을 이용해 보다 간결하게 만들어 보는 방법을 포함해서 몇 가지 의견을 남겼습니다.

2022-06-04 12:16 UTC, laco-dev commented on src/test/kotlin/lotto/domain/WinningResultTest.kt
> +        winningAmountMap[MISS] = winningAmountMap[MISS]!! + 13
MutableMap으로 넣을 필요가 없을 것 같습니다.
mapOf(...) 형태로 바로 만들어도 되지 않을까요?

2022-06-04 12:16 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +        private const val REGEX = ", "
이 경우에는 정규식이 아닌 DELIMITER가 적절한 것 같습니다.

2022-06-14 05:45 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +                .toSet()
SortedSet 이라는 타입으로 넘어가는걸 원치않아 위와 같은 형태를 취했습니다.

2022-06-14 05:45 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +            winningAmountMap[winningAmount] = winningAmountMap[winningAmount]!!.inc()
와... 세상에... 👍

2022-06-14 05:51 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +) {
부동소수점 관련 문제가 없기 때문에 계산결과가 정확해져서 사용했습니다

2022-06-14 05:52 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
더 명확하게 cachedLottoNumbers 로 명명해보았습니다

2022-06-14 05:53 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +        }
조금 고민 되는데.. 다음 단계에서 반영해보겠습니다!

2022-06-14 05:55 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
아!! 너무 잘어울리는 방법이네요 👍 👍 👍 🙇‍♂️

2022-06-14 06:05 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
아!! 너무 잘어울리는 방법이네요 👍 👍 👍 🙇‍♂️
다만 현재 로직상 `Money` 자체가 아닌, 나눠진 이후 정수 값이 필요한거라 현재 형태를 유지하고 싶습니다.

2022-06-14 06:09 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningTicket.kt
> +                .toSet()
일반적인 상황에서 말씀해주신 개념은 동의하지만, 현재 코드에 접목시키기엔 어려운거 같습니다. 
List를 Set으로 바꾸는 동작을 명확히 수행하고 있고, 메서드가 호출되는 범위 역시 `WinningTicket` 내부로 국한되어있습니다.
혹시 다른 의도로 말씀해주신걸까요? 🙇‍♂️

2022-06-14 06:12 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +                    shouldThrowExactly<java.lang.IllegalArgumentException> { LottoNumber.from(value = number) }
헉! 꼼꼼한 리뷰 감사합니다

2022-06-14 06:14 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +                    .hashCode()
아.. 그렇네요!!! 해시코드 비교가 곧 인스턴스 비교!!

2022-06-14 06:16 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoNumbersTest.kt
> +        }
https://runebook.dev/ko/docs/kotlin/api/latest/jvm/stdlib/kotlin.collections/zip-with-next

👍 👍 👍 별의별게 다있네요 정말 많이 배웁니다 🙇‍♂️

2022-06-14 06:20 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
!! 무조건 사용하면 좋을거라 생각했습니다 🙇‍♂️

2022-06-14 06:25 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    val values: Map<WinningAmount, Int>
오... 네이밍 회피하고 싶어서 그랬는데 이렇게 어려운 리뷰를.. 😅 ㅎㅎㅎ

2022-06-14 06:28 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    val values: Map<WinningAmount, Int>
잘 이해하지 못했는데요, 테스트는 배제하더라도 출력쪽에서 Map 자료구조를 활용하기 때문에 getter가 노출되어도 괜찮지 않은가요?

2022-06-14 09:13 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoNumbersTest.kt
> +            row(LottoNumbersFixture.of(setOf(1, 2, 3, 4, 5, 6)), 6),
제안해주신 방법이 테스트 코드 가독성이 훨씬 뛰어난거 같습니다. 👍

2022-06-14 09:21 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoNumbersTest.kt
> +            row(LottoNumbersFixture.of(setOf(1, 2, 3, 4, 5, 6)), 6),
테스트 코드 저어어엉말 많이 깔끔해지네요 너무너무 감사합니다 👍 👍 👍 👍 👍 👍 👍

2022-06-14 15:17 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    }
아래 글이 도움이 되실 것 같습니다.
https://blog.kotlin-academy.com/kotlin-collections-vs-sequences-in-just-5minutes-70a3c3ec94a8

2022-06-14 15:18 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    val values: Map<WinningAmount, Int>
네이밍을 회피하기 이전에, 이 값이 무엇인지 예측이 되지 않습니다.
valuse로 유지한다면, Int 타입 대신 값 객체로 만들어 보면 어떨까요?

2022-06-14 15:20 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
함수가 두 가지 역할을 해서 조금 아쉬운? 느낌이 드네요.
이렇게 만들어 볼 수도 있을 것 같아요!

```kotiln
val money = (money1 / money2).toInt()
```

2022-06-14 15:29 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningTicket.kt
> +                .toSet()
아하, private 함수이기 때문에 상황이 조금 다른 것 같군요.

그렇다면 LottoNumbers를 만드는 생성 로직은 LottoNumbers에게 맡겨보아도 좋을 것 같습니다.

2022-06-14 15:34 UTC, laco-dev approved these changes
피드백 많이 드렸는데, 대부분 잘 반영 해 주셨습니다.

BigDecimal을 비롯해서 몇 가지 주신 의견에 대한 답변을 같이 남겼습니다.
다음 미션을 진행하면서 같이 반영 해 주시면 좋을 것 같아요! 🙏🏻 🙏🏻

2022-06-14 15:34 UTC, merged

2022-06-15 02:05 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/Money.kt
> +    }
아하! 의도를 이해했습니다 👍

2022-06-20 10:13 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/WinningResult.kt
> +    val values: Map<WinningAmount, Int>
상세한 예시 안내 감사합니다..! 그러나 여전히 프로퍼티를 숨겨야할 이유가 와닿지 않습니다.. 😢 

WinningResult 를 만든 이유는 LottoTickets 에서 당첨관련 정보를 정리해서 당첨정보만을 전달하기 위함이었습니다.
WinningResult.winningAmount 내부 원소들도 모두 불변이라 영향력을 펼칠 수 없을거라 생각해서 외부로 직접 노출을 했습니다.

3단계를 진행해보면서 영직님이 남겨주신 리뷰 곰곰히 다시 생각해보겠습니다 🙇‍♂️