Step4 - 로또(수동)
next-step/kotlin-lotto pull request #395
Opened 2022-06-07 13:24 UTC by Wave1994-Hoon

안녕하세요 ~
아래 작업 내역 리뷰 요청드립니다. 🙌

> 3단계 피드백 반영
추상화레벨 수정 [[커밋 링크](https://github.com/next-step/kotlin-lotto/commit/05da7662c8816b78765a3e05ac790bf85f6c65ce)]
로또 버그 수정 [[커밋 링크1](https://github.com/next-step/kotlin-lotto/commit/2dae49e2c0af6bdda2534ce0b27a8463471db93b) / [커밋링크2](https://github.com/next-step/kotlin-lotto/commit/7a7c4f63876558a1b37e4ee2b4362cd900c28750) ]
LottoTickets 테스트 코드 [[커밋 링크](https://github.com/next-step/kotlin-lotto/commit/d395b7b13bbcee83cc5f48fff7139253a2b944ad)]
LottoTickets 프로퍼티 수정 [[커밍 링크](https://github.com/next-step/kotlin-lotto/commit/6832ab3a2da0886241230f0681151fc82c2b49e1)]

> 4단계
LottoNumber 원시 타입 wrapping
수동 로또 구매 기능 추가

2022-06-08 15:15 UTC, ohgillwhan requested changes
열심히 작성해주신 코드 잘 봤습니다!
사소한 리뷰를 남겼으니, 리뷰 확인 부탁드립니다!

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        isEnoughMoney(purchaseAmount)
`is~`는 `boolean`을 반환하고 `Exception`을 발생하지 않을것 같아요.
`check~`, `require~`, `validate~`등은 어떨까요?

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    fun isBuyAutoLotto(purchaseAmount: Int, manualLottoCount: Int) {
`is~`는 `boolean`을 반환하고 `Exception`을 발생하지 않을것 같아요.
`check~`, `require~`, `validate~`등은 어떨까요?

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    fun isBuyAutoLotto(purchaseAmount: Int, manualLottoCount: Int) {
`is~`는 `boolean`을 반환하고 `Exception`을 발생하지 않을것 같아요.
`check~`, `require~`, `validate~`등은 어떨까요?

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +class LottoTicket(val numbers: Set<LottoNumber>) : Set<LottoNumber> by numbers {
현재 `numbers`를 열어놓았는데, `delegate`가 필요할까요?

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/presentation/InboundView.kt
> +        )
```suggestion
        return LottoTickets(inputNumbers.map { LottoTicket(it) })
```

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/presentation/InboundView.kt
> +        )
```suggestion
        val tickets: MutableList<LottoTicket> = mutableListOf()

        while (tickets.size < manualPurchaseCount) {
            val inputManualNumber = readln()
            require(inputManualNumber.isNotBlank()) { "공백을 입력하셨습니다." }

            val manualNumber = inputManualNumber.toTokenize()
                .checkUniqueToken()
                .toMapInt()
                .toLottoNumber()
                .toSet()

            inputNumbers.add(LottoTicket(manualNumber))
        }

        return LottoTickets(inputNumbers)
```

2022-06-08 15:15 UTC, ohgillwhan commented on src/main/kotlin/lotto/presentation/InboundView.kt
> +        )
```suggestion
        val tickets: MutableList<LottoTicket> = mutableListOf()

        while (tickets.size < manualPurchaseCount) {
            val inputManualNumber = readln()
            require(inputManualNumber.isNotBlank()) { "공백을 입력하셨습니다." }

            val manualNumber = inputManualNumber.toTokenize()
                .checkUniqueToken()
                .toMapInt()
                .toLottoNumber()
                .toSet()

            inputNumbers.add(LottoTicket(manualNumber))
        }

        return LottoTickets(tickets)
```

2022-06-09 13:12 UTC, Wave1994-Hoon commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        return number.compareTo(other.number)
오 신기한거 알아갑니다. ㅎㅎㅎ

2022-06-09 13:45 UTC, Wave1994-Hoon commented on src/main/kotlin/lotto/presentation/InboundView.kt
> +        )
오 더 깔끔하네요 !

2022-06-11 01:13 UTC, ohgillwhan approved these changes
광훈님 지금까지 고생하셨습니다!

리뷰반영도 잘 해주셔서 감사했습니다 💯 

혹시 더 궁금한점 있으면 DM 주세요!

2022-06-11 01:13 UTC, ohgillwhan commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +class LottoTicket(val numbers: Set<LottoNumber>) : Set<LottoNumber> by numbers {
저는 반대로 `numbers`를 `private`으로 닫고, `delegate`하는 게 더 코드상으로 이쁘지 않을까 싶습니다.
`LottoTicket`이 `number`라는거 변수를 가지고 있다는것을 모든 개발자가 이해하고 있다면, `lottoTicket.numbers.each{}`보다는 `lottoTicket.each{}`가 더 깔끔할거 같습니다. 저는 위에 설명한것 처럼 모두가 해당 클래스에 있는 변수에 대해서 잘 이해하고 있다면 `delegate`가 더 보기 좋은것 같습니다! 그리고 `LottoTickets`는 제가 놓친거 같습니다 :D

(위에 남긴 리뷰는 둘 다 열어놔서, 하나만 열어놔도 괜찮지 않을까요? 라는 의미였습니다 ㅜ_ㅜ `numbers`를 열어놓고 `delegate`를 제거하라. 라는 의미는 아니였습니다 :D)

2022-06-11 01:13 UTC, merged

2022-06-11 05:39 UTC, Wave1994-Hoon commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +class LottoTicket(val numbers: Set<LottoNumber>) : Set<LottoNumber> by numbers {
오 다음 미션 부터는 private 으로 닫고, delegate 해야겠네요 ㅎㅎ