[4단계] 로또(수동)
next-step/kotlin-lotto pull request #400
Opened 2022-06-08 00:27 UTC by YooInKeun

안녕하세요 리뷰어님~ : )
[3단계에서 리뷰 주신 내용](https://github.com/next-step/kotlin-lotto/pull/390#discussion_r889699387)을 포함해서 4단계를 진행해봤는데요~

3단계에서 주신 피드백을 보고 클래스 분리에 대해 좋은 인사이트를 얻었습니다~ 👍 
(잘 반영한건지는 모르겠네요.. ㅎㅎ)

마지막 4단계 미션도 잘 부탁드립니다~!!

2022-06-08 14:28 UTC, pci2676 requested changes
이미 코드가 잘 작성되어있어서 그렇게 크게 리뷰드릴 부분이 보이지 않네요!
조금 생각해볼만한 부분에 리뷰를 남겨두었는데요
고민해보시고 개선해보셔도 좋을것 같습니다~!
다음 요청때는 머지를 해드릴텐데 더 의견을 주고받고 싶으시다면 코멘트를 남겨주시거나 DM을 주시면 될것같습니다~!

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/model/WinningStatistics.kt
> +        }
stream을 극한으로 쓰면 아래와 같이 표현할 수도 있답니다.
enum 순서를 보장하려면 EnumMap도 하나의 방법입니다~! (성능도 좋아용)

```suggestion
        fun from(winningRanks: List<WinningRank>): WinningStatistics {
                return WinningRank.values().filter { it != WinningRank.NONE }
                .associateWith { rank -> winningRanks.count { rank == it } }
                .toMap(EnumMap(WinningRank::class.java))
                .let(::WinningStatistics)
        }
```

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/view/ConsoleResultView.kt
> +        }
코틀린에 with 이라는 녀석이 존재하는데요 with에 리시버로 받은 객체를 사용하여 아래와 같이 표현하는 방법도 있습니다~!
https://kotlinlang.org/docs/scope-functions.html#with

```suggestion
    private fun printWinningStatus(statistics: WinningStatistics) = with(StringBuilder()){
        statistics.winningStatistics.forEach { (winningRank, count) ->
            this.appendLine("${winningRank.matchedNumberCount}개 일치${bonusBallMessage(winningRank)} (${winningRank.prizeMoney}원)- ${count}개")
        }
        println(this)
    }
```

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/LottoApplication.kt
> +        )
named parameter와 trailing comma를 적극적으로 사용해주시는 것이 변경할때 추가할때 굉장히 좋습니다~!
https://kotlinlang.org/docs/coding-conventions.html#trailing-commas
```suggestion
        val totalLottos = LottoGenerator.generateLottos(
            paymentPrice = paymentPrice,
            customLottos = Lottos(customLottos),
            lottoGeneratingStrategy = RandomLottoGenerating,
        )
```

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/model/RandomLottoGenerating.kt
> +            .subList(0, Lotto.LOTTO_NUMBER_COUNT)
`take(Lotto.LOTTO_NUMBER_COUNT)`
로 표현하는 방법도 있습니다~!

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/model/Lotto.kt
> +    private fun List<LottoNumber>.findMatchedNumberCount(other: Lotto) = other.lotto.count { this.contains(it) }
override 함수는 class 레이아웃상 직접 구현한 함수보다 아래쪽에 위치하는 것이 좋을것 같습니다!

2022-06-08 14:28 UTC, pci2676 commented on src/main/kotlin/lotto/model/LottoGenerator.kt
> +    ): Lottos {
사실 LottoGenerator의 lottoGeneratingStrategy 는 운영환경에서 RandomLottoGenerating만을 사용하기 때문에 아래와 같이 default로 선언해주고 운영환경에서는 명시적으로 주입을 안해주는것이 나을것 같습니다~!

```suggestion
    fun generateLottos(
        paymentPrice: Int,
        customLottos: Lottos,
        lottoGeneratingStrategy: LottoGeneratingStrategy = RandomLottoGenerating
    ): Lottos {
```

그리고
generator가 아무런 프로퍼티 없이 정적 메서드만을 제공하는 함수로 사용되는 것이 나을지
아니면 생성될때 strategy를 주입받아서 생성하여 사용하는것이 좋을지 고민해보셔도 좋을것 같아요.

2022-06-11 03:33 UTC, YooInKeun commented on src/main/kotlin/lotto/model/WinningStatistics.kt
> +        }
오 enum map 이라는 개념도 있군요~ 알려주셔서 감사합니다 👍 _👍

2022-06-11 05:25 UTC, pci2676 approved these changes
크 로또 4단계까지 모두 마치느라 그동안 고생하셨습니다! 👍 
리뷰 반영도 깔끔하게 해주셨네요!
이만 머지하도록 하겠습니다!
즐거운 주말 보네세요~!

2022-06-11 05:25 UTC, merged