Step4 : 로또(수동)
next-step/kotlin-lotto pull request #426
Opened 2022-06-21 11:52 UTC by hbm0411

일정이 밀려 늦었습니다(__)
로또 마지막 단계 잘 부탁드려요.

2022-06-21 11:53 UTC, hbm0411 commented on src/main/kotlin/lotto/view/InputView.kt
> +            println()
위의 readlnOrNull()이 개행을 커버못해서 어쩔수 없이 println을 넣었는데요...ㅠㅠ
다른 방법을 알려주시면 감사하겠습니다!

2022-06-28 09:19 UTC, hbm0411 commented on src/main/kotlin/lotto/view/InputView.kt
> +        while (true) {
예외처리에 관한 부분이 맞는지 헷갈려서 일단 한군데에만 넣었습니다.
너무 늦는것 같아 일단 리뷰요청 드립니다.
코멘트 주시면 다른 부분도 다 처리하도록 하겠습니다!
감사합니다(__)

2022-06-29 12:43 UTC, karian7 requested changes
마지막 단계도 잘 구현해 주셨습니다. 👏 
끝까지 진행하려는 의지를 응원해 드립니다. 🥇 
잘 구현하셨지만 마지막인 만큼 한번 더 핑퐁해보려고 합니다. 남긴 의견들 충분히 고민해 보시고 도전해 보시길 바랍니다.
마지막까지 화이팅 입니다~

2022-06-29 12:43 UTC, karian7 commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +        lottoTickets.asSequence()
`asSequence` 는 중간에 생기는 컬렉션을 줄이기 위해 변환이 많은경우 사용해주면 좋죠! 👍

2022-06-29 12:43 UTC, karian7 commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +            .map { (LottoPrize, count) -> LottoResult(LottoPrize, PositiveNumber(count)) }
```suggestion
            .map(::LottoResult)
```
`LottoResult` 에 생성자를 하나 더 넣어주면 사용하는쪽에서는 간결하게 표현할 수 있을것 같아요.
부 생성자를 적절하게 사용하면 이처럼 객체를 사용하는쪽에 가독성을 높일 수 있습니다. 😀

2022-06-30 09:48 UTC, hbm0411 commented on src/main/kotlin/lotto/view/InputView.kt
> +            println()
뭔가 입력의 개행을 위해 println()이 있는것이 어색하게 느껴져서 그랬습니다.
문제없다면 상관없습니다 :)

2022-06-30 09:50 UTC, hbm0411 commented on src/main/kotlin/lotto/view/InputView.kt
> +            val inputStr = requireNotNull(readlnOrNull()) { Const.ErrorMsg.INPUT_VALUE_IS_NULL_ERROR_MSG }
에러메시지를 출력하고 싶어서 이렇게 했습니다!
readln을 사용하게 되면 제가 원하는 에러메시지를 출력할 수 없는것으로 보여서요~

2022-06-30 10:07 UTC, hbm0411 commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +            .map { (LottoPrize, count) -> LottoResult(LottoPrize, PositiveNumber(count)) }
부생성자를 이용하는걸 자꾸 놓치네요 ㅎㅎ 노력해보겠습니다!

2022-06-30 10:08 UTC, hbm0411 commented on src/main/kotlin/lotto/view/OutputView.kt
> +                ?.matchedLottoCount ?: 0
모든 int에 대해 처리할 필요는 없지만, 양수만 받아야 하는 변수는 positiveNumber를 사용하는것이 더 좋다고 생각했습니다.

2022-06-30 10:32 UTC, hbm0411 commented on src/main/kotlin/lotto/domain/LottoPurchase.kt
>          }
`repeat`으로 사용하려다 보니 `mutableListOf<>()`와 `list.add()`를 사용하게 되어 지저분하다고 생각했는데
`(1..number).map{}` 으로 하니 훨씰 깔끔하네요!

2022-07-01 12:07 UTC, karian7 commented on src/main/kotlin/lotto/view/InputView.kt
> +            val inputStr = requireNotNull(readlnOrNull()) { Const.ErrorMsg.INPUT_VALUE_IS_NULL_ERROR_MSG }
🙆‍♂️

2022-07-01 12:44 UTC, merged

2022-07-01 12:46 UTC, hbm0411 commented
그동안 고생 많으셨습니다~ 감사합니다 :)