🚀 1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #447
Opened 2022-11-17 21:13 UTC by shinseongsu

# 구현 기능

- [x] 쉼표(,) 또는 콜론(:)을 구분자로 가지는 문자열을 전달하는 경우 구분자를 기준으로 분리한 각 숫자의 합을 반환 
  - [x] 쉼표로 문자 구분
  - [x] 콜론으로 문자 구분
- [x] 앞의 기본 구분자(쉼표, 콜론) 외에 커스텀 구분자를 지정할 수 있다. 커스텀 구분자는 문자열 앞부분의 “//”와 “\n” 사이에 위치하는 문자를 커스텀 구분자로 사용한다.
- [x] 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw 한다.

# 질문

nextstep 문서에는 junit 형식의 테스트 코드가 써져있는데, kotest를 사용하였습니다.
kotest에도 많은 spec들이 있던데 실무에서는 어떤 방식으로 많이 쓰는지 알고 싶습니다 😄

2022-11-18 07:18 UTC, Hyeon9mak requested changes
안녕하세요 성수님, 로또 미션을 함께하게 된 최현구입니다. 잘 부탁드립니다 🙇‍♂️ 

현재 리뷰요청 주신 프로그램은 실행이 불가능한 것 같아요.
실행이 가능한 상태로 리팩터링 후 다시 요청주시면 빠르게 리뷰 시작하겠습니다!

> nextstep 문서에는 junit 형식의 테스트 코드가 써져있는데, kotest를 사용하였습니다.
kotest에도 많은 spec들이 있던데 실무에서는 어떤 방식으로 많이 쓰는지 알고 싶습니다 😄

말씀주신대로 여러가지 스펙들이 존재하는데요, 취향의 영역이라 모두 다를 것 같습니다.
저희 팀에서는 주로 StringSpec, FreeSpec, FunSpec 을 사용하는데요,
개인적으로 저는 JUnit 의 parameterized test 와 비슷하게 테스트를 구성할 수 있다는 점에FreeSpec 을 선호하는 편입니다.
학습 과정에서 여러가지 Spec 을 병행하여 사용해보시면 성수님께 가장 잘 맞는 Spec 을 찾으실 수 있을 것 같아요 😄

궁금하신 것은 언제든지 DM 및 코멘트 주세요! 🙇‍♂️

2022-11-18 13:22 UTC, shinseongsu commented
안녕하세요 @Hyeon9mak 님
실행 메소드 리팩토링하여 다시 PR 드립니다~

2022-11-19 11:14 UTC, Hyeon9mak requested changes
안녕하세요 성수님~! 문자열 덧셈 계산기 진행 고생 많으셨습니다.
전체적으로 이해도가 높으신 것 같아 사소한 디테일에 대해 코멘트 남겼습니다!

궁금하신 점 언제든지 코멘트, DM 남겨주세요 😄 🙇‍♂️

2022-11-19 11:14 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddCalculator.kt
> +        return splitList.map { StringConvert.toInt(it) }.sum()
```kotlin
// 확장함수
fun String.toPositiveInt(): Int {
      val result = this.toInt()
      require (result >= 0) { "음수는 입력할 수 없습니다." }
      return result
  }

// 사용
splitList.sumOf { it.toPositiveInt() }
```

확장함수를 사용하면 요런 표현도 가능하겠네요~!

2022-11-19 11:14 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringSplit.kt
> +    }
삼항연산자처럼 활용하기 위해 null 이 사용되었는데요, `splitCustomDelimiter` 가 정말로 null 을 반환해야해서 사용된걸까요?
보기 좋은 코드를 만드는 것도 중요하지만, 의도 파악이 쉬운 코드를 만드는게 조금 더 중요할 것 같습니다. 만약 지금의 형태를 유지하고 싶다면 `splitCustomDelimiterOrNull` 과 같이 null 의 위험요소가 있음을 나타내주는게 좋을 것 같아요.

> 데이크스트라는 예술적 프로그래밍과 과학적 프로그래밍을 이야기한다. 예술적 프로그래밍은 문제 해결에 대해 성능과 영감, 아름다움 등에 몰두한다. 반면 과학적 프로그래밍은 표준화에 몰두한다. 예술적 프로그래밍은 훌륭하고 나도 선망하는 가치이긴 하지만 과학적 프로그래밍 관점에서는 문제가 있는데 특정한 환경에 맞춰 기가막힌 작업물을 만들어내긴 하지만 일반화하기는 어려운 트릭이 생산된다는 점. 데이크스트라에 의하면 이런 트릭에 대한 지식은 해당 환경의 수명에 영향을 받으므로 인류의 지식에 별로 기여하는 바가 없다. 고립된 환경에서 독자적인 생태계를 구축하는 것과 비슷하다.
> 
> 그래서 괴상한 트릭을 사용해 기발하게 문제를 해결하는 것이 아니라 성능상의 피해가 있다 하더라도 표준적인 방식으로 코딩하고, 훗날의 상식을 가진 다른 사람이 읽더라도 이해할 수 있게 만드는 것이 중요하다.

몇 개월 전 크게 인사이트를 얻은 구절이었는데요, 성수님도 인사이트를 얻으실 수 있을 것 같아 공유드립니다!
https://johngrib.github.io/wiki/article/science-and-delete/

2022-11-19 11:14 UTC, Hyeon9mak commented on src/main/kotlin/calculator/view/InputView.kt
> +    }
- 이미 `readLine()!!` 을 통해 NullException 이 발생하므로 검증이 안될거 같아요!
- [`readLine()` 대신 `readln()` 을 사용하면 null 체크도 필요없어 지겠네요.](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/readln.html)

2022-11-19 11:14 UTC, Hyeon9mak commented on src/test/kotlin/calculator/view/InputViewTest.kt
> +
FreeSpec 의 매력에 빠지셨군요 😄

2022-11-20 16:01 UTC, shinseongsu commented on src/main/kotlin/calculator/CalculatorApplication.kt
> +}
그렇군요~ 출력을 관리하는 view도 만들면 좋겠네요~

2022-11-20 16:02 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringConvert.kt
> +    }
👍  kotlin에서는 require를 사용하니 더 깔끔한 코드로 변하는군요

2022-11-20 16:03 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringAddCalculator.kt
> +        return splitList.map { StringConvert.toInt(it) }.sum()
아하 굳이 class나 object를 안 만들고 이런식으로도 쓸수 있군요

2022-11-20 16:08 UTC, shinseongsu commented on src/main/kotlin/calculator/view/InputView.kt
> +    }
readln이라는 메소드가 있었군요 👍 
@Hyeon9mak 코멘트 깊이가 깊네요 감사합니다 😄

2022-11-20 16:09 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringSplit.kt
> +    }
제가 생각이 짧았나 보네요
코드길이가 짧아지면 유지보수성이 늘것이라고 생각했는데.. 정말 좋은 인사이트네요 👍

2022-11-20 16:12 UTC, shinseongsu commented
@Hyeon9mak 멘토님 코멘트대로 수정하였습니다.

- ResultView 출력 class 생성
- 음수체크 확장함수로 수정
- 네이밍 수정

2022-11-21 01:01 UTC, Hyeon9mak requested changes
안녕하세요 성수님~! 빠르게 진행해주셨네요~
조금만 더 디테일을 챙기면 좋을 것 같아요. 🙏 

코멘트 확인해주시고, 다시 PR 요청 주시면 Merge 하도록 하겠습니다!
궁금하신 점 언제든지 코멘트 및 DM 남겨주세요~ 🙇‍♂️

2022-11-21 16:19 UTC, shinseongsu commented on src/main/kotlin/calculator/CalculatorApplication.kt
> +}
아하 그렇군요 감사합니다 😄

2022-11-21 16:19 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringAddCalculator.kt
> +    }
아하 그렇군요 이렇게 편하다니 코틀린 👍

2022-11-21 16:20 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringSplit.kt
> +    }
앗! 감사합니다 😃

2022-11-21 16:21 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringSplit.kt
> +    }
matches로 있는지 없는지 판단하여 if else 로 표현했는데 코멘트 남겨주시면 감사하겠습니다 😄

2022-11-21 16:21 UTC, shinseongsu commented on src/main/kotlin/calculator/view/InputView.kt
> +    }
오 여기서도 확장함수를 👍

2022-11-23 12:32 UTC, Hyeon9mak approved these changes
안녕하세요 성수님! 문자열 덧셈 계산기 고생 많으셨습니다!
null 을 통한 분기를 말끔하게 제거해주셨네요!! 👍

로또 미션을 향해 Merge 하도록 하겠습니다!
궁금한건 언제든지 DM 주세요~ 🙇‍♂️

2022-11-23 12:32 UTC, merged

2022-11-23 23:26 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/StringSplit.kt
> +    }
@Hyeon9mak 님 덕분에 무슨 코드가 더 좋은 코드인지 생각하는 계기가 된것같습니다 😄