🚀 2단계 - 로또(자동)
next-step/kotlin-lotto pull request #460
Opened 2022-11-20 14:43 UTC by chayoung-choi

- [X] 입력
    - [X] 구입 금액
    - [X] 지난 주 당첨 번호
        - [X] 입력 받은 값에서 정상적인 숫자 6개를 추출한다.
- [X] 출력
    - [X] 구입 금액에 따른 로또 리스트 값을 화면에 출력한다.
    - [X] 당첨 통계를 화면에 출력한다.
- [X] 로또
    - [X] 1~45 범위의 중복되지 않는 랜덤 숫자 6개를 생성한다.
- [X] 로또 생성자
    - [X] 구입 금액만큼 로또 번호 생성
- [X] 당첨 로또
    - [X] 당첨 로또와 비교하여 일치하는 번호의 갯수를 가져온다.
- [X] 로또 통계
    - [X] 각 등수에 당첨된 로또 수
    - [X] 총 수익률

2022-11-20 23:01 UTC, Flamme1004K requested changes
안녕하세요!

로또 게임 구현 잘 해주셨습니다! 👍👍

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

화이팅입니다! 🙌

2022-11-20 23:01 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +        private set
LottoRule을 기준으로 리팩토링 할 수 있지 않을까요?

2022-11-20 23:01 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +        println(reward)
해당 로직은 도메인이 아닌 뷰 로직이라고 생각해요! 분리해 볼까요?

2022-11-20 23:01 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun getMatchesCount(lotto: Lotto) = lotto.numbers.count { num -> winningNumbers.numbers.contains(num) }
WinningLotto에서만 사용한다면 접근 제어자를 private으로 하는게 좋지 않을까요?

2022-11-20 23:01 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun getMatchesCount(lottos: List<Lotto>) = lottos.map { lotto -> getMatchesCount(lotto) }
저는 식으로 표현할 때 반환 타입을 항상 적어두고 있어요! 그 이유는 식으로 쓸 경우 자칫 잘못하여 Unit으로 반환되버리면 나중에 에러 찾기가 매우 골치 아프기 때문이기도 하고, 다른 사람이 코드를 봤을 때 바로 반환 타입을 체크 가능하게 하기 위해서입니다.

2022-11-20 23:01 UTC, Flamme1004K commented on src/main/kotlin/stringcalculator/StringNumbers.kt
> +            val (customDelimiter, numberText) = it.destructured
피드백 반영 👍

2022-11-20 23:01 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoStatisticsTest.kt
> +class LottoStatisticsTest {
테스트 코드 매우 좋습니다 👍

2022-11-20 23:01 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoStatisticsTest.kt
> +        lottos.add(Lotto(mutableSetOf(8, 21, 23, 41, 42, 43)))
```suggestion
        lottos.add(Lotto(setOf(8, 21, 23, 41, 42, 43)))
```

setOf가 아닌 mutableSetOf를 사용한 이유를 알 수 있을까요?

2022-11-20 23:01 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoStatisticsTest.kt
> +    fun `당첨 번호와 로또 티켓을 비교하여 등수 결과를 생성한다`() {
해당 테스트도 `@CsvSource`로 가능하지 않을까요~?

2022-11-21 05:15 UTC, chayoung-choi commented on src/test/kotlin/lotto/domain/LottoStatisticsTest.kt
> +        lottos.add(Lotto(mutableSetOf(8, 21, 23, 41, 42, 43)))
`mutableListOf`를 쓰고 당연히 set도 그렇게 써야겠다 생각한 것 같습니다. 🥲

2022-11-22 10:41 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 💯

그동안 step2 고생하셨습니다! 다음 단계를 위하여 merge 하도록 하겠습니다 🙌

몇 가지 코멘트를 남겼으니 확인 부탁드리겠습니다!

궁금하신 점에 대해서는 마음껏 물어봐주세요!!

다음 미션도 화이팅입니다! 🤩

2022-11-22 10:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        const val LOTTO_NUMBER_RANGE_START = 1
```suggestion
        return numbers
            .filterNot { num -> num in LOTTO_NUMBER_RANGE }
            .isEmpty()
    }

    companion object {
        private val LOTTO_NUMBER_RANGE = 1..45
```

상수와 Range를 적절히 사용한다면 좀 더 깔끔한 코드가 될 것 같아요 😊

2022-11-22 10:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    }
와우! 제가 원했던게 이거였습니다! 리팩토링 좋습니다 👍👍

2022-11-22 10:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    private fun calculateTotalPofit(): Double {
오타가 있어보이네요!

2022-11-22 10:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +        var reward = matchesResult.map { result -> result.key.getTotalReward(result.value) }.sum().toDouble()
```suggestion
        val reward = matchesResult.map { result -> result.key.getTotalReward(result.value) }.sum().toDouble()
```

변하지 않는 값에 대해서는 `val`를 써볼까요?

2022-11-22 10:41 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun getMatchesCount(lottos: List<Lotto>): List<Int> = lottos.map { lotto -> getMatchesCount(lotto) }
전체적으로 `it` 대신에 `num`, `lotto`, `result` 로 람다 파라미터를 해놓으셨는데 이유가 있으셨을까요?

일단 저는 헷갈리지 않는다면 람다 파라미터를 사용하지 않고, `it`을 사용하고 있습니다. 왜냐하면 람다 파라미터 대신에 `it`을 사용하는 것이 코틀린 언어에서 선호하는 패턴이라고 생각하기 때문이에요.

2022-11-22 10:41 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoStatisticsTest.kt
> +    @CsvSource("1 2 3 4 5 6,6", "1 2 3 4 5 16,5", "2 5 3 4 25 16,4", "11 2 3 4 19 8,3")
`@CsvSource` 사용 좋습니다!

2022-11-22 10:41 UTC, merged

2022-11-22 13:56 UTC, chayoung-choi commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        const val LOTTO_NUMBER_RANGE_START = 1
오호! 코틀린에서는 이렇게도 사용할 수 있군요!

2022-11-22 14:03 UTC, chayoung-choi commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun getMatchesCount(lottos: List<Lotto>): List<Int> = lottos.map { lotto -> getMatchesCount(lotto) }
그렇군요! 자동차 경주때 다른 분의 리뷰를 훑어보다가(저의 소스에 대한 리뷰는 아니었음) it보다는 명시적으로 해주는게 좋다는 리뷰 내용을 본 뒤로 이렇게 써주곤 했었는데, 무조건으로 쓰는건 아닌가보군요!!