[2주차]  1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #470
Opened 2022-11-21 15:05 UTC by jaeykweon

안녕하세요 2주차 리뷰이 권재용입니다.

요구사항 및 설계 순서는 [리드미](https://github.com/jaeykweon/kotlin-lotto/blob/step1/src/main/kotlin/stringcalculator/ReadMe.md)에서 확인하실 수 있습니다.

질문 사항은 코멘트 달아놓겠습니다 감사합니다!

2022-11-21 15:08 UTC, jaeykweon commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            } ?: (DEFAULT_SEPARATORS to text)
한 줄에 많은 로직이 들어갔다고도 생각이 드는데 분리해야할까요?
```kotlin
val result = Regex(CUSTOM_SEPARATOR_REGEX).find(text)
val (separator, tokens) = result?.let {
   it.groupValues[1] to it.groupValues[2]
} ?: (DEFAULT_SEPARATORS to text)
```

2022-11-21 15:24 UTC, jaeykweon commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        }
이 더하는 로직을 여기서 처리하는게 맞을까요 아니면 `inputNumbers`에 넘기는게 맞을까요?
디미터의 법칙을 생각하면 `inputNumbers`에 모두 더하는걸 시키는게 맞다고생각됩니다.
그런데 요구사항이 더하는 것 뿐 아니라 빼기나 곱셈등 변화할 유지보수성을 생각하면 `Calculator`에서 알아서 더하거나 빼는 것이 `inputNumbers`에 너무많은 책임을 전가하지 않는 것이라고 생각되는데 어떤게 맞을까요?

2022-11-22 14:44 UTC, hyunniiii requested changes
안녕하세요 재용님~ 
몇가지 코멘트 남겼으니 확인 부탁드립니다!

2022-11-22 14:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        }
`Calculator`의 책임은 숫자를 계산하는 것이기 때문에 더해주는 책임은 `Calculator`가 가지고 있는것이 맞는 것 같습니다.

2022-11-22 14:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumber.kt
> +    constructor(string: String) : this(string.toInt())
에러 핸들링을 하면서 `생성자`에서 해주는것과 `정적 팩토리 메소드`로 해주는것 둘다 괜찮을 것 같습니다.

다만 지금 `문자열 덧셈 계산기` 구조가 `정적 팩토리 메소드`로 구현해주었을때 장점이 크게 없어보여 생성자 내부에 try catch로 핸들링 해주어도 좋을 것 같아요.

2022-11-22 14:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumber.kt
> +            throw RuntimeException("error : $value $NEGATIVE_NOT_ALLOWED_MESSAGE")
`RuntimeException`보다는 어떤 에러인지 더 잘 알 수 있도록 조금 더 구체적인 `Exception`을 사용해주세요.

ex) IllegalArgumentException, IllegatStateException

2022-11-22 14:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            val (separator, tokens) = Regex(CUSTOM_SEPARATOR_REGEX).find(text)?.let {
`Regex`는 생성 비용이 크기 때문에 한번 생성하고 재사용해주도록 해주세요. :) 

`InputNumbers` 객체가 `구분자`를 이용해서 구분해주는 책임을 가지고 있는데 
`InputNumbers`가 가지고 있어야할 책임인지 고민해보는게 좋을 것 같습니다.

2022-11-22 14:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            } ?: (DEFAULT_SEPARATORS to text)
가독성을 위해 분리해주는것도 좋은 방법입니다. :)

2022-11-22 14:48 UTC, jaeykweon commented on src/main/kotlin/stringcalculator/InputNumber.kt
> +            throw RuntimeException("error : $value $NEGATIVE_NOT_ALLOWED_MESSAGE")
요구사항에 RuntimeException을 반환하라고 되어있어서 그대로 썼습니다
말씀주신 에러들도 상속받은 에러들이라 사용해도 될거같네요 변경하겠습니다

2022-11-23 15:21 UTC, jaeykweon commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            val (separator, tokens) = Regex(CUSTOM_SEPARATOR_REGEX).find(text)?.let {
@hyunniiii 
말씀하신 내용들 
https://github.com/next-step/kotlin-lotto/commit/84b862d21d0151cc609bf09cea0c8357fbc5a11f
에서 적용해보았습니다
구분자로 입력을 분리하는 역할을 `Separator` 객체에 넘겼는데 `Separator`객체의 반환값을 단순히 
`List<String>`으로 해도 되는걸까요 아니면 VO를 만들어서 넘겨야 하는걸까요..?

2022-11-23 15:22 UTC, jaeykweon commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            val (separator, tokens) = Regex(CUSTOM_SEPARATOR_REGEX).find(text)?.let {
그리고 이렇게 분리하니까 `InputNumbers` 객체의 책임이 단순히 문자열 리스트를 입력받아 `InputNumber`로 변환해주는 역할밖에없는데 이게 맞는건지 잘 모르겠습니다

2022-11-26 15:44 UTC, hyunniiii approved these changes
안녕하세요 재용님!

피드백 반영 잘해주셨네요 :) 
다음 미션을 위해 이번 미션은 머지하도록 하겠습니다.

몇가지 코멘트 더 남겼으니 다음 미션에 함께 반영 부탁드립니다!

2022-11-26 15:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/Calculator.kt
> +            total + inputNumber.value
이 부분은 `InputNumbers` 클래스로 넘겨주고 계산된 값만 가져오도록 하는건 어떨까요 ?

2022-11-26 15:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/DefaultSeparator.kt
> +    const val CUSTOM_SEPARATOR_REGEX = "//(.)\n(.*)"
```suggestion
    private val DEFAULT_SEPARATORS = "[,:]".toRegex()
    private val CUSTOM_SEPARATOR_REGEX = "//(.)\n(.*)".toRegex()
```
다른 곳에서 사용하고 있지 않으니 `private`로 선언해주어도 괜찮을 것 같아요 :)

2022-11-26 15:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumber.kt
> +    val value: Int
```suggestion
    private val value: Int
```
여기도 `private` 로 선언해주면 될 것 같습니다 :)

2022-11-26 15:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +    val values: List<InputNumber>
```suggestion
    private val values: List<InputNumber>
```
:)

2022-11-26 15:44 UTC, hyunniiii commented on src/main/kotlin/stringcalculator/InputNumbers.kt
> +            val (separator, tokens) = Regex(CUSTOM_SEPARATOR_REGEX).find(text)?.let {
`Seperator` 반환값은  `Seperator`가 유틸성 클래스처럼 사용되기 때문에 `List<String>`으로 해줘도 괜찮을 것 같습니다 :) 

`InputNumbers` 객체는 도메인 역할을 하고 있기 때문에 `InputNumbers`자체가 `InputNumbers`를 의미하는 책임을 가지고 있는 것이라고 생각합니다. :) 

메서드를 다른 객체로 옮겨서 책임을 넘겨주는 부분은 `A객체가 B객체의 상태를 변화시켜주는 로직`을 가지고 있을 때 `B객체 스스로가 자신의 상태를 변환할 수 있도록` 비즈니스 로직적인 부분에 대한 책임을 넘겨주는 것입니다.

2022-11-26 15:44 UTC, merged