[2단계] - 로또(자동)
next-step/kotlin-lotto pull request #471
Opened 2022-11-21 17:41 UTC by SangHyunGil

안녕하세요~ 이번에는 로또(자동)을 구현해보았어요. 🤩

이번에 구현하면서 생각했던 부분은 로또를 고르는데 있어, 자동뿐만 아니라 수동으로도 뽑을 수 있다는 가정을 추가했어요.
당첨 번호 또한 수동뿐만 아니라 자동으로도 뽑을 수 있다는 가정을 추가했어요.
위의 가정들이 아직 실제로 구현된 부분은 아니지만 해당 부분을 유연하게 가져갈 수 있도록 추상화해서 구현해보았어요.

이번 리뷰도 잘 부탁드리겠습니다! 🦾

2022-11-22 12:21 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-11-22 12:21 UTC, kyucumber commented on src/main/kotlin/lotto/domain/AutoLottoTicket.kt
> +        println("[${lottoNumbers.map { it.number }.joinToString(DELIMITER)}]")
비즈니스 로직으로 보이는데 비즈니스 로직 내부에 print 구문은 제거하는게 좋을 것 같네요~

lottoNumbers라는 데이터를 받아 다른곳에서 출력하는 형태로 변경해보세요.

2022-11-22 12:21 UTC, kyucumber commented on src/main/kotlin/lotto/domain/AutoLottoTicket.kt
> +        }
mutable이 아니라 불변을 통해 lottoNumbers를 초기화 할 수 있을 것 같네요. 불변을 사용하면 사이드 이펙트를 줄이고 이해하기 쉬운 코드를 짤 수 있습니다. 가급적 불변을 사용해주세요. 

그렇게 되면 조금 간단해지기 때문에 init block을 쓰지 않아도 될 것 같아요.

2022-11-22 12:21 UTC, kyucumber commented on src/main/kotlin/lotto/util/RandomNumberGenerator.kt
> +    fun generate(range: IntRange): Int = range.random()
default 값을 추가하면 어떨까요? 로또라는 비즈니스 내에서는 이 range는 항상 같은 값이 될 것 같아요.

2022-11-22 12:21 UTC, kyucumber commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        println("${ticketCount}개를 구매했습니다.")
여기도 print 구문이 있네요. 비즈니스 로직에서 분리해보시면 좋을 것 같아요.

2022-11-22 12:21 UTC, kyucumber commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +)
이런 경우라면 data class를 사용하셔도 좋겠네요.

2022-11-22 12:45 UTC, SangHyunGil commented on src/main/kotlin/lotto/util/RandomNumberGenerator.kt
> +    fun generate(range: IntRange): Int = range.random()
이 유틸은 현재로서는 고정된 값만 들어올 수 있지만, 범용적으로 사용할 수 있는 유틸로 구성했어요.
default 값 좋네요~!

2022-11-22 12:46 UTC, SangHyunGil commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
명령과 조회를 분리하는 관점에서 두 로직을 분리해두었어요.
말씀해주신 것처럼 execute 메서드의 가시성을 private로 제한하고 getSummary를 호출하는 방향으로 구성해볼게요~!

2022-11-22 12:46 UTC, SangHyunGil commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        println("${ticketCount}개를 구매했습니다.")
이 부분도 즉각적인 피드백때문에 구성해놓았는데 수정해볼게요!

2022-11-22 12:49 UTC, SangHyunGil commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +}
지금은 오로지 생성만을 담당하고 있는 부분이라 해당 부분을 인터페이스로 사용하는 부분의 장점이 두드러지진 않을 수 있으나 추후에 어떤 로직이 추가될지 몰라 인터페이스로 구성해두었어요.
일단, 이렇게 구성하는 부분이 지나친 추상화라고 보일 수도 있겠네요 🤨

로또 티켓이라는 클래스 안에 생성 전략을 추가해 로또 번호를 자동으로 생성할지, 수동으로 생성할지에 대한 방향을 고려해도 좋을 것 같네요~!

2022-11-22 12:50 UTC, SangHyunGil commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +}
LottoTickets는 로또 티켓의 모음이지 해당 티켓이 자동인지 수동인지 몰라야한다고 생각해요.
지금은 자동 로또 티켓밖에 존재하지 않아 생성자로 해당 로또 티켓만 구성하고 있는데, 추후에는 수동으로 생성할 로또 티켓의 개수와 자동으로 생성할 로또 티켓의 개수를 받아 각각 생성해줘서 사용하려고 했어요~

2022-11-22 12:51 UTC, SangHyunGil commented on src/main/kotlin/lotto/domain/ManualWinnerLottoTicket.kt
> +    }
위의 부분과 마찬가지 이유로 구성했는데, 이 부분도 반영해볼게요 😄

2022-11-22 15:59 UTC, SangHyunGil commented
생성 전략을 추가해 로또 티켓이라는 클래스에서 컴포지션으로 가져가 로또 번호를 자동으로 생성할지, 수동으로 생성할지에 대한 방향으로 진행해보았어요.
리뷰어님이 남겨주신대로, 입출력관한 부분은 Application에서 진행할 수 있도록 분리해보았어요.
추가적으로 로또 번호를 생성하는데 Immutable하게 할 수 있도록 방법을 변경했고, RandomGenerator는 사용하지 않아 제거하였어요~!

2022-11-23 13:23 UTC, kyucumber approved these changes
피드백 잘 반영해주셨네요.

간단한 코멘트 하나 남겨두었으니 확인 부탁드려요.
다음 단계 진행을 위해 머지하겠습니다.

2022-11-23 13:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/LottoAutoGenerateStrategy.kt
> +    }
👍

2022-11-23 13:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        lottoSummary = LottoSummary(lottoInfos)
이런 경우면 execute에서 LottoSummary를 리턴 타입으로 가지고 바로 리턴해도 괜찮지 않을까요?

인스턴스 변수로 정의할 필요가 없을 것 같아서 코멘트 남겨보았어요.

2022-11-23 13:23 UTC, merged