Step2 로또(자동)
next-step/kotlin-lotto pull request #474
Opened 2022-11-22 08:53 UTC by shinaaaa

2022-11-23 11:54 UTC, ujusy requested changes
안녕하세요, 김신님 👋

2단계 구현 고생하셨습니다 :) 
고민해볼 몇 가지 코멘트 남겼습니다.
확인 후 다시 요청주세요!

2022-11-23 11:54 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +            }
추후 더 많은 케이스가 추가될 경우 해당 함수가 거대해질 수 있을 것 같아요.
[`associateWith`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/associate-with.html) 를 활용해 볼 수 있을 것 같아요. :)

2022-11-23 11:54 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +        fun winningStatistics(
해당 함수에 대한 테스트를 작성해보는게 어떨까요?

2022-11-24 08:07 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +            return totalPrize.divide(purchasingCost)
생각도 못했는데 감사합니다.

2022-11-24 08:23 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +enum class LottoGameResult(val criteriaForWinning: Int, val prize: BigDecimal) {
🙇‍♂️

2022-11-24 08:23 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +        get() = 1..45
🙇‍♂️

2022-11-24 08:26 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +    FIRST(6, BigDecimal(2000000000)),
좋은 방법 감사합니다.

2022-11-24 08:32 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoGame.kt
> +    fun checkAnswer(lotto: Lotto, winnerLotto: Lotto): LottoGameResult {
🤔

2022-11-24 08:42 UTC, shinaaaa commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        val gameResults = gameBoard.map { LottoGame.checkAnswer(it, winnerNumber.winnerNumber) }
🧐

2022-11-24 09:11 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +            }
좋은 방법 감사합니다.

2022-11-24 09:20 UTC, shinaaaa commented on src/main/kotlin/lotto/domain/PurchaseResult.kt
> +        change = cost.toInt() % LOTTO_PRICE
🫡

2022-11-25 08:36 UTC, ujusy requested changes
안녕하세요 김신님 👋

피드백 반영 고생하셨습니다 👍 
추가로 고민해볼만한 코멘트를 남겼습니다 :) 
반영 후 다시 리뷰 요청주세요! 
다음 요청 시에는 머지 진행하겠습니다. 🙌

2022-11-25 08:44 UTC, shinaaaa commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +    fun main() {
이름.....🤔

2022-11-25 08:54 UTC, shinaaaa commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        }
🫡

2022-11-25 12:39 UTC, ujusy approved these changes
안녕하세요, 김신님 👋 

피드백 빠르게 반영해주셨네요 👍 👍 
그리고 TDD 로 구현 잘 해주셨네요 ! 
조금 더 고민해보면 좋을 코멘트 남겼습니다!
다음 미션 진행하시면서 같이 반영해주세요 :) 

다음 미션도 화이팅 입니다 💪💪

2022-11-25 12:39 UTC, ujusy commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        }
> winningStatistics에서 반환한 값을 psintWinningStatics 에 전달하여 느슨한 결합을 만들어보는건 어떨까요?

이 부분을 너무 추상적으로 말씀드린 것 같네요 :) 
`ResultView.printWinningStatistics`이 로또 결과를 출력하는 역할을 모두 가지고있는게 어떨까요?
```suggestion
        val statistics = LottoGameResult.winningStatistics(gameResults)
        ResultView.printWinningStatistics(statistics)
```

2022-11-25 12:39 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoGame.kt
> +        MutableList(numberOfGames) { lottoFactory.create() }
구매한 로또가 `MutableList`이기 때문에 외부에서 값을 변경할 수 있을 것으로 보여져요 :) 
여기서 변경가능한 리스트일 이유가 있을까요?

2022-11-25 12:41 UTC, merged

2022-11-25 13:17 UTC, shinaaaa commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        }
```
statistics.forEach {
            ResultView.printWinningStatistics(
                it.key.criteriaForWinning,
                it.key.prize,
                it.value
            )
        }
```
이 부분을 `ResultView.printWinningStatistics(statistics)` 여기서 구현하라는 말씀이신거죠?