feat: Step2. 로또(자동)
next-step/kotlin-lotto pull request #496
Opened 2022-11-26 05:57 UTC by rolroralra

- [x] 구매 비용과 티켓 가격을 입력했을 때, 로또를 자동적으로 발급한다. (비용, 가격)
- [x] 로또 티켓 하나를 랜덤하게 발급한다. (6개 다른 번호 in (1..45))
- [x] 특정 갯수의 다른 로또 티켓을 랜덤하게 발급한다.
- [x] 당첨 번호를 발급한다.
- [x] 당첨 통계를 계산한다. (3개 일치 갯수, 4개 일치 갯수, 5개 일치 갯수, 6개 일치 갯수)
- [x] 수익율을 계산한다.

2022-11-26 08:23 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitPolicy.kt
> +            6 to 2000000000
별도의 enum을 사용해서 각각의 숫자가 무엇을 의미하는지 나타내면 어떨까요?

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +        }
생성과 동시에 ticketCount를 이용해 초기화를 진행할거면 MutableList에서 add를 호출하는게 아니라 불변(List)을 사용하고 즉시 초기화화는 형태로 사용할 수 있지 않을까요?

ticketCount 개수만큼 초기화 된 이후에는 집계에만 활용하기 때문에 변경될 필요가 없어보여요. 코틀린 자체도 함수형 패러다임이 일부 섞여있기 때문에 가급절 불변한 컬렉션과 val을 이용해 불변값을 가지게 코딩해보시면 좋을 것 같아요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/number/LottoNumber.kt
> +    }
LottoNumber는 Int 값을 래핑하고 로또 숫자 범위 안의 값으로 생성되는지 검증하는 역할을 하는 것 같아요.

randomShuffle은 LottoTicket에서만 사용되는 함수인데 LottoNumber에서 이 책임을 가지는게 조금 부자연스럽다는 생각이 드네요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/number/LottoNumber.kt
> +}
검색해보니 테스트에서만 쓰는 확장함수 같은데 비즈니스 코드를 오염시키고 있네요.

제거하고 테스트 쪽 클래스로 옮기시는게 어떨까요?

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/price/LottoCost.kt
> +}
이런 경우라면 inline class(value class 키워드 사용)를 활용해보셔도 좋을 것 같습니다.

[이펙티브 코틀린 아이템 47. 인라인 클래스의 사용을 고려하라
](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-47)

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +): List<LottoTicket> by _list {
차라리 저는 `LottoTicket`에 적용되었다면 조금 더 의미있는 delegation 사용이 되었을 것 같아요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +            .get()
다른 곳에 이유를 남겨두었는데요. 가변이 아니라 불변 컬렉션을 사용하도록 변경해보세요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/infra/io/LottoInputReader.kt
> +}
미션과 별개지만 코멘트 남깁니다.

파일의 끝에 newline이 남도록 IDE 설정을 변경하거나 ktlint 설정을 체크해보세요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitPolicy.kt
> +        }
reduce나 sum을 활용해서 불변으로 계산해볼 순 없을까요?

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/LottoAnswer.kt
> +class LottoAnswer(lottoAnswerNumberList: List<Int>) {
`List`라는 인터페이스에서 lottoAnswerNumberList가 `List`인 사실을 충분히 인지할 수 있기 때문에 뒤의 List 키워드는 제거되어도 괜찮다고 생각합니다. 이건 취향 차이일 수 있어 참고만 부탁드려요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +    val lottoTicketList = LottoTicketContainer()
로또라는 미션에서 봤을 때 Lotto는 Lotto 게임 한장으로 이해될 수 있지 않을까요?

LottoTicketList를 가지는 이 클래스의 이름이 Lotto가 적절할지도 한번 고민해보시면 좋을 것 같네요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/price/LottoTicketPrice.kt
> +}
개인적으론 LottoCost와 동일한 역할을 하고 있어서 하나의 클래스로 합치고 default ticket price를 기준으로 Cost를 생성하는 부분을 별도로 추출하거나 하면 어떨까 하는 생각이 드네요.

의미상 같이 사용해도 큰 문제는 없을 것 같고 오히려 중복으로 정의되어 있어서 혼란을 줄 수 있을 것 같아요.

2022-11-26 08:23 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/LottoAnswer.kt
> +    val lottoNumberList: List<LottoNumber>
지난주 당첨 번호를 나타내는 6개의 숫자도 `LottoTicket`일 수 있지 않을까요? LottoTicket을 이용해 중복을 제거할 수 있지 않을까요?

2022-11-26 11:48 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +): List<LottoTicket> by _list {
리뷰 감사합니다. 처음으로 `디미터의 법칙`을 알게되었습니다. 

덕분에 좋은거 배웠습니다.

![https://mangkyu.tistory.com/147](https://mangkyu.tistory.com/147)

2022-11-26 11:51 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +): List<LottoTicket> by _list {
일급 컬렉션 객체를 전반적으로 `delegation`을 통해서 컬렉션의 조회기능을 편하게 제공하는 것이 목표였습니다.

말씀대로 그런 기능들을 오픈해버리면, 다른 개발자가 추가 개발을 진행할 때 `디미터의 법칙`을 위반하는 코드가 추가될 수 있겠네요.

2022-11-26 11:56 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +    val lottoTicketList = LottoTicketContainer()
그냥 저는 단순히 Lotto를 구매한 한건에 대해서 클래스라고 생각하고 진행하였습니다.

그래서 이것이 중심으로 도메인로직이 흘러간다는 컨셉으로 생각을 했습니다. 

그래서 단순히 `Lotto`라고 명칭을 했는데, 

현업의 경험과 개인적인 생각으로 어떤 클래스명이 좋은지 조언해주시면  감사하겠습니다ㅠㅠ

2022-11-26 12:38 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitPolicy.kt
> +            6 to 2000000000
enum으로 해두는게 좋을거 같네요.

감사합니다.

2022-11-26 12:41 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +        }
mutableList를 사용한 이유는 랜덤으로 로또 티켓을 발급하는데, 동일한 숫자로 구성된 티켓이 있는 경우도 있어서
(shuffle메서드를 사용하다 보니)

외부적으로 add 메서드를 공개하지는 않고, 내부적으로 티겟 할당 개수를 받아서 초기화하는 방식으로 하였습니다.

1. 총 구매 비용
2. 티켓 1장당 가격

위 2개 파라미터를 받아서, Lotto 클래스를 생성하는 것으로 하였습니다.

2022-11-26 12:42 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/LottoAnswer.kt
> +    val lottoNumberList: List<LottoNumber>
당첨 번호도 LottoTicket클래스로 하면 됬지만,

우선 추상적인 개념으로 다른 역할을 할수도 있다고 생각해서, 따로 클래스를 두었지만,

말씀대로 기능이 겹치는게 많으므로,

1. 아예 같은 클래스 활용
2. 상속

위 2가지 방법이 있는거 같아서, 우선 상속을 시도해 보았습니다.

2022-11-26 12:45 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/price/LottoTicketPrice.kt
> +}
말씀하신 부분을 잘 이해를 못하겠어서 ㅠㅠ

코드 예시 조금만 들어주실수 있을까요?

2022-11-26 12:45 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +//        get() = _list.size
제거하였습니다.

2022-11-26 12:45 UTC, rolroralra commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        lottoResultView.printLottoResultView(lottoResult)
리뷰 반영해보았습니다.

2022-11-26 12:46 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitPolicy.kt
> +            6 to 2000000000
enum 클래스 하나 만들어보았습니다.

2022-11-26 12:51 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitPolicy.kt
> +        }
넵 변경하였습니다.

2022-11-26 12:52 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/LottoAnswer.kt
> +class LottoAnswer(lottoAnswerNumberList: List<Int>) {
넵. 감사합니다.

2022-11-26 12:53 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +    val lottoTicketList = LottoTicketContainer()
어떤 클래스 명이 좋을까요? 

저는 우선 이 클래스가 로또의 중심 클래스라고 생각을 해서, 

특별히 다른 클래스 명을 생각해보지 않았습니다.

경험상 클래스 네이밍 하는거에 대한 팁이 있으시면 조언부탁드립니다 ㅠㅠ

2022-11-26 14:28 UTC, rolroralra commented on src/main/kotlin/lotto/infra/io/LottoInputReader.kt
> +}
아 넵 감사합니다. 

intellij 에 설정을 안했었네요.

2022-11-26 14:29 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/ticket/LottoTicketContainer.kt
> +            .get()
넵 반영하였습니다.

2022-11-26 14:30 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/price/LottoCost.kt
> +}
리뷰 감사합니다 ㅠㅠ

2022-11-26 14:35 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/number/LottoNumber.kt
> +    }
리뷰 감사합니다.

반영하겠습니다.

2022-11-26 14:36 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/number/LottoNumber.kt
> +}
그러네요. 리뷰 감사합니다.

2022-11-28 13:03 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/price/LottoTicketPrice.kt
> +}
LottoCost와 LottoTicketPrice가 동일하게 0 이상의 값을 가지는 제약 조건을 해결하기 위한 클래스로 보이거든요. 그래서 두개를 하나로 쓰면 어떨까 하는 의견이었어요.

이렇게 되면 DEFAULT_LOTTO_TICKET_PRICE인 1000원을 기준으로 생성하는 부분이 애매해 질 수 있어서 그 부분에 대해서 추가 의견 남겨드린거에요~ 혹시 잘 이해가 안되시면 DM 주시면 답변해드리겠습니다!

2022-11-28 13:05 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

추가로 코멘트 하나 더 남겼고 이전에 남겨주신 코멘트에도 답변 달아두었어요. 확인하시고 다음 단계 진행에 참고 부탁드립니다.

https://github.com/next-step/kotlin-lotto/pull/496#discussion_r1033514949
https://github.com/next-step/kotlin-lotto/pull/496#discussion_r1033516094
https://github.com/next-step/kotlin-lotto/pull/496#discussion_r1033516572

2022-11-28 13:05 UTC, kyucumber commented on src/main/kotlin/lotto/domain/lotto/benefit/LottoBenefitLevel.kt
> +        }
enum이 늘어날 때 마다 when에 값을 추가해주어야 하는 단점이 있을 것 같아요.

요거 when 이 아니라 values()와 filter를 활용해볼 수 있을까요?

2022-11-28 13:05 UTC, merged

2022-11-29 09:42 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/LottoAnswer.kt
> +    val lottoNumberList: List<LottoNumber>
아 그러네요. Composition으로 하는게 좋을거 같네요.

코드리뷰 반영해서 다음 미션에 커밋하겠습니다.  감사합니다.

2022-11-29 09:43 UTC, rolroralra commented on src/main/kotlin/lotto/domain/lotto/Lotto.kt
> +    val lottoTicketList = LottoTicketContainer()
넵 아무래도 클래스 네이밍, 패키지 구조 등은 팀원들과 협업해야 되다 보니, 의견에 맞쳐서 정해야할 거 같습니다.