🔥 3단계 - 로또(2등)
next-step/kotlin-lotto pull request #509
Opened 2022-11-27 17:25 UTC by heedoitdox

안녕하세요! 영직님 🙂 
바쁘실텐데 항상 꼼꼼한 피드백 감사드려요 😙

이전에 남겨주신 피드백도 최대한 반영하여 3단계 구현해 보았습니다.
감사합니다 🫶

### 질문 사항
1. 코틀린 프로퍼티는 별도로 getter() 를 만들지 않아도 된다고 해주셨었는데요! 객체는 서로 메세지를 주고받기 때문에 단순한 getXXX() 메서드라도 만들어주는 것이 좋다고 피드백을 받은 적이 있습니다.. 취향의 영역인건가요..? 🤔🤔🤔🤔🤔 
2. 전단계 피드백에서 `그렇다면, Int 값 1 ~ 45가 아닌, LottoNumber에 대해 45개의 인스턴스만 유지하고 재활용하도록 하려면 어떻게 할 수 있을까요?` 라고 말씀해 주셔서 `LottoNumber` 를 이전에 구현했던 개념(6자리 로또) 과 다르게 object class 로 45개의 수를 모두 가지고 있도록 구현해보았습니다! 의도하신 바가 맞을까요? 
3. `LottoNumber` 와 `LottoNumbers` 역할이 겹친다는 느낌이 드네요. 개선할 수 있을까요..?
4. 전 단계에서 `WinningLottoNumbers` 의 존재여부에 대해서 질문주셨는데 리팩토링하면서 필요없음을 깨달았으나 이번 단계에서 보너스 볼의 개념이 생겨나면서 필요해 진 것 같습니다! 역할에 맞게 잘 분리한걸까요? 하핫.. 😀

2022-11-28 11:16 UTC, laco-dev requested changes
2등 미션 잘 해주셨습니다.

Lotto라는 새로운 객체를 만드는 과정에서 고민을 많이 하신 것 같은데
기존 역할과 구분이 잘 되지 않아 오히려 어색한 부분이 생겼습니다.

관련해서 피드백 같이 남겨드렸으니 확인 부탁드립니다.

2022-11-28 11:16 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    }
이 함수는 WinningStatistics를 반환해야 맞지 않을까요?

2022-11-28 11:16 UTC, laco-dev commented on src/test/kotlin/lotto/domain/RankTest.kt
> +        `when`("보너스 숫자가 일치하지만 4개 이하의 개수가 일치한다면") {
"보너스 숫자가 일치하지 않으면" 은 어떤지 궁금합니다!

여러개를 한번에 테스트 하는 방법을 사용한다면 테스트 이름도 연동되서 만들면 더욱 좋을 것 같습니다.

"보너스 숫자가 일치할 때, X개가 일치하면 Y등이다."
"보너스 숫자가 일치하지 않을 때, X개가 일치하면 Y등이다."

https://kotlintesting.com/kotest-parameterized/

혹은 이 방법이 애매하다면, 하나씩 테스트를 작성하는 것도 괜찮다고 생각합니다.
테스트코드 길이가 짧다고 해서 이해와 가독성이 꼭 좋은 편은 아닙니다.

2022-11-28 11:16 UTC, laco-dev commented on src/test/kotlin/lotto/domain/WinningStatisticsTest.kt
> +        )
테스트 코드 가독성 개선을 위해 Fake 생성 방식을 이용할 수 있습니다.

https://blog.kotlin-academy.com/item-30-consider-factory-functions-instead-of-constructors-e1c747fc475

예를 들어 위 코드를 아래와 비교하면 어떤가요?
```kotlin
val purchasedLotto = Lotto(21, 22, 23, 4, 5, 6)
val winningLotto = WinningLotto(21, 22, 23, 30, 31, 32)
val lottos = List(14) { DEFAULT_LOTTO } + purchasedLotto
...
```

2022-11-28 14:03 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/Rank.kt
> +                .firstOrNull { it.numberOfMatch == numberOfMatch } ?: MISS
헉..

2022-11-28 15:21 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/Rank.kt
> +                .firstOrNull { it.numberOfMatch == numberOfMatch } ?: MISS
find() 와 firstOrNull() 은 차이가 없어보입니다. 더 직관적이라 find() 가 많이 쓰이나요? 👀

2022-11-29 14:16 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +value class LottoNumber(val number: Int) {
좋은자료 감사합니다 🙂 상태와 행동 이해가 되었습니당!!

2022-11-29 15:22 UTC, heedoitdox commented on src/test/kotlin/lotto/domain/RankTest.kt
> +        `when`("보너스 숫자가 일치하지만 4개 이하의 개수가 일치한다면") {
확실히 테스트명과 테스트들이 좀 중구난방인 점이 있는 것 같네요 😅 
BehaviorSpec 에서 given,when,then 블록들의 장점도 잘 못살린 것 같구요..
개선해 보겠습니다!

2022-11-29 17:37 UTC, heedoitdox commented on src/test/kotlin/lotto/domain/WinningStatisticsTest.kt
> +        )
와 정말 좋은글이네요 👍👍👍👍 
더불어 이전단계에서 질문드렸던 정적팩터리메서드와 부생성자 중 어떤 것을 사용할까대한 정리도 되었어요!
(전자에 많은 비중이 실린 글이지만 😊)
잘 참고해서 개선해 보겠습니다!

2022-11-29 18:40 UTC, heedoitdox commented on src/test/kotlin/lotto/domain/WinningStatisticsTest.kt
> +        )
왜 미리 생각해보지 못했을까 통탄스럽습니다..

2022-11-29 19:09 UTC, heedoitdox commented
안뇽하세요 영직님! 
피드백해주신 것들 최대한 반영해 보았습니다..!

1~45 로또넘버의 대한 인스턴스 재활용은 로또자판기 `LottoVendingMachine` 가 하는 것이 맞을 것 같아 이동하고 
여러장의 로또 상태와 행동은 LottoNumbers 로 원복하고 새로 만들었던 `Lotto` 는 삭제했습니다...! 
추가적으로 좋은 자료들을 많이 남겨주셔서 도움이 많이 되었습니다 😊

2022-11-30 14:33 UTC, laco-dev approved these changes
좋습니다! 

훨씬 구조가 잘 들어오는 것 같아요. 👍🏻 
간단한 의견 몇가지 남겼으니 확인만 해 주시면 될 것 같습니다.

마지막 미션까지 화이팅입니다. 🎉

2022-11-30 14:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Rank.kt
> +                .firstOrNull { it.numberOfMatch == numberOfMatch } ?: MISS
아하, 네 find() 함수가 내부적으로 firstOrNull()을 사용하고 있습니다.
제 의도는 filter와 firstOrNull()을 두번 사용해서 불필요한 호출이 이뤄지지 않을까 싶었습니다...

아마 컬렉션 갯수가 적어서 취향의 영역이 될 수도 있기는 한데
양이 많아진다면 predicate 로직을 별도로 분리해서 사용하는 방법도 있기는 합니다.
```kotlin
val predicate: (Rank) -> Boolean =
    { it != SECOND && it.numberOfMatch == numberOfMatch } 
return Rank.values().find(predicate) ?: MISS
```

2022-11-30 14:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +            Pair(lottoNumbers.getNumberOfMatch(it), it.isMatchBonusLottoNumber(bonusLottoNumber))
마이너한 의견입니다.

Kotlin에서 Pair를 만들 때에는 A to B 형태로만드는게 조금더 친화적이기는 합니다.

2022-11-30 14:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        val ranks = matchResult.map { Rank.valueOf(it.first, it.second) }
matchResult의 First와 Second가 어떤 타입인지 코드로 볼 때는 추측이 어려운 감이 있는데요.
분해 선언이라는 방법을 이용하면 각각 변수를 할당할 수 있습니다.
```kotlin
matchResult.map { (matchedCount, isMatchedBonusNumber) -> Rank.valueOf(...)  }
```

2022-11-30 14:34 UTC, merged

2022-11-30 16:10 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/WinningLottoNumbers.kt
> +        val ranks = matchResult.map { Rank.valueOf(it.first, it.second) }
😱