Step2: 로또(자동)
next-step/kotlin-lotto pull request #511
Opened 2022-11-27 18:25 UTC by MyStoryG

안녕하세요. 리뷰어님!
step2 로또(자동) 리뷰 요청드려요. 잘 부탁드립니다!

2022-11-28 13:58 UTC, kyucumber requested changes
안녕하세요 몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/LottoTicket.kt
> +        }
while도 좋지만 shuffle과 take를 활용해서 6개의 로또 숫자를 만들어볼수도 있을 것 같네요~

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    }
메소드에서 바로 반환하기 때문에 인스턴스 변수로 대신 메소드 내 지역 변수로 선언해도 괜찮을 것 같아요.

가급적 불필요한 인스턴스 변수를 만들지 않도록 해보시면 좋을 것 같네요.

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +            resultView.showLottoTicket(lottoTickets[i].getLottoTicketNumbers())
MutableList를 사용하지 않고 `(0..quantity).map { }`와 같은 형태로 불변 컬렉션을 활용해보세요.

아래 글도 한번 읽어보세요.

[이펙티브 코틀린 아이템 01. 가변성을 제한하라](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-01/#%EA%B0%80%EB%B3%80-%EC%BB%AC%EB%A0%89%EC%85%98%EA%B3%BC-%EC%9D%BD%EA%B8%B0-%EC%A0%84%EC%9A%A9-%EC%BB%AC%EB%A0%89%EC%85%98-%EA%B5%AC%EB%B6%84%ED%95%98%EA%B8%B0)

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/LottoTicket.kt
> +    }
TicketStrategy 인터페이스와 getLottoTicketNumbers 메소드의 override는 어떤 이점을 가지고 있을까요? 단순히 가진 숫자를 반환하는거라면 인터페이스를 통한 추상화가 불필요해보여요.

현재 테스트에서 반환하는 숫자를 다르게 가져가는 것 이외에 장점이 없는 것 같아요. 테스트를 위한 코드처럼 느껴지네요.

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/WinnerNumber.kt
> +class WinnerNumber(input: String) {
로또 당첨 번호 또한 1-45 사이의 6개의 숫자를 가지는 동일한 특성을 가지고 있어요.

`LottoTicket`과 코드가 조금 중복된다는 생각이 드는데요 `LottoTicket`을 활용해 중복을 제거하는 구조를 가질 순 없을까요?

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/WinningCalculator.kt
> +    }
enum 등을 활용해 당첨 결과에 대한 정보를 명확히 드러내면 어떨까요?

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/WinningCalculator.kt
> +                        resultWinningStatistics.matchSix * MATCH_SIX
이 부분도 enum을 활용하고 반복문을 통해 개선해보시면 좋을 것 같네요.

2022-11-28 13:58 UTC, kyucumber commented on src/main/kotlin/lotto/model/WinningStatistics.kt
> +data class WinningStatistics(var matchThree: Int, var matchFour: Int, var matchFive: Int, var matchSix: Int, var rate: Double)
Map(`Map<Enum, Int>`)과 같은 자료구조를 활용해보아도 좋을 것 같습니다.

2022-11-28 13:58 UTC, kyucumber commented on src/test/kotlin/lotto/LottoTest.kt
> +internal class LottoTest {
테스트를 잘 작성해주셨네요, 다만 각각의 클래스별로 나누어 단위 테스트를 작성해보시면 좋을 것 같아요.

- LottoTicketTest
- TicketQuantityTest
- WinnerNumberTest
- ...

2022-12-12 13:45 UTC, kyucumber requested changes
안녕하세요

피드백 잘 반영해주셨습니다. 몇가지 코멘트 더 남겨두었으니 확인 부탁드려요~

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +    }
요건 validRange를 통해 검증되는 부분일 것 같아요. 도달할 수 없는 코드로 보이네요~ 제거하면 어떨까요?

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +class LottoNumber(input: String) {
이 클래스도 테스트를 작성해주시면 좋을 것 같네요!

46을 넣었을 때 "1에서 45 사이의 값을 입력하세요." 예외 메시지가 잘 나오는지 등을 검증해보세요.

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +    override fun hashCode(): Int = number.hashCode() * 31
equals나 hashCode를 별도로 정의하셨네요. 코틀린의 data class를 활용해보셔도 좋을 것 같아요. data class는 equals, hashCode를 자동으로 만들어줘요.

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/model/Rank.kt
> +        }
!!를 사용해서 결과가 없는 경우 NPE가 발생하는 것 보다는 어떤 값으로 인해 예외가 발생했는지 별도로 예외 메시지를 남겨주시면 좋을 것 같아요~

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/model/WinningCalculator.kt
> +        mutableMapOf(
groupBy 등을 활용하시면 mutableMap을 사용하지 않고도 결과를 도출할 수 있을거에요. 불변한 map을 이용해 결과를 구해보세요.

2022-12-12 13:45 UTC, kyucumber commented on src/main/kotlin/lotto/view/ResultView.kt
> +        println("6개 일치 (2000000000원)- ${result.ranks[Rank.FIRST]}개")
Map.entry를 이용해 반복문을 사용하고 Rank에 담긴 당첨 개수, 금액을 이용해 하드코딩과 중복을 줄여볼 수 있지 않을까요?

2022-12-13 13:23 UTC, MyStoryG commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +    }
그렇네요! 제거 하겠습니다!

2022-12-13 13:25 UTC, MyStoryG commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +    override fun hashCode(): Int = number.hashCode() * 31
그렇네요! 제가 굳이 할 필요가 없었네요. 😂

2022-12-14 11:54 UTC, kyucumber approved these changes
몇가지 코멘트 남겨두었습니다.

다음 단계에 꼭 반영해주세요.

다음 단계 진행을 위해 머지하겠습니다.

2022-12-14 11:54 UTC, kyucumber commented on src/main/kotlin/lotto/model/Rank.kt
> +            return selectedRank
try catch를 활용해 이렇게 하시기 보다는 null safe operator, elvis operator 등을 활용해보세요.

2022-12-14 11:54 UTC, kyucumber commented on src/main/kotlin/lotto/view/ResultView.kt
> +        }
for loop의 3..6과 같이 쓰지 않고 result 안에 결과가 포함되어 있으니 그 부분을 활용해볼 수 있지 않을까요?

2022-12-14 11:54 UTC, merged

2022-12-18 16:12 UTC, MyStoryG commented on src/main/kotlin/lotto/model/WinningCalculator.kt
> +        }
넵! 어떤 값으로 인해 예외가 발생했는지 별도로 예외 메시지를 남기면 좋겠다는 말씀에 단순히 순간 떠오른 방법이 단순히 try catch 였네요. 🥲