4단계 - 로또(수동)
next-step/kotlin-lotto pull request #520
Opened 2022-11-29 11:39 UTC by leedo1982

코드리뷰 해주신대로 캐시를 구현했는지 확신이 없네요 :) 

코드리뷰 감사합니다 ~

2022-11-30 09:00 UTC, ddaaac requested changes
안녕하세요 도원님 👋 

4단계도 큰 변화없이 잘 구현해주셨습니다 💯 

몇 가지 코멘트를 남겼으니 확인 부탁드려요!

2022-11-30 13:18 UTC, leedo1982 commented on src/main/kotlin/lotto/model/RandomLottoNumberGenerator.kt
> +private const val LOTTO_SIZE = 6
하나의 const 만 사용하도록 수정하겠습니다 :)

2022-11-30 13:19 UTC, leedo1982 commented on src/test/kotlin/lotto/model/LottoGradeTest.kt
> +            val (correctNumber, grade) = it
넵, 해당방법 사용하도록 하겠습니다

2022-11-30 13:38 UTC, leedo1982 commented on src/main/kotlin/lotto/model/LottoGame.kt
> +        repeat(lottoAmount / LOTTO_PER_AMOUNT - directNumbers.size) {
넵, 포장해보겠습니다 ㅎ

2022-11-30 13:44 UTC, leedo1982 commented on src/main/kotlin/lotto/model/LottoGame.kt
> +        lottos.addAll(directNumbers)
네, 변경해보겠습니다

2022-12-02 10:38 UTC, ddaaac requested changes
안녕하세요 도원님 👋 

리뷰 반영 잘 해주셨어요! 이대로 머지해도 될 것 같은데 조금 더 얘기해보고 싶은 부분이 있어서 리뷰 반영 요청 드립니다.

확인해보시고 코멘트 주세요~

2022-12-02 13:14 UTC, leedo1982 commented on src/main/kotlin/lotto/model/LottoGame.kt
> +        repeat(lottoAmount.amount / LOTTO_PER_AMOUNT - directNumbers.size) {
좋은 방법인거 같습니다 :) 수정하겠습니다

2022-12-02 13:20 UTC, leedo1982 commented on src/main/kotlin/lotto/LottoGameController.kt
> +            lottoGame.draw(winningNumber, LottoNumber.valueOf(plusNumber))
해당 내용에대해 깊이 생각안하고 사용했었는데, 뭔가 기준이 있는게 사용에 명확하고 이해하기 좋을꺼 같네요~
수정해보겠습니다

2022-12-02 13:23 UTC, leedo1982 commented on src/main/kotlin/lotto/model/LottoGame.kt
>      }
init 의 순서가 좀더 명확하게 이해되었습니다. 수정하겠습니다

2022-12-02 13:57 UTC, leedo1982 commented on src/main/kotlin/lotto/model/LottoGame.kt
>      }
LottoGame 를 만들때, 살짝 즉석복권의 상상을 하면서 구현했었는데요.
내가 복권을 구매해서, 그 복권을 긁는거 까지... 긁는 역할을 남에게 주면 복권의 재미가 없으니깐..ㅎ(응집도가 낮아진다고 생각했어요ㅎ)
그래서 복권을 구매해서, 긁는거까지 한 객체에서 진행했습니다

추가적으로 궁금한게 있는데요. 
하나의 클래스에 하나의 책임만 가져야 한다는 의미로 말씀하신 걸까요?
이렇게 역할들이 쪼개지면  응집도가 너무 낮아지진 않을까요? 
가 궁금해요 :) 

리뷰 감사합니다

2022-12-04 12:00 UTC, merged