🔥 4단계 - 로또(수동)
next-step/kotlin-lotto pull request #538
Opened 2022-12-04 13:50 UTC by heedoitdox

안녕하세요! 영직님🙂 드디어 마지막 단계 PR을 올리게 되었습니다....⛳️
이번주차 강의를 들으면서 영직님께서 해주셨던 피드백들이 어떤말이었는지 깨달은 부분들이 많아요
항상 좋은 피드백 주셔서 감사합니다! 😊

2022-12-05 11:28 UTC, laco-dev requested changes
4단계 미션 잘 해주셨습니다.

그동안 여러가지 고민하시면서 개선한 결과, 조금 더 자연스럽게 미션을 진행하실수 있던 것 같습니다.

일급 컬렉션이나 다른 개념들도 적용 해 보셨는데, 관련해서 몇가지 의견 남겨드렸습니다. 🙏🏻

2022-12-05 11:28 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
로또 번호 인스턴스 재활용 👍🏻

2022-12-05 11:28 UTC, laco-dev commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val userLottos = manualUserLottos.addAll(randomUserLottos)
지금은 로또를 만드는 방법이 InputView, VendingMachine 등 여러군데에서 분산이 되어 있어요.
로또 머신에게 적절한 메시지를 보내 비즈니스 로직을 안으로 숨겨보면 어떨까요?

```kotlin
val lottos: UserLottos = LottoVendingMachine.buyLottos(purchaseAmount, manualLottoNumbers)
```

2022-12-05 11:28 UTC, laco-dev commented on src/main/kotlin/lotto/domain/UserLottos.kt
> +    fun add(lottoNumbers: LottoNumbers): UserLottos {
불변 형태의 일급 컬렉션으로 사용하기 때문에 _lottos라는 컬렉션이 가변으로 만들어지지 않아도 될 것 같습니다.

```kotlin
fun add(lottoNumbers: LottoNumbers) : UserLottos {
   return UserLottos(lottos + lottoNumbers)
}

fun addAll(lottos: List<LottoNumbers>): UserLottos {
   return UserLottos(this.lottos + lottos)
}
```

2022-12-05 11:28 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
4단계 미션 프로그래밍 요구사항에 있듯이, 가급적 오류를 발생시키지 않고, 적절한 반환 형태를 고민 해 보면 어떨까요?

예를 들어 로또를 구매할 수 없는 가격이 주어진다면 구매가능한 수동 로또의 갯수는 0개라고 볼 수 있을 것 같아요.

2022-12-05 11:28 UTC, laco-dev commented on src/main/kotlin/lotto/domain/PurchaseAmount.kt
> +    fun canBuyNumberOfLotto(count: Int) = count < getNumberOfLotto()
count로 음수가 들어와도 항상 구매가 가능하다고 판단하지 않을까요?

2022-12-05 15:18 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/UserLottos.kt
> +    fun add(lottoNumbers: LottoNumbers): UserLottos {
엇 안그래도 이부분 제가 깜빡하고 질문을 못드렸네요 
리뷰요청 전에 아래와 같이 테스트 코드로 확인해 보니 처음 선언하여 반환된 인스턴스랑 추가한 인스턴스랑 사이즈가 똑같더라구요 
첨부해 주신 코드로 테스트 해보니 잘 통과되네요...
```kotlin
 "불변 컬렉션 테스트" {
        val userLotto = UserLottos()
        val addUserLotto = userLotto.add(lottoNumberOf(1, 2, 3, 4, 5, 6))
        userLotto.lottos.size shouldBe 0
        addUserLotto.lottos.size shouldBe 1
    }
```
이번주차 강의에서 방어적 복사를 설명하시면서 제이슨께서 샘플코드를 작성해주셨었는데요 
(빨간박스는 제가 노트용으로 표시한 것이기때문에 무시하셔도 됩니다!)
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/73086575/205670989-3813b879-0340-45c1-86a6-adc47bc43018.png">
이 경우에 외부에서 cars.add() 를 하는 경우를 막기 위해서라고 이해했습니다. 
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/73086575/205671996-3ee7089d-fef2-4d72-a54c-9ed6d13c1f1f.png">
그렇다면 다시 로또로 돌아오면
이게 ... `LottoNumbers` 에 대해서는 가변할 일이 없기 때문에 (로또 번호가 6개에서 더이상 추가될 일이 없다) 
요런 backing properties 전략 사용없이 _lottos 컬렉션의 선언도 필요없게 된 것일까요?

질문이 좀 길었는데
강의를 들을 때는 저렇게 불변 객체로 만드는 구나 라고 이해했었는데 제가 잘못 이해한 부분이 있는 것 같습니다... 🥸😓

2022-12-05 15:20 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
😭

2022-12-05 16:04 UTC, heedoitdox commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
제가 이 요구사항을 빠뜨렸네요! 반영하겠습니다.

2022-12-05 16:04 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/PurchaseAmount.kt
> +    fun canBuyNumberOfLotto(count: Int) = count < getNumberOfLotto()
😱

2022-12-05 17:26 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/PurchaseAmount.kt
> +    fun canBuyNumberOfLotto(count: Int) = count < getNumberOfLotto()
위 사항을 반영하니 해당 메서드는 자연스레 지워졌네요 🙃

2022-12-06 04:12 UTC, laco-dev commented on src/main/kotlin/lotto/domain/UserLottos.kt
> +    fun add(lottoNumbers: LottoNumbers): UserLottos {
강의 엄청 열심히 들으셨군요... 👍🏻 

backing properties 전략은 외부에서 내부의 상태를 변경하는 것을 막기 위한 전략입니다.
UserLottos가 가지고 있는 공개 인터페이스가 모두 UserLottos를 반환하기 때문에 항상 다른 인스턴스를 반환하게 됩니다.
즉, 내부적으로 정의해둔 _lottos가 아무런 사용이 되고 있지 않다는 의미라서 불필요하다고 생각했습니다.

불변객체를 활용하는 것은 이펙트를 없앨 수 있는 좋은 방법이지만 코드가 복잡해진다는 트레이드 오프를 가집니다.

2022-12-06 04:33 UTC, laco-dev requested changes
피드백 잘 반영 해주셨습니다.

Main함수와 로직이 섞여 있어서 컨트롤러를 만들어봐도 괜찮을 것 같다는 생각이 들기도 합니다!
질문주신 내용에 대한 답변과 같이 몇가지 추가적으로 남겨보았습니다. 🙏🏻

2022-12-06 04:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +    }
요구사항이 변경되면서 이 함수는 더이상 사용이 되지 않아요.
LottoVendingMachine에게 불필요한 책임이 될 수 있으니, 변경에 따라 같이 지워주시면 됩니다!

2022-12-06 04:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +        return WinningLottoNumbers(lottoNumbers = lottoNumbers, bonusLottoNumber = bonusLottoNumber)
> 보너스 번호는 당첨 번호와 중복되지 않아야 한다

오류를 발생시키지 않는 방법으로는 여러가지가 있기는 합니다.

1. sealed class로 만들어서 타입을 나누기 
```kotlin
sealed class WinningLotto {
   data class Valid(...): WinningLotto
   object Invalid : WinningLotto
}
```
2. Result 타입으로 만들기
```kotlin
fun makeWinningLotto(...): Result<WinningLotto>
```

하지만 저는 위 케이스는 명확한 논리적인 오류라서, 예외를 발생시키는 것이 가장 적합하다고는 생각이 들어요.

---
마이너한 다른 의견인데, 로또 머신이 UserLottos를 반환하는 역할을 하고 있어서 WinningLottoNumbers를 만드는 것은 WinningLottoNumbers에서 스스로 해도 되지 않을까요? 
둘이 협력 관계라고는 잘 느껴지지 않습니다 🤔 

```kotlin
val winningLottoNumbers = WinningLottoNumbers.from(...)
```

2022-12-06 04:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +        }
로또번호들을 만드는 방법이 반복되고 있어서 LottoNumbers에게 생성 책임을 넘겨봐도 좋을 것 같아요

2022-12-06 04:33 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getBonusNumber(): Int {
따로 답변을 다는곳이 애매해서 이쪽에 같이 남겼습니다!

> 다시 입력받게 하도록 수정하고 싶었거든요...

InputVIew에서 예외를 처리한다는 사실 자체가, 어떠한 로직을 가진다는 의미로 볼 수도 있어요.
단순히 InputView는 입력에 대한 처리만 수행하도록 만드는 것이 좋을 것 같습니다

다시 숫자를 받기 위한 로직을 Main 함수가 아닌 자동차 경주에서 진행한 컨트롤러 개념에서 처리를 할 수도 있을 것 같아요!

2022-12-07 16:21 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +        return WinningLottoNumbers(lottoNumbers = lottoNumbers, bonusLottoNumber = bonusLottoNumber)
저는 자판기는 로또번호를 만든다.. 로또 객체를 만든다..? 라는 관점에서 생성하는 역할은 다 자판기가 해주면 좋을 것 같다고 생각해서 역할을 옮긴 것인데 영직님 피드백대로 협력 관계.. 라고 생각해보니 의문스러운 위치에 있는 것 같긴하네요.. 흠..
아직 협력하는 객체들의 대한 이해가 어려워요 😭

2022-12-07 17:00 UTC, heedoitdox commented on src/main/kotlin/lotto/domain/UserLottos.kt
> +    fun add(lottoNumbers: LottoNumbers): UserLottos {
오! 이해했습니다! 제가 위 전략을 적용한 예가 강의에서랑은 다른 상황이었던 것 같네용! 
외부에서도 애초에 불변 객체 밖에 줄 수 없다면 내부의 상태도 변경될 수 없지만 가변객체를 전달해버렸을 때 방어하기위해 사용하는 전략이군요..?
간단한 테스트로 이해했네요....
```kotlin
internal class FooTest: StringSpec({
    "불변 객체 테스트" {
        val list = listOf(1,2,3,4,5)
        val foo = Foo(list)

        foo.value.size shouldBe 5
        list.toMutableList().add(7)
        foo.value.size shouldBe 6 // 실패
        list.toMutableList().add(8)
        foo.value.size shouldBe 7 // 실패
    }
})
```
위 테스트는 두번째 조건부터 실패합니다.
저는 중간에 mutableList 로 바꿔서 add 하면 고대로 반영되어서 불변이 깨질거라고 예상했거든요!
그런데 애초에 가변객체로 인스턴스를 만드니 뒤에서 어떤 변화를 줘도 가변이 되지 않는군요..!
그리고 코틀린에서는 기본적으로 안전한 코딩을 하다보니 왜 불변객체를 만들어야하고 왜 예상치 못한 곳에서 가변이 일어날 수 있는지를 생각하지 못했던 것 같습니다. 😂
혼자서 끄적여 봤습니당 ! ㅎㅎ

2022-12-07 17:01 UTC, heedoitdox commented
> backing properties 전략은 외부에서 내부의 상태를 변경하는 것을 막기 위한 전략입니다. UserLottos가 가지고 있는 공개 인터페이스가 모두 UserLottos를 반환하기 때문에 항상 다른 인스턴스를 반환하게 됩니다. 즉, 내부적으로 정의해둔 _lottos가 아무런 사용이 되고 있지 않다는 의미라서 불필요하다고 생각했습니다.
> 
> 불변객체를 활용하는 것은 이펙트를 없앨 수 있는 좋은 방법이지만 코드가 복잡해진다는 트레이드 오프를 가집니다.

오! 이해했습니다! 제가 위 전략을 적용한 예가 강의에서랑은 다른 상황이었던 것 같네용! 
외부에서도 애초에 불변 객체 밖에 줄 수 없다면 내부의 상태도 변경될 수 없지만 가변객체를 전달해버렸을 때 방어하기위해 사용하는 전략이군요..?
간단한 테스트로 이해했네요....
```kotlin
internal class FooTest: StringSpec({
    "불변 객체 테스트" {
        val list = listOf(1,2,3,4,5)
        val foo = Foo(list)

        foo.value.size shouldBe 5
        list.toMutableList().add(7)
        foo.value.size shouldBe 6 // 실패
        list.toMutableList().add(8)
        foo.value.size shouldBe 7 // 실패
    }
})
```
위 테스트는 두번째 조건부터 실패합니다.
저는 중간에 mutableList 로 바꿔서 add 하면 고대로 반영되어서 불변이 깨질거라고 예상했거든요!
그런데 애초에 가변객체로 인스턴스를 만드니 뒤에서 어떤 변화를 줘도 가변이 되지 않는군요..!
그리고 코틀린에서는 기본적으로 안전한 코딩을 하다보니 왜 불변객체를 만들어야하고 왜 예상치 못한 곳에서 가변이 일어날 수 있는지를 생각하지 못했던 것 같습니다. 😂
혼자서 끄적여 봤습니당 ! ㅎㅎ

2022-12-07 17:10 UTC, heedoitdox commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getBonusNumber(): Int {
> InputVIew에서 예외를 처리한다는 사실 자체가, 어떠한 로직을 가진다는 의미로 볼 수도 있어요.
맞아요 저도 InputView 에서는 UI 기능만 딱 깔끔하게 있었으면 했는데 main 함수가 더 길어질 것이냐 라는 고민에서 InputView 에서 처리를 했던 것 같네요.. 사실 영직님 말씀대로 컨트롤러 개념으로 처리하고 메서드로 좀 분리하는게 맞았을 것 같네요 좋은 의견 감사합니다!

2022-12-08 10:35 UTC, laco-dev approved these changes
피드백 반영 잘 해주셨습니다.

아직은 잘 이해가 되지 않고 어려운 부분이 많이 있으실텐데요.
이번 전체 과정들을 통해서, 앞으로 개발할때 조금씩 생각났던 개념들을 생각하는 것만으로도 많은 도움이 되실 것 같습니다.

로또 미션 고생 많으셨고, 다음 미션들도 화이팅입니다. 👍🏻

2022-12-08 10:35 UTC, merged