2단계 - 로또(자동)
next-step/kotlin-lotto pull request #548
Opened 2022-12-11 12:31 UTC by jaeykweon

2단계 - 로또(자동) 리뷰 부탁드립니다

테스트를 어떻게 해야할 지 모르는 부분은 작성하지 못했습니다.

질문사항은 코멘트로 남겨놓겠습니다

감사합니다.

2022-12-12 06:20 UTC, jaeykweon commented on src/main/kotlin/lotto/view/OutputViewImpl.kt
> +    }
이 경우 티켓 개수를 직접 입력받아서 출력만 하는게 맞을까요
아니면 UnusedTickets를 입력받아 getTicketCount() 메소드를 여기서 호출하는게 맞을까요?

2022-12-12 06:32 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
여기가 고민이었던 것이, 티켓 가격을 입력받자니 어디서 그 가격을 받아와야하는지가 고민이었습니다
컨트롤러에서 호출하게될텐데 어디서 받아와서 해야할지 모르겠습니다

2022-12-12 06:40 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/LottoUnusedTicket.kt
> +class LottoUnusedTicket {
추후 수동 생성을 위해 나름 확장성을 고려하여 만든 클래스입니다...

2022-12-12 13:55 UTC, hyunniiii requested changes
안녕하세요 재용님.
미션 구현 잘 해주셨습니다!
몇가지 코멘트 남겼으니 확인부탁드립니다 : )

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/Cash.kt
> +    )
현금이 숫자가 아니라면 게임 진행에 문제가 되는 부분이니 Cash 클래스 내부보다는 현금을 입력받는 부분에서 해주는게 좋을 것 같습니다.

Cash 부분에서는 `천원 단위가 아닐 때` 이럴 경우에 대해 체크해줄 수 있을 것 같습니다!

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
이 부분은 View 에 있어야할 것 같아요 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/Cash.kt
> +        return Cash(value % TICKET_PRICE) to LottoUnusedTickets.from(ticketCount)
`Cash` 객체에서 로또 객체를 생성해주는 책임은 없어도 되지 않을까요 ? :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    }
```suggestion
    fun matches(inputNumbers: LottoNumbers): Int {
         return numbers.count{
			number -> inputNumbers.numbers.contains(number)
	    }
    }
```

count를 이용해도 괜찮을 것 같습니다 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoRewards.kt
> +    }
이것도 view 부분에 관한 것 같습니다 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoUnusedTicket.kt
> +class LottoUnusedTicket {
`toAuto()` , `toManual()`을 의도하신걸까요?

아직 이 클래스의 용도를 잘 모르겠습니다. 
수동 로또 부분에서 추가해주는게 어떨까요?

현재는 `LottoUnusedTicket, LottoUsedTicket` 등으로 클래스가 과하게 분리되어 있어 코드를 파악하기 쉽지 않은 것 같습니다 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/view/InputViewImpl.kt
> +object InputViewImpl {
`Impl` 이라는 이름을 사용해주신 이유는 무엇일까요?
`Impl`은  자바의 옛 관습이라고 볼 수 있을 것 같습니다. 
여기에서는 `Impl`을 제거해줘도 괜찮을 것 같아요 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/view/OutputViewImpl.kt
> +    }
이 부분은 inputView 쪽에 티켓을 구매하고 바로 출력해줘도 될 것 같아요 :)

2022-12-12 13:55 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
이 부분은 수익률을 위한 부분인 것 같습니다.
이게 `Cash` 객체에 있어야 할 책임인지 고민해보면 좋겠습니다 :)

2022-12-16 13:33 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
이 부분을 제외하고 리뷰 주신 내용 모두 반영하였습니다
수익률 클래스를 따로 만들어야할지 고민이 듭니다
수익률을 계산하기 위해서는 cash 클래스를 거쳐야만 할텐데
cash 객체 내부에서 처리하는게 아니라면 어떻게 해야할지 잘 모르겠습니다 ㅠㅠ

2022-12-19 04:46 UTC, hyunniiii approved these changes
안녕하세요 재용님!
리뷰가 늦어서 죄송합니다 😭 
몇가지 코멘트 남겼으니 다음 미션과 함께 반영 부탁드립니다!

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
`Cash`는 `로또 게임을 진행하기 위해 넣는 돈` 을 의미하는 것 같아요.
`보상금`과 ` 게임을 진행하기 위한 돈`에 대한 부분은 하나의 클래스를 사용하는 것이 아닌 따로 분리해주는게 맞을 것 같아요 :)

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +            inputNumbers.numbers.contains(number)
이 부분은 `LottoNumbers` 에서 메시지를 던져주도록 수정할 수 있을 것 같아요 :)

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        }
```suggestion
	fun from(): LottoNumbers {
		return LottoNumbers(LOTTO_NUMBERS.shuffled()
			.take(6)
			.sorted()
			.map { number ->
				LottoNumber(number)
			}
		)
	}
```

한번에 초기화 해줄 수 있습니다 :)

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        fun from(input: String): LottoNumbers {
여기도 위와 동일하게 변경 가능할 것 같아요 :)

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        }
이 부분은 Cash 클래스 내부에서 확인해주는 것 같아보여요 :)  
다시 한번 작성해줄 필요가 없는 것 같습니다.

2022-12-19 04:46 UTC, hyunniiii commented on src/main/kotlin/lotto/domain/LottoUnusedTickets.kt
> +data class LottoUnusedTickets(
`UnusedTicket` 과 `UsedTicket` 클래스가 하는일이 모호해보입니다.

결과를 확인한 티켓, 결과를 확인하지 않은 티켓 을 의미하는걸까요?
그렇다면 두가지 클래스로 분리했을때의 장점이 무엇이 있는지 고민해보면 좋을 것 같아요 :)

2022-12-19 04:46 UTC, merged

2022-12-20 16:50 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        }
step3에 적용하였습니다

2022-12-20 16:50 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        fun from(input: String): LottoNumbers {
step3에 적용하였습니다

2022-12-20 16:50 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        }
중복 확인하여 step3에서 제거하였습니다

2022-12-20 16:52 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/LottoUnusedTickets.kt
> +data class LottoUnusedTickets(
두 클래스로 분리했을때 장점은 추후 자동 입력과 수동 입력에 굉장히 유연하게 대처할 수 있다는 점인거 같습니다
우선 로또 구매로 unusedTicket을 준비하고 원하는 개수만큼만 수동, 자동으로 나눠주면 됩니다

2022-12-20 16:53 UTC, jaeykweon commented on src/main/kotlin/lotto/domain/Cash.kt
> +    }
따로 분리하였을때 수익률은 어떻게 계산해야할지 감이 오지않습니다
어찌되었든 초기 금액의 값이 필요할텐데, 다른 클래스로 분리하였을때 어느쪽에서 어떻게 계산해주어야할지 모르겠습니다..