[Step4] 로또(수동)
next-step/kotlin-lotto pull request #553
Opened 2022-12-12 15:45 UTC by namonak

2022-12-12 15:49 UTC, namonak commented
@YooInKeun 리뷰어님,

4단계 - 로또(수동) PR 요청드립니다! 혹독한 리뷰 부탁드리겠습니다 🙇

2022-12-15 02:38 UTC, YooInKeun requested changes
4단계 미션 진행하시느라 고생 많으셨습니다~ 👍 
몇가지 피드백 남겼으니 확인해주시고 재요청 부탁드려요 🙇‍♂️ 
로또 미션 얼마 남지 않았네요~
좀만 더 화이팅입니다 🔥 🔥

2022-12-15 02:38 UTC, YooInKeun commented on src/test/kotlin/lotto/domain/ManualLottoCountTest.kt
> +class ManualLottoCountTest {
수동 로또 개수가 0 미만인 경우에 대해 예외 테스트를 추가해주면 좋겠네요~

2022-12-15 02:38 UTC, YooInKeun commented on src/main/kotlin/lotto/application/LottoGenerator.kt
> +        return Lotto(LottoNumber.lotto.shuffled().take(MAXIMUM_LOTTO_NUMBER_LENGTH).sortedBy { it.value })
적절한 줄바꿈으로 가독성을 신경 써주시면 더욱 좋을 거 같아요~

2022-12-15 02:38 UTC, YooInKeun commented on src/main/kotlin/lotto/domain/WinningNumbers.kt
> +    fun getLottoRank(lotto: Lotto): LottoRank {
getXXX 이라는 네이밍은 getter 의 느낌이 드는데, 로직은 뭔가 계산하고 찾아내는 기능들이 정의되어 있네요~
이에 맞게 네이밍을 정의해보는 것은 어떨까요~?

2022-12-15 02:38 UTC, YooInKeun commented on src/test/kotlin/lotto/domain/LottosTest.kt
> +        val lotto = Lotto(listOf(LottoNumber.from(1), LottoNumber.from(2), LottoNumber.from(3), LottoNumber.from(4), LottoNumber.from(5), LottoNumber.from(6)))
테스트 코드도 중복을 의식하면서 리팩토링 해주면 좋을 거 같은데요~
다음과 같이 간결하게 바꿔줄 수도 있겠네요!

```suggestion
        val lotto = Lotto(listOf(1, 2, 3, 4, 5, 6).map { LottoNumber.from(it) })
```

2022-12-15 15:06 UTC, namonak commented on README.md
> +## 4단계 - 로또(수동)
칭찬해 주셔서 감사합니다! 리뷰어님의 꼼꼼한 리뷰 덕분입니다~ 😄

2022-12-17 04:40 UTC, namonak commented on src/main/kotlin/lotto/domain/ManualLottoCount.kt
> +        require(lottoCount >= manualLottoCount) { "수동으로 구매할 로또 수는 구매 금액을 초과할 수 없다." }
네, 조언해 주신대로 `ManualLottoCount` 객체 생성시에 음수 값에 대한 예외 처리 기능을 추가해 보았습니다 😃
확인 부탁드립니다 🙏

- https://github.com/next-step/kotlin-lotto/commit/858e9e385b1fbf081b35eb110552ab307ff11db0

2022-12-17 04:43 UTC, namonak commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val _lotto = MutableList(MAXIMUM_LOTTO_NUMBER) { LottoNumber(it + MINIMUM_LOTTO_NUMBER) }
칭찬해 주셔서 감사합니다 😄 지난번 온라인 강의때, 백킹 프로퍼티에 대한 내용이 있어서 이 부분을 활용해 보았습니다. (완전히 같은 경우 인지는 모르겠네요... 😃)

2022-12-17 04:45 UTC, namonak commented on src/test/kotlin/lotto/domain/ManualLottoCountTest.kt
> +class ManualLottoCountTest {
세세한 부분 까지 확인해 주셔서 감사합니다 😄
https://github.com/next-step/kotlin-lotto/pull/553#discussion_r1049119980 코멘트 주신 내용 수정하면서, 이 부분도 같이 수정해 보았습니다. 확인 부탁드립니다 🙏 

- https://github.com/next-step/kotlin-lotto/commit/858e9e385b1fbf081b35eb110552ab307ff11db0 , src/test/kotlin/lotto/domain/ManualLottoCountTest.kt

2022-12-17 05:17 UTC, namonak commented on src/test/kotlin/lotto/domain/LottosTest.kt
> +        val lotto = Lotto(listOf(LottoNumber.from(1), LottoNumber.from(2), LottoNumber.from(3), LottoNumber.from(4), LottoNumber.from(5), LottoNumber.from(6)))
오... 좋은 팁 감사합니다! 🙏 테스트 코드 작성 중 `Lotto` 객체 생성시에 복수의 `LottoNumber` 객체를 생성하는 부분의 코드가 지저분해 마음이 쓰였는데요. 리뷰어님 코멘트를 보니 이 부분이 정리가 되었습니다! 😃

- https://github.com/next-step/kotlin-lotto/commit/5763d8a2b29f92e048e9b913030bf3ee86e53dd2 , https://github.com/next-step/kotlin-lotto/commit/4b355df2b00a43f5bd6b45bed1158b1e7f98d71c

추후 도전 과제를 진행하면서도 이 부분 꼭 기억해 두겠습니다! 감사합니다 🙏

2022-12-17 05:40 UTC, namonak commented on src/main/kotlin/lotto/domain/WinningNumbers.kt
> +    fun getLottoRank(lotto: Lotto): LottoRank {
네이밍 컨벤션을 준수하는 습관은 하루 아침에 바뀌기 정말 어려운것 같네요 😭과제를 진행하면서 컨벤션 관련 코멘트를 많이 남겨주셨는데, 아직도 부족하네요 😭

말씀해 주신대로 해당 메서드에 getXXX 네이밍은 어울리지 않는것 같습니다 😢
find, to 두가지를 목록에 두고 고민해 보다가... find는 데이터를 조회하는 의미가 있는것으로 생각되었고, to는 해당 객체를 다른 객체로 변경하는 의미로 풀이되어, `findLottoRank`로 최종 변경해 보았습니다! 적절한지 확인 요청드리겠습니다 🙏 

- https://github.com/next-step/kotlin-lotto/commit/d7ec8465aaee4ad8e3027ba7d81133543de20716

2022-12-17 05:52 UTC, namonak commented on src/main/kotlin/lotto/application/LottoGenerator.kt
> +        return Lotto(LottoNumber.lotto.shuffled().take(MAXIMUM_LOTTO_NUMBER_LENGTH).sortedBy { it.value })
네, 세세한 부분까지 리뷰해 주셔서 감사합니다 😃
아래와 같이 수정해 보았습니다! 확인 부탁드립니다 🙏

- https://github.com/next-step/kotlin-lotto/commit/0af0c917e5fe4dd34709cc6375d7b3993394c359

2022-12-17 06:12 UTC, namonak commented on src/main/kotlin/lotto/controller/InputFilter.kt
> +    private fun makeLottos(count: Int): List<Lotto> {
좋은 예제 전달해 주셔서 감사합니다! 이 부분은 Gist에 메모해 두고 잘 기억해 둬야 겠네요 😃
전달해 주신 예제 동일하게 적용해 보았습니다! 확인 부탁드립니다 🙏

- https://github.com/next-step/kotlin-lotto/commit/b862972a226b846b1de02d62cd6ea5c4788e8a01

2022-12-17 06:59 UTC, namonak commented on src/main/kotlin/lotto/application/LottoGenerator.kt
> +            lottoList.addAll(manualLottos.value)
조언해 주신대로, `Lottos` 객체에 `plus()` 메서드를 추가하였고, 메시지를 통해 수동 로또와 자동 로또를 병합하도록 수정하였습니다 😃
확인 부탁드리겠습니다 🙏 

- https://github.com/next-step/kotlin-lotto/commit/18770e81343c58a083a32424c2cf96a425b77bf9

2022-12-17 07:08 UTC, namonak commented on src/main/kotlin/lotto/domain/ManualLottoCount.kt
> +data class ManualLottoCount(val manualLottoCount: Int, private val lottoCount: Int) {
일단, `lottoCount` 프로퍼티는 `init` 메서드에서 초기값 검증시에 사용하고 있습니다!
혹시... 제가 리뷰어님의 의도를 잘못 파악한 것일까요? 확인 부탁드리겠습니다 🙏🙇

```kotlin
data class ManualLottoCount(val manualLottoCount: Int, private val lottoCount: Int) {
    init {
        require(manualLottoCount >= 0) { "수동으로 구매할 로또의 갯수는 0 이상이어야 합니다." }
        require(lottoCount >= manualLottoCount) { "수동으로 구매할 로또 수는 구매 금액을 초과할 수 없다." }
    }
}
```

2022-12-17 07:24 UTC, namonak commented on src/main/kotlin/lotto/application/LottoGenerator.kt
>  package lotto.application
`LottoGenerator`, `LottoResultGenerator` 클래스의 패키지 경로를 `application`에서 `controller`로 변경하였습니다 🥲
이번 PR 요청을 드리기 전에, 패키지 경로에 대해서 많이 생각해 봤는데요... 아래의 포스트 내용을 제가 잘못 이해한 것 같네요 😭 

[패키기 구조 가이드](https://cheese10yun.github.io/spring-guide-directory/)

> application 디렉터리는 도메인 객체와 외부 영역을 연결해주는 파사드와 같은 역할을 주로 담당하는 클래스로 구성됩니다. 대표적으로 데이터베이스 트랜잭션을 처리를 진행합니다. service 계층과 유사합니다.

번거롭게 해드려 죄송합니다 🙇 아래와 같이 수정했습니다 🙏

- https://github.com/next-step/kotlin-lotto/commit/8a2cf4aa96adb44ecf553da7c875b1fd843df885

2022-12-17 13:29 UTC, YooInKeun commented on src/main/kotlin/lotto/domain/ManualLottoCount.kt
> +data class ManualLottoCount(val manualLottoCount: Int, private val lottoCount: Int) {
앗 검증시에 사용하고 있군요. 제가 잘못 봤네요~ 죄송합니다 🙏

2022-12-17 13:33 UTC, YooInKeun commented on src/main/kotlin/lotto/application/LottoGenerator.kt
> +            lottoList.addAll(manualLottos.value)
해당 메소드도 테스트해주는 것이 좋을 거 같습니다!

2022-12-17 14:05 UTC, YooInKeun requested changes
4단계 피드백 반영해주시느라 고생 많으셨습니다 🙇‍♂️ 
몇가지 더 얘기 나눠보고 싶은 사항에 대해 코멘트 달았는데요~
확인해주시고 재요청 주시면 감사하겠습니다! 🔥

2022-12-17 14:05 UTC, YooInKeun commented on src/main/kotlin/lotto/controller/LottoGenerator.kt
> +        } catch (e: Exception) {
1. `LottoGenerator` 가 `controller` 인 이유를 알 수 있을까요~?
`controller` 의 역할인 `domain` 과 `view` 를 연결하는 역할에 관계없이 로또를 생성하는 `domain` 기능을 담당하고 있는 거 같아서요~ 🤔 

2. `try-catch` 구문은 어떤 예외를 처리하기 위함인지 알 수 있을까요?

2022-12-17 14:05 UTC, YooInKeun commented on src/main/kotlin/lotto/controller/LottoResultGenerator.kt
> +data class LottoResultGenerator(private val winningNumbers: WinningNumbers, private val lottos: Lottos) {
`LottoGenerator` 와 마찬가지로 `LottoResultGenerator`가 `controller` 인 이유를 알 수 있을까요?

2022-12-17 15:15 UTC, namonak commented on src/main/kotlin/lotto/domain/Lottos.kt
> +    fun plus(other: Lottos) = Lottos(value.plus(other.value))
기본적인 부분을 누락해서 죄송합니다 😭
`Lottos` 클래스에 `plus()` 메서드에 대한 테스트 코드를 추가해 보았습니다! 😃 확인 부탁드리겠습니다 🙏 

- https://github.com/next-step/kotlin-lotto/commit/ed46117692d576d8136d9946113fd303d5362e76

2022-12-17 16:04 UTC, namonak commented on src/main/kotlin/lotto/controller/LottoGenerator.kt
> +        } catch (e: Exception) {
코멘트 남겨 주신 부분에 대해서 다음과 같이 코멘트 남겨드립니다~ 😄

1. 패키지명 관련해서 너무 번거롭게 해드려 정말 죄송합니다 🙇😭 말씀하신 대로 `LottoGenerator`, `LottoResultGenerator`는 Domain과 View를 연결하는 역할과 관계없이, 로또를 생성하는 기능을 갖고 있으므로 Domain 영역에 위치해야 할 것 같습니다 😢 기존 Domain 영역에 너무 많은 클래스 들이 몰려 있는 느낌이 들어, 이를 분리하는 데만 신경 쓴 나머지, 기준을 제대로 세우지 않고 분리한 점에 대해서 반성하도록 하겠습니다 🙇🙏
2. 네, 말씀하신 `try-catch` 구문의 본래 목적은 `generateByLottoCount()` -> `generate()` 통해 생성되는 자동 로또(`Lottos`)에서 매우 낮은 확률이지만 중복이 발생할 경우, 프로그램을 종료시키지 않고 다시 자동 로또를 생성하기 위해 추가한 것입니다~ 다만, 가장 기본적인 원칙인 Domain, View 영역 분리를 지키지 못한 부분이 있어서 https://github.com/next-step/kotlin-lotto/commit/0c7862cd8743c604782865425deb2cad7542f170 과 같이 수정하였습니다! 🥲 자동 로또 번호 생성 시 중복이 발생될 경우, 굳이 에러 메시지를 출력할 필요 없이 내부적으로 다시 생성하는 방향으로 생각해 보았습니다 😃

다시 한번 확인 부탁드리겠습니다 🙇🙏

2022-12-17 16:17 UTC, namonak commented on src/main/kotlin/lotto/controller/LottoResultGenerator.kt
> +data class LottoResultGenerator(private val winningNumbers: WinningNumbers, private val lottos: Lottos) {
죄송합니다 🙇 코멘트 주신 내용 관련하여 https://github.com/next-step/kotlin-lotto/pull/553#discussion_r1051423149 1번 항목에 코멘트를 남겨드렸습니다! 확인 부탁드리겠습니다 🙏

- https://github.com/next-step/kotlin-lotto/commit/ea7b071bb0c579c099fd3ab2cab7035b7267d216

2022-12-18 04:39 UTC, YooInKeun approved these changes
로또 미션 진행하시느라 정말 고생 많으셨습니다~ 💯 
최정님과 리뷰를 진행하면서 적극적으로 문제에 대해 깊이 파고드는 자세를 보며 저 또한 많이 배웠습니다.
또한 피드백을 항상 겸손한 자세로 받아 들여주셔서 감사했어요 🙇‍♂️  
남은 미션들도 응원하겠습니다~!! 🔥 🔥

2022-12-18 04:39 UTC, merged