[2단계] 로또 구현
next-step/kotlin-lotto pull request #582
Opened 2022-12-27 08:51 UTC by riyenas0925

안녕하세요 리뷰어님! PR이 늦어 죄송해요 🙏
꼼꼼한 리뷰 부탁드려요 🙇

2022-12-27 12:55 UTC, laco-dev requested changes
로또 미션 잘 해주셨습니다.

TDD 관점에서 기능을 작게 잘 분리 해 주신 것 같습니다. 👍🏻 
객체를 만들고 분리하는 연습을 하는 과정에서 생각해 볼 만한 내용을 몇가지 남겨드렸으니 충분히 고민하시고 도전 해 보세요. 🙏🏻

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
구입 금액이 0보다 낮은 기준은, 비즈니스 로직으로 볼 수 있지 않을까요?
가령 이 함수가 아닌 다른 방법을 통해 Int 값을 받아 올 수도 있습니다.

Amount 라는 객체를 만들어서 역할을 옮겨보면 어떨까요?

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
마찬가지로 중복되지 않는 6개의 로또 숫자를 가지는 규칙을  별도의 객체를 만들어서 역할을 넘겨보면 좋겠습니다!

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/view/ResultView.kt
> +object ResultView {
```
[8, 21, 23, 41, 42, 43]
[3, 5, 11, 16, 32, 38]
[7, 11, 16, 35, 36, 44]
[1, 8, 11, 31, 41, 42]
[13, 14, 16, 38, 42, 45]
[7, 11, 30, 40, 42, 43]
[2, 13, 22, 32, 38, 45]
[23, 25, 33, 36, 39, 41]
[1, 3, 5, 14, 22, 45]
[5, 9, 38, 41, 43, 44]
[2, 8, 9, 18, 19, 21]
[13, 14, 18, 21, 23, 35]
[17, 21, 29, 37, 42, 45]
[3, 8, 27, 30, 35, 44]
```

로또 번호들을 출력하는 기능이 빠져있는 것 같아요!

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
1이나 43과 같은 매직넘버를 상수로 만들어 보면 어떨까요?
각각의 값이 어떤 의미를 가지는지 이름으로 드러낼 수 있을 것 같아요

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        }
로또 번호 6가지를 생성하는 방법은 강의 자료에 있는 힌트를 활용하면 보다 쉽게 만들 수 있을 것 같아요
```
로또 자동 생성은 shuffled()을 활용한다.

Hint : List<Int>.shuffled().take(6)
```

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +) {
당첨금액의 이름으로 몇개가 일치했는지가 드러나는 것 보다는 등수로 나타내면 어떨까요? 
WinningAmount.SIX가 1등을 의미하는 것으로는 잘 와닿지 않을 것 같아요

이렇게 되면 0, 1, 2는 아마 다른 이름으로 만들어져야 할 것 같아요
```kotlin
enum class WinningAmount {
   FIRST(...)
}
```

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    SIX(6, 2000000000);
마이너한 내용인데 코틀린에서는 `2_000_000` 처럼 작성할 수 있어요

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    private val count: Int,
count가 무엇을 의미하는지 잘 드러나지 않아요.
matchCount 처럼 지어보면 어떨까요?

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/LottoApplication.kt
> +    }
amount를 전달하고 해당 갯수만큼의 로또티켓을 반환하도록 만들어도 되지 않을까요?
구매 가능한 갯수를 먼저 가져오고 다시 호출할 필요가 없어 보여요.

2022-12-27 12:55 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoComparator.kt
> +object LottoComparator {
LottoComparator가 비교를 통해 어떤 결과를 가져오기를 기대할까요?
`Map<Int, Int>` 타입이 무엇을 의미하는지 알기 어려울 것 같아요.

명확하게 결과를 알기 위한 값이라면  LottoStatistics랑 같이 아래와 같은 구조로 만들어 볼 수 있지 않을까요?

```kotlin
class LottoGameResult(
   private val winningCountByAmount: Map<Int, WinningAmount>,
   val statistics: LottoStatistics
) {
   fun getWinningCount(winningAmount: WinningAmount): Int { ... }
   fun getRateOrReturn(...) { ... }
}
```

2022-12-27 12:55 UTC, laco-dev commented on src/test/kotlin/lotto/domain/LottoComparatorTest.kt
> +        )
테스트 코드에서는 가독성 향상을 위해 Fake 함수와 같은 방법을 사용해도 괜찮습니다.

위 코드는 이런식으로 만들어 볼 수도 있어요
```kotlin
val winningNumber = LottoNumbers(1, 2, 3, 6, 8, 9)
```

2022-12-27 13:08 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    SIX(6, 2000000000);
3자리씩 끊어 표현하는게 가독성이 더 좋을 것 같아요~

2022-12-28 11:10 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
1, 43이라는 숫자가 직관적일거라 생각해 매직넘버로 하지 않았는데 로또 규칙을 모르는 사람이 본다면 헷갈릴 수 있겠네요 😃 매직 넘버로 수정할게요~

2022-12-28 12:25 UTC, riyenas0925 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
리뷰어님 의견에 동의해요! 구입 금액을 검증하는 로직을 LottoMachine으로 이동하려고 해요

2022-12-28 12:50 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +) {
FIRST_PLACE, SECOND_PLACE로 변경하고 상금이 없는 나머지는 LOSING_TICKET 등으로 표시하려고 해요

2022-12-28 12:52 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    private val count: Int,
동의해요~ matchCount로 변경할게요

2022-12-28 13:04 UTC, riyenas0925 commented on src/test/kotlin/lotto/domain/LottoComparatorTest.kt
> +        )
테스트용 유틸 오브젝트를 만들어서 사용하는 방향으로 구현했어요.

2022-12-28 13:05 UTC, riyenas0925 commented on src/main/kotlin/lotto/LottoApplication.kt
> +    }
Application에서 로또 티켓을 출력해야 한다는 생각때문에 이처럼 구현했네요 😢 리뷰어님 의견 주신 대로 변경할게요!

2022-12-28 13:08 UTC, riyenas0925 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
동의해요~ 여기가 아닌 LottoTicket에서 검증해야할 책임이라 생각해요! 변경할게요

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        val ticketAmount = getTicketAmount(amount)
getTicketAmount()가 함수 내부로 이동되면서 더이상 public으로 유지할 필요가 없을 것 같네요!

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +                element = LottoTicket(numbers)
List Builder를 이용하면 위 로직을 조금 더 간단하게 만들어 볼 수 있습니다.
```kotlin
val ticketBundle = List(ticketAmount) { ... }
```

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val numbers: Set<Int>
로또 생성은 LottoGenerator가 한다고 하지만, 지금은 LottoTicket이 Int를 가지게 되면서 1부터 43사이의 숫자가 아닌 값도 위치할 수 있게 되었어요.

LottoTicket이 이전처럼 LottoNumber를 가지고 있어야 이러한 위험에서 안전할 수 있지 않을까요?

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    LOSING_TICKET(null, 0),
일치하는 갯수는 0개로 잡으면 될 것 같아요
nullable로 만드는 이점이 있을까요?

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoGameResult.kt
> +) {
새롭게 추가하고 변경된 구조들에 대한 테스트코드도 같이 수정이 필요할 것 같아요!

2022-12-29 13:33 UTC, laco-dev commented on src/main/kotlin/lotto/view/ResultView.kt
> +
```
3개 일치 (5000원)- 1개
4개 일치 (50000원)- 0개
5개 일치 (1500000원)- 0개
6개 일치 (2000000000원)- 0개
```

위 요구사항 출력 조건도 구현에서 빠진 것 같습니다!

2022-12-29 13:33 UTC, laco-dev commented on src/test/kotlin/lotto/domain/LottoComparatorTest.kt
> +        )
네 작성해주신 방법도 유사합니다. 🆗

2022-12-29 13:36 UTC, laco-dev requested changes
아직 구현이 완료되지 않은 부분이 있어서 한번 더 수정 요청을 드립니다.

로또번호는 스스로가 할 역할이 명확하게 있기 때문에, 활용하는 방법으로 잘 살려보면 좋을 것 같습니다.

2023-01-01 06:50 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        val ticketAmount = getTicketAmount(amount)
Application에서만 사용하던 함수였는데 LottoMachine 내부에서 출력하는 방식으로 변경하고 private로변경할게요~

2023-01-01 06:54 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +                element = LottoTicket(numbers)
아래처럼 변경하면 의미가 더욱 명확해지네요~!
```
val ticketBundle = buildList(ticketAmount) {
    val numbers = LottoNumberGenerator.auto()
    add(LottoTicket(numbers))
}
```

2023-01-01 06:55 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/WinningAmount.kt
> +    LOSING_TICKET(null, 0),
해당 부분은 이점이 없을 것 같아요~ 3,2,1,0개 맞는 개수를 nullable로 만들었는데 생각해보니 0으로 해도 큰 문제가 없을 것 같아요!

2023-01-01 09:34 UTC, riyenas0925 commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    val numbers: Set<Int>
LottoNumberGenerator에서 정해진 범위의 숫자만 생성하고 있어서 Int로 변경했는데 이런 검증은 LottoNumber에서 하는게 맞아보이네요! 다시 LottoNumber에서 검증하는 방식으로 수정할게요~

2023-01-01 14:08 UTC, laco-dev approved these changes
피드백 반영 잘 해주셨습니다. 👍🏻 

다음 3단계 미션을 진행하면서 현재 구현한 구조가 어떻게 활용되는지 경험해보시면 좋을 것 같습니다. 💪🏻

2023-01-01 14:08 UTC, merged