[2단계] 로또 구현
next-step/kotlin-lotto pull request #586
Opened 2022-12-28 14:59 UTC by chomily

안녕하세요, 소연님 😄
오랜...만...의 PR입니다...
2단계 로또 미션 제출해요!

2022-12-29 16:02 UTC, ujusy reviewed
안녕하세요, 수진님 👋

2단계 로또 구현 잘해주셨습니다 !! 
조금만 더 힘내서 로또 마무리 하시죠 🏃‍♀️🏃‍♀️
고민해볼 몇 가지 코멘트 남겼습니다 :)
확인 후 다시 요청 주세요~!

또 lint 설정이 안되어있는 것 같으니 확인부탁드려요!

2022-12-29 16:04 UTC, ujusy requested changes
앗..리뷰 요청 버튼이 아니라 코멘트를 눌렀네요 😅
위에 코멘트 남겼으니 확인부탁드려요!

2022-12-31 05:07 UTC, chomily commented on src/main/kotlin/com/nextstep/lotto/domain/Lotto.kt
> +            println("사이즈" + setOf(numbers).size)
앗,, 확인용으로 출력했던 코드가 남아있었네요! 제거했습니다 :)

2022-12-31 05:10 UTC, chomily commented on src/main/kotlin/com/nextstep/lotto/domain/LottoStat.kt
> +        require(matchNumbers in (0..6)) { "일치하는 숫자의 개수는 0에서 7사이 입니다. rank: $matchNumbers" }
앗 ㅎㅎ..

2022-12-31 05:28 UTC, chomily commented on README.md
> +# 로또
로또 프로젝트에 lint 가 켜져있지 않았네요! 감사합니다~ lint 설정하고 스타일 수정했습니다 :)

2023-01-01 04:18 UTC, ujusy approved these changes
안녕하세요, 수진님 :) 

리뷰 반영 잘 해주셨습니다 👍 
몇 가지 피드백 남겼는데 다음 미션 진행하시면서 반영해주세요 :) 
조금만 더 화이팅입니다 💪💪

2023-01-01 04:18 UTC, ujusy commented on src/main/kotlin/com/nextstep/lotto/domain/LottoNumber.kt
> +        require(value in 1..45) { "로또 번호는 1에서 45 사이의 숫자여야 합니다. number: $value" }
위에서 선언한 `LOTTO_NUMBER_LOWER_BOUND`, `LOTTO_NUMBER_UPPER_BOUND` 를 사용해볼 수 있을 것 같아요 :)

2023-01-01 04:18 UTC, ujusy commented on src/main/kotlin/com/nextstep/lotto/view/OutputView.kt
> +        (3..6).forEach {
중복을 잘 제거해주셨어요 :) 
지금은 3~6개 일치를 출력하지만 추후에 일치하는 개수가 변경되면 매번 출력 부분을 변경해줘야 할 것 같아요.
이를 위해 `Rank`에서는 우리가 정말 관리해야하는 `matchCount`를 관리하고 `Rank`의 `matchCount`를 통해 관리하는 건 어떨까요?
고민해보시고 적용해보셔도 좋을 것 같아요!

2023-01-01 04:18 UTC, merged