🚀 1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #607
Opened 2023-06-11 15:32 UTC by rladowl92

안녕하세요!
로또 미션 step1 PR 드립니다.
잘부탁드립니다.

### 기능 요구사항
- 쉼표(,) 또는 콜론(:)을 구분자로 가지는 문자열을 전달하는 경우 구분자를 기준으로 분리한 각 숫자의 합을 반환 (예: “” => 0, "1,2" => 3, "1,2,3" => 6, “1,2:3” => 6)
- 앞의 기본 구분자(쉼표, 콜론) 외에 커스텀 구분자를 지정할 수 있다. 커스텀 구분자는 문자열 앞부분의 “//”와 “\n” 사이에 위치하는 문자를 커스텀 구분자로 사용한다. 예를 들어 “//;\n1;2;3”과 같이 값을 입력할 경우 커스텀 구분자는 세미콜론(;)이며, 결과 값은 6이 반환되어야 한다.
- 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw 한다.

2023-06-12 09:07 UTC, vsh123 commented on src/test/kotlin/Calculator/StringAddCalculatorTest.kt
> +package Calculator
네이밍룰에 맞게 패키지명을 바꿔보면 어떨까요?

https://kotlinlang.org/docs/coding-conventions.html#naming-rules

2023-06-12 09:07 UTC, vsh123 commented on src/test/kotlin/Calculator/StringAddCalculatorTest.kt
> +            null to 0, "" to 0,
요것도 컴마기준으로 라인분리를 해도 좋을 것 같아요~

2023-06-12 09:08 UTC, vsh123 commented on src/test/kotlin/Calculator/StringAddCalculatorTest.kt
> +    "계산 성공" {
너무많은 케이스가 하나의 테스트에 존재하는거 같은데요!
목적에 맞게 테스트를 분리해보면 어떨까요?

2023-06-12 09:09 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +class StringAddCalculator {
object클래스로 선언해보는건 어떨까요?

2023-06-12 09:09 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            return 0
> 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw 한다.

라는 요건에 부합하는 리턴일까요?

2023-06-12 09:10 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            matcher.group(2).split(matcher.group(1))
매직넘버가 존재하는 것 같아요 :)

2023-06-12 09:10 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            input.split(",", ":")
여기두 매직넘버가 존재하네요!

2023-06-12 09:11 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        val custom = matcher.find()
custom보다 더 명확한 네이밍을 해보면 어떨까요?

2023-06-12 09:11 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +}
lint가 적용되어있지 않은 것 같아요! 한번 확인 부탁드려요~

2023-06-12 09:12 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        val splitList = if (custom) {
네이밍은 특정 collection의 이름보다 복수형으로 작성하면 어떨까요? 

https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/

2023-06-12 09:15 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        tokens.firstOrNull { it > 0 } ?: throw RuntimeException("0 이상의 숫자를 입력해주세요.")
해당 조건절이 맞는지 다시한번 확인해보면 좋을 것 같아요!

ex) "1,2,-3"

2023-06-12 09:16 UTC, vsh123 commented on src/test/kotlin/Calculator/StringAddCalculatorTest.kt
> +        }
list선언과 shouldThrow의 위치가 바뀐것 같아요~!

2023-06-13 01:03 UTC, rladowl92 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            return 0
아, 별도로 아래에 이런조건이 있었습니다ㅎㅎ

<img width="669" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/36468143/dbe7289f-a3c8-4aee-895a-a505a2591135">

2023-06-13 01:09 UTC, rladowl92 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            matcher.group(2).split(matcher.group(1))
몇 번째 group인지를 표시하는 인덱스 같은 개념으로 사용하는 숫자라서 이름을 붙이긴 그렇고,,
대신 아래와 같이 의도를 확인할수있도록 수정하였는데 괜찮을까요?
```
val delimiter = matcher.group(1)
val inputs = matcher.group(2)
```

2023-06-13 01:15 UTC, rladowl92 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        val custom = matcher.find()
미션에서도 커스텀 구분자라는 용어를 사용하고 있고 혼란이 없을것같다고 생각했는데요, 혹시 더 좋은 네이밍을 추천해주실 수 있을까요?ㅎㅎ

2023-06-13 10:09 UTC, rladowl92 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +class StringAddCalculator {
util성 클래스라서 object로 선언하는걸까요?

2023-06-13 12:21 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +class StringAddCalculator {
넵 맞습니다!
해당 객체는 여러번 생성될 필요가 없을 것 같아요~ :)

2023-06-13 12:24 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        val custom = matcher.find()
custom의 리턴값은 boolean인데요!!
boolean이라면 is~나 exist~ prefix를 앞에 붙여서 Boolean 타입이라는걸 강조할 수 있을 것 같아요!

2023-06-13 12:29 UTC, rladowl92 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        val custom = matcher.find()
아;; 저도 네이밍때문에 헷갈렸네요! boolean 타입임을 알수있도록 수정하겠습니다ㅎㅎ

2023-06-13 12:35 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        if(tokens.any { it < 0 }) throw RuntimeException("0 이상의 숫자를 입력해주세요.")
lint가 실패했을 것 같은데 확인 부탁드려요!

2023-06-13 12:35 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        }
if-else 구문을 별도의 private함수로 빼면 해당 splitToken함수의 가독성이 더 좋아지지 않을까요?

어떻게 생각하시나요?

2023-06-13 12:35 UTC, vsh123 commented on src/test/kotlin/calculator/StringAddCalculatorTest.kt
> +    val stringAddCalculator = StringAddCalculator
해당 정의가 필요할까요?

2023-06-13 12:35 UTC, vsh123 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +            matcher.group(2).split(matcher.group(1))
1 = DELIMETER_GROUP_INDEX
2 = INPUT_GROUP_INDEX

와 같이 상수화 할 수 있겠지만, 지금 해주신 방법으로도 충분히 의도가 드러나는 것 같네요!

2023-06-13 12:36 UTC, vsh123 requested changes
안녕하세요!
피드백 반영 잘 해주셨네요 👍 
몇가지 코멘트드를 남겨놓았으니 한번 더 확인 부탁드립니다!

2023-06-14 11:08 UTC, vsh123 approved these changes
안녕하세요!

피드백반영 잘해주셨네요 :)

이번스텝은 여기서 머지하도록 하겠습니다 남은 스텝도 화이팅하세요!

2023-06-14 11:08 UTC, merged