[Step1] 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #621
Opened 2023-06-13 17:09 UTC by qktlf789456

많은 지적과 리뷰 부탁드립니다!! 감사합니다.

2023-06-14 12:57 UTC, ohgillwhan requested changes
상준님 코드 잘 봤습니다!
리뷰 확인 부탁드리며, `ktlint`도 확인 부탁드릴게요~

2023-06-14 12:57 UTC, ohgillwhan commented on src/test/kotlin/calculator/StringAddCalculatorTest.kt
> +        assertThatExceptionOfType(RuntimeException::class.java)
코틀린에서는 `assertThrows<ExceptionClass>`로 처리가 가능합니다~

2023-06-14 12:57 UTC, ohgillwhan commented on src/test/kotlin/calculator/StringAddCalculatorTest.kt
> +class StringAddCalculatorTest {
프로젝트에 있던 기본 테스트들인거 같아요.
함수명을 변경해고 `@DisplayName`을 제거하여 코틀린스럽게 테스트명을 추가해볼까요?

2023-06-14 12:57 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +typealias Calculation = (leftOperand: Operand, rightOperand: Operand) -> Operand
클래스와 같이 정적 타입보다 행위에 더 가깝기 때문에 `Calculator`는 어떨까요?
`Supplier` 같이요.

2023-06-14 12:57 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +data class CustomOperation(val symbol: String)
`value class`도 한번 알아볼까요?
https://velog.io/@dhwlddjgmanf/Kotlin-1.5%EC%97%90-%EC%B6%94%EA%B0%80%EB%90%9C-value-class%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

2023-06-14 12:57 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +    fun normalFormula(): String = findCustomOperationDefinition()?.let {
함수는 동사로 시작행햐 할것 같아요~

2023-06-14 12:57 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +    private val customOperations: MutableList<CustomOperation>
`Mutable`은 최대한 없애볼까요?
`listOf(1) + listOf(2) = listOf(1, 2)` 가 됩니다! 응용해보면 어떨까요?

2023-06-14 12:57 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +    private val formulaFormat: FormulaFormat
`init`에서만 사용할것이기 때문에, `init` 에만 선언하는건 어떨까요?

2023-06-18 08:45 UTC, qktlf789456 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +    fun add(stringFormula: String?): Int {
요구사항에 null 입력이 포함되어 있었고, 테스트코드에서도 `@NullAndEmptySource` 가 포함되어 있었습니다.
요구사항에 명시된 내용처럼 null 입력에 대한 부분은 nullable 파라미터 외 수용할만한 혹시 더 괜찮은 방법이 있을까요?

2023-06-18 08:46 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +typealias Calculation = (leftOperand: Operand, rightOperand: Operand) -> Operand
행위에 가깝기 때문에 `Calculator` 이 좀 더 명확할수도 있겠군요 ㅎㅎ

2023-06-18 08:53 UTC, qktlf789456 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +            formulaElements.nextFormulaElement()?.run { result = operator.calculation(result, operand) } ?: break
`formulaElements` 의 역할은 계산 가능한 식을 의미하고 있는 도메인 모델로 설계했습니다.
`StringAddCalculator` 에서 해당 모델을 통해 계산로직을 제공해주고 있으므로, 책임을 분리했는데 `formulaElements` 에서 sum 같은 계산 결과까지 제공해준다면 책임의 범위가 더 커질 것 같다는 생각이 들어서요. 혹시 어떤 방법으로 sum 을 제공하는것이 더 바람직하다고 생각하실까요? 의견 듣고싶습니다. :)

2023-06-18 08:58 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +data class CustomOperation(val symbol: String)
`They don't have an identity and can only hold values.`
위 경우 value class 로 선언하는것이 훨씬 더 이점이 많군요 ㅎㅎ 감사합니다.

2023-06-18 08:59 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +enum class Operation(val symbol: String, val calculation: Calculation) {
사실 저번주 진행했던 계산기 코드를 가져와서 사용했는데 좋은 지적 감사합니다 ㅎㅎ

2023-06-18 09:00 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +        private const val CUSTOM_OPERATION_DEFINITION_REGEX = "//(.)\n(.*)"
네이밍을 REGEX 라고 하고.. 실수해버렸군요 바로 적용했습니다 ㅎㅎ

2023-06-18 09:04 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +    } ?: formula
메소드에서 다른 메소드를 사용하고 있는 경우인데요, 호출당하는 메소드가 아래에 선언되는데 혹시 일반적인 경우일까요? 관련 레퍼런스가 있다면 참고해보겠습니다.

2023-06-18 09:11 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +    fun normalFormula(): String = findCustomOperationDefinition()?.let {
좀 더 명확하게 `val` 로 바꿨습니다 ㅎㅎ

2023-06-18 09:16 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +    private val formulaFormat: FormulaFormat
사실 동반객체에서도 사용중인데 조금 더 좋은 구조가 있을까요? ㅎㅎ

2023-06-18 09:30 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +        formulaFormat.findCustomOperationDefinition()?.run { addPlusCustomOperation(this) }
해당 필드들을 클래스 내부에 유지하는게 좋을지 더 고민해봐야겠습니다.
필드로 딱 필요한 것들만 유지되면 좋겠지만, 그래도 private 접근지정자라 괜찮지 않을까? 생각했네요.
하지만 말씀주신것처럼 클래스를 파악하는데 좀 더 지저분한 코드가 된 것 같기도 합니다 ㅠ

2023-06-18 09:34 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +    private val formulaFormat: FormulaFormat
[FormulaElements.kt](https://github.com/next-step/kotlin-lotto/pull/621/files/21f3c912010214bd3918c66042df48b8f0619036#diff-bf89343b9142921e5e3bf9f60cf60b413ba1db2f6c16f41987bb2b5da7251524)
위에서 주신 피드백대로 반영해보며, 불필요 필드는 제거했습니다!

2023-06-18 09:45 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +        startValue = formulaStringNumbers().firstOrNull()?.toIntOrNull()?.toOperand() ?: 0.toOperand()
예외 발생도 생각했지만 불필요한 try catch 만 늘어날 것 같아서
요구사항에 따라 기본값을 지정해주고 싶은 마음에 `?.` 체이닝이 많아졌네요ㅠ 혹시 더 좋은 코드로 바꿀 수 있을까요?

2023-06-18 09:52 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +            .let { ArrayDeque(it) }
`elements` 는 `nextFormulaElement()` 메소드에서 필요한 필드이며, private 선언이므로 구현을 바꾸게 된다면 사라질 수도 있는 필드입니다.
`startValue` 와 `nextFormulaElement()` 메소드 이 두개로 나눈 이유에 대해서 질문하신걸까요?

2023-06-18 10:04 UTC, qktlf789456 commented on src/main/kotlin/calculator/FormulaElements.kt
> +    init {
FormulaElements 객체에 필요한 필드만 존재하고, 생성과정에만 필요했던 필드들은 제거했습니다 ㅎㅎ
변경 후 `init` 에서 적절한 역할을 하고있는건지 확인해주시면 감사드리겠습니다.

2023-06-19 00:02 UTC, ohgillwhan commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +    fun add(stringFormula: String?): Int {
크게 문제 없으니 괜찮을것 같습니다 💯

2023-06-19 00:08 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +    } ?: formula
일반적으로 코드를 볼 때 위에서 아래로 읽기 때문에 자연스럽게 읽을 수 있습니다.
아마 클린코드에서도 나올거에요. 아래링크에 세로 순서 한번 확인해보실까요?

https://dalsacoo-log.tistory.com/entry/cleancode-5

2023-06-19 00:09 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +        formulaFormat.findCustomOperationDefinition()?.run { addPlusCustomOperation(this) }
오해가 생길 수 있고, 그리고 다른 개발자가 수정하면 안되는데 해버리면 다른 로직에 문제가 생기겠죠?

2023-06-19 00:19 UTC, ohgillwhan commented on src/main/kotlin/calculator/FormulaElements.kt
> +        startValue = formulaStringNumbers().firstOrNull()?.toIntOrNull()?.toOperand() ?: 0.toOperand()
`formulaStringNumbers().first().toInt().toOperand()`로 잘못된 값은 바로 `Exception` 발생시키고, 사용자 단에서 다시 입력하게 하는것도 방법이겠네요!

2023-06-19 00:31 UTC, ohgillwhan commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +            formulaElements.nextFormulaElement()?.run { result = operator.calculation(result, operand) } ?: break
이제 고민을 해볼게 `StringAddCalculator`가 아니라 `WebAddCalculator`라는게 생겼다고 고민을 해볼게요. 그러면 그 때 해 `while`코드가 양쪽에 중복이 되게 될거에요. 우선 여기서 응집도가 떨어진것을 느낄 수 있을거에요. 현 코드에는 버그가 없지만, 버그가 생긴다면 양쪽 다 수정을 해줘야 할거구요. 그러면 우선 해당 코드는 다른곳에 응집이 되어야 한다고 느낄 수 있을거같아요. 이러한 이유로 `StringAddCalculator`는 조금 `sum`을 두려면 고민이 필요할것 같아요.

대신 `StringAddCalculator`는 문자로 들어온것을 파싱하고, 파싱된 숫자로 `formulaElements`를 생성한 다음 `sum`을 제공하면 위에 문제가 사라지겠네요! 
`formualElements`에서 `sum()`을 제공하는게 책임의 범위가 커지는것에 대한 고민을 해보자면, 해당 클래스는 이미 `elements`를 가지고 있기 때문에 그 `elements`를 사용하는 어떠한 것도 문제가 되지는 않을것 같아요. 오히려 응집도가 더 높아질 수 있겠죠?

2023-06-19 00:36 UTC, ohgillwhan approved these changes
남겨드린 리뷰 확인 부탁드립니다!
`step2`에 적용 부탁드려요.

2023-06-19 00:36 UTC, ohgillwhan commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +            formulaElements.nextFormulaElement()?.run { result = operator.calculator(result, operand) } ?: break
제가 `sum`에 대해 리뷰드린것 고민 부탁드릴게요!

2023-06-19 00:36 UTC, merged