Step2
next-step/kotlin-lotto pull request #661
Opened 2023-06-16 12:26 UTC by sjparkk

안녕하세요!

로또 미션 앞으로 잘 부탁드리겠습니다!

먼저 이전에 문자열 계산기 관련 수정 사항입니다.

1. 계산기 내로 input를 캡슐화하였습니다.

2. 수식의 유효성을 체크하는 로직에서는 require와 같은 선언적 체크를 이용하여 exception을 날릴 수 있는 부분이 throw 하고 있는 음수를 입력할 수 없습니다. 부분밖에 보이지 않습니다! 근데 여기서 궁금한 점은 require를 사용하면 IllegalArgumentException 을 날리게 되는데 구현사항 항목으로 RuntimeException을 발생시키게 되어 있어. 해당 부분 수정을 하지 않았습니다. 혹시 제가 이해한 부분이 틀린 점이 있을까요?

3. 함수명만으로 봤을 때 의미가 모호한 것들 수정했습니다 (split())

4. 기존 split() 함수에서 처리하는 여러가지 역할을 함수 분리를 통해 수정하였습니다.

5. input.split("\n")[1]의 경우 1을 매직리터럴 처리하였습니다. 여기서 궁금한 점이 해당 부분 말고도 input.length == 1과 같이 이러한 숫자들도 다 의미를 부여해서 매직리터럴로 취급하여 처리를 하는 것이 맞을까요?

아니면 해당 리터럴이 어떤 의미가 명확히 전달되어야 하는 부분에서만 처리하면 되는 것일까요?

6. String과 같은 자료형 문구를 사용한 변수명 수정하였습니다.

7. 리뷰 - 테스트를 용이하게 하기 위해, split, getCustomDelimiter, stringAdd 함수를 private에서 public으로 만드신 것 같습니다.
테스트 코드에서만 접근하는 용도로 private 함수를 public으로 변경한다는 것은, 그만큼 클래스가 두 개 이상의 책임을 갖는다는 의미이기도 합니다. 클래스를 분리해보면 어떨까요?

질문 - 해당 사항에 대해서 제가 이해한 바과 정확한지 알고 싶습니다. 먼저 제가 이해한 바로는 
1. 테스트만을 위해서 public으로 만드는 것은 X
2. 하나의 클래스에서 여러가지 일을 가지는 것은 X -> 예를 들어 계산기에서는 계산만 할 것, 구분자 관련 연산은 구분자 클래스를 만들어서 해당 클래스 내로 함수를 옮길것

으로 이해했는데 맞을까요?

추가적으로 2단계 미션인 로또도 구현하여 리뷰 요청드립니다!

혹여나 제가 잘못 이해한 부분이나 추가적인 내용이 있다면 리뷰 부탁드리겠습니다.

감사합니다!!

2023-06-16 12:47 UTC, BeokBeok commented
> 수식의 유효성을 체크하는 로직에서는 require와 같은 선언적 체크를 이용하여 exception을 날릴 수 있는 부분이 throw 하고 있는 음수를 입력할 수 없습니다. 부분밖에 보이지 않습니다! 근데 여기서 궁금한 점은 require를 사용하면 IllegalArgumentException 을 날리게 되는데 구현사항 항목으로 RuntimeException을 발생시키게 되어 있어. 해당 부분 수정을 하지 않았습니다. 혹시 제가 이해한 부분이 틀린 점이 있을까요?

A. 이 부분은 제가 놓쳤네요. 😅 
요구사항을 꼼꼼하게 잘 챙겨주셨네요. 👍

2023-06-16 12:49 UTC, BeokBeok commented
> input.split("\n")[1]의 경우 1을 매직리터럴 처리하였습니다. 여기서 궁금한 점이 해당 부분 말고도 input.length == 1과 같이 이러한 숫자들도 다 의미를 부여해서 매직리터럴로 취급하여 처리를 하는 것이 맞을까요?

A. 해당 숫자가 어떤 것을 의미하는지 이해할 수만 있다면, 그대로 사용하셔도 무방합니다. 😅 
다만, 숫자만 봐서는 어떤 것을 의미하는지 어려울 경우에는 매직리터럴로 취급합니다. 🙏

2023-06-16 12:50 UTC, BeokBeok commented
> 질문 - 해당 사항에 대해서 제가 이해한 바과 정확한지 알고 싶습니다. 먼저 제가 이해한 바로는
테스트만을 위해서 public으로 만드는 것은 X
하나의 클래스에서 여러가지 일을 가지는 것은 X -> 예를 들어 계산기에서는 계산만 할 것, 구분자 관련 연산은 구분자 클래스를 만들어서 해당 클래스 내로 함수를 옮길것

A. 네 맞습니다.
정확히는 하나의 클래스에서는 한 가지 책임만 갖는다고 봐주시면 좋을 것 같습니다. 🙏

2023-06-16 13:27 UTC, BeokBeok requested changes
이전 단계 피드백과 로또(자동) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/calculator/DelimiterManager.kt
> +        }
```suggestion
        return result?.groupValues?.get(1)
```
let을 잘 활용해주셨습니다. 👍 
지금도 좋지만, (?)를 활용하면 한 줄로도 작성할 수 있습니다. 😄

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        private const val CUSTOM_INPUT: Int = 1
```suggestion
        private const val CUSTOM_INPUT_INDEX: Int = 1
```
CUSTOM_INPUT이라고만 한다면, 이게 입력받은 값인 것인지 키값인 것인지 잘 모를 것 같습니다.
사용하는 곳을 보니 인덱스와 관련된 것으로 보이는데, INDEX라는 단어를 넣어보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/Lotto.kt
> +    }
Lotto 클래스에서 로또를 구매하는 함수를 잘 구현해주셨네요. 👍 
다만, Lotto 클래스가 가지는 책임보다 더 큰 범주이지 않을까 라는 생각이 듭니다.
Lotto 클래스가 buyLotto 함수를 호출하는 상황을 풀어서 보면, "로또가 로또를 구매한다" 라는 의미로 와닿아요.
현실세계에 빗대보아도 일반 사람이 로또를 구매하지만, 로또가 로또를 구매하지는 않으니까요. 🤔 
Lotto 클래스에 접근하는 곳에서 buyLotto 함수를 구현해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/Lotto.kt
> +class Lotto {
```suggestion
class Lotto(
    val value: List<Int>
 {
```
Lotto는 반드시 여섯 개의 숫자 리스트를 가지고 있습니다.
그렇다면 캡슐화를 해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoApplication.kt
> +        return Pair(inputMoney, lottoBundle)
Pair를 활용해주셨네요. 👍 
Pair는 간편하게 두 개의 값을 묶을 수 있지만, first가 무엇인지, second가 무엇인지 알기가 어렵습니다.
Pair 대신 data class를 활용해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +    }
로또 입력 숫자 개수는 로또와 관련이 있어 보입니다.
그렇다면 Lotto 클래스에서 검증하는 것이 좋지 않을까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +        return result.toList()
숫자가 몇개 일치하는지 체크하는 로직을 잘 구현해주셨네요. 👍 
다만, LottoEnum 이라는 곳에 몇개가 일치하면 얼마인지에 대한 정보를 담는 클래스를 구현해주셨는데요.
그렇다면 LottoEnum 클래스에서 이 로직을 구현해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoEnum.kt
> +    SIX_COLLECT(6, 2000000000)
```suggestion
    SIX_COLLECT(6, 2_000_000_000)
```
코틀린에서는 천 단위로 언더바를 추가하면 가독성이 좋아집니다.

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoEnum.kt
> +enum class LottoEnum(
클래스명도 마찬가지로 예약어를 클래스명으로 작성하는 것을 지양하시는 것이 좋습니다.
LottoRank 와 같은 네이밍은 어떠신가요?

2023-06-16 13:27 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoNumber.kt
> +class LottoNumber {
```suggestion
class LottoNumber(
    val value: Int
) {
```
LottoNumber 클래스도 반드시 숫자를 가집니다.
그렇다면 캡슐화하도록 개선해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +        val actual = lotto[0].toSet()
```suggestion
        val actual = lotto[0]
```
set으로 변환하는 순간 중복된 숫자가 없어지게 됩니다.
정말로 중복된 숫자가 있는지 확인해보기 위해서는 set으로 변환하지 않도록 개선해보면 어떨까요?

2023-06-16 13:27 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
LottoTest 클래스에서는 Lotto 클래스에 해당하는 것만 작성하시는 것이 좋습니다.
LottoChecker와 Calculator에 대한 테스트 코드를 작성하시고 싶으시다면, LottoCheckerTest와 CalculatorTest 파일에 작성해보면 어떨까요?

2023-06-17 01:15 UTC, sjparkk commented on src/main/kotlin/calculator/DelimiterManager.kt
> +    }
null 처리를 먼저 진행함으로써 fixedDelimiter 를 삭제하였습니다!

2023-06-17 01:15 UTC, sjparkk commented on src/main/kotlin/calculator/DelimiterManager.kt
> +        }
let을 사용할 필요가 없었네요! 한줄로 변경하였습니다!

2023-06-17 01:15 UTC, sjparkk commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        private const val CUSTOM_INPUT: Int = 1
명확한 의미 전달을 위해 INDEX를 붙여 수정하였습니다 :)

2023-06-17 01:17 UTC, sjparkk commented on src/main/kotlin/lotto/Lotto.kt
> +    }
로또가 로또를 구매한다고 생각하니 정말 이상하네요!

해당 역할을 하는 LottoManager Class를 생성하여 해당 클래스에 buyLotto 함수를 구현하였습니다!

2023-06-17 01:17 UTC, sjparkk commented on src/main/kotlin/lotto/Lotto.kt
> +class Lotto {
캡슐화를 진행하니 코드가 많이 수정되었네요. 캡슐화 진행하였습니다~!

2023-06-17 01:37 UTC, sjparkk commented on src/main/kotlin/lotto/LottoApplication.kt
> +        return Pair(inputMoney, lottoBundle)
Data Class를 만들어 처리하였습니다!

2023-06-17 01:39 UTC, sjparkk commented on src/main/kotlin/lotto/LottoChecker.kt
> +    }
Lotto Class 내로 검증 로직 수정하였습니다!

2023-06-17 01:43 UTC, sjparkk commented on src/main/kotlin/lotto/LottoChecker.kt
> +        return result.toList()
혹시 해당 부분이 아래 로직을 말씀하신 걸까요?

    fun winningMoneyCheck(collectCounts: List<Int>): Int {
        var winningMoney = 0
        collectCounts.forEach { count ->
            winningMoney += LottoRank.values().find { it.count == count }?.prizeMoney ?: NONE_PRIZE_MONEY
        }
        return winningMoney
    }
    
Q. 먼저 해당 부분은 enum 클래스 내부로 수정하였습니다!

혹여나 제가 잘못 수정한 부분이 있다면 좀 더 자세히 설명 부탁드리겠습니다!

2023-06-17 01:43 UTC, sjparkk commented on src/main/kotlin/lotto/LottoEnum.kt
> +    SIX_COLLECT(6, 2000000000)
꿀팁 감사합니다!

2023-06-17 01:43 UTC, sjparkk commented on src/main/kotlin/lotto/LottoEnum.kt
> +enum class LottoEnum(
LottoRank 변경하였습니다!

2023-06-17 01:43 UTC, sjparkk commented on src/main/kotlin/lotto/LottoNumber.kt
> +class LottoNumber {
캡슐화 진행하였습니다!

2023-06-17 01:47 UTC, sjparkk commented on src/test/kotlin/lotto/LottoTest.kt
> +        val actual = lotto[0].toSet()
해당 부분에서 질문이 있습니다!

먼저 제가 의도한 바는 이렇습니다.

검증하고자 하는 것 - 발급 받은 6개의 숫자 중 중복 된 숫자는 있을 수 없다 

즉, buyLotto()를 통해 얻은 lotto는 무조건 6개의 숫자로 이루어진 리스트여야 한다 -> toSet()을 하게 되면 중복된 숫자가 없어지게 된다 -> 그래서 toSet()을 하고 이후에 검증하고자하는 assert문에서 6이 나오지 않으면 검증하고자 했던 buyLotto()는 실패한다. -> toSet()을 했는데도 6이 나오면 중복된 것이 없다는 의미이기 때문에 테스트가 통과한다.

라는 의미로 작성하였습니다.

혹여 틀린 부분있다면 답변 부탁드리겠습니다! :)

2023-06-17 01:47 UTC, sjparkk commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
각 테스트에 대한 분리도 진행하였습니다. 감사합니다~

2023-06-17 01:47 UTC, sjparkk commented
코멘트 주신 부분들 수정하여 리뷰 재요청드립니다~ ^^ 즐거운 주말 보내세요!

2023-06-17 12:49 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +        val actual = lotto[0].toSet()
말씀하신 의도라면 set으로 변환하는 것이 의미가 있겠네요! 👍

2023-06-17 13:19 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/Calculator.kt
> +class Calculator {
클래스명만 봐서는 어떤 것을 계산하는지 잘 모르겠네요. 🤔 
구현된 함수를 보니, 수익률을 계산하고 있는 것으로 보이네요.
그렇다면 클래스명을 수익률과 관련된 이름으로 변경해보면 어떨까요?

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoApplication.kt
> +    fun lottoRun() {
함수는 행동을 의미하므로, 동사구로 작성해주시는 것을 권장합니다. 🙏

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +        return result.toList()
코드 위치 설정이 잘못 되어있었네요. 🙏 
말씀하신 부분이 맞습니다. 👍

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +    fun lottoCheck(winningNumber: String, lottoBundle: List<List<Int>>): List<Int> {
함수명만 봐서는 로또의 무엇을 체크하는지 와닿지가 않네요. 🤔 
함수가 하는 일에 대해서 좀 더 의도가 드러나도록 함수명을 변경해보면 어떨까요?

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +    fun lottoCheck(winningNumber: String, lottoBundle: List<List<Int>>): List<Int> {
```suggestion
    fun lottoCheck(winningNumber: String, lottoBundle: List<List<Int>>): List<LottoRank> {
```
LottoRank 클래스는 로또번호 일치 개수에 대해서 알고 있습니다.
그렇다면 LottoRank 를 활용해보면 어떨까요?

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoManager.kt
> +    fun buyLotto(money: Int): List<List<Int>> {
```suggestion
    fun buyLotto(money: Int): List<Lotto> {
```
로또 번호의 리스트를 Lotto 클래스로 관리를 하고 계십니다.
그렇다면, 구현하신 Lotto 클래스를 활용해보면 어떨까요?

2023-06-17 13:19 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoRank.kt
> +        fun getPrizeMoney(count: Int): Int {
```suggestion
        fun getPrizeMoney(count: Int): LottoRank {
```
당첨금에 대한 정보를 LottoRank의 prizeMoney로 관리하고 계십니다.
그렇다면 LottoRank를 활용해보면 어떨까요?

2023-06-17 13:19 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoCalculatorTest.kt
> +class LottoCalculatorTest {
```suggestion
class CalculatorTest {
```
대체로 테스트 코드의 클래스명은 `클래스명Test` 로 작성합니다. 😅

2023-06-17 13:19 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +class LottoTest {
```suggestion
class LottoGeneratorTest {
```
구현부를 보니, LottoTest보다는 LottoGeneratorTest에 가까워보입니다. 🙏

2023-06-17 13:19 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
내가 원하는 번호로 로또가 생성되는지 테스트코드를 작성해보면 어떨까요?

2023-06-17 13:20 UTC, BeokBeok commented
추가로, 현재 같은 번호로 로또가 여러장 생성되고 있습니다.
이 부분도 개선부탁드립니다. 😅 🙏 
![스크린샷 2023-06-17 오후 10 20 29](https://github.com/next-step/kotlin-lotto/assets/48344355/80fd5040-a6d5-473a-98e4-ead339756cc3)

2023-06-17 14:20 UTC, sjparkk commented on src/main/kotlin/lotto/Lotto.kt
> +    }
private 접근자를 제거하여 getLotto 함수 제거 및 init 블록을 두어 validation 처리하도록 변경하였습니다!

2023-06-17 14:20 UTC, sjparkk commented on src/main/kotlin/lotto/Lotto.kt
> +        private const val COLLECT_LOTTO_SIZE = 6
하나로 수정하였습니다!

2023-06-17 14:21 UTC, sjparkk commented on src/main/kotlin/lotto/Calculator.kt
> +class Calculator {
수익률 계산기로 사용하고 있어 RateCalculator로 수정하였습니다!

2023-06-17 14:21 UTC, sjparkk commented on src/main/kotlin/lotto/LottoApplication.kt
> +    fun lottoRun() {
로또 추첨을 시작하는 함수였는데 동사구 형태로 startLottery로 함수명 수정하였습니다!

2023-06-17 14:22 UTC, sjparkk commented on src/main/kotlin/lotto/LottoChecker.kt
> +    fun lottoCheck(winningNumber: String, lottoBundle: List<List<Int>>): List<Int> {
LottoRank 로 수정하였습니다~! 해당 과정에서 변경되는 코드 및 테스트 코드 수정하였습니다!

2023-06-17 14:22 UTC, sjparkk commented on src/main/kotlin/lotto/LottoManager.kt
> +    fun buyLotto(money: Int): List<List<Int>> {
Lotto 로 수정하였습니다~! 해당 과정에서 변경되는 코드 및 테스트 코드 수정하였습니다!

2023-06-17 14:23 UTC, sjparkk commented on src/main/kotlin/lotto/LottoRank.kt
> +        fun getPrizeMoney(count: Int): Int {
LottoRank 로 수정하였습니다~! 해당 과정에서 변경되는 코드 및 테스트 코드 수정하였습니다!

2023-06-17 14:23 UTC, sjparkk commented on src/test/kotlin/lotto/LottoTest.kt
> +class LottoTest {
LottoGeneratorTest로 수정하였습니다!

2023-06-17 14:38 UTC, sjparkk commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
질문이 있습니다!

현재 getLottoNumbers() 는 내부적으로 getLottoNumber()을 이용하여 1~45 숫자 중 shuffled을 통해 무작위로 숫자를 하나씩 반환 받아 로또 넘버를 생성하여 로또 넘버를 발급 받고 있는데 -> 내가 원하는 번호로 로또가 생성되는지 검증이 가능할까요? (랜덤으로 로또 넘버가 생성되므로)

그리고 추가적으로 해당 부분을 보는 도중에 1-45에서 숫자를 뽑는 중에 중복 숫자에 대한 처리가 되어 있지 않아서 해당 부분 추가하였습니다!

2023-06-17 14:43 UTC, sjparkk commented
리뷰 주신 내용 반영하였습니다!! 

추가적으로 LottoChecker Class의 경우에는 로또와 관련 된 동작들을 모아둔 클래스인데 Cheker 라는 이름때문에 역할이 불분명해진거 같습니다..!! 지금 현재로는 LottoManager 내로 옮기는 것이 맞는거 같은데 Step3를 진행하면서 이 부분 개선해보도록 하겠습니다!!

감사합니다!

2023-06-17 14:44 UTC, BeokBeok commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
> 현재 getLottoNumbers() 는 내부적으로 getLottoNumber()을 이용하여 1~45 숫자 중 shuffled을 통해 무작위로 숫자를 하나씩 반환 받아 로또 넘버를 생성하여 로또 넘버를 발급 받고 있는데 -> 내가 원하는 번호로 로또가 생성되는지 검증이 가능할까요? (랜덤으로 로또 넘버가 생성되므로)

A. 함수 내부에서 shuffled와 같은 랜덤을 처리하고 있다보니, 함수를 호출할 때마다 매번 다른 결괏값이 도출됩니다.
그래서 말씀하신대로 내가 원하는 번호로 로또가 생성되는지에 대한 검증을 할 수 있을지 의문이 생기게 됩니다.
제어할 수 없다면, 상단으로 올려보면 어떨까요?

추가로, 컴파일 의존성과 런타임 의존성에 대해서 학습해보시면 큰 도움이 되실 것 같습니다. 🙏

2023-06-17 14:51 UTC, sjparkk commented
추가적으로 하나 질문이 있습니다!

지금 현재 lotto 테스트 패키지 하위에 4개의 테스트 클래스가 존재하는데 혹시 4개의 테스트 클래스 전부를 한번에 실행시켜 검증하는 방법이 있을까요??😭

2023-06-17 14:56 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-06-17 14:56 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoApplication.kt
> +    private val resultView = ResultView
LottoApplication에 RateCalculator와 LottoChecker는 생성자로 받고 있지만, InputView와 ResultView는 멤버 변수로 정의해주셨네요. 👍 
혹시 신종님만의 기준이 있으신지 궁금합니다. 🤔

2023-06-17 14:56 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoChecker.kt
> +class LottoChecker {
저는 LottoChecker라는 이름만 보았을 때에는 로또 번호가 유효한 번호들로만 구성되어있는지 혹은 로또 당첨번호가 일치하는지 등등 어떤 책임을 가지는 클래스인지 감이 잘 오질 않네요. 🤔 
이렇게 Checker와 같은 포괄적인 의미를 가진 이름으로 클래스명을 작성하시게 되면, 두 가지 이상의 책임을 갖는 클래스로 만들기 쉬워집니다.
의미가 명확하도록 고민해보시고 변경해보시면 어떨까요?

2023-06-17 14:56 UTC, BeokBeok commented on src/main/kotlin/lotto/utils/LottoGenerator.kt
> +    private val numbers: MutableList<Int>
LottoGenerator가 숫자의 리스트를 캡슐화하고 있네요. 👍 
제가 생각하기에 Generator는 무에서 유를 창조하는(?) 일을 한다고 생각합니다.
그래서 numbers를 캡슐화하는 것이 어색해보이는데, 신종님은 어떻게 생각하시는지 궁금합니다!

2023-06-17 14:56 UTC, merged

2023-06-17 14:59 UTC, BeokBeok commented
> 추가적으로 하나 질문이 있습니다!
> 
> 지금 현재 lotto 테스트 패키지 하위에 4개의 테스트 클래스가 존재하는데 혹시 4개의 테스트 클래스 전부를 한번에 실행시켜 검증하는 방법이 있을까요??😭

A. 프로젝트에 lotto 폴더를 선택하신 후, 마우스 오른쪽을 누르시고 Run 누르시면 됩니다. 😄 
![스크린샷 2023-06-17 오후 11 58 28](https://github.com/next-step/kotlin-lotto/assets/48344355/897ba178-aaba-4c25-8d16-265cc1762299)

2023-06-18 01:50 UTC, sjparkk commented on src/main/kotlin/lotto/LottoApplication.kt
> +    private val resultView = ResultView
먼저 RateCalculator와 LottoChecker 생성자 매개변수로 선언한 것은 LottoApplication 클래스 기능에 대해 종속 클래스 인 것을 강조하고 싶어 생성자 매개변수로 넣었고, InputView와 ResultView의 경우는 Object 로 선언 되어 싱글톤 개체로 생성되기 때문에 따로 생성자에 넣지 않았습니다..!

혹시 제가 잘못 생각하고 있는 부분이나 매끄럽지 않은 부분이 있으면 현석님의 의견이 궁금합니다!

2023-06-18 01:50 UTC, sjparkk commented on src/main/kotlin/lotto/utils/LottoGenerator.kt
> +    private val numbers: MutableList<Int>
제가 생각한 LottoGenerator 클래스의 역할은 로또 번호에 대한 생성입니다.

 여기서 말하는 로또 번호란 로또 추첨 시 사용하는 6개의 숫자의 배열을 뜻합니다. 1부터 45까지의 숫자에서 6개의 숫자를 무작위로 뽑게 되는데요. 이때 제가 생각한 무에서 유를 창조하는 Generator 역할로써 LottoGenerator는 이 6개에 대한 숫자를 생성하는 역할로 생각했습니다! 
 
  LottoGenerator 자체가 1부터 45까지의 숫자를 생성하는 것은 아니기에 numbers(1~45)를 전달 받아서 로또에 대한 숫자만 생성하는 것으로 의도하여 작성하였습니다!

2023-06-18 01:53 UTC, sjparkk commented on src/main/kotlin/lotto/LottoChecker.kt
> +class LottoChecker {
저도 이 부분이 계속 마음에 걸렸는데 제가 의도하고 있던 LottoChecker 내 동작은 크게 두가지로 나뉠수 있더라고요. 

1. 로또 당첨 번호와 로또 번호들을 비교하여 당첨 결과 반환
2. 로또 당첨 금액 결과 반환 

그래서 1에 대한 동작을 하는 함수들은 LottoNumberMatcher Class
2에 대한 동작은 LottoMoneyMatcher Class로 수정하였습니다!

2023-06-18 02:01 UTC, sjparkk commented on src/test/kotlin/lotto/LottoTest.kt
> +    }
해당 부분을 구현할 때 아래에서 코멘트(https://github.com/next-step/kotlin-lotto/pull/661#discussion_r1233173250) 단 것처럼

1. LottoGenerator()는 1-45 까지의 숫자를 전달 받는다
2. LottoGenerator().getLottoNumbers()에서 getLottoNumbers()은 내부적으로 해당 클래스 내 존재하는 private getLottoNumber() 함수를 통해 랜덤한 숫자를 전달 받아 6개가 되면 반환한다.

이러한 로직에서 제가 원하는 숫자에 대하여 로또 번호 생성 여부를 확인하기 위해 테스트 코드를 작성하기 위해서는 getLottoNumbers() 함수 자체로 테스트가 가능한 부분일까요??

제어할 수 없다면 상단으로 올리는 것을 말씀해주셨는데 여기서 제어할 수 없는 부분이 랜덤으로 생성하는 부분이라고 하면 해당 함수를 상단으로 배치해 getLottoNumbers()에 번호를 넘겨야 하는 것인가요?

이렇게 하게 되면 제가 설계가 LottoGenerator 클래스가 변경이 되는 것 같습니다..

위에서 말했듯이 아래 사항을 유지하면서 테스트를 작성해볼 수 있는 방법이 있을까요?? 😅
1. LottoGenerator()는 1-45 까지의 숫자를 전달 받는다
2. LottoGenerator().getLottoNumbers()에서 getLottoNumbers()은 내부적으로 해당 클래스 내 존재하는 private getLottoNumber() 함수를 통해 랜덤한 숫자를 전달 받아 6개가 되면 반환한다.

2023-06-18 12:56 UTC, BeokBeok commented on src/main/kotlin/lotto/LottoApplication.kt
> +    private val resultView = ResultView
Object로 선언되어 있어도 생성자에 넣을 수 있지 않을까요?
추가로, 멤버변수는 클래스 내부에서 자유롭게 접근하여 편하게 조작할 수 있는 장점이 있지만, 멤버변수의 값에 따라 함수 호출 결괏값이 달라진다는 단점이 있습니다.

의존성 주입 관련해서 학습해보시면 도움이 될 것 같아요!