문자 덧셈 계산기
next-step/kotlin-lotto pull request #665
Opened 2023-06-16 14:02 UTC by goyounggyeong

[Step1]  1단계 - 문자열 덧셈 계산기
안녕하세요. 
코드리뷰 잘 부탁드립니다 :)

2023-06-17 04:44 UTC, vsh123 requested changes
안녕하세요! 

이번미션 잘 부탁드립니다 :)

몇가지코멘트를 남겨놨으니 확인부탁드려요~

2023-06-17 04:44 UTC, vsh123 commented on README.md
> +#### 요구사항
요구사항 작성 👍 

다만 각 라인별로 공백을 주시면 markdown파일이 조금 더 깔끔하게 나올 것 같아요!

<img width="936" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/32254689/43684642-0eb3-447d-a4d6-6ce20babf755">

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +class StringAddCalculator {
object클래스 적용을 고려해보면 어떨까요?

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/ExpressionParser.kt
> +class ExpressionParser(val inputExpression: String) {
- 해당클래스는 테스트가 하나도 없네요!! 테스트를 작성해보면 어떨까요?
- inputExpression는 프로퍼티로 들고 있지 않아도 될 것 같아요!

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/ExpressionParser.kt
> +    init {
class layout에 맞게 위치를 변경해보면 어떨까요?

https://kotlinlang.org/docs/coding-conventions.html#class-layout

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/ExpressionParser.kt
> +        private set
둘다 불변 프로퍼티로 선언이 가능해보입니다!! 
가변으로 선언하신 이유가 있을까요?

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/ExpressionParser.kt
> +    private fun getCustomSeperator(inputExpression: String): String {
private 함수이지만 customSeprator 프로퍼티와 getter가 겹치게 될 것 같아요!! 다른 함수명으로 변경해주면 어떨까요?

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/ExpressionParser.kt
> +            arrayOf(",", ":", customSeperator[0].toString())
매직넘버가 많아보이네요! 상수로 변경해보면 어떨까요?

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        val numberArray = expressionParser.numberString.split(*expressionParser.customSeperator)
numberString을 꺼내오지말고, expressionParser에서 split까지 해주는건 어떨까요? 이렇게된다면 expressionParser의 클래스 명 변경도 고려해보면 좋겠군요!!

2023-06-17 04:44 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        for (i in numberArray) resultCalculator = add(resultCalculator, i)
코틀린 함수를 활용하면 더 간결하게 만들 수 있을 것 같아요!! 아래중에 하나를 선택해서 변경해보면 어떨까요?

* [sumOf](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/sum-of.html)
* [fold](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/fold.html)
* [reduce](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/reduce.html)

2023-06-17 04:44 UTC, vsh123 commented on src/test/kotlin/calculator/StringAddCalculatorTest.kt
> +    @ParameterizedTest
ParameterizedTest 👍

2023-06-17 15:06 UTC, goyounggyeong commented on src/main/kotlin/calculator/ExpressionParser.kt
> +class ExpressionParser(val inputExpression: String) {
calculator class가  expression을 호출 하기때문에 직접 선언하지 않았지만 아래 두 항목으로 테스트 하고 있습니다.

- 구분자를 컴마(,) 이외에 콜론(:)을 사용할 수 있다. expression
- "//"와 "\n" 문자 사이에 커스텀 구분자를 지정할 수 있다. expression

2023-06-17 15:08 UTC, goyounggyeong commented on src/main/kotlin/calculator/ExpressionParser.kt
> +class ExpressionParser(val inputExpression: String) {
inputExpression 변수를 파라미터로 선언하고 메소드에 이중으로 받고있는 inputExpression를 제거 하도록 변경했습니다.

2023-06-17 15:52 UTC, goyounggyeong commented
꼼꼼하게 봐주셔서 감사합니다.
리뷰해주신 내용을 반영해서 다시 코드리뷰 올렸습니다.
확인부탁드립니다 :)

2023-06-17 16:00 UTC, goyounggyeong commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +        for (i in numberArray) resultCalculator = add(resultCalculator, i)
와... 이코드 해결하니까 코드 라인수가 확 줄었어요. 좋은 팁 감사합니다.

2023-06-18 07:46 UTC, vsh123 approved these changes
안녕하세요!
피드백 반영 잘 해주셨네요! 💯 

추가적으로 코멘트 남겼으니 다음스텝에서 함께 반영해주시면 좋을 것 같아요!
빠른진행을 위해 이번 스텝은 머지하도록 할게요~

2023-06-18 07:46 UTC, vsh123 commented on src/main/kotlin/calculator/NumberExtractor.kt
> +class NumberExtractor {
해당클래스도 object클래스가 될 수 있겠네요!

2023-06-18 07:46 UTC, vsh123 commented on src/test/kotlin/calculator/StringAddCalculatorTest.kt
> +        assertThatExceptionOfType(RuntimeException::class.java).isThrownBy {
check()함수를 사용하면 IllegalStateException이 throw되는데요! 해당 테스트도 IllegalStateException를 검증하는게 더 좋아보입니다!

2023-06-18 07:46 UTC, vsh123 commented on src/main/kotlin/calculator/StringAddCalculator.kt
> +    fun sumByExpression(inputExpression: String?) =
return값을 명시해주면 어떨까요?

2023-06-18 07:46 UTC, merged