🚀 2단계 - 로또(자동)
next-step/kotlin-lotto pull request #667
Opened 2023-06-16 16:05 UTC by waveofmymind

안녕하세요 리뷰어님!
지난 1단계에서 말씀해주신 고려사항에 대해 나름 반영해보았습니다!
그리고 2단계를 구현해보았습니다.

항상 세심한 리뷰 감사합니다.
이번 단계도 잘 부탁드려요!

2023-06-18 00:51 UTC, namjackson requested changes
안녕하세요 상준님!
2단계 고생하셨습니다.
고민할법한 추가적인  포인트들 코멘트로 남겼으니, 확인해주세요!
변경사항 적용 후, 다시 리뷰요청해주시면 좋을거같아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +    fun start() {
start 함수가 너무 큰거 같아요! 함수를 나눠보아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoMatcher.kt
> +        }
> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다

depth가 2를 넘고 있어요! 프로그램 요구사항을 충족해주세요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/MatchResult.kt
> +    companion object {
companion object  의 위치는 클래스의 가장 아래에 작성해주세요!

https://kotlinlang.org/docs/coding-conventions.html#class-layout

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/MatchResult.kt
> +        )
map으로 관리하기보단 Enum 클래스를 사용해보면 어떨까요?

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/WinningNumbers.kt
> +data class WinningNumbers(val numbers: List<Int>)
WinningNumbers도 하나의 LottoNumbers라고 볼수 있지 않을까요?

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    }
랜덤영역에 대한 부분은 어떻게 테스트할수 있을지 고민해보아요!
(자동차 미션때 랜덤기능을 어떻게 구현했는지 생각해보아도 좋을거같아요)


로또 생성의 대한 책임을 가지는 클래스를 분리해보면 어떨까요?

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/domain/Lotto.kt
> +class Lotto private constructor(val lottoList: List<LottoNumbers>) {
Lotto가 아닌 복수형으로 표기하면 좋을거 같아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/MatchResult.kt
> +        )
MatchResult 클래스의 책임을 무엇일까요?
Prize 관련 책임을 분리해보아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoMatcher.kt
> +    companion object {
companion object만 있는 클래스라면, object로 구현하는거랑 차이가 없을거같아요!

개인적으로는 matchingLotto의 책임은 WinningNumbers가 가져야할 책임은 아닐까요?
고민해보셔도 좋을거같아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoMatcher.kt
> +        fun matchingLotto(lotto: Lotto, winningNumbers: WinningNumbers): Map<Int, Int> {
Map<Int, Int>은 무엇을 의미할까요?

MatchResult를 바로 리턴해주면 어떨까요?

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoMatcher.kt
> +                    if (winningNumbers.numbers.contains(number)) {
디미터 법칙을 준수하도록 코드를 작성해보셔도좋을거같아요!
객체의 내부의 데이터를 접근하여, 동작하기 보다, 
객체에게 메세지를 던져서, 객체가 일을하도록 작성되면 좋을거 같아요!

2023-06-18 00:51 UTC, namjackson commented on src/main/kotlin/lotto/view/ResultView.kt
> +        val earningRate = matchResult.calculateEarningRate(count * PER_LOTTO_PRICE)
View에서는 결과를 그려주는 이외의 로직은 수행하지 않도록 해보는건 어떨까요?

2023-06-18 23:50 UTC, waveofmymind commented
안녕하세요 리뷰어님!
말씀해주셨던 고려사항을 최대한 반영하려고 구현해보았습니다.

항상 세심한 리뷰 감사합니다.
이번 리뷰도 잘 부탁드리겠습니다!

2023-06-19 07:23 UTC, namjackson approved these changes
안녕하세요 상준님!
피드백 잘적용해주셨네요!
추가적으로 고민할법한 부분들 코멘트로 남겼으니, 확인해주세요! 
변경사항은 다음미션 진행하면서 적용해주시면 좋을거 같아요! 😄 
빠른 미션 진행을 위해 머지하겠습니다!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoGame.kt
> +        val lottos = Lottos.of(input, RandomLottoNumberGenerator())
Lottos보다는 generateLottos의 책임을 가지는, 로또 머신이나, 로또판매점 등의 객체를 생성해보면 어떨까요?

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/controller/MatchResult.kt
> +    private val matches: Map<Int, Int>
Map<Int, Int>라는 구조는 무엇인지 파악하기 힘든 구조인거 같아요
matchCount가 아닌 생성하신 Prize로 관리하면 어떨까요?
`Map<Prize,Int>`가 좀더 직관적이라는 생각이 들어요!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/controller/WinningNumbers.kt
> +        }
컬렉션의 groupingBy , eachCount등의 함수들이 있으니, 참고해보셔도 좋을거같아요!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    val lottoNumbers: List<Int> = numberGenerator.generateNumbers()
로또 생성에 대한 책임을 분리해봐도 좋을거같아요!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/Lottos.kt
> +        const val PER_LOTTO_PRICE = 1000
외부에서 사용하지 않는다면 private을 기본으로 해주셔도 좋을거같아요!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/Prize.kt
> +    SIXTH(6, 2000000000);
숫자가 너무커서 읽기 힘든경우에는 아래처럼 표기도 가능합니다.
```suggestion
    SIXTH(6, 2_000_000_000);
```

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/Prize.kt
> +    SIXTH(6, 2000000000);
1등,2등 등의 네이밍이 아닌 
matchCount 기반의 네이밍이네요!
matchCount는 요구사항에 따라 변경될수 있지 않을까요? 
도메인에 맞는 네이밍을 지어봐도좋을거같아요!

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/Prize.kt
> +            return values().find { it.matchCount == matchCount }
prize에 당첨되지 않은 항목도 있으면 어떨까요?

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/Prize.kt
> +        }
calculateTotalPrice는 MatchResult에서 해야할일 아닐까요?

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/numberGenerator/RandomLottoNumberGenerator.kt
> +    }
companion object 은 항상 클래스의 가장 아래에 위치해주세요! 
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2023-06-19 07:23 UTC, namjackson commented on src/main/kotlin/lotto/domain/numberGenerator/RandomLottoNumberGenerator.kt
> +    }
매번 숫자를 랜덤으로 만들어주고, 로또 번호를 생성해주기보다,
로또번호객체들을 생성해놓고 재활용하도록 해보면어떨까요?

2023-06-19 07:23 UTC, merged