[step1] refactor: CustomDelimiter에서 Regex를 한번만 생성하도록 수정
next-step/kotlin-lotto pull request #670
Opened 2023-06-16 18:11 UTC by neity16

[step1 PR] : https://github.com/next-step/kotlin-lotto/pull/636
리뷰 잘 부탁드립니다.
감사합니다🙌

2023-06-17 11:15 UTC, sah3122 requested changes
자동로또 구현 잘해주셨네요 👍 
몇가지 생각거리들과 이전 PR의 코멘트 추가해두었는데 확인 부탁드립니다. 😄 
주말 잘 보내세요 !

2023-06-17 11:15 UTC, sah3122 commented on src/main/kotlin/lotto/Lotto.kt
> +    fun renderLotto(outputView: OutputView)
도메인 객체와 UI Layer간의 결합을 없애보는것을 권장 드립니다. 
UI Layer를 위한 값 객체를 선언하여 전달하는 연습을 해보세요 😄

2023-06-17 11:15 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLotto.kt
> +class SixFortyFiveLotto(val numbers: List<Int>) : Lotto<List<Int>, Int> {
로또 객체가 Store를 통하지 않고 생성된다면 1부터 45까지 번호를 보장하고 중복이 없는 6개의 번호를 가질수 있을까요 ?

2023-06-17 11:15 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLottoStore.kt
> +        val LOTTO_WINNING_PRICE_MAP = listOf(0, 0, 0, 5000, 50000, 1500000, 2000000000)
당첨 금액을 관리하는 enum class를 정의해보는건 어떨까요 ?

2023-06-17 11:15 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLottoStore.kt
> +            randomNumberSet.add(randomNumber)
1부터 45까지 번호를 보장하는 LottoNumber 클래스를 정의해보세요 😄

2023-06-17 11:15 UTC, sah3122 commented on src/main/kotlin/lotto/view/output/SixFortyFiveResultOutputView.kt
> +                  """
요구사항이 변경될때마다 해당 로직은 영향을 많이 받게 됩니다. 
정적인 텍스트 보단 텍스트의 중복을 제거해볼수 있을까요 ?

2023-06-17 15:03 UTC, neity16 commented on src/main/kotlin/lotto/SixFortyFiveLotto.kt
> +class SixFortyFiveLotto(val numbers: List<Int>) : Lotto<List<Int>, Int> {
`LottoNumber` 클래스를 정의하고 해당 로또가 `1~45` 사이의 중복되지 않는 `6`개의 수를 가질 수 있도록 수정하겠습니다.
좋은 의견 감사합니다👍

2023-06-17 15:38 UTC, neity16 commented on src/main/kotlin/lotto/Lotto.kt
> +    fun renderLotto(outputView: OutputView)
값 객체를 선언하여 전달하는 것이 잘 이해가 되지 않아서
혹시 괜찮으시다면 예시코드로 설명해주시면 감사하겠습니다🙇‍♂️

2023-06-18 04:30 UTC, neity16 commented on src/main/kotlin/lotto/Lotto.kt
> +    fun renderLotto(outputView: OutputView)
혹시 아래처럼 `OutputView` 라는 추상체에만 의존하도록 하고 내부에서는 `renderMessage()`를 호출해주는 형식을 말씀주신걸까요?

```kotlin
interface LottoStore<T, V> {
    fun renderWinningInsight(renderOutputView: () -> OutputView)
	...(생략)
}
```

2023-06-18 09:35 UTC, sah3122 commented on src/main/kotlin/lotto/Lotto.kt
> +    fun renderLotto(outputView: OutputView)
Lotto 라는 도메인 객체와 OutputView 와의 접점을 없애기 위해 출력에 필요한 값들을 가지고 있는 객체를 선언하여 OutputView 로 전달하는것이 어떨지에 대한 코멘트 였습니다 😄

2023-06-18 09:51 UTC, sah3122 requested changes
피드백 반영 잘해주셨습니다 👍 
다음 미션을 진행하기전 몇가지 고민거리를 추가로 남겨두었는데 확인 부탁드려요 🙏

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLottoNumber.kt
> +class SixFortyFiveLottoNumber(val value: List<Int>) {
로또 번호를 나타내는 클래스는 List 가 아닌 번호 하나로 정의하는것이 어떨까요 ?
`SixFortyFiveLottoNumber`라는 클래스 네이밍은 로또에서 사용되는 번호를 유추할수 있고, 로또는 로또 번호를 여러개 가지는것을 유추 할수 있어요 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLotto.kt
> +class SixFortyFiveLotto(val numbers: SixFortyFiveLottoNumber) : Lotto<SixFortyFiveLottoNumber, Int> {
로또 객체가 6개의 로또 번호를 가지는것을 녹인다면 `List<SixFortyFiveLottoNumber>`를 정의하는것이 자연스럽겠네요 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLotto.kt
> +        const val LOTTO_PRICE = 1000
LOTTO_PRICE 라는 상수는 사용하는 클래스에서 선언할수 있다면 불필요한 결합을 낮출수 있을것 같습니다 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLottoNumber.kt
> +            }
로또 번호는 매번 동일한 범위의 숫자를 보장할수 있으니 매번 생성하지 않고, 캐싱된 값을 전달하는것도 좋을것 같네요 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/view/output/SixFortyFiveResultOutputView.kt
> +        }
피드백 반영 잘해주셨습니다 👍 
한가지 아쉬운점은 아직 UI Layer에 비즈니스 로직이 남아있는것 같습니다. 
로또 당첨 결과를 담고 있는 객체만 파라미터로 전달 받아 출력할수 있는 구조로 리팩토링 해보세요 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/view/output/SixFortyFiveResultOutputView.kt
> +        (3..6).forEach { index ->
당첨되지 않은 로또정보를 담고 있지 않는다면 조금더 간단히 표현할수 있을것 같아요 😄

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveWinningPrice.kt
> +enum class SixFortyFiveWinningPrice(val price: Int) {
enum 정의 👍 
당첨에 대한 정보(몇개가 일치하는지)도 추가하여 당첨금을 구하는 로직을 해당 enum 클래스로 옮겨볼수 있을까요 ?

2023-06-18 09:51 UTC, sah3122 commented on src/main/kotlin/lotto/SixFortyFiveLottoStore.kt
> +        )
SixFortyFiveWinningPrice 의 값을 외부에 노출하기 보단, SixFortyFiveWinningPrice의 메서드를 정의하여 메시지를 던져보세요 😄

2023-06-18 12:10 UTC, neity16 commented on src/main/kotlin/lotto/SixFortyFiveLotto.kt
> +        const val LOTTO_PRICE = 1000
로또의 가격은 각 `Lotto`의 종류에 따라 결정되는 수이기 때문에 `Lotto`에 위치하는 것이 자연스러울 것 같다는 생각입니다🤔

2023-06-18 12:12 UTC, sah3122 approved these changes
남겨드린 코멘트는 다음 미션 진행하시면서 확인 부탁드립니다 👍

2023-06-18 12:12 UTC, merged

2023-06-18 12:21 UTC, neity16 commented on src/main/kotlin/lotto/SixFortyFiveLottoStore.kt
> +        )
해당 로직은 `step3`에서 별도 `enum`의 `valueOf` 메서드로 추출하여 생략하겠습니다☺️