1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #672
Opened 2023-06-17 04:35 UTC by sksskaw

안녕하세요 리뷰어님! 이번 미션 잘 부탁드립니다~

본격적인 TDD미션이 시작됐습니다
요구사항을 처리할 수록 기존에 작성했었던 테스트 코드를 수정해야되는 경우가 계속 발생되는군요..ㅠ
그만큼 처음에 작성하는 테스트 코드를 잘 짜야 할 것 같네요

2023-06-17 13:55 UTC, saintbeller96 requested changes
안녕하세요!
문자열 덧셈 계산기 잘 구현해주셨습니다👍👍
로또 미션에 들어가기 전, 한 번쯤 고민해보셨으면 좋을 것 같은 부분이 있어 관련된 피드백을 남겼습니다!
확인해 보신 후에 리뷰 요청 부탁드려요🙂

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/ParsedStringValidator.kt
> +) {
일반적으로 `XXXValidator`에 기대하는 기능은 검증할 대상을 전달하고 그 값이 유효한지를 확인하는 기능인 것 같아요.
그런 점에서 `ParsedStringValidator`가 `검증할 대상`을 상태로 가지고 있는 건 어색하다고 생각합니다🥲
만약 다른 문자열을 검증해야 하는 경우가 생기면 `ParsedStringValidator`를 새로 생성해야 할 것 같아요.
검증 대상을 상태로 가지는 대신 함수의 인자로 받도록 만들면 어떨까요?
```kotlin
val valid = parsedStringValidator.isValid(parsedString)
```

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/ParsedStringValidator.kt
> +    }
이 함수들은 문자열 리스트 속 원소를 `음수가 아닌 숫자`로 변환가능한지 확인하는 책임을 가지고 있는 것처럼 보여요🙂
`음수가 아닌 숫자`라는 타입을 새로 정의해보는 건 어떨까요? 자연스럽게 관련된 책임을 해당 객체로 이동할 수 있을 것 같아요.

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringCalculator.kt
> +}
마찬가지로 StringCalculator가 연산할 대상을 상태로 가지고 있는게 어색해보여요.
위 코멘트에서 언급한 것처럼 프로퍼티 대신 함수의 인자로 받게끔 수정해보면 어떨까요??

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringParser.kt
> +            ?: return inputString.split(":", ",")
기본 구분자는 변하지 않는 값인만큼 상수로 관리하면 어떨까요?

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringParser.kt
> +    }
1. check라는 함수 이름은 일반적으로 어떤 값을 확인한 후 Unit이나 예외를 던지는 함수를 나타내요.(검증 시 사용하는 `check()` 함수를 생각해보시면 좋을 것 같아요) 이 함수는 문자열에서 커스텀 구분자를 추출하는 책임을 가졌으니 그 의미를 잘 드러내는 함수 이름으로 바꿔보면 어떨까요?
2. `Regex(CUSTOM_SEPARATOR_PATTERN)` 또한 변하지 않는 값이니 상수로 관리해주시면 좋을 것 같습니다!
3. 코틀린의 get 함수가 오퍼레이터라면 다음과 같이 사용할 수 있어요.
```kotlin
return matchResult?.groupValues[1]
```

2023-06-17 13:55 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringParser.kt
> +        const val CUSTOM_SEPARATOR_PATTERN = """//(.*)\n"""
외부에서 사용하지 않는 프로퍼티는 `private`으로 관리되면 좋을 것 같아요🙂

2023-06-19 03:53 UTC, saintbeller96 requested changes
안녕하세요!
피드백 반영 잘 해주셨습니다👍
다만 몇가지 피드백은 아직 반영되지 않은 것 같아요🥲
로또 미션으로 들어가기 전에 한 번 더 생각해보셨으면 하는 부분이 있어 의견을 추가했습니다.
혹시 다른 의견을 가지고 계시거나 이해가 잘 되지 않는다면 편하게 말씀주셔도 좋습니다!
한 번 확인해보시고 다시 리뷰 요청 부탁드려요🙂

2023-06-19 03:53 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/ParsedStringValidator.kt
> +class ParsedStringValidator {
상태를 가지지 않는다면 object로 관리해주는 건 어떨까요?

2023-06-19 03:53 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/ParsedStringValidator.kt
> +    }
이번 미션의 요구사항 중 하나로 depth가 2를 넘기면 안되는 조건이 있습니다.
forEach 안에 try 문이 추가됨에 따라 depth가 2가 되었어요🥲

2023-06-19 03:53 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/ParsedStringValidator.kt
> +        return !parsedString.any { it.toInt() < 0 }
이런 경우 any 대신 none을 사용할 수 있습니다.
```suggestion
        return parsedString.none { it.toInt() < 0 }
```

2023-06-19 03:53 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringCalculator.kt
> +        check(ParsedStringValidator().check(parsedStringList)) {
StringCalculator는 입력받은 문자열이 유효한지를 판단하기 위해 ParsedStringValidator와 협력하고 있어요.
이런 협력 관계를 잘 나타내기 위해 StringCalculator의 생성자를 통해 PasedStringValidator를 주입받도록 하면 어떨까요?

2023-06-19 03:53 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringParser.kt
> +    }
3번째 답변은 제가 잘못 답변했네요..🥲
non-null 타입에서만 get 오퍼레이터로 사용할 수 있군요.
그렇다면 다음과 같이 nullable 한 값을 위에서 빠르게 제거해주는 방식도 좋을 것 같아요.
```suggestion
         val matchResult = pattern.find(inputString) ?: return null
         return matchResult.groupValues[1]
```

2023-06-19 06:49 UTC, sksskaw commented
했었던 생각의 흐름

ParsedStringValidator를 object로 수정했는데
StringCalculator의 생성자로 주입해야 할까?
협력관계를 나타내기 위함이라면 필드변수로 의존성주입 해버려도 되지 않을까?
왜 생성자로 주입하라고 피드백 주셨을까??

validator가 인터페이스라면?
검증기가 어려개라면?
아 이러면 생성자로 주입 받아야겠구나

// 아니면 또다른 이유가 있었을까요?


질문
상태가 없는 객체는 전부 object로 생성하는게 맞을까요?
StringParser도 상태가 없는데 object로 했어야 할까요?

2023-06-20 01:11 UTC, sksskaw commented on src/main/kotlin/stringCalculator/StringPositiveNumber.kt
> +}
문자가 양수인지 전에 숫자로 변환이 가능한지 체크하는부분은 어디에서 해주어야 하나요??

2023-06-20 01:35 UTC, saintbeller96 commented
> 했었던 생각의 흐름
> 
> ParsedStringValidator를 object로 수정했는데 StringCalculator의 생성자로 주입해야 할까? 협력관계를 나타내기 위함이라면 필드변수로 의존성주입 해버려도 되지 않을까? 왜 생성자로 주입하라고 피드백 주셨을까??
> 
> validator가 인터페이스라면? 검증기가 어려개라면? 아 이러면 생성자로 주입 받아야겠구나
> 
> // 아니면 또다른 이유가 있었을까요?
> 
> 질문 상태가 없는 객체는 전부 object로 생성하는게 맞을까요? StringParser도 상태가 없는데 object로 했어야 할까요?

1. 말씀주신 것처럼 생성자 주입은 객체에 유연성을 제공하는 등의 장점을 가지고 있어요. 예를 들면, 주입받은 객체와 같은 타입의 객체를 코드 변경 없이도 자유롭게 변경할 수 있습니다.(전략 패턴, Mocking 등)

2. 객체를 인스턴스로 만들었을 때, 각 인스턴스가 구분될 필요가 있는지 없는지 고민해보시면 좋을 것 같아요.

예를 들어 동일한 상태를 가지는 리스트 2개를 생성해보겠습니다.
```kotlin
val list1 = listOf(1)
val list2 = listOf(1)
```
이 두 리스트는 같은 인스턴스로 볼 수 있을까요?

반대로 지난 미션에서 enum으로 정의했던 사칙연산을 보겠습니다.
(object보다 더 적합한 예시라고 생각해서 enum을 예시로 들었는데요, object와 enum은 둘 모두 싱글턴으로 생성됩니다)
```kotlin
enum class Operator(val symbol: String) {
    PLUS("+")
    // 생략
}

val op1 = Operation.PLUS
val op2 = Operation.PLUS
```
이 때 op1 과 op2는 다른 인스턴스일까요?

이렇게 인스턴스로 만들었을 때 구분할 필요가 있는지 없는지를 고려해보시고 구분할 필요가 없다면 object를, 구분할 필요가 있다면 class를 사용하시면 좋을 것 같습니다.
(대부분 상태가 없다면 object가 더 적합한 경우가 많더라구요.)
비슷한 문제로 enum을 사용할 때와 sealed class를 사용할 때도 고민해보시면 좋을 것 같아요!

2023-06-20 01:35 UTC, merged

2023-06-20 01:52 UTC, saintbeller96 commented on src/main/kotlin/stringCalculator/StringPositiveNumber.kt
> +}
6번째 줄에서 숫자로 변환할 수 있는지 파악하는 로직이 추가되면 될 것 같아요.
저는 아래처럼 표현하는 것을 선호하는데요,
```kotlin
    constructor(value: String) : this (
        value.toIntOrNull() ?: throw IllegalArgumentException("숫자로 변환할 수 없습니다")
    )
```
require나 requireNotNull을 사용해주셔도 좋을 것 같아요.