Step2 - 로또(자동)
next-step/kotlin-lotto pull request #675
Opened 2023-06-17 07:16 UTC by maenguin

안녕하세요 리뷰어님
이번에는 라이브 세션에서 배운 TDD 방법론을 사용해봤습니다.
클래스 보다 테스트를 먼저 생각하게 되니 좀 더 객체의 역할과 책임이 명확해지고 변경에 유연한 구조가 나오는것 같습니다. 
덕분에 재미있게 구현할 수 있었습니다.

제가 이번주는 출장과 야근 때문에 과제를 많이 못해서 아마 이번주 끝나도 리뷰어님을 계속 찾게 될것 같습니다 ㅎㅎ...

2023-06-17 17:40 UTC, Flamme1004K requested changes
안녕하세요!

로또 구현 고생하셨습니다! TDD로 구현하시는 모습이 매우 인상 깊네요. 

로또 미션 피드백과 저번에 드린 피드백에 대한 반영 내역 확인 부탁드립니다 😊

화이팅입니다! 🙌

2023-06-17 17:40 UTC, Flamme1004K commented on README.md
> +- [x] 로또 입출력 기능을 구현한다
👍👍

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/InputView.kt
> +        return readln().split(", ").map { it.toInt() }.toSet()
<img width="985" alt="스크린샷 2023-06-18 오전 2 23 25" src="https://github.com/next-step/kotlin-lotto/assets/50702723/fa4b4ee8-ab45-402b-a750-e358b7656515">

', '에  대해서 trim을 하는게 더 좋지 않을까요?

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/ResultView.kt
> +        println("총 수익률은 ${earningsRate}입니다.")
(기준이 1이기 때문에 결과적으로 손해라는 의미임)

라는 문구도 상황에 따라 추가해보세요!

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/Main.kt
> +    resultView.outputEarningsRate(earningsRate)
```suggestion
    val seedMoney = inputView.inputSeedMoney()
    val issuedLottos = lottoSeller.sell(seedMoney)
    resultView.outputIssuedLottos(issuedLottos)

    val winningNumbers = inputView.inputWinningNumbers()
    val lottoMatchStat = issuedLottos.check(Lotto(winningNumbers))
    resultView.outputLottoMatchStat(lottoMatchStat)

    val earningsRate = lottoMatchStat.calculateEarningsRate(seedMoney)
    resultView.outputEarningsRate(earningsRate)
```

개인적으로 코틀린의 타입 추론에 대해서 타입은 생략해도 좋다고 봅니다.

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +data class IssuedLottos(val lottos: List<Lotto>) {
일급 컬렉션 사용 👍

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +}
당첨에 대한 룰을 enum으로 리팩토링해도 괜찮지 않을까요~?

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        val randomSixNumbers = List(MAX_LOTTO_NUMBER) { it + 1 }
it + 1을 지울 수는 없을까요?

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +data class Lotto(
Lotto와 LottoMachine class는 분리해줘도 좋을 것 같습니다. 저 같은 경우에는 클래스 간 연관 관계에 대해서는 코틀린 파일을 따로 놓고 있습니다.

2023-06-17 17:40 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        return numbers.intersect(winningLotto.numbers).size
오.. intersect 사용 👍

2023-06-17 17:40 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoMatchStatTest.kt
> +internal class LottoMatchStatTest {
더 다양한 이자율 테스트를 할 수 있지 않을까요~?

2023-06-19 05:40 UTC, maenguin commented on src/main/kotlin/lotto/view/InputView.kt
> +        return readln().split(", ").map { it.toInt() }.toSet()
커밋 [1319db8](https://github.com/next-step/kotlin-lotto/pull/675/commits/1319db83303be75cd614a8e12f5d7ef100fd65d4) 으로 반영했습니다.
꼼꼼하게 봐주셔서 감사합니다

2023-06-19 05:41 UTC, maenguin commented on src/main/kotlin/lotto/view/ResultView.kt
> +        println("총 수익률은 ${earningsRate}입니다.")
커밋 [45c2ff1](https://github.com/next-step/kotlin-lotto/pull/675/commits/45c2ff129a43efe8ef3822596ccf3cc268e66d9e)으로 반영했습니다 👍

2023-06-19 05:43 UTC, maenguin commented on src/main/kotlin/lotto/Main.kt
> +    resultView.outputEarningsRate(earningsRate)
개인적으로 클래스 선언 혹은 팩토리 메서드를 사용하는 경우가 아니라면 타입 파악을 위해 타입을 붙이는 편입니다.

2023-06-19 05:44 UTC, maenguin commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        val randomSixNumbers = List(MAX_LOTTO_NUMBER) { it + 1 }
커밋 [d42fd65](https://github.com/next-step/kotlin-lotto/pull/675/commits/d42fd65254e8b9823fe68004c08d2e5d452a2731) 으로 반영했습니다.
말씀주신게 이게 맞는지 모르겠지만 리뷰어님 덕분에 더욱 코틀린 다워진것 같습니다.

2023-06-19 05:44 UTC, maenguin commented on src/main/kotlin/lotto/domain/Lotto.kt
> +data class Lotto(
커밋 [d42fd65](https://github.com/next-step/kotlin-lotto/pull/675/commits/d42fd65254e8b9823fe68004c08d2e5d452a2731)으로 반영했습니다

2023-06-19 05:45 UTC, maenguin commented on src/test/kotlin/lotto/domain/LottoMatchStatTest.kt
> +internal class LottoMatchStatTest {
커밋 [3ca1402](https://github.com/next-step/kotlin-lotto/pull/675/commits/3ca1402f76ebe5d19a3b0764e9b8bc1cfdb465bc)으로 반영했습니다

2023-06-19 05:45 UTC, maenguin commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +}
커밋 [3ca1402](https://github.com/next-step/kotlin-lotto/pull/675/commits/3ca1402f76ebe5d19a3b0764e9b8bc1cfdb465bc)으로 반영했습니다

2023-06-19 05:45 UTC, maenguin commented on src/test/kotlin/lotto/domain/LottoMatchStatTest.kt
> +internal class LottoMatchStatTest {
step2 피드백을 반영하고 나서 저번에 반영하지 못한 step1 피드백을 반영했습니다~!

2023-06-19 05:46 UTC, maenguin commented
step2 피드백을 반영하고 나서 저번에 반영하지 못한 step1 피드백을 반영했습니다~!

2023-06-19 15:16 UTC, Flamme1004K commented on src/main/kotlin/lotto/Main.kt
> +    resultView.outputEarningsRate(earningsRate)
오호 그렇군요! 저 같은 경우에는 메서드 제외하고는 타입을 모두 생략하고 있어서요! 이 부분은 스타일 차이겠군요 😊

2023-06-19 15:20 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +)
꼭 해당 클래스가 필요할까요? LottoRank의 List를 반환하는 것만으로도 충분하지 않을까합니다.

2023-06-19 15:20 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        val matchCount = numbers.intersect(winningLotto.numbers).size
intersect 사용 👍

2023-06-19 15:24 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoRank.kt
> +            return values().find { it.matchCount == matchCount } ?: MISS
👍

2023-06-19 15:24 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +internal class LottoTest {
상세한 테스트 케이스 👍

2023-06-19 15:26 UTC, merged

2023-06-21 07:51 UTC, maenguin commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +)
해당 로직을 클라이언트에 위임해도 무방해서 짚어주신대로 없어도 되는 클래스가 맞습니다.
일단 통계처리를 서비스에서 처리했다고 가정하고 만들어봤습니다.

2023-06-21 07:52 UTC, maenguin commented on src/main/kotlin/lotto/domain/Lotto.kt
> +}
넵 빼도록 변경했습니다.
저번에 말씀주신것 같은데 리뷰어님은 파일안에 클래스를 어떤 경우에 여러개 두시나요?
저는 엔티티-밸류 관점에서 밸류인경우에는 보통 파일내에 두는 편입니다.
현재 경우에는 별로 맞지 않았죠

2023-06-21 15:00 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +}
저는 도메인 클래스에 대해서는 다 따로두는 편이에요. 왜냐하면 한 눈으로 보면서 바로바로 파악할 수 있기 때문이에요.

단 일급 컬렉션 같은 경우에는 연관 된 클래스와 같이 두고 있습니다. 지금 미션에 대한 요구사항에 대해서는 일급 컬렉션에 대해 강제하고 있지만, 실전에서는 일급 컬렉션에 대해서 너무 과도하게 사용하다보면 덩치가 커지는 케이스들이 몇몇 보여서 상황에 따라서 추가하고 삭제하기 편하게 같이 두는 편이에요.