[Step2] 로또(자동)
next-step/kotlin-lotto pull request #700
Opened 2023-06-18 14:25 UTC by graygreat

안녕하세요~~
과제가 좀 늦어졌네요.

당첨 통계를 내는 부분에서 시간을 좀 많이 잡아 먹은 것 같네요.
이번 리뷰도 잘 부탁드립니다!

2023-06-18 23:37 UTC, Flamme1004K requested changes
안녕하세요!

로또 게임 구현 잘 해주셨습니다! 👍👍 TDD로 구현하시는 모습 매우 인상 깊었습니다!

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

화이팅입니다! 🙌

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/Separator.kt
> +            val regexResult = Regex(REGEX_PATTERN).find(text)
Regex(REGEX_PATTERN) 을 상수화 시키면 매번 생성할 필요가 없지 않을까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/Separator.kt
> +            return Separator(customSeparator.toString())
```suggestion
            return Separator(customSeparator.toString())
```

`toString()`으로 한다면 customSeparator가 null인 경우에 "null"을 반환하겠죠? 코틀린에서는 null은 매우 중요해요.
null이 왜 중요할까요? 그리고 null을 어떻게 해야피할 수 있을까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/Separators.kt
> +    fun getSeparators() = separators
아이고! https://github.com/next-step/kotlin-lotto/pull/657#discussion_r1232371795 기억하시나요?

한번 더 고민해보시길 바래요! 😊

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/TokenizedExpression.kt
> +        println(splitData)
println은 지워줘도 되겠죠~?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/TokenizedExpression.kt
> +            MESSAGE_CONTAIN_NEGATIVE
require 사용 👍👍

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/LottoApplication.kt
> +    val lottoController = LottoController(LottoGenerator(), LottoStatistics())
로또 생성기와, 로또 전략을 주입하는 모습 👍

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/README.md
> +## 기능 목록
요구사항 정리 👍

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return inputPayment / LOTTO_PRICE
inputPayment로 지으신 이유가 궁금하네요 : )

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        val numbers = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER).toList()
로또 번호들이 미리 생성되어지도록 만들어볼까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +value class LottoNumber(
value class 사용 👍

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    }
equals,hashCode를 재정의한 이유를 듣고 싶습니다! 😊

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lottos.kt
> +)
MutableList는 외부에서 수정이 가능하죠. 외부에서는 읽기만 가능하도록 변경해볼까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Rank.kt
> +        }
intersects를 사용해볼까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/InputView.kt
> +        val winnerNumbers = readln().split(", ")
<img width="975" alt="스크린샷 2023-06-19 오전 8 34 50" src="https://github.com/next-step/kotlin-lotto/assets/50702723/da2e117d-1f75-4c8a-9a63-7041fd3d3930">

trim을 해주면 더 좋지 않을까요?

2023-06-18 23:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/OutputView.kt
> +        println(String.format("총 수익률은 %.2f입니다.", profitRate))
- 기준이 1이기 때문에 결과적으로 손해라는 의미임

라는 부분이 빠졌네요 😱

2023-06-18 23:37 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoGeneratorTest.kt
> +class LottoGeneratorTest : StringSpec({
테스트 케이스 👍👍

2023-06-19 00:01 UTC, graygreat commented on src/main/kotlin/calculator/domain/Separator.kt
> +            val regexResult = Regex(REGEX_PATTERN).find(text)
이렇게 되면 Seprator가 생성될 때 마다 생성되긴 하겠네요.
패턴에 이름을 주기 위해서 상수화 시켜줬는데 그냥 Regex 안에 박아 두는 것도 좋을 것 같네요.

2023-06-19 00:21 UTC, graygreat commented on src/main/kotlin/calculator/domain/Separator.kt
> +            return Separator(customSeparator.toString())
우선 null 이 중요한 이유는 kotlin은 자바와 다르게 null을 처리할 수 있는 타입이 따로 제공됩니다. 그렇기 때문에 nullable 하지 않은 변수에 null이 들어오면 문제가 생기게 됩니다.
해결 방안은 nullable 타입으로 변경하거나 엘비스 연산자와 같이 안전하게 호출할 수 있도록 변경하면 될 것 같습니다.

2023-06-19 00:36 UTC, graygreat commented on src/main/kotlin/calculator/domain/Separators.kt
> +    fun getSeparators() = separators
Separator, Separators를 없애고 정규식으로 요구사항 충족하도록 했습니다.

2023-06-19 00:38 UTC, graygreat commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return inputPayment / LOTTO_PRICE
이름 그대로 입력받은 지불금액 이라는 뜻입니다 :)
근데 적다보니 그냥 payment로 해도 되겠군요 ㅎ

2023-06-19 00:40 UTC, graygreat commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        val numbers = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER).toList()
companion object로 뺐습니다!

2023-06-19 00:43 UTC, graygreat commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +    }
로직 구현할 때, 두 가지 방법을 생각했었습니다.
1. data class에서 toString만 오버라이딩
2. class에서 equals, hashcode, toString 모두 오버라이딩

data class는 이미 오버라이딩 되어 있는데 또 오버라이딩 하는 것 보단 class에서 모두 새롭게 오버라이딩 해주는게 더 좋다고 생각하였습니다.

2023-06-19 01:17 UTC, graygreat commented on src/main/kotlin/lotto/domain/Rank.kt
> +        }
오호 교집합을 구할 수 있는 함수네요 :)
사용해보겠습니다

2023-06-19 14:59 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/Separator.kt
> +            return Separator(customSeparator.toString())
좋아요! 그거에요 : ) 저는 항상 null에 대해 안전하도록 코드를 짜고 있습니다 + ㅁ+

2023-06-19 15:05 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 💯

step2 고생하셨습니다! 🙌 이만 머지하도록 하겠습니다!

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

미션 화이팅입니다! 🤩

2023-06-19 15:05 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/TokenizedExpression.kt
> +        val regexResult = Regex("""(?:\/\/(.)\n)*(.*)""").find(text)
Regex("""(?:\/\/(.)\n)*(.*)""")를 매번 생성할 필요 없이 미리 생성하는게 더 좋지 않을까요?

2023-06-19 15:05 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        private val LOTTO_NUMBERS = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER).toList()
맞아요! 제가 원했던 부분이였습니다! 잘하셨어요 : )

2023-06-19 15:05 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +        return ranks
map을 사용한다면 mutableListOf를 선언 안해줘도 괜찮을 것 같은데 해볼까요?

2023-06-19 15:06 UTC, merged