2단계 - 로또(자동)
next-step/kotlin-lotto pull request #704
Opened 2023-06-18 15:56 UTC by yeonsuyang

잘부탁드립니다!!

2023-06-19 14:58 UTC, Flamme1004K requested changes
안녕하세요!

로또 게임 구현 잘 해주셨습니다! 👍👍

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

화이팅입니다! 🙌

2023-06-19 14:58 UTC, Flamme1004K commented on src/main/kotlin/calculator/domain/Calculator.kt
> +        val numbers = getNumbers(text)
getNumbers(text)를 한다면 String이 아닌 숫자가 나와야하는게 아닐까요?

2023-06-19 14:58 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Bank.kt
> +        val revenue = winningScore.keys.sumOf { winningScore[it]?.times(it.reward) ?: 0 }
!! 와 ?: 를 제거해볼까요?

2023-06-19 14:58 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +        return (LOTTO_START_NUM..LOTTO_LAST_NUM).toList().shuffled().take(LOTTO_NUM_COUNT).sorted()
1 ~ 45의 로또를 미리 만들어 놓을 수는 없을까요?

2023-06-19 14:58 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Rank.kt
> +        fun getValue(count: Int): Rank? {
Null을 반환하는 것보다는 아무것도 해당하지 않는 enum을 만드는게 낫지 않을까요?

enum은 때때로 null을 회피하기 위한 방법으로도 쓰인답니다.

2023-06-19 14:58 UTC, Flamme1004K commented on src/main/kotlin/lotto/view/ResultView.kt
> +            println(LOSS_STRING)
👍

2023-06-19 14:58 UTC, Flamme1004K commented on README.md
> +- [x] 자동 생성된 로또의 번호를 출력한다. -> ResultView
요구사항 정리 👍

2023-06-20 03:55 UTC, yeonsuyang commented on src/main/kotlin/lotto/domain/Bank.kt
> +        val scores = tickets.mapNotNull { Rank.getValue(winningTicket.score(it)) }
어느부분에서 교집합을 이용해야하는것인지 잘 이해하지 못하였습니다ㅠㅠ!

2023-06-20 12:34 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Bank.kt
> +        val scores = tickets.mapNotNull { Rank.getValue(winningTicket.score(it)) }
winningTicket과 tickets를 교집화시킨다면 교차되는 LottoNumber의 수를 알 수 있지 않을까요~?

2023-06-20 12:49 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 💯

step2 고생하셨습니다! 🙌 이만 머지하도록 하겠습니다!

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

미션 화이팅입니다! 🤩

2023-06-20 12:49 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Bank.kt
> +    fun calculateRateOfReturn(money: Int, score: Map<Rank, Int>): Float {
Map이 아닌 List 형태이면 계산 로직을 더 가볍게 만들 수 있지 않을까요?

2023-06-20 12:49 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +class ShuffleNumGenerator : LottoNumGenerator {
ShuffleNumGenerator보다 자동이라는 뜻이 더 잘 어울리지 않을까요?

2023-06-20 12:49 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +    internal fun `로또의 숫자는 6개이며 모든 숫자는 1과45의 사이이다`() {
반대 상황에 대한 테스트는 없을까요?

2023-06-20 12:49 UTC, merged

2023-06-21 07:37 UTC, yeonsuyang commented on src/main/kotlin/lotto/domain/Bank.kt
> +        val scores = tickets.mapNotNull { Rank.getValue(winningTicket.score(it)) }
해당 부분에 저는 .count { this.nums.contains(it) } 를 사용하였는데, 
lotto.numbers.intersect(nums.toSet()).size 와 큰 차이가 있을까요?

2023-06-21 07:39 UTC, yeonsuyang commented on src/main/kotlin/lotto/domain/Bank.kt
> +    fun calculateRateOfReturn(money: Int, score: Map<Rank, Int>): Float {
저는, 각 RANK와 해당하는 count를 맵으로 저장하였는데 List형태는 Rank에 count도 들어갈수 있도록 추천해주시는걸까요?

2023-06-21 13:03 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Bank.kt
> +    fun calculateRateOfReturn(money: Int, score: Map<Rank, Int>): Float {
Map보다는 List를 선호한 이유는 Map을 이용한 계산 로직은 항상 null에 대한 체크를 해줘야하며, 체크를 한 후에 그에 대한 값을 가져와야하는 부분을 볼 수가 있죠. 하지만 리스트를 사용한다면 존재하는 Rank에 대해서 sum이나 map과 같은 연산에 도움이 되는 메서드를 사용할 수 있기 때문이였습니다.