Step2 - 로또(자동)
next-step/kotlin-lotto pull request #709
Opened 2023-06-19 02:30 UTC by ohsung

안녕하세요.
범준님

리뷰 부탁드립니다.

감사합니다.

2023-06-19 11:39 UTC, ddaaac requested changes
안녕하세요 성오님 👋 

전반적으로 구현을 깔끔하게 해주셨네요.

몇 가지 코멘트 남겼으니 확인해주세요~

2023-06-19 11:39 UTC, ddaaac commented on src/main/kotlin/lotto/model/Lotto.kt
> +        fun createWinning(numbers: String) = Lotto(numbers.split(DELIMITER).map { LottoNumber(it.toInt()) }.toSet())
String -> 객체 변환이 Lotto 도메인의 책임인지 고민이 되더라구요. 컬렉션 -> Lotto 정도까지가 적당한 책임이고, String의 파싱은 View에서 해도 충분하지 않을까요?

2023-06-19 11:39 UTC, ddaaac commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +data class LottoNumber(val number: Int) {
값 객체를 사용해주셨네요 👍 

[value class](https://kotlinlang.org/docs/inline-classes.html)를 사용해보셔도 좋을 것 같아요.

2023-06-19 11:39 UTC, ddaaac commented on src/main/kotlin/lotto/model/LottoWinning.kt
> +    }
Lotto 객체에서 getter로 데이터를 꺼내서 계산을 하고 있어요.
Lotto 객체가 스스로 계산할 수 있는 로직은 객체에게 맡겨보는 건 어떨까요?

2023-06-19 11:39 UTC, ddaaac commented on src/main/kotlin/lotto/model/LottoWinning.kt
> +        }
mapNotNull과 [groupBy](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/group-by.html)를 활용해봐도 될 것 같아요 😄

2023-06-19 11:39 UTC, ddaaac commented on src/main/kotlin/lotto/model/LottoWinning.kt
> +
lottoResult에서 계산한 Map이 여기 파라미터로 다시 돌아오는 구조네요. 이 함수가 LottoWinning에 있을 필요는 없어보여요. Statistics와 같은 객체가 있어도 좋을 것 같습니다!

2023-06-19 11:39 UTC, ddaaac commented on src/test/kotlin/lotto/model/LottoTest.kt
> +            Lotto(listOf(1, 2, 3, 4, 5, 6, 7, 8).map { LottoNumber(it) }.toSet()).numbers.size
경계값들 꼼꼼하게 테스트 해주셨네요 💯

2023-06-19 13:12 UTC, ohsung commented on src/main/kotlin/lotto/model/Lotto.kt
> +        fun createWinning(numbers: String) = Lotto(numbers.split(DELIMITER).map { LottoNumber(it.toInt()) }.toSet())
좋은 의견 감사합니다.

2023-06-19 14:21 UTC, ohsung commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +data class LottoNumber(val number: Int) {
좋은 리뷰 감사합니다.

2023-06-19 14:28 UTC, ohsung commented on src/main/kotlin/lotto/model/LottoWinning.kt
> +        }
코틀린을 아직도 Java 처럼 사용하고 있었네요.
효과적인 코틀린 사용법 감사합니다.

2023-06-20 10:55 UTC, ddaaac approved these changes
안녕하세요 성오님 👋 

리뷰 반영 깔끔하게 해주셨네요.

다음 단계 진행해주세요!

2023-06-20 10:55 UTC, ddaaac commented on src/main/kotlin/lotto/model/Lotto.kt
> +    }
intersect + count를 사용하는 방법도 있을 것 같네요 :)

2023-06-20 10:55 UTC, ddaaac commented on src/main/kotlin/lotto/model/Lotto.kt
> +        fun createWinning(numbers: String) = Lotto(numbers.split(DELIMITER).map { LottoNumber(it.toInt()) }.toSet())
도메인은 View에서 검증 로직이 있는가와 별개로 항상 검증 로직을 가져야한다고 생각해요. View는 얼마든지 바뀌거나 추가될 수 있는 것이니 도메인에 유효성 검증 규칙이 없다면 View가 추가되거나 변경될 때 규칙이 누락될 수도 있겠죠.
따라서 검증의 중복이 발생하더라도 도메인 객체에는 검증 로직을 꼭 두려고 하는 편이에요.

2023-06-20 10:55 UTC, merged