🚀 2단계 - 로또(자동)
next-step/kotlin-lotto pull request #713
Opened 2023-06-19 09:18 UTC by jinuk17

피드백 잘 부탁드립니다 🙏

2023-06-19 14:31 UTC, ujusy requested changes
안녕하세요, 2단계 구현 고생하셨습니다 👍 
고민해볼 몇 가지 코멘트 남겼습니다.
확인 후 다시 리뷰 요청 주세요 :) !!

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/application/console/ConsoleLottoSimulation.kt
> +}
저장할 때 마다 new line 을 추가하도록 설정할 수 있어요! 
<img width="892" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/49120090/b52be251-fd1d-4e97-9d83-d503c3f86ccd">

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/application/console/ConsoleLottoSimulation.kt
> +}
커밋 전에 ktlint 체크를 자동하면 좋을 것 같아요 :)

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/application/console/InputView.kt
> +class InputView {
`InputView` 와 `ResultView` 는 상태를 전혀 갖지 않는 것 같은데 그렇다면 singleton이어도 되지 않을까요? :)

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +fun interface LottoFactory {
`functional interface` 👍

2023-06-19 14:31 UTC, ujusy commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +        val lottoNumbers = listOf(1, 1, 2, 3, 4, 5, 6).toLottoNumbers()
중복을 검증하는데 데이터에 7개의 숫자가 들어가있네요 !

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    val numbers: List<LottoNumber>
여기서 `numbers` 를 따로 선언하신 이유가 있을까요?!

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +enum class LottoResult(val price: Int, val matchCount: Int) {
`price` 보다는 상금을 더 잘 나타낼 수 있는 단어는 어떨까요? :) ( ex. `winningAmount` 등..)

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        return (1..count).map { lottoFactory.create() }
이렇게도 작성해 볼 수 있습니다 :)  
```suggestion
  return List(count) {}
```

2023-06-19 14:31 UTC, ujusy commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        return 6 - difference.size
magic number를 상수화해보는건 어떨까요? :)

2023-06-19 14:31 UTC, ujusy commented on src/test/kotlin/lotto/domain/LottoMachineTest.kt
> +        withData(
여러 경우 테스트 👍

2023-06-20 08:52 UTC, jinuk17 commented on src/main/kotlin/lotto/application/console/ConsoleLottoSimulation.kt
> +}
아 ,,, racing 프로젝트에만 설정해서 여기서는 적용이 안되었네요, 감사합니다 👍

2023-06-20 09:18 UTC, jinuk17 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    val numbers: List<LottoNumber>
`numbers` 는 입력값을 정렬한 값이라 따로 선언했습니다.

2023-06-20 09:23 UTC, jinuk17 commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +        val lottoNumbers = listOf(1, 1, 2, 3, 4, 5, 6).toLottoNumbers()
테스트 의도는 `중복 제거 후에 6개의 숫자로 구성 되어도 정상처리 되지 않는다` 였습니다.
테스트 메시지에 의도가 포함되도록 좀 더 고민해보겠습니다.

2023-06-20 09:26 UTC, jinuk17 commented on src/main/kotlin/lotto/application/console/ConsoleLottoSimulation.kt
> +}
이 부분은 안그래도 엄청 고통받고 있었는데 꿀팁 감사합니다 🙏

2023-06-20 13:16 UTC, ujusy approved these changes
리뷰 반영 잘해주셨습니다 👍 
크게 언급드릴 내용이 없어 머지하겠습니다!
다음 step3도 화이팅입니다 :)

2023-06-20 13:16 UTC, merged