🚀 4단계 - 로또(수동)
next-step/kotlin-lotto pull request #732
Opened 2023-06-20 10:28 UTC by parkjun5

어느덧 마지막 풀리퀘스트네요!

이번 과제를 진행하면서 상세히 리뷰해주셔서 감사합니다.
특히 객체의 역할과 그에 따른 문제가 발생 혹은 수정을 해야 할 때,
어떠한 객체를 먼저 확인될 것이고 그에 따른 mvc 패턴으로 객체를 나누는 것은 좋은 경험이였습니다.

수고하셨습니다!

2023-06-20 23:48 UTC, Hyeon9mak requested changes
안녕하세요 세준님, 어느덧 마지막 단계네요 😄 
간단한 코멘트 남겼으니 확인해주세요.
궁금하신 점 코멘트, DM 남겨주세요~

2023-06-20 23:48 UTC, Hyeon9mak commented on src/main/kotlin/view/InputView.kt
> +    private val inputReader: InputReader = InputReader { readln() },
https://github.com/next-step/kotlin-lotto/pull/690#discussion_r1234554958

요 부분에 대한 세준님 의견이 궁금합니다 😄

2023-06-20 23:48 UTC, Hyeon9mak commented on src/main/kotlin/domain/WinningFinder.kt
> +        }
일치하는 개수별 당첨금액이 얼마인지 `Prize` 클래스에 직접 물어볼 수도 있지 않을까요? 😄 

> 객체에 정보를 끌어다 사용하지 말고, 객체에게 메세지를 보내라.

2023-06-20 23:48 UTC, Hyeon9mak commented on src/test/kotlin/domain/LottoMachineTest.kt
> +    }
검증내용에 사용되는 값은 계산식을 기입하기보다 실제 원하는 상수 결과값을 입력하는게 조금 더 안전한 검증이 될 것 같아요.
사용되는 계산식이 잘못되었을 수도 있으니까요!

2023-06-20 23:48 UTC, Hyeon9mak commented on src/test/kotlin/domain/WinningCheckerTest.kt
> +            prize shouldBe expected
테스트명과 테스트 내용이 일치하는 걸까요? 😱

2023-06-21 06:56 UTC, parkjun5 commented on src/main/kotlin/view/InputView.kt
> +    private val inputReader: InputReader = InputReader { readln() },
아 이부분 답변을 달지 않았군요!

input 테스트를 위해 사용하는 부분입니다.

가짜 input들을 입력시켜서 통합테스트가 가능하게 하였습니다.

2023-06-21 07:14 UTC, parkjun5 commented on src/main/kotlin/view/InputView.kt
> +    private val inputReader: InputReader = InputReader { readln() },
요구 사항에서는  통합테스트가 필요 없다고 명시되어 있지만, 코드 변경시 전체 기능에 이상이 없는 것을 확인하기 위해서 추가하였습니다.

개인적으로 단위테스트가 매우 중요하지만,  테스트 성능에 영향을 주지 않는 한에서 통합테스트 한 두개 정도는 있으면 좋다고 생각합니다.

2023-06-21 07:19 UTC, parkjun5 commented on src/main/kotlin/domain/WinningFinder.kt
> +        }
객체 자체를 넘겨주지 않고 Prize에서 필요한 정보를 넘겨주는 것이 좀더 객체가 능동적으로 작동하는 것 같아요

더해서 Prize 클래스를 넘겨줄 필요도 없이, prizeMoney를 넘겨줘도 괜찮을 것 같네요!

2023-06-21 07:24 UTC, parkjun5 commented on src/test/kotlin/domain/WinningCheckerTest.kt
> +            prize shouldBe expected
복사의 위험성.. 다른 테스트를 복사하면서 만들다보니 발생한 괴상한 테스트가 되었네요.🙄

2023-06-21 07:25 UTC, parkjun5 commented on src/test/kotlin/domain/LottoMachineTest.kt
> +    }
상수값으로 넣는 것이 어떠한 값인지도 알수 있어서 중요한 내용이네요. 수정하겠습니다.

2023-06-22 03:57 UTC, Hyeon9mak requested changes
안녕하세요 세준님, 피드백 잘 반영해주셨습니다.
아주 간단한 코멘트 하나만 더 남겼으니 확인해주세요.
확인 후 리팩터링 해주시거나, 세준님의 추가 의견을 남겨주시면 approve 하도록 하겠습니다. 😄

2023-06-22 03:57 UTC, Hyeon9mak commented on src/main/kotlin/view/InputView.kt
> +    private val inputReader: InputReader = InputReader { readln() },
입력에 대한 테스트가 필요한걸까요? 아니면 다른 객체를 테스트할 때 `InputReader` 가 사용되는걸까요?
전자라면 꼭 필요한 테스트인지, 후자라면 객체의 역할을 분리해서
더 쉬운 테스트 코드 작성이 가능하지 않을지 고민도 해보면 재밌겠네요 😄

2023-06-22 03:57 UTC, Hyeon9mak commented on src/main/kotlin/view/InputView.kt
> +        }
`List(manualSize) { ... }` 를 활용할 수도 있겠네요 😄

2023-06-22 03:57 UTC, Hyeon9mak commented on src/main/kotlin/domain/Prize.kt
> +            }
👍 👍

2023-06-22 06:34 UTC, parkjun5 commented
작업을하다보니 컨트롤러가 너무 많은 기능을 담당하는 듯 하여서 서비스로 따로 뺴고 private fun들을 분리시켜주었네요.

또한 Pari로 리턴해주면서 파라미터가 너무 복잡해진 경우가 많아 이부분도 개선하였습니다.

2023-06-22 06:35 UTC, parkjun5 commented on src/main/kotlin/view/InputView.kt
> +    private val inputReader: InputReader = InputReader { readln() },
처음 이 InputReader라는 funtaional interface 를 만들어줄때에는 입력에 대한 테스트가 필요하다고 생각하였습니다.
하지만 테스트들을 지금 확인해보니 MockInputReader와 같은 가짜 객체가 아예 없어져버렸네요.

그래서 기존 커밋목록을 따라서 테스트가 어떻게 바뀌었는지 확인해보았습니다.
기록을 따라 찾아보니 Input테스트는 InputView보다는 LottoRunner를 테스트하는 내용이였습니다.

그와중에 LottoRunner의 역할을 다른 객체들이 나누어 가지면서 전체 테스트도 없어진 듯 합니다.

원래 목적과는 완전히 달라져버린 코드였네요..😰

2023-06-23 08:28 UTC, Hyeon9mak approved these changes
안녕하세요 세준님! 로또 미션 마지막까지 고생하셨습니다.
미션 막바지에 많은 리팩터링을 진행해주신 것 같아요. 😄 
쉽지 않은 일이었을텐데 실행력이 너무 멋집니다.
미션 요구사항도 충족된 것 같고, 피드백을 잘 반영해주셔서 approve 하도록 하겠습니다.
다음 미션도 화이팅 💪

2023-06-23 08:28 UTC, Hyeon9mak commented on src/main/kotlin/LotteryController.kt
> +        LotteryService.reportResult(prizeCountMap, lotteries.size)
자동차 경주 미션에서 학습했던 mvc 패턴에서 view 와 소통하는 건 controller 였던 것 같아요.
현재는 service 가 직접적으로 view 와 소통하는 것 같은데요,
이후에 controller 가 view 와 소통하고, 소통한 내용을 service 에게 넘겨 로직을 수행하도록 하는 방향으로
리팩터링 해보시면 다음 미션들을 진행하는데 한결 수월하실 것 같아요 😄 👍

2023-06-23 08:28 UTC, merged