Step4 - 로또(수동)
next-step/kotlin-lotto pull request #734
Opened 2023-06-20 12:39 UTC by dongjoon1251

이전에 주신 코멘트 반영 후 step4 기능 추가해서 PR올립니다~!

2023-06-21 01:46 UTC, malibinYun approved these changes
4단계 미션 고생 많으셨어요!
이미 너무 깔끔한 구조로 미션을 수행해주셔서 크게 피드백을 남길 게 없었네요 👍
피드백을 반영하시거나, 다른 도전을 해보셔도 좋고,
이만 미션을 마무리하셔도 좋습니다.
종료하시려면 DM이나 코멘트 부탁드려요! 🙂

2023-06-21 01:46 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/domain/LottoRank.kt
> +
matchCount가 5일 때만 SECOND or THIRD 를 반환하고, 나머지는 find로 반환해보는 방법도 있겠네요!
아래 방법은 참고 정도만 해주셔도 좋습니다 :)
```suggestion
        fun from(matchCount: Int, matchBonus: Boolean): LottoRank {
            return when {
                matchCount == 5 && matchBonus -> SECOND
                matchCount == 5 && !matchBonus -> THIRD
                else -> values().find { it.matchCount == matchCount } ?: MISS
            }
       }
```

2023-06-21 01:46 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/domain/LottoStore.kt
> +    fun buy(payment: Int, algorithm: LottoNumberGenerationAlgorithm): Lottos {
typealias를 활용해서 계산 전략을 교체하는 방법은 처음 보네요 😮👍
좋은 아이디어 라고 생각해요!

2023-06-21 01:46 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/domain/LottoStore.kt
> +    private fun canBuy(payment: Int): Boolean = payment >= LOTTO_PRICE
Iterator 의 hasNext() 같은 아이디어에서 따오신 것 같아요.
받은 금액으로 몇 장을 살 수 있는 지 개수를 받은 뒤, `List() { }`, `.map { }` 등의 코틀린 함수들을 활용해보는 건 어떨까요?
while문을 제거할 수 있을 것으로 기대돼요 :)

2023-06-21 01:46 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/domain/Lottos.kt
연산자 오버로딩을 활용해주셨네요! 👍👍

2023-06-21 01:46 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/domain/WinningLotto.kt
> +            .eachCount())
한 메서드에서 많은 일들을 하고 있는 것으로 보여요.
1장의 로또를 비교하는 메서드를 분리하는 등, 메서드를 분리해보는 건 어떨까요?

또, 한 줄로 파라미터와 체이닝을 작성하는 경우,
Exception 등이 발생했을 때 동일한 라인 위치로 콘솔에 나타나기에 디버깅하기 어려워질 수도 있어,
적절히 줄바꿈을 해주는 것도 좋은 방법입니다 :)

2023-06-21 01:46 UTC, malibinYun commented on src/test/kotlin/next/step/lotto/domain/LottoNumberGeneratorTest.kt
> -                val number = LottoNumberGenerator.random()
typealias를 활용하면 괴상한 소괄호를 사용해야하는 단점이 생길 수 있었군요 ㅠ_ㅠ
다른 사람들이 100% 태클을 걸 내용으로 예상 돼서 아쉬운 마음이네요

2023-06-21 01:46 UTC, malibinYun commented on src/test/kotlin/next/step/lotto/domain/LottoStoreTest.kt
> +                LottoStore.buy(1500, Lottos.of(setOf(Lotto.from(setOf(1, 2, 3, 4, 5, 6))))) shouldBe 500
줄바꿈을 적절히 활용하면 가독성을 더 챙길 수 있을 것이 기대됩니다 :)

2023-06-21 01:46 UTC, malibinYun commented on src/test/kotlin/next/step/lotto/domain/LottoStoreTest.kt
> +                    )
어떤 에러 메시지가 나왔는 지도 검증해보는 건 어떨까요?

2023-06-21 01:47 UTC, malibinYun requested changes
4단계 미션 고생 많으셨어요!
이미 너무 깔끔한 구조로 미션을 수행해주셔서 크게 피드백을 남길 게 없었네요 👍
피드백을 반영하시거나, 다른 도전을 해보셔도 좋고,
이만 미션을 마무리하셔도 좋습니다.
종료하시려면 DM이나 코멘트 부탁드려요! 🙂

2023-06-21 01:49 UTC, dongjoon1251 commented
@malibinYun 주신 피드백들 반영하는 방향으로 진행해볼게요! 배우기 위함이니 서두르지 않겠습니다 :)

2023-06-21 14:05 UTC, dongjoon1251 commented on src/main/kotlin/next/step/lotto/domain/LottoRank.kt
> +
@malibinYun 제시해주신 방법에서 로직이 한 눈에 잘 들어오기도 하고, when 구문도 써보고 싶기도 해서 이렇게 바꿔보겠습니다 :)

2023-06-21 14:14 UTC, dongjoon1251 commented on src/main/kotlin/next/step/lotto/domain/LottoStore.kt
> +    private fun canBuy(payment: Int): Boolean = payment >= LOTTO_PRICE
@malibinYun 아 이것도 바꿔야지 하고 그냥 지나갔네요 ㅎㅎ while문 안쓰는 방향으로 시도해보겠습니다!

2023-06-21 14:18 UTC, dongjoon1251 commented on src/main/kotlin/next/step/lotto/domain/WinningLotto.kt
> +            .eachCount())
@malibinYun 한 줄이 너무 길어서 애매했는데 메소드를 분리해서 사용하는게 좋겠네요!

2023-06-21 14:19 UTC, dongjoon1251 commented on src/test/kotlin/next/step/lotto/domain/LottoStoreTest.kt
> +                LottoStore.buy(1500, Lottos.of(setOf(Lotto.from(setOf(1, 2, 3, 4, 5, 6))))) shouldBe 500
@malibinYun 아무래도 그렇죠? ㅋㅋ 수정할게요!

2023-06-21 14:21 UTC, dongjoon1251 commented on src/test/kotlin/next/step/lotto/domain/LottoStoreTest.kt
> +                    )
@malibinYun 메소드에 넣는 파라미터에 따라 달라지니까 검증해보는게 좋겠네요!

2023-06-21 14:34 UTC, dongjoon1251 commented on src/test/kotlin/next/step/lotto/domain/LottoNumberGeneratorTest.kt
> -                val number = LottoNumberGenerator.random()
@malibinYun 인터페이스 만들어서 주입하는 걸로 바꿔봐야겠네요 ㅎㅎ

2023-06-22 14:37 UTC, malibinYun approved these changes
로또 미션 완주 하시느라 고생 많으셨어요 🎉
덕분에 즐겁게 커뮤니케이션 하면서 리뷰를 진행할 수 있었어요 :)
미션도 너무 잘 구현해주시고, 피드백도 너무 잘 반영해주셨어요 👍
저와 나누었던 이야기가 앞으로 도움이 되셨으면 좋겠어요!
남은 다른 미션들도 모두 완주하시길 응원할게요! 💪🔥

2023-06-22 14:37 UTC, malibinYun commented on src/main/kotlin/next/step/lotto/view/InputView.kt
> +        }
try-catch는 kotlin의 runCatching을 활용해볼 수도 있어요!
이후에 참고해보시면 좋겠어요 :)

2023-06-22 14:37 UTC, merged

2023-06-22 14:55 UTC, dongjoon1251 commented on src/main/kotlin/next/step/lotto/view/InputView.kt
> +        }
@malibinYun 아 main에는 적용하고 여기는 또 이렇게 했네요 ㅋㅋ 감사합니다!