🚀 3단계 - 로또(2등)
next-step/kotlin-lotto pull request #742
Opened 2023-06-21 01:43 UTC by jinuk17

2023-06-21 14:59 UTC, ujusy requested changes
안녕하세요, 로또 step3 잘 구현해주셨습니다 👍 
몇 가지 궁금한 부분과 코멘트 남겼습니다.
확인 후 다시 리뷰 요청 주세요!

2023-06-22 08:37 UTC, jinuk17 commented on src/main/kotlin/lotto/domain/LottoGame.kt
> +    ) : this(WinningLotto(Lotto(winningNumber.map { LottoNumber.of(it) }), LottoNumber.of(bonusNumber)))
보너스 볼이 없는 경우에 작성한 주생성자를 유지하다가 저렇게 되었던 것 같네요 ~ 
현재는 사용하는 부분이 없어서 부생성자를 주생성자로 변경하는게 더 나아보입니다. 👍

2023-06-22 08:44 UTC, jinuk17 commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +enum class LottoResult(val winningAmount: Int, val matchCount: Int, val checkBonus: Boolean) {
네 피드백 주신데로 확장의 경우를 고려해서 고민을 해봤습니다. 

결과를 count 로 변경하려다 보니 로또 당첨 번호도 보너스 숫자를 list 로 받아야 할 것 같고, 
그러다 보니 오히려 코드 상으로 보너스 번호가 N 개 일 수도 있다라는 착작을 주게 되지 않을까 우려가 됩니다.

혹시 현재 요구사항에 대한 도메인 표현과 확장을 함께 고려할 방법이 있을까요 ?

2023-06-22 11:19 UTC, ujusy commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +enum class LottoResult(val winningAmount: Int, val matchCount: Int, val checkBonus: Boolean) {
말씀하신대로 변경했을 때 그런 착각을 줄 수도 있을 것 같습니다. 다만, 확장의 측면에서 애초에 보너스 개수가 N 개일 수있도록 설계하는 방식도 틀린 것 아닌 것 같습니다. 하지만 이 방식으로 변경하게되면 현재로서는 여기저기 변경이 많아질 것 같네요! 
확장성을 어디까지 고려할 것인지도 결국 주어진 도메인과 주어진 상황에 따라 천차만별인 것 같아 구현하면서 판단할 수 밖에 없는 것 같아요! 
이 경우도 특별히 정답은 없는 것이니 현재 상태로 진행하셔도 무방합니다

2023-06-23 03:50 UTC, ujusy approved these changes
리뷰 반영 잘 해주셨습니다 👍 
크게 언급드릴 내용은 없어 바로 머지하겠습니다~
다음 미션도 화이팅입니다 💪💪

2023-06-23 03:50 UTC, ujusy commented on src/test/kotlin/lotto/domain/WinningLottoTest.kt
> +    "로또 번호로 당첨 결과(2등)를 확인 할 수 있다. 당첨 번호(1, 2, 3, 4, 5, 6), 보너스 7" {
리뷰 반영 👍

2023-06-23 03:50 UTC, merged