3단계 - 로또(2등)
next-step/kotlin-lotto pull request #743
Opened 2023-06-21 07:40 UTC by yeonsuyang

잘부탁드립니다!

2023-06-21 12:59 UTC, Flamme1004K requested changes
안녕하세요!

피드백 반영 감사합니다. 💯 step3 고생하셨습니다! 

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

2023-06-21 12:59 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LotteryShop.kt
>      fun getTickets(lottoCount: Int): List<Lotto> {
- 일급 컬렉션을 쓴다.
    - [일급 컬렉션을 사용하는 이유](https://woowacourse.github.io/javable/post/2020-05-08-First-Class-Collection)

라는 프로그래밍 요구 사항이 빠진 것 같아요 : )! 반영 부탁드립니다.

2023-06-21 12:59 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Rank.kt
> +                count == 3 -> FIFTH
values() 함수를 사용한다면 when을 사용하지 않고 구현할 수 있지 않을까요?

2023-06-21 12:59 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/BankTest.kt
> +        }
`@Parameterizedtest` 를 사용하여 수익률에 대한 테스트를 하나로 묶어 볼까요?

2023-06-21 13:04 UTC, Flamme1004K commented
https://github.com/next-step/kotlin-lotto/pull/704#discussion_r1236963583
https://github.com/next-step/kotlin-lotto/pull/704#discussion_r1236967814

덧글 확인 부탁드립니다 ^^!

2023-06-23 00:51 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 💯 다음 단계를 위하여 merge 하도록 하겠습니다 🙌

몇 가지 코멘트를 남겼으니 확인 부탁드립니다!

다음 미션도 화이팅입니다! 🤩

2023-06-23 00:51 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Bank.kt
> +    fun score(tickets: Tickets, winningTicket: WinningTicket): List<Rank> {
Bank와 Tickets를 봤을 때 Bank는 그저 로또 티켓을 주면 로또 티켓에 대한 돈을 주는 역할을 하는 것 같아요.

score라는 메서드를 WinningTicket에게 주는건 어떨까요?

2023-06-23 00:51 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LotteryShop.kt
> +    fun getTickets(lottoCount: Int): Tickets {
일급 컬렉션 사용 👍

2023-06-23 00:51 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
num 대신 Lotto 자체를 받는다면 로직이 더 깔끔해지지 않을까요?

2023-06-23 00:51 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +class AutoNumGenerator : LottoNumGenerator {
이름 👍

2023-06-23 00:51 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Rank.kt
> +            return Rank.values().firstOrNull { it.count == count && it.hasBonus == hasBonus } ?: NONE
values 사용 좋습니다!

2023-06-23 00:51 UTC, merged

2023-06-23 04:22 UTC, yeonsuyang commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
보너스볼을 가지고 있는지 체크하는 로직이라 num을 받는것으로 구현하였습니다.