Step4 - 로또(수동)
next-step/kotlin-lotto pull request #755
Opened 2023-06-22 16:10 UTC by maenguin

안녕하세요 리뷰어님 마지막 스텝이네요

프로그래밍 요구사항 중에 "예외 처리를 통해 에러가 발생하지 않도록 한다." 라는 요구사항이 있는데
코드에 어떻게 녹여낼지 잘 모르겠어서 반영을 못했는데요
리뷰어님이 짚어주시면 감사하겠습니다.

마지막이니 맵게 부탁드립니다..!

2023-06-23 15:06 UTC, Flamme1004K requested changes
안녕하세요!

step4도 구현 잘하셨습니다! 몇 가지 코멘트를 남겼으니 확인 부탁드릴게요!

그리고 벌써 마지막 미션이네요! 더 함께하고 싶은데 이 미션이 끝나면 못 한다는 게 아쉽습니다! 😭 그만큼 재밌어서 그런 것 같아요! 그러므로! 마지막 merge 까지 함께 열심히 해보아요!!

화이팅입니다 🥳🥳🥳

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +    val autoCount: Int = 0,
amnualCount, autoCount도 구매한 Lotto 종류에 대한 카운트를 한것이죠? 좀 더 개선해나아가서 Lotto 들에게 자동인지, 수동인지에 대한 상태를 준다면 count에 대한 부분도 지울 수 있고, IssuedLottos에게 lottos에 대한 각 카운트를 가지고와달라는 메서드를 호출할 수 있지 않을까요~?

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    val numbers: Set<LottoNumber>
포장 좋습니다 👍

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +fun Iterable<Int>.toLottoNumberSet(): Set<LottoNumber> {
Iterable을 사용한 이유를 알고 싶어요~

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
Comparable이 필요한 이유를 알 수 있을까요?

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +class LottoNumber private constructor(private val value: Int) : Comparable<LottoNumber> {
LottoNumber를 만약에 요번에 배운 value class로 사용한다면 어떠한 장점이 있을까요?

2023-06-23 15:06 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        private val NUMBER_CACHE: Map<Int, LottoNumber> = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER).associateWith(::LottoNumber)
LottoNumber에 대해 캐시 구현 너무 좋네요 👍

2023-06-23 15:06 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +internal class LottoNumberTest {
테스트 케이스 👍

2023-06-23 15:07 UTC, Flamme1004K commented
> 예외 처리를 통해 에러가 발생하지 않도록 한다.

에 대해서 모두 잘 해주셨습니다. 사용자 예외에 대한 처리를 말한 것으로 저도 이해했는데 사용자 예외에 대한 처리 및 그리고 LottoNumber에 대한 에러 처리도 모두 잘해주셨어요 : )!

2023-06-24 08:45 UTC, maenguin commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +fun Iterable<Int>.toLottoNumberSet(): Set<LottoNumber> {
더 구체적인 타입으로 선언할 필요없이 Iterable로 선언했을때 충분히 원하는 메서드를 만들 수 있었고
추상화된 타입이어서 더 다양한 상황에서 LottoNumberSet을 사용할 수 있기에 Iterable을 사용했습니다

2023-06-24 08:46 UTC, maenguin commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
LottoMachine에서 자동 로또 번호를 생성하고 정렬을하는데 그때 필요해서 구현했습니다

2023-06-24 08:48 UTC, maenguin commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +class LottoNumber private constructor(private val value: Int) : Comparable<LottoNumber> {
Primitive 타입의 장점을 그대로 가져올 수 있겠군요..!!

2023-06-24 08:50 UTC, maenguin commented on src/main/kotlin/lotto/domain/IssuedLottos.kt
> +    val autoCount: Int = 0,
좋은 의견 감사합니다 커밋 [5b34cfc](https://github.com/next-step/kotlin-lotto/pull/755/commits/5b34cfc0c41110e85abdd5e367042ca0616f32f9)으로 반영했습니다.

2023-06-24 09:02 UTC, maenguin commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +class LottoNumber private constructor(private val value: Int) : Comparable<LottoNumber> {
아쉽게도 value class를 써도 sort할때는 래퍼로 취급되어서 Comparable이 필요하네요..

2023-06-24 09:08 UTC, maenguin commented on src/main/kotlin/lotto/Main.kt
> +    val winningNumbers: Set<LottoNumber> = inputView.inputWinningNumbers().toLottoNumberSet()
저는 일단 당첨 로또와 구입한(혹은 할)로또는 개념적으로 분리할 필요가 있다고 생각해서
당첨 로또가 로또를 가지지 않는게 좋다고 생각했습니다.
그럴일은 없겠지만 당첨 번호룰이 바뀌어서 그냥 번호 5개와 보너스 번호 2개를 뽑게 된다면..?
너무 과하게 생각했을까요 ㅋㅋㅋ...

2023-06-24 09:13 UTC, maenguin commented on src/main/kotlin/lotto/Main.kt
> +    val manualLottoList = manualLotto.map { Lotto(it.toLottoNumberSet()) }
이렇게 하지 않은 이유는 View가 Model을 의존하지 않길 바랬고
IssuedLottos는 의미 그대로 발급한 로또로서 발급 주체에(여기서는 LottoSeller)의해서 획득할 수 있길 바랬습니다.

IssuedLottos의 이름을 그냥 Lottos로 바꿨다면 또 느낌이다르네요
Lottos로 가공해서 던져줘도 무리가 없을꺼란 느낌이 또 듭니다 ㅋㅋ...

2023-06-24 09:40 UTC, maenguin commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +class LottoNumber private constructor(private val value: Int) : Comparable<LottoNumber> {
커밋 [6d551a1](https://github.com/next-step/kotlin-lotto/pull/755/commits/6d551a1649c65b0aabfd63212dde7e693beae81e)으로 value 클래스를 사용해보았습니다

2023-06-24 16:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/Main.kt
> +    val winningNumbers: Set<LottoNumber> = inputView.inputWinningNumbers().toLottoNumberSet()
왠지 로또가 슈퍼볼이 되는 느낌이네요. 🤣
개념적으로 분리하는 편도 좋지만, 저는 Lotto 객체가 결국에는 IssuedLottos 와 winningLotto 모두 동일하게 쓰이다 보니 같이 쓰여도 좋겠다는 생각이 들긴 했어요. 왜냐하면 현재로서는 Lotto에 대한 비교 로직만 공통적이게 적용이 될 것이기 때문이라서요. 아마 Lotto 객체가 너무 많은 일을 한다면 분리해 줘야 하는 신호 긴하죠 : )

2023-06-24 16:19 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +class LottoNumber private constructor(private val value: Int) : Comparable<LottoNumber> {
크 굳입니다!

2023-06-24 16:21 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +fun Iterable<Int>.toLottoNumberSet(): Set<LottoNumber> {
추상화 된 타입을 재사용한거라면 좋은 것 같기도 해요! 

저는 확장함수 사용할 때나, 메서드에 대한 인자에 대한 부분은 모두 현재 어울리는 것으로 정해놓고 서서히 추상화를 하고는 있습니다.

2023-06-24 16:26 UTC, Flamme1004K requested changes
안녕하세요!

피드백 반영 감사합니다 : )! 이제 머지해도 괜찮을 것 같은데요!

코멘트 달아드렸으니 한번 더 체크 후에 리뷰 요청 부탁드립니다!

2023-06-24 16:26 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +}
피드백 반영 👍

2023-06-24 16:26 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        val LOTTO_NUMBERS = LOTTO_RANGE.map(::LottoNumber)
더 깔끔하게 리팩토링 하셨군요. 좋습니다 👍

2023-06-25 14:16 UTC, maenguin commented
이제 보내드릴때가 된것 같습니다..
플람님 덕분에 많이 배웠습니다.
그동안 감사했습니다

2023-06-25 15:13 UTC, Flamme1004K approved these changes
안녕하세요!

그동안 로또 미션 하시느라 고생하셨습니다!

마지막 머지 하도록 하겠습니다!

블랙잭 미션 응원하겠습니다! 화이팅입니다! 아좌아좌!🥳🥳🥳

2023-06-25 15:13 UTC, merged