[Step4] 로또(수동)
next-step/kotlin-lotto pull request #762
Opened 2023-06-24 05:23 UTC by graygreat

안녕하세요~
2주차 마지막 미션인데, 조금 늦네요 ㅠ

step 1, 2, 3에서 피드백 잘 주셔서 step4에는 큰 어려움 없이 개발했던 것 같습니다.

추가로 step3에서 남겨주신 부분 중 모르겠는 부분이 있어서 [링크](https://github.com/next-step/kotlin-lotto/pull/738#discussion_r1236934605) 같이 남깁니다.

리뷰 잘 부탁드립니다 :)

2023-06-24 07:37 UTC, Flamme1004K requested changes
안녕하세요!

step4도 구현 잘하셨습니다! 몇 가지 코멘트를 남겼으니 확인 부탁드릴게요!

마지막까지 화이팅입니다!! 🥳🥳🥳

2023-06-24 07:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/controller/LottoController.kt
> +    private fun generateManualLottos(manualLottoCount: Int): MutableList<LottoNumbers> {
```suggestion
    private fun generateManualLottos(manualLottoCount: Int): List<LottoNumbers> {
```

코틀린은 불변을 지키기 매우 좋은 언어이죠! List로 변경하여 불변을 지켜주는게 좋을 것 같습니다. 불변이라는게 더 이득이 되는 경우가 더 많기 때문이죠

2023-06-24 07:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +    fun generateLottos(count: Int, manualLottos: List<LottoNumbers>): Lottos {
```suggestion
    fun generateLottos(count: Int, manualLottos: Lottos): Lottos {
```

로 변경해볼까요!?

추가로 이제 LottoNumbers 클래스를 Lotto로 변경해도 괜찮지 않을까합니다~

LottoNumber가 모여서 Lotto가 되는 것처럼 말이죠 😊

2023-06-24 07:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoNumbers.kt
> +        return lottoNumber in lottoNumbers
피드백 반영 👍

2023-06-24 07:37 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Rank.kt
> +            val countOfIntersect = lottoNumbers.findIntersectCount(winningNumber.lastLottoNumbers.lottoNumbers)
https://github.com/next-step/kotlin-lotto/pull/738#discussion_r1240625886

코멘트 확인 부탁드립니다!

2023-06-24 07:37 UTC, Flamme1004K commented on src/test/kotlin/lotto/domain/LottoGeneratorTest.kt
> +        val lottos = lottoGenerator.generateLottos(count, mutableListOf())
수동에 대한 테스트도 한번 해주시죠! 😊

2023-06-24 08:11 UTC, graygreat commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +    fun generateLottos(count: Int, manualLottos: List<LottoNumbers>): Lottos {
그렇네요 ㅎㅎ
변경해보겠습니다~

2023-06-24 16:38 UTC, Flamme1004K requested changes
안녕하세요!

피드백 반영 감사합니다!  몇 가지 코멘트를 남겼으니 확인 부탁드릴게요!

마지막까지 화이팅입니닷! 🤩

2023-06-24 16:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +class Lotto(
피드백 반영 👍

2023-06-24 16:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        repeat(count - manualLottos.lottoNumbers.size) {
```suggestion
        repeat(count - manualLottos.size()) {
```

manualLottos.size() 로 바로 가지고 오는게 좋지 않을까요?

2023-06-24 16:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        return lottoNumber in lottoNumbers
피드백 반영 👍

2023-06-24 16:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
>          }
해당 전략이 Rank enum class에 가면 좋을 것 같아요!

그렇게 된다면 Enum 메서드인 values()로 한번 더 리팩토링이 가능할거에요.

그리고 Rank에 NONE이라는 값을 추가하면 Null에 대한 부분도 자연스럽게 해소되지 않을까요? 때때로 ENUM은 Null 처리용으로도 쓰인답니다.

2023-06-24 16:38 UTC, Flamme1004K commented on src/main/kotlin/lotto/domain/RankFactory.kt
> +class RankFactory {
RankFactory이라니! 새롭군요! 좋습니다 👍

2023-06-25 07:00 UTC, Flamme1004K approved these changes
안녕하세요!

그동안 로또 미션 하시느라 고생하셨습니다!

마지막 머지 하도록 하겠습니다!

블랙잭 미션 응원하겠습니다! 화이팅입니다! 아좌아좌!🥳🥳🥳

2023-06-25 07:01 UTC, merged