[Step4] 로또(수동)
next-step/kotlin-lotto pull request #778
Opened 2023-06-26 07:48 UTC by yoo-jaein

안녕하세요! 코드 리뷰 잘 부탁드립니다.

2023-06-26 13:44 UTC, sah3122 requested changes
수동 로또 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 마지막까지 화이팅 해주세요 !

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    private val sortedNumbers = numbers.map { it.number }.sorted()
상태 값으로 가지고 있지 않고 getter 만 제공하는건 어떨까요 ?

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    private val auto: Boolean = false
자동로또는 로또의 구입 방법중 한가지라고 생각합니다. 
상태값으로 가지고 있어야 할까요 ?

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        require(numbers.size == NUMBER_OF_LOTTO_NUMBERS) { LOTTO_NUMBERS_MUST_BE_6 }
중복되지 않는 6개 번호를 만족해야하는데 중복 검사가 빠져있네요 😢

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        fun createRandomList(size: Int): List<LottoNumber> = LOTTO_NUMBERS.shuffled().take(size)
개인적으론 함수명 또는 변수명에 명시적인 타입을 선언하기 보단 이와 같은 경우 복수형으로 선언하는것을 권장합니다 😄 
반환값이 Set Collection으로 변경되어도 의미를 유지할수 있어요 😄

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/controller/LottoController.kt
>      private fun buyLottos(budget: Int): Lottos {
로또 구입과 당첨 금액 검사를 담당하는 서비스 클래스를 만들어 보는건 어떨까요 ? 
`로또 기계 또는 상점에서 로또를 구입한다.`와 같이 자연스러운 모델링이 될수 있으면 좋을것 같아요 😄

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/LottoPurchase.kt
> +class LottoPurchase(
구매 정보를 담고 있는 클래스를 값 객체로 활용하여 구매를 담당하는 클래스에게 전달할수 있으면 좋을것 같아요 😄

2023-06-26 13:44 UTC, sah3122 commented on src/main/kotlin/lotto/domain/Lottos.kt
> +    fun printAll() = lottos.forEach { println(it.toString()) }
도메인 클래스는 입 / 출력과 관련된 역할을 담당하지 않는것이 좋을것 같습니다. 
입 / 출력과 같은 UI Layer는 변경이 자주 일어나는 영역이며 도메인 클래스가 UI 요구사항에 의해 변경되는것은 도메인이 가장 바깥 레이어로 노출되어있다는것을 의미합니다. 
UI Layer 와 결합을 제거해보세요 😄

2023-06-26 13:44 UTC, sah3122 commented on src/test/kotlin/lotto/LottoTest.kt
> +    fun `로또를 수동 생성할 수 있다`() {
6개 번호를 보장하는 테스트를 제거하지 않는것이 어떨까요 ? 
해당 요구사항은 로또 미션의 중요한 비즈니스 요구사항입니다. 
비즈니스 요구사항을 테스트 코드를 통해 알수 있으면 잘 정리된 문서가 될수 있어요 ! 

추가로 중복된 번호가 입력되는 경우 Exception을 던지는것도 추가해보세요 😄

2023-06-26 13:44 UTC, sah3122 commented on src/test/kotlin/lotto/LottosTest.kt
> +        val myLotto1 = Lotto.manualCreate(lottoNumbers1)
테스트 코드에서 자주 사용되는 객체는 TestFixutre로 정의하여 보는것도 좋을것 같습니다. 
다양한 Fixutre가 모일수록 테스트 코드를 작성하는 시간이 줄어들수 있어요 ! 
https://thalals.tistory.com/375

2023-06-27 02:18 UTC, yoo-jaein commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    private val sortedNumbers = numbers.map { it.number }.sorted()
기존 코드에서 출력 로직을 ```Lotto```의 ```toString()```에서 수행했기 때문에 ```sortedNumbers```를 내부 상태 값으로 들고있었습니다.

출력 로직을 모두 ```ResultView```로 보내면서 해당 값을 지우고 아래 코드로 수정해봤습니다.
```kotlin
// ResultView
private fun printLotto(lotto: Lotto) {
    val sortedNumbers = lotto.numbers.map { it.number }.sorted()
    println("[${sortedNumbers.joinToString(", ") { it.toString() }}]")
}
```

2023-06-27 03:56 UTC, yoo-jaein commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        require(numbers.size == NUMBER_OF_LOTTO_NUMBERS) { LOTTO_NUMBERS_MUST_BE_6 }
중복 검사를 추가했습니다.
```kotlin
    init {
        require(numbers.size == NUMBER_OF_LOTTO_NUMBERS) { LOTTO_NUMBERS_MUST_BE_6 }
        require(numbers.toSet().size == numbers.size) { LOTTO_NUMBERS_MUST_BE_UNIQUE }
    }
```

2023-06-27 04:33 UTC, yoo-jaein commented on src/test/kotlin/lotto/LottoTest.kt
> +    fun `로또를 수동 생성할 수 있다`() {
다시 추가했습니다!

2023-06-27 04:35 UTC, yoo-jaein commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    private val auto: Boolean = false
자동, 수동 값은 구매할 때만 알면 되는 값이네요. 해당 필드는 삭제했습니다.

2023-06-27 04:50 UTC, yoo-jaein commented on src/test/kotlin/lotto/LottosTest.kt
> +        val myLotto1 = Lotto.manualCreate(lottoNumbers1)
```LottoFixture```를 추가했습니다.

2023-06-27 04:50 UTC, yoo-jaein commented on src/main/kotlin/lotto/domain/LottoPurchase.kt
> +class LottoPurchase(
구매 정보를 담을 ```OrderRequest```를 추가했습니다.

2023-06-27 04:52 UTC, yoo-jaein commented on src/main/kotlin/lotto/controller/LottoController.kt
>      private fun buyLottos(budget: Int): Lottos {
로또 구입과 당첨 검사를 담당하는 ```LottoShopService```라는 서비스 클래스를 추가했습니다. 기존의 ```LottoPurchase```를 여기서 사용하도록 수정해봤습니다.

2023-06-28 06:33 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
로또 미션 진행하며 적지않은 피드백들을 반영해주신다고 고생많으셨어요 🙏 
남아있는 미션들도 끝까지 완주해보세요 😄

2023-06-28 06:33 UTC, sah3122 commented on src/main/kotlin/lotto/domain/LottoPurchase.kt
>          return lottos
Lottos.manual() / auto() 와 같이 로또일급 컬렉션이 로또 생성을 담당하는것도 좋을것 같네요 😄

2023-06-28 06:33 UTC, sah3122 commented on src/main/kotlin/lotto/service/LottoShopService.kt
> +class LottoShopService {
서비스 객체 선언 👍

2023-06-28 06:33 UTC, merged

2023-06-28 06:49 UTC, yoo-jaein commented
꼼꼼하고 좋은 리뷰 남겨주셔서 감사합니다 ㅎㅎ