🚀 3단계 - 로또(2등)
next-step/kotlin-lotto pull request #786
Opened 2023-06-29 14:04 UTC by jonghyunhub

안녕하세요 리뷰어님!

좋은 피드백 감사합니다. 덕분에 많이 배우고 있네요 🤗
이번 미션에서도 피드백 잘 부탁드리겠습니다 🙏🏻

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/BonusBall.kt
> +class BonusBall(val bonusNumber: Int, lotteryPaper: LotteryPaper) {
BonusBall이라는 클래스 이름과는 달리 LotteryPaper가 있는 이유는 무엇일까요?
LotteryPaper와 BonusBall 의 책임을 한번더 고민해보면 좋을거 같아요!

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/BonusBall.kt
> +class BonusBall(val bonusNumber: Int, lotteryPaper: LotteryPaper) {
val bonusNumber: Int 도 하나의 LottoNumber 가 아닐까요?
LottoNumber라는 객체를 만들어보아요!

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LotteryPaperFactory.kt
> +        } while (lotteryPaperValidator.isAlreadyExistLotteryPaper(lotteryPaperList, generatedLotteryPaper))
동일한 로또를 사지 말아야하는 이유가 있나요?
로또를 생성하는데, 
로또 생성이외의 lotteryPaperList에 대한 관심사가 있어야할까요?
한번 고민해보셔도 좋을거 같아요!

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +        bonusBall: BonusBall
winningNumber 에 bonusBall도 포함되어있지 않을까요?
winningNumber 객체를 생성해보면 어떨까요?

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +        val matchedCountsMap = getMatchedCount(winningLottoNumber, purchasedLotteryPapers.lotteryPaperList)
winningNumber의 내부의 값을 가져와서 사용하기보단, 
winningNumber에게 책임을 부여하고, 위임하는 구조는 어떨까요?

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +            SecondLevelDiscriminator.checkPrizeLevelIsSecond(eachPrizeLevel, matchedCount.key, bonusBall)
SecondLevelDiscriminator라는 싱글턴 객체에 직접 접근하게 된다면,
의존성이 강하게 생기게 됩니다. 싱글턴객체의 직접접근은 지양해주세요!

PrizeLevel 의 책임이 SecondLevelDiscriminator으로 분산된건 아닐까요? 
PrizeLevel의 책임을 한번더 고민해보면 어떨까요?

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoMatcher.kt
> +            SecondLevelDiscriminator.checkPrizeLevelIsSecond(eachPrizeLevel, matchedCount.key, bonusBall)
checkPrizeLevelIsSecond라는 함수의 리턴값이 Prize라는걸 예상할수 있을까요?

2023-06-29 15:28 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +    private val lotteryPaperList: MutableList<LotteryPaper> = mutableListOf()
LottoShop 객체에서 lotteryPaperList을 가지고 있는 특별한 이유가 있을까요?

2023-06-29 15:37 UTC, namjackson requested changes
안녕하세요 종현님!
3단계 구현 잘해주셨네요! 
몇가지 고민할법한 포인트들 코멘트로 남겼으니, 
확인해주세요! 변경사항 적용후, 다시 리뷰요청해주시면 감사하겠습니다 😄

2023-06-29 15:37 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +    }
두 함수는 순서가 정해져있는 함수입니다. ( + buyLottoTicket)
순서가 정해져있어서, 순서가 바뀌거나, 앞의 함수가 실행되지 않는다면, 정상 동작하지 않을거 같아요! 

generate라는 네이밍과 달리 리턴값이 없고, getPurchasedLotteryPapers함수 호출마다 generateLottoNumbers의 실행 여부를 체크해야하는 구조네요! 
따로 분리한 이유가 있을까요?

2023-06-29 15:37 UTC, namjackson commented on src/main/kotlin/lotto/domain/PrizeLevel.kt
> +    SECOND(5, 30_000_000),
2등과 3등의 차이를 여기서는 알수가 없네요,
(2등과 3등의 차이를 알기위해, 실제 PrizeLevel이 사용되는 로직을 살펴봐야하는 구조네요)
Prize에서 보너스볼 유무를 PrizeLevel에서 관리하면 어떨까요?

2023-06-30 03:12 UTC, jonghyunhub commented on src/main/kotlin/lotto/domain/BonusBall.kt
> +class BonusBall(val bonusNumber: Int, lotteryPaper: LotteryPaper) {
LottoNumber를 만들어서 사용하면 따로 복잡하게 사용할 필요가 없어지겠네요! 감사합니다 👍

2023-07-02 11:24 UTC, namjackson approved these changes

2023-07-02 11:24 UTC, namjackson commented on src/test/kotlin/lotto/domain/LotteryPaperFactoryTest.kt
> +        Assertions.assertThat(generatedLotteryPaper.getLottoNumbers()).hasSize(6).allMatch { it.lottoNumber in 1..45 }
given when then
 준비 실행 검증 단계를 나눠보면 어떨까요?
 테스트의 가독성도 올라가고, 무엇을 테스트하는지 명확해지기도 해요!
 ```suggestion

        // given
        val generatedLotteryPaper = lotteryPaperFactory.generateLotteryPaper(listOf())
        // when 
        val lottoNumber = generatedLotteryPaper.getLottoNumbers()
        val expectedSize = 6
        // then
        assertThat(lottoNumber)
             .hasSize(expectedSize)
             .allMatch { it.lottoNumber in 1..45 }
```

2023-07-02 11:24 UTC, namjackson commented on src/test/kotlin/lotto/domain/LotteryPaperTest.kt
> +class LotteryPaperTest {
추가로 생성된 LottoNumber, WinnerNumber등의 테스트 코드도작성해보아요!

2023-07-02 11:26 UTC, namjackson approved these changes
안녕하세요 종현님!
피드백 잘적용해주셨네요!
추가적으로 고민할법한 부분들 코멘트로 남겼으니, 확인해주세요!
변경사항은 다음 미션 진행하면서 적용해주세요!

2023-07-02 11:26 UTC, namjackson commented on src/test/kotlin/lotto/domain/LottoMachineMatcherTest.kt
> +            ),
테스트를 위한 코드에서 객체생성의 코드가 길어져서, 가동성이 저하되었네요!
테스트헬퍼와 같은 팩토리함수를 만들어보면 어떨까요?

2023-07-02 11:27 UTC, merged

2023-07-03 08:31 UTC, jonghyunhub commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
로또 머신에서 생성한 로또 용지를 내부 변수로 가지고 있을 필요가 없네요!
감사합니다 👍

2023-07-03 15:47 UTC, jonghyunhub commented on src/main/kotlin/lotto/domain/LotteryPaperFactory.kt
> +            generatedLottoNumber = lottoNumberGenerationStrategy.generateLottoNumber()
이런 방법이 있었군요! 피드백 감사합니다 💪