Step1: 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #808
Opened 2023-11-02 03:39 UTC by Factoriall

일단 TDD 위주로 짜기 위해 README.md에 기능 목록을 업데이트하고 이에 맞춰 코드를 작성하려는 연습을 진행했습니다.

2023-11-02 14:56 UTC, hjjae2 requested changes
안녕하세요, 기현님!

자동차 미션 함께 진행하게 된 이현재입니다. 잘부탁드립니다. 🙇‍♂️ 

몇 가지 코멘트 남겼는데요, 확인 한번 부탁드립니다! 🙇

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun parseWithDelimeter(text: String): List<String> {
Delimiter 오타인 것 같네요!

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/Calculator.kt
> +        val result = Regex("//(.)\n(.*)").find(text)
1. `Regex("//(.)\n(.*)")` 객체는 변함이 없어보이는 객체로 보여지네요, 클래스 변수로써 관리하면 더 효율적일 수 있을까요?
2. `"//(.)\n(.*)"` 라는 정규표현식도 어떤 정규표현식인지 의미가 궁금할 것 같아요. 변수/상수로써 관리한다면 의미를 부여할 수 있기에 조금 더 코드를 빠르게 이해하는데 도움이 될 수 있을까요?
    - 아래의 `",|:"` 도 마찬가지로 의견 드려보아요!
4. (사소한 의견입니다.) result 라는 네이밍도 좋지만, 조금 더 의미를 부여할 수 있는 네이밍을 사용해봐도 좋겠네요.

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun parseWithDelimeter(text: String): List<String> {
조금은 같이 고민해봐도 좋을 것 같아 코멘트 남겨보아요.

현재는 Calculator 에서 문자열을 파싱하는 역할까지 갖고 있습니다. Calculator 를 어떻게 해석할 지에 따라 다를 것 같아, 지금의 형태도 이해가 됩니다.
다만, 파싱 처리를 위한 클래스를 별도로 분리하고 이 클래스와 협력하는 형태로 구성한다면 조금 더 각각의 클래스에게 적절한 역할을 부여하는 형태가 될 수도 있을 것 같아요.

기현님은 어떻게 생각하시나요? 💭

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/Calculator.kt
> +        if (text.isNullOrEmpty()) return 0
사소하지만 상수로 관리해도 좋겠네요. 👍

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/Token.kt
> +data class Token(private val text: String) {
사소한 의견입니다.

양수의 숫자만 다루는 클래스로 보여지네요. (Token 이라는 네이밍보다) 이를 더 잘 표현할 수 있는 네이밍은 없을까요? 🤔

2023-11-02 14:56 UTC, hjjae2 commented on src/main/kotlin/calculator/ParsedToken.kt
> +data class ParsedTokens(val tokenList: List<Token>) {
일급 컬렉션으로 관리해주셨군요. 👍 

사소한 의견입니다만, Token 목록을 관리해주는 클래스일 뿐인데 이름에 `Parsed` 가 붙은게 조금 의문이 들었어요.
그렇다면 Token 도 ParsedToken 이었어야 하지 않나? 라는 생각이 처음에 들었거든요. 

기현님께서 어떻게 생각하셨는지 궁금하네요!

2023-11-02 14:56 UTC, hjjae2 commented on src/test/kotlin/calculator/CalculatorTest.kt
테스트 코드 깔끔하게 작성해주셨네요. 👍

2023-11-03 11:02 UTC, Factoriall commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun parseWithDelimeter(text: String): List<String> {
저도 이부분 고려해서 Calculator와 Parser를 나눠서 작성을 했었는데, 이렇게 하니깐 Calculator가 하는 역할이 아예 없더라고요. 말그대로 Calculator().calculate() 이것만 하고 나머지는 ParsedToken이나 Parser가 모든 처리가 이뤄져서... 그래서 Parser와 Calculator를 합쳐서 그냥 Calculator 하나로 정의했습니다.

2023-11-03 12:54 UTC, Factoriall commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun parseWithDelimeter(text: String): List<String> {
다시 생각해보니 그래도 Parser를 만드는게 좀더 기능 분리에 용이할 것으로 보여 분리 진행했습니다.

2023-11-04 00:29 UTC, hjjae2 approved these changes
안녕하세요, 기현님! 

의견 드린 부분에 대해서 잘 반영해주셨네요. 👍 

다음 단계로 넘어가도 좋을 것 같아 머지하도록 하겠습니다. 고생하셨습니다. 🙇

2023-11-04 00:29 UTC, merged