Step2: 로또(자동)
next-step/kotlin-lotto pull request #810
Opened 2023-11-02 05:10 UTC by wdj0717

안녕하세요 남재님! 말씀주신 부분대로 README에 요구사항 분석하여 해당 부분으로 commit을 한번 쪼개봤습니다.
저번 미션에서 마지막 단계인 리팩토링에서 Mvc구조로 변경하는 작업이 있어서 해당 구조로 작업을 해봤는데,
Service단 자체가 도메인영역으로 사용이 되도 되는지에 대해 여쭤보고 싶습니다!

이번에도 잘부탁드립니다! 감사합니다!

2023-11-02 07:32 UTC, namjackson requested changes
안녕하세요 동재님!
2단계 고생하셨습니다!
몇가지 고민할법한 코멘트 남겼으니, 확인해주세요!

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
현실세계에서는 LottoStore가 winningRank를 해주지만,
객체 세계에서는 서로 다른 책임을 가지고 있지는 않을까요?
winningLotto 객체에게 위임해보면 어떨까요?

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/view/OutputView.kt
> +        val rateOfReturn = totalWinningMoney.toDouble() / inputPrice.toDouble()
연산작업은 하나의 도메인 로직은 아닐까요?
View에서는 화면 관련 기능만 수행해보면 어떨까요?

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
buyLotto는 테스트에서만 사용되네요, 
테스트 진행을 위해 함수를 노출하게되는데 고민해보면 좋을거같아요!

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        require(lottoCount > 0) { throw RuntimeException("로또를 구매할 수 없습니다.") }
require은 내부적으로 어떤 동작을 하고있을까요?

(2중으로 throw  되고있어요!)

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        return(1..lottoCount).map { buyLotto() }
`List(lottoCount) { buyLotto() }`
라고 표현할수도 있어요!

2023-11-02 07:32 UTC, namjackson commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +class LottoTest : FunSpec({
범위 외의 숫자로 구성된 로또도 생성이 가능할까요?
5개의 번호만 가지고 있는 로또도 로또라 부를수 있을까요?

추가로 고민해보아요

2023-11-02 07:32 UTC, namjackson commented on src/test/kotlin/lotto/domain/LottosTest.kt
> +    test("당첨번호와 로또번호를 비교하여 당첨 결과를 확인할 수 있다.") {
당첨 결과를 확인해보면 어떨까요?

2023-11-02 07:32 UTC, namjackson commented on src/test/kotlin/lotto/domain/LottoStoreTest.kt
> +    }
LottoStore가 아닌 , Lotto가 가져야할 테스트는 아닐까요?

2023-11-02 07:32 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoController.kt
> +    fun run() {
> Service단 자체가 도메인영역으로 사용이 되도 되는지에 대해 여쭤보고 싶습니다!

정확히 어떤 의미인지 모르겠어요! 스프링의 구조를 말씀하시는 걸까요?
Service 또한 도메인 영역으로 볼수도 있을거같아요!

2023-11-02 11:26 UTC, wdj0717 commented
안녕하세요 남재님! 피드백이 너무 만족스러웠습니다! 감사합니다!
한가지 제가 이해가 안되는 부분이 있어서 이부분에 대해서 답변해주시면 감사하겠습니다!
로또 번호를 생성하는데에 있어서 원하는 로또번호를 생성할 수 있게 추상화를 해야한다는 말씀이 조금 이해가 안됐습니다.
자동으로 랜덤으로 번호를 생성해야하는데, 원하는 로또번호를 생성한다는 의미가 정확히 어떤 관점으로 말씀하신건지 답변 부탁드립니다!

좋은 피드백 다시 한번 더 너무 감사합니다!

2023-11-03 02:46 UTC, namjackson approved these changes
안녕하세요 동재님! 
피드백적용잘해주셨네요! 
몇가지 추가적으로 코멘트남겼으니, 확인해주세요 😄 
변경사항은 다음단계 진행시 포함해주세요!

2023-11-03 02:47 UTC, merged

2023-11-03 03:15 UTC, wdj0717 commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    override fun shuffleNumber(): List<Int> {
음 넵! 자동차 미션에서는 랜덤값에 start end변수를 받아서 테스트를 진행했었습니다. 
default 값을 선언해놓고 테스트시에는 해당 변수값을 주어서 테스트를 진행했었는데...이부분을 좀 더 고민해봐야겠네요!