Step1 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #816
Opened 2023-11-02 13:15 UTC by moto6

2023-11-03 04:15 UTC, laco-dev requested changes
TDD 를 활용하기 위한 과정과 꼼꼼히 작성한 모습이 드러나서 좋았습니다. 
다만 객체를 분리하고 개선하는 과정에서 역할과 의미가 바뀌어 버렸기 때문에 의존관계가 다소 어렵게 만들어진 것 같습니다.

로또 미션에서 고민이 필요한 내용들이기 때문에, 남겨드린 피드백을 먼저 확인 하고 넘어가면 좋을 것 같습니다. 🙏🏻

2023-11-03 04:15 UTC, laco-dev commented on src/main/kotlin/calculator/model/Token.kt
> +        return Token(value + token.value)
data class를 사용한다면 copy() 함수를 이용해서 복사가 가능합니다.
```kotlin
return copy(value = value + token.value)
```

2023-11-03 04:15 UTC, laco-dev commented on src/main/kotlin/calculator/app/StringCalculator.kt
> +object StringCalculator {
이름은 StringCalculator 이지만, 실제로 String과 관련된 처리가 더이상 존재하지 않아요.
역할을 잘 분리 해주셨기 때문에 이름과 역할이 서로 달라지게 된 것으로 보이는데요.

`input -> formula -> result`로 만드는 과정이 하나의 세트로 동작한다면, StringCalculator에서 한번에 처리해도 되지 않을까요?
```kotlin

object StringCalculator {
   fun calculate(rawExpession: String): Int  {
      val tokens = ...
      val formula = ...
      return result
   }
}
```

2023-11-03 04:15 UTC, laco-dev commented on src/main/kotlin/calculator/app/StringCalculator.kt
> +        return reduce.value
formula에 있는 tokens를 직접 접근해서 처리하고 있어요.
그렇다면, 이 동작을 formula가 하도록 역할을 넘겨주면 어떨까요?

```kotlin
val result = formula.sum()
return result
```

2023-11-03 04:15 UTC, laco-dev commented on src/main/kotlin/calculator/component/Tokenizer.kt
> +    }
isNumeric()함수에서 이미 toIntOrNull()를 이용해 변환하고 있는데, 이후에 다시 input.toInt()가 호출이 되고 있어요.
무거운 작업은 아니라서 큰 영향은 없지만, toIntOrNull()의 동작이 명확함으로 바로 사용해도 되지 않을까요?
```kotlin
return input.toIntOrNull() ?: throw IllegalArgumentException(...)
```

2023-11-03 04:15 UTC, laco-dev commented on src/main/kotlin/calculator/view/ConsoleView.kt
> +object ConsoleView {
이전 자동차 경주 미션에서 InputVIew, OutputView로 입력/출력을 나누어서 구현 하셨었나요?
입력/출력 로직이 ConsoleView로 하나로 합쳐져있어서 질문드립니다.

2023-11-03 04:15 UTC, laco-dev commented on src/test/kotlin/calculator/component/TokenizerTest.kt
> +        actual shouldContain TokenFixture.TOKEN[3]
Fixture를 사용한 테스트 환경 분리방법 좋습니다. 👍🏻 

다만 Fixture를 사용하게 되면, 이 값이 의미하는 결과가 무엇인지 확인하기 위해 코드 이동과 결과 예측이 추가로 필요합니다.
복잡한 객체를 생성하는 것이 아니라면, 테스트 코드 내에서 모든 컨텍스트가 드러나도록 작성 하면 어떨까요?

```kotlin
actual shouldContain Token(1)
actual shouldContain Token(2)
```

2023-11-03 10:22 UTC, moto6 commented on README.md
> +# kotlin-lotto
넵 조금더 커밋메시지와 커밋 단위에 대해서 신경쓰겠습니다!

2023-11-03 10:28 UTC, moto6 commented on src/main/kotlin/calculator/component/Formula.kt
> +package calculator.component
차이가 없는거같아 model 로 통합하였습니다!

2023-11-03 10:29 UTC, moto6 commented on src/main/kotlin/calculator/component/Sanitizer.kt
> +object Sanitizer {
넵 엘비스연산자를 사용해서 리팩토링을 진행했습니다!

2023-11-03 10:33 UTC, moto6 commented on src/main/kotlin/calculator/component/Helper.kt
> +}
네 이부분 삭제하겠습니다!

2023-11-03 10:35 UTC, moto6 commented on src/test/kotlin/calculator/model/TokenTest.kt
> +        }
shouldNotThrow {  } 를 사용해서 수정하겠습니다! 
커버리지로는 적당한 다른 숫자로 변경하겠습니다!

2023-11-03 10:38 UTC, moto6 commented on src/main/kotlin/calculator/model/Token.kt
> +        return Token(value + token.value)
좋은 꿀팁 알려주셔서 감사합니다. 코틀린 언어에 대해서 조금더 학습하겠습니다!

2023-11-03 10:44 UTC, moto6 commented on src/main/kotlin/calculator/app/StringCalculator.kt
> +object StringCalculator {
넵 피드백 감사합니다
1) 이름과 역할이 좀더 잘 맞도록 이름 수정
2) StringCalculator에서 한번에 처리하도록 (계산기 외부에서 토큰화하지 않고 내부에서 토큰화하도록)

위 두가지로 수정하겠습니다!

2023-11-03 10:52 UTC, moto6 commented on src/main/kotlin/calculator/app/StringCalculator.kt
> +        return reduce.value
앗 완전 좋은 아이디어인거같습니다 바로 적용하겠습니다!

2023-11-03 10:55 UTC, moto6 commented on src/main/kotlin/calculator/component/Tokenizer.kt
> +    }
엘비스 연산자를 여기서도 적용해 불필요한 함수호출을 제거하도록 리팩토링 하겠습니다!

2023-11-03 10:56 UTC, moto6 commented on src/main/kotlin/calculator/view/ConsoleView.kt
> +object ConsoleView {
이전 자동차 경주 미션에서 InputVIew, OutputView로 입력/출력을 나누어서 구현 하였습니다. 

이번에 ConsoleView로 하나로 합쳐서 구현되어있는 이유는.. InputVIew, OutputView 를 나누면 오버엔지니어링이 될꺼같아서 입니다!

2023-11-03 10:59 UTC, moto6 commented on src/test/kotlin/calculator/component/TokenizerTest.kt
> +        actual shouldContain TokenFixture.TOKEN[3]
넵 해당부분은 제거해내겠습니다!

2023-11-03 11:03 UTC, moto6 commented
안녕하세요 리뷰어님! 
정성스럽고 꼼꼼하게 리뷰해주셔서 너무너무 감사합니다. 

리뷰를 고치면서 아래의 것들을 느꼈습니다 
```
1) 코틀린 공부를 하자 : elvis연산자 등을 몰랐음..
2) 나쁜 습관 : 불필요한 코드 남겨놓기, 패키지 구조를 복잡하게 
```

위 두가지는 앞으로도 잘 기억하고 개선하겠습니다! 

좋은 리뷰 다시한번 감사드립니다!

2023-11-04 01:27 UTC, laco-dev approved these changes
피드백 꼼꼼히 반영하고 답변들을 남겨주셔서 좋았습니다. 👍🏻 

코틀린 기능을 더 잘 써볼수 있도록 해당 관점에서 확인해보도록 하겠습니다.
이후 로또 미션도 화이팅입니다.

2023-11-04 01:27 UTC, laco-dev commented on src/main/kotlin/calculator/view/ConsoleView.kt
> +object ConsoleView {
네, 의도를 명확히 가지고 계시다면 충분합니다.
현재 미션들에서는 입력과 출력이 나뉘는 정도의 생기지는 않으니까요.

이후 미션들에서도 아마 동일한 질문이 들어올 수 있는데, 참고해주시면 되겠습니다.

2023-11-04 01:27 UTC, merged