🚀 1단계 - 문자열 덧셈 계산기
next-step/kotlin-lotto pull request #849
Opened 2023-11-04 20:49 UTC by giibeom

안녕하세요 리뷰어님 :)
로또 미션 동안 잘 부탁드립니다 🙏🙏
(코틀린을 아예 처음 써봐서 좀 어렵네요 😂)

### 고민 포인트

1. 객체의 역할을 어떻게 분리할 지 아래와 같이 고민해보았습니다

   <img src="https://github.com/next-step/kotlin-lotto/assets/59248326/0ff23c17-3c44-4974-87a7-8ed8bc84c8df" width="50%" />

2. 코틀린을 코틀린답게 사용하는 방법에 대해 관심이 많지만... 이게 잘 쓴건지 잘 모르겠습니다 🤔
3. kotest도 잘 사용하고 있는건지, 더 깔끔하게 잘 사용하는 방법이 있을지 궁금합니다!

<br>

#### 하드한 피드백과 매정한 Request Change 부탁드립니다 ㅎㅎ 😊 🙇🏻‍♂️

2023-11-06 12:52 UTC, Rok93 requested changes
기범님 안녕하세요. 로또 미션을 함께하게 된 김경록입니다. 😃
리뷰가 늦어서 죄송합니다. 🙏🙇‍♂️

객체 Diagram을 그려서 공유해주신 점이 인상적이었고, 그 덕분에 저도 기범님의 구현 의도를 조금 더 잘 파악할 수 있었던 것 같습니다. 😃
현재 `InputAnalyzer` 객체가 너무 많은 책임을 가지고 있는 것 같아요. 🤔 
이 책임들을 적절히 다른 객체들에게 위임해주면 조금 더 객체지향적인 코드로 변경해볼 수 있을 것 같습니다. 관련해서는 코멘트로 남겨두었으니 참고해주셔서 반영해주시면 좋을 것 같습니다. 🙏 

잘 이해가 안되거나 미션 진행하면서 어려운 부분이있으면 언제든지 DM 주세요. 😁

2023-11-06 12:52 UTC, Rok93 commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +        if (number < 0) {
음수라는 표현에서 `0` 정도는 의미를 파악하기 상대적으로 쉬울 수 있지만 그럼에도 불구하고 `매직 넘버`는 코드를 직관적으로 이해하기 어렵게 만드는 요소라고 생각해요. 🤔
[참고글](https://javabom.tistory.com/28)을 읽어보시고 코드의 의미를 조금 더 직관적으로 드러내도록 변경해보시면 좋을 것 같습니다. 🤗

2023-11-06 12:52 UTC, Rok93 commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +        inputString.split(*delimiters.toTypedArray()).forEach { token ->
사소한 부분이지만 `Array`로 변경하는 것도 좋지만 정규식으로 변경해서 분리하는 방법도 괜찮은 것 같아요. 🤔
```suggestion
        val regex = delimiters.joinToString("|").toRegex()
        inputString.split(regex).forEach { token ->
```

2023-11-06 12:52 UTC, Rok93 commented on src/main/kotlin/calculator/InputView.kt
> +fun main() {
파일 이름은 `InputView`인데, 실제로는 애플리케이션을 실행하는 역할을하고 있는 곳인 것 같아요. 👀
NumberCalculatorMain,  NumberCalculatorApplication 같은 네이밍은 어떨까요? 🤔

2023-11-06 12:52 UTC, Rok93 commented on src/main/kotlin/calculator/NumberCalculator.kt
> +object NumberCalculator {
`문자열 덧셈 계산기` 도메인을 다루고있는데, `숫자 계산기` 객체보다는 조금 더 도메인에 fit한 객체를 만들어보면 어떨까요? 🤔

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +    }
`object DelimiterParser {}` 객체를 새로 생성하여, 구분자를 분리하는 역할을 부여하였습니다! (`extractDelimiters()`)

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +    }
`Delimiters` 객체를 새로 생성하여 숫자 목록(`PositiveNumbers`)을 추출하는 역할을 부여하였습니다! (`extractPositiveNumbers()`)

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +        }
요구 사항에서 `RuntimeException`으로 던지라고 해서 일부로 해당 코드를 작성하였는데, `IllegalArgumentException`가 어차피 `RuntimeException`을 상속받는 형태니까 상관없으려나요?? 🤔🤔

![image](https://github.com/next-step/kotlin-lotto/assets/59248326/a86ee4b9-f855-4817-a64c-be93ef8a6447)

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +            validateIsNonNegative(token.toInt())
오! 현재는 `PositiveNumbers` 일급 컬렉션에서 `add()` 할 때 음수에 대한 유효성 검증 로직을 추가해놓았는데요 😃
말씀하신대로 VO로 만들어서 관리해도 좋아보이네요!

![image](https://github.com/next-step/kotlin-lotto/assets/59248326/11c7f79e-1d42-4ddb-a2b3-847352daa677)

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputView.kt
> +fun main() {
저도 동일한 생각이 들어서 전체적으로 리팩터링 할 때 `InputView`는 `StringCalculator(Application)` 객체로 변경하였습니다! 😂😂

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/NumberCalculator.kt
> +object NumberCalculator {
생각해보니 전체적으로 리팩터링을 했지만, 도메인스러운(?) 객체는 `Delimiters` 정도네요 🤔
계산에 대한 역할을 일급 컬렉션인 `PositiveNumbers`에 줘서 그런가 싶기도 하네요 😅

따로 뺄 만한 도메인 객체가 있을까요??

2023-11-10 19:44 UTC, giibeom commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +        inputString.split(*delimiters.toTypedArray()).forEach { token ->
와우 "|"로 List를 하나로 묶어서 정규표현식으로 만드는 아주 좋은 방법이군요!
감사합니다 👍

2023-11-11 11:00 UTC, Rok93 commented on src/main/kotlin/calculator/InputAnalyzer.kt
> +        }
아아... 그렇군요 미션 요구사항에서는 RuntimeException을 던지라고하고있긴한데, IllegalArgumentException 예외를 던져도 크게 상관없을 것 같습니다. 😃

2023-11-11 11:13 UTC, Rok93 commented on src/main/kotlin/calculator/NumberCalculator.kt
> +object NumberCalculator {
객체지향은 객체와 객체간의 협력을 통해서 객체의 역할을 수행하는 것이 핵심이에요. 
현재 delimiters, positiveNumbers, delimiterParser 등의 객체들은 잘 설계해주셨지만, 
이들의 협력이 이루어지도록 구성하지는 않은 것 같아요. 👀

지금의 구조에서 `StringCalculator` 객체를 생성할 것 같아요. 🤔

```kotlin
object StringCalculator {

    fun add(input: String): Int {
        val expression = DelimiterParser.extractPureInput(input)
        val delimiters = DelimiterParser.extractDelimiters(input)
        val positiveNumbers = delimiters.extractPositiveNumbers(expression)

        return positiveNumbers.sum()
    }
}


// 실행부
fun main() {
    StringCalculator.add(readln())
    println(result)
}
```

2023-11-11 11:48 UTC, Rok93 approved these changes
기범님 피드백 잘 반영해주셨네요. 👍
이만하면 1단계는 충분한 것 같아서 이만 머지하겠습니다. 😉
몇몇 코멘트 남겨둔 부분은 확인해서 다음단계 진행하실 때, 같이 반영해주세요.🙏

잘 이해가 안되거나 어려운 부분이 있으면 언제든지 DM 주세요. 🤗

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/DelimiterParser.kt
> +            delimiters.add(it.groupValues[1])
`1`과 `2`가 어떤 값인지 의도를 바로 파악하기가 어려운 것 같아요. 👀
상수로 추출하여 의도를 조금 더 명확하게 드러내보면 좋을 것 같습니다. 🙏

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/DelimiterParser.kt
> +    fun extractPureInput(input: String): String {
분리해낸 결과가 무엇인지 생각해봤을 때, 저는 입력에서 `수식` or `식`을 분리하는 기능이라 생각했어요. 🤔
이 메서드를 실행한 결과가 무엇인지 네이밍에서 조금 더 드러나도록 변경해보면 어떨까요?

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/Delimiters.kt
> +            throw RuntimeException("입력 값은 쉼표(,), 콜론(:), 커스텀 구분자를 제외한 나머지 문자는 모두 숫자로 입력해야 합니다.")
token 값이 무엇인지도 예외 메세지에 포함되어있으면 조금 더 에러를 파악하기 쉽겠죠? 🤗

```suggestion
            throw RuntimeException("입력 값은 쉼표(,), 콜론(:), 커스텀 구분자를 제외한 나머지 문자는 모두 숫자로 입력해야 합니다. token: $token")
```

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/DelimiterParser.kt
> +        return delimiters
일단 비어있는 Delimiters를 선언한 뒤, 하나하나 추가하는 것 보다. 
미리 Delimiters 객체를 생성하기위해 필요한 값들을 만든 뒤에, 생성자를 통해 단순히 주입해주도록 변경해보면 어떨까요? 😃

객체가 생성된 이후, 별다른 준비과정없이 자신의 책임을 수행하기만하면 되는 상태로 만들어주세요. 🙏 (PositiveNumbers 또한 비슷한 상황인 것 같습니다.)

```suggestion
        fun extractDelimiters(input: String): Delimiters {
        val customDelimiterMatchResult = CUSTOM_DELIMITER_PATTERN.find(input)
        val delimiters = if (customDelimiterMatchResult != null) {
            DEFAULT_DELIMITER + customDelimiterMatchResult.groupValues[1]
        } else {
            DEFAULT_DELIMITER
        }

        return Delimiters(delimiters)
    }
```

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/Delimiters.kt
> +    }
하나의 요소를 추가하는 것과 다수의 요소를 추가하는 것은 엄연히 다른 기능인 것 같아요. 🤔
저희가 흔하게 쓰고있는 Collection도 그런 의도에서 add와 addAll 메서드를 나눈게 아닐까요? 😉

2023-11-11 11:48 UTC, Rok93 commented on src/main/kotlin/calculator/Delimiters.kt
> +            throw RuntimeException("입력 값은 쉼표(,), 콜론(:), 커스텀 구분자를 제외한 나머지 문자는 모두 숫자로 입력해야 합니다.")
입력 값에 대한 검증,  그 중에서도 분리했을 때의 `값이 0보다 큰 값이 맞는지`를  Delimiters 객체가 검증하는게 맞을까요? 🤔
개인적으로 PositiveNumber 객체가 생성되는 시점에 이 검증이 수행되는 것이 조금 더 올바른 방향이라고 생각해요. 👀

지금의 경우에는 이 검증을 위해서 구분자로 숫자(여야하는 것)들을 다 분리하여 값 하나하나를 검증하고있어요. (이 방식은 비효율적인 것 같아요. 🥲)
어짜피 delimiters로 쪼개야하는 값들인데, 이 검증을 쪼개는 역할만 있는 객체에게 시키는게 맞는지 고민해보시면 좋을 것 같습니다. 😃

2023-11-11 11:48 UTC, merged