[step2] 로또 자동
next-step/kotlin-lotto pull request #855
Opened 2023-11-05 13:11 UTC by Ahn-seokjoo

로또 자동 작업입니다 !!
리뷰 부탁드립니다.

2023-11-06 12:11 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-11-06 12:11 UTC, kyucumber commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +        6 -> 2_000_000_000
결과가 더 늘어나진 않겠지만 결과가 늘어날 때 마다 when 구문에 추가해주어야 하며, 깜빡할 경우 버그가 발생할 우려가 있어보여요. enum을 활용해볼 순 없을까요?

2023-11-06 12:11 UTC, kyucumber commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +    }
enum과 Map(`Map<Enum, Int>`)를 활용하도록 개선해볼 수 있을까요?

2023-11-06 12:11 UTC, kyucumber commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +    }
현재 Lotto 클래스의 역할이 거의 없습니다. 이 부분의 역할을 Lotto 클래스로 옮겨볼 수 있을까요?

2023-11-06 12:11 UTC, kyucumber commented on src/test/kotlin/lotto_auto/LottoTest.kt
> +class LottoTest : FunSpec({
위에 validation에 대한 이야기를 적어두었는데요. 실제로 8개를 전달해 생성하거나 이런 경우 예외가 발생하는지 여부도 테스트로 체크되면 좋을 것 같아요.

2023-11-06 13:43 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/Lotto.kt
> +    val number: List<Int> = createLotto(),
79070934479a0fe2279f401eb764638e3324abb9 반영했습니다.

2023-11-06 13:52 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/Lotto.kt
> +        private fun createLotto(): List<Int> = (1..45).shuffled().take(6).sorted()
79070934479a0fe2279f401eb764638e3324abb9 반영했습니다.
그런데, 테스트 관련 궁금한점이 있는데요, withData의 파라미터로 listOf(0,1,2,3,4,5) 와 같이 전달할 경우 io.kotest.core.spec.InvalidDslException: Cannot add a root test after the spec has been instantiated: java.util.Arrays.ArrayList 를 맞는데, FunSpec 내부에 잘 위치해있는데 왜 에러가 나는지 모르겠네요 (주석처리 해두었습니다)

2023-11-06 13:54 UTC, Ahn-seokjoo commented on src/test/kotlin/lotto_auto/LottoTest.kt
> +class LottoTest : FunSpec({
79070934479a0fe2279f401eb764638e3324abb9 해당 테스트에 추가해두었습니다. (6개아 아니게 넘겼을 때 에러)

2023-11-06 14:12 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +    }
03443a4656574a59404535d60d5f60f4a815da76 수정했습니다.

2023-11-06 14:52 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +        6 -> 2_000_000_000
9d3e34acc43633eb186371ff9718c351895650b0 활용하였습니다!

2023-11-06 14:52 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +    }
9d3e34acc43633eb186371ff9718c351895650b0 수정해보았습니다~!

2023-11-07 09:28 UTC, Ahn-seokjoo commented on src/main/kotlin/lotto_auto/lotto/Lotto.kt
> +        private fun createLotto(): List<Int> = (1..45).shuffled().take(6).sorted()
위의 문제 해결하였습니다~!

2023-11-07 11:15 UTC, kyucumber approved these changes
코멘트 남겨두었는데요, 다음 단계 진행에 참고 부탁드려요.

다음 단계 진행을 위해 머지하겠습니다.

2023-11-07 11:15 UTC, kyucumber commented on src/main/kotlin/lotto_auto/lotto/Lotto.kt
> +    fun lottoMatchCount(lastWeekLottoNumber: Lotto): Int {
바로 LottoPrize를 반환할수도 있을까요?

2023-11-07 11:15 UTC, kyucumber commented on src/main/kotlin/lotto_auto/lotto/LottoAuto.kt
> +        )
이렇게 하는것도 좋지만 결국 LottoPrize가 늘어나게 되면 코드 작업으로 대응이 필요할 것 같아요.

Kotlin의 groupingBy와 eachCount와 같은 메서드를 활용해 Map으로 바로 뽑아볼 수 있을까요?

2023-11-07 11:15 UTC, merged