Step2 - 로또 (자동)
next-step/kotlin-lotto pull request #861
Opened 2023-11-05 19:04 UTC by sodp5

안녕하세요! 2단계 로또미션 제출합니다.

미션 구현 중 궁금한 점이 있었습니다.
테스트에서 랜덤 요소를 컨트롤하기 위해서 LottoGenerateStrategy 를 통해 로또 번호를 부여했습니다.
하지만 결과적으로는 DefaultLottoGenerateStrategy가 랜덤한 요소를 갖고 있어서 내부 구현이 조금 잘못되더라도
테스트에서 잘 걸러내지 못할 수 있게 된것 같은데 이 부분을 어떻게 개선해볼 수 있을까요??
구체적으로는, 중복 기능을 제거하거나 정렬 기능을 제거해도 테스트가 통과할 가능성이 있는 부분입니다.

2023-11-06 12:44 UTC, ddaaac requested changes
안녕하세요 경문님 👋 

로또 미션 구현 잘 해주셨습니다.

몇 가지 코멘트를 남겼으니 확인해주세요~

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +)
> 하지만 결과적으로는 DefaultLottoGenerateStrategy가 랜덤한 요소를 갖고 있어서 내부 구현이 조금 잘못되더라도
테스트에서 잘 걸러내지 못할 수 있게 된것 같은데 이 부분을 어떻게 개선해볼 수 있을까요??

랜덤을 생성하는 부분은 테스트가 어려운데 구현이 잘 못 되었으면 어떻게 할지 질문일까요? 좋은 질문입니다! 

로또 번호들이 가져야할 규칙이 3가지 있습니다. 로또 도메인에 대해서 잘 생각해보시면 떠오를 거에요.
이렇게 도메인에 대한 탐구를 마치면 이제 이를 코드에 녹여내야합니다.
코틀린 같은 경우에는 해당 규칙들을  `init` 블럭과 `require`를 사용해서 구현할 수 있겠네요.
이렇게 도메인이 자체적으로 완전하다면 랜덤 생성 부분에서 잘못된 값을 만들어도 도메인에서 받아주지 않기 때문에 문제가 없을거에요.

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/DefaultLottoGenerateStrategy.kt
> +        }
운이 나쁘다면 실행 시간이 오래걸릴 수 있을 것 같아요.
리스트를 미리 만들어두고 랜덤하게 셔플하는 방식을 사용하는 건 어떨까요?

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoWinning.kt
> +    CorrectFive(5, 1500000),
1_500_000 과 같이 구분자를 넣어주면 읽기 편해질 것 같습니다.

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        val lottoCount = money / 1000
상수는 분리해주시면 좋을 것 같습니다.

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoWinning.kt
> +            val correctCount = count.coerceIn(0..6)
파라미터가 적당한 값이 아니라면 에러를 뱉어야하지 않을까요?

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoWinningChecker.kt
> +    fun check(lottos: List<Lotto>, winningNumbers: List<Int>): List<Lotto> {
check라고 하면 코틀린의 검증 함수인 `check`가 떠오르는 것 같아요. 적당한 다른 이름을 찾아보는 것도 괜찮아보입니다.

2023-11-06 12:44 UTC, ddaaac commented on src/main/kotlin/lotto/ui/ResultView.kt
> +        return totalReward / investmentMoney.toDouble()
이런 로직은 도메인 로직에 속할 것 같아요. View에서 도메인으로 옮겨볼까요?

2023-11-06 12:44 UTC, ddaaac commented on src/test/kotlin/lotto/domain/DefaultLottoGenerateStrategyTest.kt
> +    }
처음 드린 코멘트를 반영하면 이 테스트들도 옮겨지겠네요.

2023-11-07 17:59 UTC, sodp5 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +)
말씀주신 내용 잘 이해했습니다!
다만 리뷰를 반영하기전에 궁금한 점이 있어서 먼저 질문을 드려보려고 합니다.

말씀주시 방법으로 구현하는 경우 1..45이나 중복 없음과 같은 로또의 룰이 Lotto 클래스에서 고정된다고 생각되는데요!
특정한 가정으로 로또 번호의 범위나 중복이 허용된다는 룰이 생길 수도 있는데 이 부분을 외부에서 컨트롤 해줄 수 있는 구조도 좋지 않을까? 란 의문이 남았는데,
너무 일반화를 하려 했는지 (클래스를 구체적으로 정의하지 않았는지) 궁금해서 리뷰어님의 생각을 여쭤보고자 질문드립니다!

2023-11-08 12:21 UTC, ddaaac requested changes
안녕하세요 경문님 👋 

남겨주신 질문에 코멘트 달았습니다.

확인하시고 다시 리뷰 요청주세요~

2023-11-08 12:21 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +)
- 가장 먼저 로직의 재활용 관점에서 얘기할 수 있을 것 같아요. 지금 로또는 1. 랜덤 생성된 로또와 2. 당첨 번호를 입력할 때 모두 같은 규칙을 갖습니다. 두 로또 모두 같은 규칙을 갖는데 외부에서 이 검증/생성을 컨트롤 하고 있다면 생성해줄 때마다 로직이 겹치게 들어가야하겠죠(지금은 당첨 번호에 대한 검증은 존재하지 않습니다).
- 이 코드에 대해 알지 못하는 사람이 로또의 규칙을 코드에서 찾아보려고 한다면 어떤 클래스를 찾아보게 될까요? 특정 로직이 있을만한 곳에 로직을 배치하는 게 빠르게 코드를 파악하기 좋을 것 같다는 생각이 듭니다. 개인적으로는 가장 직관적이고 예측 가능한 코드가 가장 유지보수하기 좋은 코드라고 생각해요.
- 말씀해주신대로 랜덤 로또와 당첨 로또의 규칙이 달라질 때를 생각해볼 수도 있을 것 같아요. 이런 경우 지금처럼 DTO 개념으로 로또 클래스를 사용할 수도 있지만 `Lotto`라는 인터페이스를 두고 각 구현체를 만드는 쪽이 변화에 유연하게 대응할 수 있는 방법일 것 같아요. 다만, 개인적으로 요구사항의 변화를 예측해서 인터페이스를 만드는 건 크게 의미있는 행동은 아니라고 생각합니다. 실제로 구체적인 새로운 요구사항이 등장했을 때 인터페이스를 도출해내고 구현체를 나눠도 늦지 않은 것 같네요.

2023-11-11 06:11 UTC, sodp5 commented on src/test/kotlin/lotto/domain/DefaultLottoGenerateStrategyTest.kt
> +    }
묘하게도 비슷한 테스트 같긴 한데 있는게 더 자연스럽다고 느껴져서 유지해두었어요!

이 테스트가 제거되기 위해서는 어느정도 구조의 변경이 있어야 더 자연스럽다고 느껴지는데
혹시 리뷰어님께서는 어떤 형태를 의도하신건지 알 수 있을까요??

2023-11-11 06:18 UTC, sodp5 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +)
세 가지 내용 모두 많이 공감되었습니다.
모두 실무에서도 자주 겪는 내용같아서 더 많이 생각해보는 기회가 되었습니다. 😂

지금 보니 질문이 부족했던것 같은데 좋은 말씀 주셔서 감사합니다!

2023-11-12 01:43 UTC, ddaaac approved these changes
안녕하세요 경문님 👋 

리뷰 반영 잘 해주셨습니다.

몇 가지 코멘트를 남겼으니 다음 단계에 함께 반영해주세요.

2023-11-12 01:43 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        require(numbers.toSet().size == NUMBERS_COUNT) {
큰 차이는 없지만 `numbers.distinct()`를 사용하면 의미를 조금 더 분명하게 전달할 수도 있습니다.

2023-11-12 01:43 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        return copy(winning = LottoWinning.of(correctCount))
개인적으로는 특별한 이유가 없다면 도메인 객체에 data 키워드를 사용하는 건 지양하려고 해요.
data 키워드가 열어주는 여러 편리한 함수, 특히 copy와 같은 함수는 객체지향을 해치고 유지보수하기 까다로운 코드를 만들 수 있다는 생각이 듭니다. 객체 외부에서도 copy 함수를 쉽게 사용할 수 있기 때문이죠.

2023-11-12 01:43 UTC, ddaaac commented on src/test/kotlin/lotto/domain/DefaultLottoGenerateStrategyTest.kt
> +    }
`Lotto`에 해당 로직이 들어가면서 `LottoTest`에서 이를 테스트하는 형식이 될 것 같다는 코멘트였습니다.
양쪽 다 테스트가 있는 것도 좋네요 👍

2023-11-12 01:43 UTC, ddaaac commented on src/main/kotlin/lotto/domain/LottoGenerateStrategy.kt
> +    fun generate(): List<Int>
LottoGenerate이라면 완성된 Lotto 객체를 반환해도 좋을 것 같아요.
새로 추가한 Lotto의 룰도 분명하게 가져갈 수 있고요.

2023-11-12 01:43 UTC, ddaaac commented on src/main/kotlin/lotto/domain/Lottos.kt
> +    fun matchAll(winningNumbers: List<Int>): Lottos {
winningNumbers가 가져야할 룰도 있을 것 같아요. 지금은 winningNumbers에 겹치는 숫자, 6개가 아닌 숫자들이 와도 이 객체를 통과할 것 같습니다.

2023-11-12 01:43 UTC, merged