Step3: 로또(2등)
next-step/kotlin-lotto pull request #881
Opened 2023-11-07 15:03 UTC by Factoriall

# 한 일
1. 2등 로직 추가
2. Lotto를 생성하는 LottoCreator 생성
3. Creator 생성에 따른 Strategy 삭제
4. Creator에 대응되는 AutoLotto, ManualLotto 생성
5. IntInput, LottoNumbersInput 생성, 인풋이 제대로 들어갔는지 확인하는 역할 담당
6. 변수명, 테스트 이름 변경

2023-11-08 09:20 UTC, hjjae2 requested changes
안녕하세요, 기현님!

몇 가지 코멘트 남겼는데요, 확인 한번 부탁드립니다! :bow:

2023-11-08 10:02 UTC, Factoriall commented on src/main/kotlin/lotto/domain/AutoLotto.kt
> +        LottoNumbers(*list.toIntArray())
사실 코멘트를 이해하지 못했습니다. 그래서 Lotto에 대한 팩토리 메소드 구현하면 된다고 판단했었습니다. 

그러니깐... LottoNumbers에 대한 내용이라면, LottoNumbers를 인터페이스화해createLottoNumbers를 추상 메소드로 선언하고, 각각 RandomLottoNumbers랑 ManualLottoNumbers를 구현해 이를 씀으로써 외부에서 생성 로직을 은닉하라고 부분으로 이해했는데 제가 맞게 이해했나요?

2023-11-08 10:09 UTC, Factoriall commented on src/main/kotlin/lotto/domain/IntInput.kt
입력에 대한 체크 로직만 있으니 view 패키지로 들어가는게 맞는걸로 보입니다!

2023-11-08 10:22 UTC, Factoriall commented on src/main/kotlin/lotto/domain/LottoNumbersInput.kt
> +        }
생각해보니 그냥 toInt에서 try/catch문만 써도 충분할거 같습니다. require 쓰겠다고 너무 돌아간거 같네요...

2023-11-09 09:48 UTC, hjjae2 approved these changes
안녕하세요, 기현님!

의견 드린 부분에 대해서 잘 반영해주셨네요. 👍 

코멘트 남긴 내용이 있는데요, 다음 미션에서 함께 확인 부탁드릴게요! 고생하셨습니다. 🙇

2023-11-09 09:48 UTC, hjjae2 commented on src/main/kotlin/lotto/domain/AutoLotto.kt
> +        LottoNumbers(*list.toIntArray())
LottoNumbers.random() 정도의 정적 팩터리 메서드를 생각했습니다.
```kotlin
override val lottoNumbers: LottoNumbers = LottoNumbers.random()
```
비슷하게 LottoNumber 정적 팩터리까지 만들게 됐다면, 결국 LottoNumber 생성에 대한 로직(= 1..45 값 내의 번호)은 LottoNumber 만 갖게 될 수 있을 것 같아요.

2023-11-09 09:48 UTC, hjjae2 commented on src/main/kotlin/lotto/domain/LottoRank.kt
>              }
지금도 좋습니다. :+1: 
다만, (`of` 내에서) 여전히 Enum 의 속성 값(예: containCount)을 활용하지 않고 있기에 수정이 필요한 경우 두 곳을 수정해줘야 겠네요. 🤔 

다음과 같이 enum class 의 메서드로 정리하는 방법도 있을 것 같은데요, 더 관리가 쉽다고 생각하시는 것을 적용하면 좋을 것 같아요.

```kotlin
enum class LottoRank(val containCount: Int, val money: Int) {
    FIRST(6, 2_000_000_000) { ... },
    ...;

    protected abstract fun isMatch(matchingCount: Int, isBonusMatched: Boolean): Boolean

    companion object {
        fun of(winningNumbers: WinningNumbers, lottoNumbers: LottoNumbers): LottoRank =
            values().find {
                it.isMatch(
                    getMatchingCount(winningNumbers.winningNumbers, lottoNumbers),
                    isBonusMatched(lottoNumbers, winningNumbers.bonusNumber),
                )
            } ?: NONE
    ...
```

2023-11-09 09:48 UTC, merged

2023-11-10 11:21 UTC, Factoriall commented on src/main/kotlin/lotto/domain/LottoRank.kt
>              }
그리고 enum 클래스 안에 abstract로 저렇게 쓰는 개념을 처음으로 알았습니다! 감사합니다

2023-11-10 11:37 UTC, Factoriall commented on src/main/kotlin/lotto/domain/AutoLotto.kt
> +        LottoNumbers(*list.toIntArray())
아 이거 이펙티브 자바에서 봤던 정적 팩토리 메서드 그것이군요. 
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/
똑같은 코드가 여기 있네요 ㅋㅋㅋㅋ;