step1: 문자열 덧셈 계산기 구현
next-step/kotlin-lotto pull request #888
Opened 2023-11-08 14:03 UTC by inhyeokk

안녕하세요 리뷰어님. 1단계 - 문자열 덧셈 계산기 리뷰 요청 드립니다.

### What
- 1단계 - 문자열 덧셈 계산기 구현 했습니다.

### How
- 기능 요구 사항 및 기능 목록 작성
- StringAddApplication.main 메서드에서 실행
- StringAddCalculator 가 계산 기능 수행
- StringAddTokenizer 가 계산을 위한 문자열 변환 기능 수행
- StringNumber 문자열 계산기 숫자를 담당하는 값
- 각 클래스 별 테스트 코드 작성

### 리뷰 받고 싶은 내용
- 프로덕션과 테스트 환경에서 공통으로 사용되는 상수는 어떻게 관리하는게 좋을까요?
- StringAddTokenizerTest 의 customDelimiterTokens 테스트는 customDelimiter 테스트 과정을 포함하고 있습니다. 이렇게 해도 괜찮을까요? customDelimiterTokens 를 좀 더 단순화해서 단지 커스텀 구분자를 ';' 로 가정하고 테스트를 구현하는게 나을지? 아니면 다른 방법이 있을지 궁금합니다.
- null 체크를 위해 isNotNull 을 추가해두었는데, 그 아래 블록에서 올바르게 null 처리를 하는 방법이 무엇일지 궁금합니다. 현재는 !! 처리를 해둔 상태입니다.

2023-11-10 00:23 UTC, Hyeon9mak requested changes
안녕하세요 인혁님! 로또 미션을 함께하게된 최현구입니다. 🙇‍♂️ 
1단계 미션 잘 진행해주셨어요.

> 프로덕션과 테스트 환경에서 공통으로 사용되는 상수는 어떻게 관리하는게 좋을까요?

저는 인혁님께서 작성해주신 것처럼 중복되더라도 각 환경에 상수를 두는게 좋다고 생각해요.
프로덕션 환경과 테스트 환경에서 공통으로 사용된다고 하여 프로덕션 환경 상수를 public 하게 열면,
접근해선 안될 객체들도 해당 상수에 접근이 가능해져서
추후 유지보수에 어려움이 만들어지는 일도 생길 것 같아요.

> StringAddTokenizerTest 의 customDelimiterTokens 테스트는 customDelimiter 테스트 과정을 포함하고 있습니다. 이렇게 해도 괜찮을까요? 

우리는 왜 테스트 코드를 작성할까요? 테스트 코드를 통해 얻고자 하는 것이 무엇일까요?
저는 꼭 프로그램을 실행시켜보지 않더라도 안정감을 얻고자하는거라 생각해요.
그런 관점에서는 큰 문제가 되지 않을 것 같아요. 오히려 더 든든해보이는 걸요? 😄 

> null 체크를 위해 isNotNull 을 추가해두었는데, 그 아래 블록에서 올바르게 null 처리를 하는 방법이 무엇일지 궁금합니다. 현재는 !! 처리를 해둔 상태입니다.

assertJ isNotNull 은 아쉽게도 스마트 캐스팅을 지원하지 않는 것 같아요.
https://proandroiddev.com/smart-casts-via-assertions-kotlin-contracts-fd737a92013b
이 글을 참고하는 방법도 좋을 것 같긴한데... 배보다 배꼽이 크지 않나라는 생각이 드네요 🤔 

그 외에 간단한 코멘트 남겼으니 확인해주세요.

2023-11-10 00:23 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddCalculator.kt
> +    private const val NULL_OR_BLANK_RESULT = 0
상수를 이용한 이름 부여 좋아요! 👍

2023-11-10 00:23 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddTokenizer.kt
> +        }
객체지향 생활체조에 따라 else 문을 제거해볼 수 있을까요?

2023-11-10 00:23 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddTokenizer.kt
> +        }
1, 2 인덱스가 무엇을 뜻하는 인덱스인지도 이름을 부여해주면 좋겠네요 👍

2023-11-10 00:23 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddTokenizer.kt
> +        private val FIND_CUSTOM_DELIMITER_REGEX: Regex = "//(.)\n(.*)".toRegex()
생성비용이 큰 Regex 에 대해 상수화 👍

2023-11-10 00:23 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringNumber.kt
> +    fun toInt(): Int = value.toInt()
value class 활용 👍 
값 그 자체를 뜻하므로, 프로퍼티로 Int 를 갖고 생성 단계에서만 String 을 파라미터로 입력 받는 건 어떨까요?
(hint: 정적 팩터리 메서드)

2023-11-10 00:23 UTC, Hyeon9mak commented on src/test/kotlin/calculator/domain/StringAddTokenizerTest.kt
> +    }
꼼꼼한 테스트 💯

2023-11-10 00:34 UTC, inhyeokk commented on src/main/kotlin/calculator/StringAddCalculatorApplication.kt
> +}
main 메서드의 템플릿으로 `@JvmStatic` 이 함께 추가 되었네요. 의도는 아니었어서 제거해두겠습니다.

2023-11-10 11:47 UTC, inhyeokk commented on src/main/kotlin/calculator/StringAddCalculatorApplication.kt
> +}
제거하니 동작을 안하는군요. 최상위 레벨이 아닌 클래스의 companion object 내에 main 메서드를 선언하는 경우 `@JvmStatic` 이 필수인 듯 합니다.

크게 신경쓴 부분은 아니었는데 entry point 와 JvmStatic 에 대해 다시 한번 확인했어요.

혹시 이 부분을 의도하신 질문이 맞을까요?

2023-11-10 12:17 UTC, inhyeokk commented on src/main/kotlin/calculator/domain/StringNumber.kt
> +    fun toInt(): Int = value.toInt()
고민했던 내용인데 이렇게 수정하니 더 좋네요. 리뷰 감사해요. 🙇 https://github.com/next-step/kotlin-lotto/pull/888/commits/543b107840dab3583025c28f1f34b26f349ae9e5

2023-11-10 12:21 UTC, inhyeokk commented on src/main/kotlin/calculator/domain/StringAddTokenizer.kt
> +        }
이 부분도 고민하다가 덮어둔 부분인데 짚어주셔서 감사합니다. 아래와 같이 수정했어요.
- else 제거 https://github.com/next-step/kotlin-lotto/pull/888/commits/afde5d3db4f3e23d2dee338b81f68e66d867f9a9
- 인덱스 이름 부여 대신 조금 더 간결한 방법으로 문서를 참고했어요.([링크](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-match-result/group-values.html)) https://github.com/next-step/kotlin-lotto/pull/888/commits/1ce0fcb00f3aa6fdeb6afb3effda497fd91f79c0

2023-11-10 12:26 UTC, inhyeokk commented
안녕하세요 리뷰어님. 남겨주신 코멘트에 대한 수정사항 반영해두었습니다.

상세한 피드백 남겨주셔서 감사해요.

2023-11-11 06:54 UTC, Hyeon9mak approved these changes
안녕하세요 인혁님! 리뷰 내용 잘 반영해주셨습니다.
코드가 더욱 깔끔해진 것 같아요.
바로 다음 단계로 넘어가도 좋을 것 같습니다 😄

2023-11-11 06:54 UTC, Hyeon9mak commented on src/main/kotlin/calculator/StringAddCalculatorApplication.kt
> +}
main 의 경우 프로그램의 시작점이 되기 때문에 무조건 하나의 인스턴스만 존재하게 될 것 같아요. 때문에 "companion object 로 만들어줄 필요가 있을까?" 를 의도한 코멘트였습니다. 그 외에도 여러가지 고민을 해주신 것 같네요 😄 👍

2023-11-11 06:54 UTC, Hyeon9mak commented on src/main/kotlin/calculator/domain/StringAddTokenizer.kt
> +        }
destructured 를 이용한 구조분해!! 👍 👍 💯 
엄청 깔끔하고 멋지네요 👍

2023-11-11 06:54 UTC, merged