[Step4] 로또(수동) 구현
next-step/kotlin-lotto pull request #921
Opened 2023-11-12 07:15 UTC by jyunkim

안녕하세요 수현님, step4 리뷰 요청드립니다!

마지막까지 잘 부탁드리고, 그동안 감사했습니다~!

2023-11-13 02:20 UTC, wisemuji requested changes
안녕하세요 지현님!

마지막 단계 구현을 잘 해주셨습니다 💯  이전 단계에서 설계를 잘 해주셔서 깔끔한 구현이 좋았습니다
피드백 드릴 내용이 많지 않은데, 고민해보시면 좋을만한 코멘트를 조금 달았으니 확인해주시면 감사하겠습니다.
아마 다음 리뷰 요청에서는 머지할 수 있을 것이라고 생각해요.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-11-13 02:20 UTC, wisemuji commented on src/main/kotlin/lotto/domain/Won.kt
> +    }
operator overloading을 잘 활용해주셨네요!
이러한 산술 연산자 외에도 단항 산술 연산자, Collection get/set을 확장하는데에도 활용 가능하니 참고만 해주세요!
- https://thdev.tech/kotlin/2018/04/01/Kotlin-Operator-Overloading/

2023-11-13 02:20 UTC, wisemuji commented on src/main/kotlin/lotto/view/LottoInputView.kt
> +                .map { LottoNumber(it.trim().toInt()) }
뷰가 도메인을 직접적으로 참조해도 괜찮은지에 대한 의견은 개발자마다 분분합니다. 🤔 
도메인으로 변환하는 것 까지는 뷰의 책임이 아니라고 생각할 수도 있을 것 같아요.
컨트롤러가 변환 책임을 들고 있을 수 있을 것 같은데 어떻게 생각하시나요?

2023-11-13 02:20 UTC, wisemuji commented on src/test/kotlin/lotto/domain/LottoShopTest.kt
> +            .isEqualTo(Lotto(manualLottoNumbers))
Lotto를 data class나 value class로 바꾸지 않고도 동등성을 비교할 수 있도록 구현해주셨네요 👍

2023-11-13 13:28 UTC, jyunkim commented on src/main/kotlin/lotto/domain/PurchasedLottos.kt
> +    manualLottoNumbers: List<List<LottoNumber>>,
이해하기 어렵습니다.. ManualLottoNumbers라는 클래스를 추가하도록 할게요!

2023-11-13 13:57 UTC, jyunkim commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +    fun purchaseLottos(purchaseAmount: Won, manualLottoNumbers: List<List<LottoNumber>>): List<Lotto> {
private method로 추출해보았습니다.

2023-11-13 14:06 UTC, jyunkim commented on src/main/kotlin/lotto/view/LottoInputView.kt
> +                .map { LottoNumber(it.trim().toInt()) }
음 저도 뷰와 도메인을 완전히 분리해서 결합도를 낮추는 것도 좋다고 생각합니다. 컨트롤러가 변환 책임을 가지도록 수정해볼게요!

2023-11-13 14:52 UTC, jyunkim commented on src/main/kotlin/lotto/view/LottoInputView.kt
> +                .map { LottoNumber(it.trim().toInt()) }
수정해보니 코드가 생각보다 복잡해지는군요.. 2차원 리스트도 생기게 되어 가독성도 떨어지는 것 같습니다.
만약 뷰가 도메인을 참조하지 못하게 한다면, 뷰에서 사용하는 dto 객체를 정의하는게 좋아보이네요!
다만 현재 코드상으로 dto까지 구현하는건 다소 불필요해보여 현재 코드 유지하는게 어떨까 합니다!

2023-11-14 06:48 UTC, wisemuji approved these changes
안녕하세요 지현님!

마지막까지 피드백 잘 반영해주셨습니다 🙂 
지현님과 미션을 진행하면서 다소 도전적인 피드백도 몇 남겨드렸었는데, 모두 훌륭하게 잘 진행해주셨어요.
지현님의 개발에 대한 철학과 여러 의견을 보면서 저도 인사이트를 얻어가는 뜻깊은 시간이 되었습니다.

개발자로서 성장하는 과정에 소중한 경험이 되었기를 바랍니다!
앞으로의 미션도 응원할게요 💪

2023-11-14 06:48 UTC, wisemuji commented on src/main/kotlin/lotto/view/LottoInputView.kt
> +                .map { LottoNumber(it.trim().toInt()) }
이것이야말로 정답이 없는 트레이드오프의 영역인 것 같아요! 말씀해주신 것처럼 DTO 객체로 묶는다면 관심사의 분리를 잘 해볼 수 있지만, 작은 프로그램에서 너무 많은 보일러플레이트 코드가 생긴다는 단점도 있고요. 이러한 회색 영역에서는 특히나 개발자의 경험과 노하우가 중요하다고 생각합니다 🙂 
저도 지현님의 말씀에 이견 없습니다!

2023-11-14 06:48 UTC, merged