step2: 로또(자동) 구현
next-step/kotlin-lotto pull request #937
Opened 2023-11-13 11:08 UTC by inhyeokk

안녕하세요 리뷰어님. 2단계 - 로또(자동) 리뷰 요청 드립니다.

### What
- 2단계 - 로또(자동) 구현 했습니다.

### How
- 기능 요구 사항 및 기능 목록 작성
- LottoApplication.main 메서드에서 실행
- view 패키지 내 입력과 출력을 담당하는 InputView 와 ResultView 구현
- domain.model 패키지 에 value class, data class 배치
- 각 클래스 별 테스트 코드 작성

### 리뷰 받고 싶은 내용
- `LottoMatchCount` enum 의 경우 단순히 열거 타입으로 정의한 상태라 테스트 코드를 작성하지 않았는데요, 혹시 이 부분에 대한 테스트 코드도 필요할까요? 아니면 다른 패키지로 옮겨두는게 좋을 것 같은데 mvc 패턴에서는 이 경우 어떻게 하는것이 올바른 방법일지 궁금합니다.
- 그 외 value class, data class 도 개수가 많아져서 domain 내 model 패키지로 옮겨두었습니다. 적절한 배치가 맞을까요? 1주차 5단계의 그림에서 domain(model) 을 의미하는 듯 하여 혹시나 이렇게 해도 괜찮을지 질문드려요.
- `LottoNumber` 의 상수인 `LOTTO_NUMBER_START` 와 `LOTTO_NUMBER_END` 의 경우 `LottoNumber` 와 `Lotto` 에서 함께 사용되어 접근 제한자를 public 으로 두었습니다. 두 곳 이상에서 사용 되지만 LottoNumber 에 더 해당한다고 생각하여 LottoNumber 파일 내에 선언 해두었는데요. 올바른 방법인지 궁금합니다.
- 부족한 점이 많습니다. 많은 코멘트 부탁드려요. 🙇 

(참고) 아직 TDD 에 익숙하지 않아 '프로그래밍 요구사항인 커밋을 기능 목록 단위로 추가한다.' 를 지키지 못했습니다. 커밋이 뒤죽박죽 되는 것 보다는 한번에 커밋하는게 원활한 리뷰에 도움이 될 것 같다고 생각하여 한번에 커밋 했어요. 앞으로는 가능한 연습해보겠습니다.

2023-11-14 14:41 UTC, Hyeon9mak requested changes
안녕하세요 인혁님! 자동 로또 구현 잘 해주셨습니다.

> `LottoMatchCount` 테스트 코드

코멘트를 참고해주시면 아마 테스트 코드 작성이 시작될 것 같아요 😉 

> value class, data class 도 개수가 많아져서 domain 내 model 패키지로 옮겨두었습니다. 적절한 배치가 맞을까요?

패키지를 나누고 배치하는 것의 기준은 무엇일까요?
"내가 이런 비즈니스 로직을 수정하고 싶은데, 아마도 여기 있을 것 같아."
라는 의식의 흐름을 맞춰주는게 가장 좋다고 생각해요.
모두가 이해하고 있는 공통의 지식(=상식)을 이용하는 방법이 바로 객체지향인거 같습니다 😄

> `LottoNumber` 의 상수인 `LOTTO_NUMBER_START` 와 `LOTTO_NUMBER_END`

역시나 코멘트를 확인해주세요!

커밋은 기능목록/요구사항 목록을 README.md 파일에 남긴 단위로 쪼개는 연습을 해보셔도 좋을 것 같아요.
궁금하신점 코멘트, DM 남겨주세요.

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
```suggestion
    fun generateLottosByAuto(cash: LottoCash): List<Lotto> {
        val count = cash.value / LOTTO_PRICE
        return List(count) { Lotto.auto() }
    }
```
요렇게 구현해볼 수도 있겠네요 😄

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
로또를 1장이라도 구매할 수 있는 최소 금액이 충족되지 못한 경우에도, 사용자에게 추가 금액을 입력하도록 힌트를 줄 수 있지 않을까요?

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        }
`N 개면 N 등이다.` 라는 로직을 확인하거나 유지보수하고 싶을 때 `LottoStore` 와 `LottoMatchCount` 중 어떤 클래스 파일을 먼저 열어보게 될까요?
아마도 이게 객체가 적절한 책임을 갖는 방법일 것 같아요 😄 👍

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/LottoNumber.kt
> +}
꼭 팩터리 메서드를 통하지 않더라도, `init` 키워드를 이용하면 생성자를 자연스럽게 활용할 수 있게 될 것 같아요.

```kotlin
@JvmInline
value class LottoNumber(val value: Int) {

    init {
        require(value in LOTTO_NUMBER_START..LOTTO_NUMBER_END) { "로또 숫자의 범위는 1~45 입니다." }
    }
    
    companion object {
        private const val LOTTO_NUMBER_START = 1
        private const val LOTTO_NUMBER_END = 45

        fun valueOf(value: String): LottoNumber {
            require(value.toIntOrNull() != null) { "숫자 이외의 값일 수 없습니다." }
            return LottoNumber(value.toInt())
        }
    }
}
```

그리고 1~45 범위로 제한하여 검사하기 때문에 음수확인은 자동으로 생략되겠네요!

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
구입금액이나 당첨번호를 꼭 문자열로 전달해야할까요?
LottoApplication 이 집중해야하는 것은 로또 비즈니스 행위들이므로, 
정수 원시값이나 List<String> 정도는 IntputView 분리해주는 것에 대해 어떻게 생각하실까요? 🤔

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/LottoCash.kt
> +}
`LottoNumber` 와 마찬가지로 생성자를 살려보는건 어떨까요? 😉

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
1~45 번까지의 로또 숫자 캐싱 👍 매번 인스턴스를 생성할 필요 없이 같은 값을 끌어다 사용하면 되겠네요!
단 아래 남겨드렸던 코멘트와 마찬가지로 "캐싱된 로또 숫자들은 어떤 것들이 있을까?" 를 확인하고 싶을 때 `Lotto`와 `LottoNumber` 중 어느 클래스 파일을 먼저 열어보게 될지 고민해보면 재밌겠네요!

> N 개면 N 등이다. 라는 로직을 확인하거나 유지보수하고 싶을 때 LottoStore 와 LottoMatchCount 중 어떤 클래스 파일을 먼저 열어보게 될까요?

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
그 외에도 중복되면 안될 것 같기도 해요~ 😉

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
어떤 문자열을 단위로 분리한다... 는 view 의 책임 아닐까요? 😉

2023-11-14 14:41 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +            }
subList 를 대신할 take 라는 친구도 있습니다! 👍

2023-11-15 00:49 UTC, inhyeokk commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
오,, 이 부분도 고민 되었던 것 중 하나인데 리뷰 요청하면서 적는다는걸 잊어버렸습니다.
1. 문자열 그대로 리턴한다.
2. 정수 원시 값이나 List 와 같은 기본 타입의 경우 변환하여 리턴한다.
3. 좀 더 구체화하여 특정 model 를 생성한 뒤 리턴한다.

대략 3가지 정도가 있을텐데 뷰의 역할을 어디까지로 제한해야하는지가 헷갈렸습니다. 그런데 적어주신 것처럼 LottoApplication 의 입장에서 보면 뷰가 기본 타입 정도는 변환하여 리턴해도 좋을 것 같아요.

그런데 한가지 더 궁금한 점이 있는데요. 
ResultView 의 경우 특정 model 을 생성하지는 않지만 파라미터로 전달받아 출력하고 있습니다. InputView 와 ResultView 가 입력과 출력을 담당하고 대치한다고 생각해보면, 이것도 기본 타입을 전달받아야하나 라는 생각이 드는데,, 이 부분에 대해서는 어떻게 생각하시는지 궁금합니다.

날카로운 코멘트 감사해요. 👍

2023-11-15 13:20 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +            }
take 좋네요 👍  https://github.com/next-step/kotlin-lotto/pull/937/commits/076e4c12822b493e74d8168d150ab76b21e065fa

2023-11-15 13:21 UTC, inhyeokk commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
InputView 에서 정수 원시 값이나 List 와 같은 기본 타입의 경우 변환하여 리턴하도록 수정했어요. https://github.com/next-step/kotlin-lotto/pull/937/commits/b608fddb73149fd866ab439402eade100459edcc

2023-11-15 13:21 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
위 코멘트에서 수정했습니다. https://github.com/next-step/kotlin-lotto/pull/937#discussion_r1394191925

2023-11-15 13:23 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/LottoNumber.kt
> +}
그러게요. 1주차에서 팩토리 메서드 사용 피드백을 받았어서 그런지 생각이 갇혀 있었던 것 같아요. 수정했습니다. 👍 https://github.com/next-step/kotlin-lotto/pull/937/commits/450c02e74f2fac109ef4931f7ce1bb64e455fb56

2023-11-15 13:43 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val lottos = LottoStore.generateLottosByAuto(lottoCash)
```suggestion
            var lottoCash: LottoCash
            var lottos: List<Lotto>
            do {
                val cash = InputView.readCash()
                lottoCash = LottoCash(cash)
                lottos = LottoStore.generateLottosByAuto(lottoCash)
            } while (lottos.isEmpty())

```

2023-11-15 13:43 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val lottos = LottoStore.generateLottosByAuto(lottoCash)
> 로또를 1장이라도 구매할 수 있는 최소 금액이 충족되지 못한 경우에도, 사용자에게 추가 금액을 입력하도록 힌트를 줄 수 있지 않을까요?

이런식으로 힌트를 줄 수는 있을 것 같은데요, 문제에 명시된 실행 결과와 달라져도 괜찮나요? 힌트라고 하셔서 이렇게 이해하긴 했는데, 만약 말씀하신 힌트가 로그나 예외라면 말씀 남겨주세요.

2023-11-15 13:45 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
위에건 수정했고 https://github.com/next-step/kotlin-lotto/pull/937/commits/0fa680952dd4c34688c5dfaeb11e7ee5418b5a28 
아래 코멘트는 코멘트 링크 확인 부탁드릴게요. https://github.com/next-step/kotlin-lotto/pull/937#discussion_r1394213998

2023-11-15 14:26 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
흠,, 생각하면 할수록 Lotto 보다는 LottoNumber 쪽이 더 가까운 것 같아요. LottoNumber 를 생성할 수 있는 범위에 대한 목록이라고 이해하니 더더욱 그런 듯 해요. 

LottoNumber 로 옮겨두고 생성자 대신 get 메서드로 목록에서 값을 꺼낼 수 있도록 수정했습니다. https://github.com/next-step/kotlin-lotto/pull/937

2023-11-15 14:31 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +        }
https://github.com/next-step/kotlin-lotto/pull/937/commits/288f4b9655ca0ff1b64f9a29e4145e3f9492a67d

2023-11-15 14:58 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +        }
LottoMatchCount 의 팩토리 메서드를 추가해서 `N 개면 N 등이다.` 로직을 묶고 테스트 코드 추가했습니다. https://github.com/next-step/kotlin-lotto/pull/937/commits/f5fa905e0d4ffc6bedeccdd78cc625c8eecce122

좋은 리뷰 감사합니다. 👍

2023-11-15 15:00 UTC, inhyeokk commented
안녕하세요 리뷰어님. 남겨주신 코멘트에 대해 수정사항 반영했습니다.

많은 코멘트와 좋은 리뷰 감사합니다. 🙇 시간 되실 때 확인 부탁드릴게요.

2023-11-18 00:43 UTC, Hyeon9mak approved these changes
안녕하세요 인혁님! 제가 해외 일정이 생겨서 리뷰가 많이 늦었습니다. 🙏 
리뷰 내용 꼼꼼히 고민하고 반영해주시는 덕분에 리뷰하는데 많은 힘이 납니다 💪 
저도 여러가지 추가 코멘트를 남겼는데요, 3단계를 진행하시면서 함께 확인해주시면 될 것 같습니다.

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/LottoStore.kt
> +    }
> 객체에 메세지를 보내라

`LottoMatchCount` 의 값을 꺼내어 사용하다가, 질문을 하도록 바꾼 덕분에 코드가 엄청 간결해졌군요!
새로운 등수나 상금이 등장한다고 해도, `LottoStore` 에는 변화가 없겠어요 👍

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +value class Lotto private constructor(private val list: List<LottoNumber>) : List<LottoNumber> by list {
by 키워드를 사용해주셨었군요!
인혁님께서 느끼시기에 어떤 장단점이 있으셨나요?

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/LottoMatchCount.kt
> +    ;
`LottoMatchCount` 가 `reward` 와 함께 `matchCount` 를 갖는 것도 방법이겠어요!
그럼 팩터리 메서드에서 개수를 비교하는 로직도 더욱 간결해지겠네요!

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/LottoMatchCount.kt
> +            else -> throw IllegalArgumentException("로또 숫자의 일치 수는 로또 숫자 수의 범위를 벗어날 수 없습니다.")
throw 문 등을 작성할 땐 어떤 입력값 때문에 에러가 발생했는지 알려주는 것도 좋은 방법 같아요.

```kotlin
throw IllegalArgumentException("로또 숫자의 일치 수는 로또 숫자 수의 범위를 벗어날 수 없습니다. matchCount=$matchCount")
```

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/view/ResultView.kt
> +    }
> ResultView 의 경우 특정 model 을 생성하지는 않지만 파라미터로 전달받아 출력하고 있습니다. InputView 와 ResultView 가 입력과 출력을 담당하고 대치한다고 생각해보면, 이것도 기본 타입을 전달받아야하나 라는 생각이 드는데,, 이 부분에 대해서는 어떻게 생각하시는지 궁금합니다.

좋은 고민이라고 생각합니다 😄 👍 

역시나 저는 유지보수가 기준이라고 생각합니다. List<Lotto> 의 변화에 ResultView 가 적은 영향을 받도록하는 극한의 유지보수를 위해선 별개 DTO(data transfer object) 를 사용해서 LottoApplication -> dto -> ResultView 구조를 그려볼 수도 있을 것 같아요.
그러나 "현재 구조에서 꼭 그렇게까지 해야하는가?" 라는 고민 또한 생기겠어요.

결국 이펙티브 코틀린 미션에서 중심이 되는 기조는 "domain 의 변화는 적고, view 의 변화가 잦은 환경이다." 인 것 같아요. domain 은 그저 자신이 할 일에만 집중하고 view 가 domain 에 맞춰주는 형태만 유지된다면 어떤 방식이든 괜찮다고 생각합니다!

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +value class Lotto private constructor(private val list: List<LottoNumber>) : List<LottoNumber> by list {
중복이 포함되어서 안된ㄷ면.. List 말고 다른 collection 이 더 잘 어울리지 않을까요? 😉

2023-11-18 00:43 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val lottos = LottoStore.generateLottosByAuto(lottoCash)
재입력을 요구하는 것이 충분히 친절하고 좋은 느낌이네요 😄 
의도한 것은 `LottoStore` 에서 구매를 거절하는 것이었어요.
`LottoApplication` 은 domain logic 과 view 간의 소통에만 집중하고,
"최소 금액이 충족되지 않는다면 구매할 수 없다." 라는 것 까지도 domain logic 이라고 생각했기 때문이에요.

살짝만 바꿔주면 지금처럼 친절하게 재입력을 요구하는 프로그램이 될 것 같은데...
`LottoStore` 에게 구매에 충분한 금액인지 물어보는 건 어떨까요?

2023-11-18 00:43 UTC, merged

2023-11-19 06:49 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +value class Lotto private constructor(private val list: List<LottoNumber>) : List<LottoNumber> by list {
value class 를 이번 세션에서 처음 써보는거라 경험적으로 느낀점이 많지는 않은데요.

그럼에도 느낀 부분이라면,, 
value class 가 프로퍼티 하나만을 갖는 값 자체의 의미를 하다보니 by 델리게이트로 클래스가 프로퍼티 자체를 의미하도록하여 값을 꺼내는 코드를 단순화하기에 좋았습니다.

하지만 Lotto 의 경우에는 프로퍼티가 LottoNumber 의 List 라 LottoNumberList 와 같은 의미를 갖는 네이밍을 가진다면 더 좋겠지만 직관성을 갖기 위해 Lotto 라는 네이밍을 지었는데요. 값과 프로퍼티 자체를 연결하는 by 델리게이트의 특성상 네이밍에 더 주의가 필요할 것 같았습니다.

더하여 by 델리게이트가 interface 만 사용이 가능하기 때문에 LottoNumber 의 경우 Int 타입으로 이 경우에는 같은 방식으로 구현이 어려워서 일관성이 떨어질 수 있다는 단점도 있을 것 같아요.

2023-11-19 11:50 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Lotto.kt
> +value class Lotto private constructor(private val list: List<LottoNumber>) : List<LottoNumber> by list {
Set 으로 수정했습니다. 👍  https://github.com/next-step/kotlin-lotto/pull/962/commits/a58b10b060004827869473b554835487e91208f8

2023-11-19 11:50 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/LottoMatchCount.kt
> +    ;
https://github.com/next-step/kotlin-lotto/commit/04427eed00f7edda7e3c0e0ba3eba2dbb7d821ed

2023-11-19 11:50 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/LottoMatchCount.kt
> +            else -> throw IllegalArgumentException("로또 숫자의 일치 수는 로또 숫자 수의 범위를 벗어날 수 없습니다.")
https://github.com/next-step/kotlin-lotto/commit/3851324d5714cab9ef32d198fbdd17769ec59bb3

2023-11-19 11:52 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val lottos = LottoStore.generateLottosByAuto(lottoCash)
남겨주신 의도에 따라 적절히 수정 했을지 싶은데,, 
로또를 구매할 수 있는 금액이 아닌 경우 구입 금액을 재입력 받을 수 있도록 적용했습니다. 확인 부탁드릴게요. https://github.com/next-step/kotlin-lotto/commit/030215814957bbb869b912e0ced2079090fa19bf