🚀 4단계 - 로또(수동)
next-step/kotlin-lotto pull request #938
Opened 2023-11-13 12:32 UTC by AlbertImKr

경록님 안녕하세요!!

4단계 미션 리뷰 요청드립니다. 😀

2023-11-14 14:29 UTC, Rok93 requested changes
홍광님 4단계도 구현 잘해주셨습니다. 👍💯
몇몇 코멘트 남겨두었으니 확인해서 반영해주시면 좋을 것 같습니다. 🙏
미션 진행하면서 어려운 부분이 있으면 언제든지 DM 주세요. 😃

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/LottoGameManager.kt
> +        val winningLottoTicket = WinningLottoTicket(firstWinningTicket, bonusNumber)
winningLottoTicket을 만들기위한 로직을 private 메서드로 쪼개면, 조금 더 Controller의 로직의 가독성이 좋아질 것 같아요. 😃

```kotlin
    private fun createWinningLottoTicket(): WinningLottoTicket {
        val lottoNumbersString = LottoInputHandler.inputWinningNumbers()
        val firstWinningTicket = LottoTicketExtractor.extractLottoTicket(lottoNumbersString)
        val bonusNumber = LottoNumber(LottoInputHandler.inputBonusNumber())
        return WinningLottoTicket(firstWinningTicket, bonusNumber)
    }
```

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/LottoGameManager.kt
> +        val lottoTickets = lottoBookingSystem.generateMultipleTickets(player)
<img width="1356" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/47850258/c97fe46f-4bed-432c-88b3-11efd5e18d7b">

<img width="1539" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/47850258/29fc2101-c96b-434d-908f-5034ffadeecf">

<img width="755" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/47850258/49e3dfe7-935d-4440-8e2b-f990ae15281b">


`manualLottoTicket`은 당첨 통계를 내는데 사용되지 않고 있는 것으로 보이네요. 🤔

로또를 생성하기 위해서 Player 객체를 사용하고있는데, 이 과정이 조금 어색하게 보이다보니, `lottoTIckets`를 생성하는 로직이 이해하기가 힘들었던 것 같아요. 🤔
조금 더 단순하게 lottoTickets를 만들 수는 없을까요? 

Player 객체 사용 없이, 어떤 객체가 `구입 금액`과 `수동 로또의 갯수`를 통해서 수동 로또, 자동 로또의 갯수를 계산하고 
lottoBookingSystem이 수동 로또를 생성, lottoBookingSystem이 자동 로또를 생성해서 이 둘을 합친 lotoTickets를 초기화한다면 로직이 조금 더 단순해져서 이해하기가 쉬울 것 같아요. 👀

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/business/LottoNumberSet.kt
> +abstract class LottoNumberSet(lottoNumbers: Set<LottoNumber>) {
**WinningLottoTicket**가 이제 더이상 LottoNumberSet를 상속하지 않으니 
`LottoNumberSet` 추상클래스를 둘 필요가 없을 것 같아요. 🤔

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/view/LottoPurchaseSummaryPrinter.kt
>          lottoTickets.forEach { it: LottoTicket -> println(it.lottoNumbers.map { it.number.toString() }) }
람다식 안의 람다 식의 경우 가급적 `it`이 중첩되니 명시적으로 람다 변수를 다른 값으로 지정해서 사용하거나 지금처럼 메서드 참조를 사용하는 방식으로 우회할 수도 있겠네요. 😃

```suggestion
        lottoTickets.forEach { println(it.lottoNumbers.map(LottoNumber::number)) }
```

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/business/WinningLottoTicket.kt
> +class WinningLottoTicket(val winningLottoNumbers: LottoTicket, val bonusNumber: LottoNumber) {
`winningLottoNumbers`, `bonusNumber` 두 값은 외부에 직접 호출할 일이 없으니 private 접근제한자로 변경해보는 것도 괜찮을 것 같아요. 😉

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/business/LottoTicketExtractor.kt
> +    }
약간 View의 영역이라고 느껴지는데요. 🤔

입력받은 `문자열` 혹은 `List<Int>`을 LottoTicket으로 변경하는 역할은 Controller에서 수행하도록 해보면 어떨까요? 😉

2023-11-14 14:29 UTC, Rok93 commented on src/main/kotlin/lotto/business/LottoTicketExtractor.kt
> +            .map { LottoNumber(it) }
자동으로 로또를 발급받을 때는 캐싱한 `LottoNumber` 객체를 활용해서 LottoTicket 객체를 생성했었는데, 
ManualLottoTicket도 캐싱된 LottoNumber를 활용하도록 변경해보면 어떨까요? 😃

`LottoNumber`를 캐싱해두는 역할은 어디서 수행하는게 좋다고 생각하시나요? 👀
지금은 RandomLottoPicker 클래스에 캐싱이 되어있는데, 이 캐싱 위치에 대해서 고민해보시면 좋을 것 같습니다. 🤔

2023-11-14 14:29 UTC, Rok93 commented on src/test/kotlin/lotto/business/WinningLottoTicketTest.kt
>          // given
file Changed에는 나오지 않아서 여기에 코멘트 남깁니다. 

`LotteryStatisticsGeneratorTest` 클래스가 보이는데, 현재 클래스 네이밍이 LotteryStatisticsGenerator에서 `PrizeResults`로 변경된 것이라 생각됩니다. 👀
테스트 클래스의 네이밍도 수정되어야하지 않을까요?

2023-11-15 21:54 UTC, AlbertImKr commented on src/main/kotlin/lotto/business/Player.kt
> +class Player(tickets: List<LottoTicket> = listOf(), purchasableCount: Int) {
저는 Player가 사용자가 구입한 로또 티켓을 관리하는 역할이라서 적절하다고 생각합니다. 
- 경록님이 생각하시는 수동 로또와 자동 로또 갯수를 반환해주는 역할은 어떤 역할인가요 ?  계산만 하는 클래스 인가요 ?
- 구입수량은 Controller에서 관리하나요 ?

2023-11-16 00:03 UTC, AlbertImKr commented
경록님 
피드백 적용했습니다. 
리뷰 요청드립니다.

2023-11-16 16:10 UTC, Rok93 commented on src/main/kotlin/lotto/business/LottoBookingSystem.kt
> +    }
`LottoBookingSystem`은 도메인 객체 즉 model의 영역이라고 생각되는데요. 🤔
내부적으로는 수동 로또를 직접 입력받고있어요. 👀
LottoBookingSystem에서 직접적으로 입력을 받지않고 외부에서 주입받도록 변경해보면 어떨까요? 

또 한가지 얘기해보고 싶은건 수동 로또를 생성하는 시점에 `require(purchasableCount >= manualCount) { "구매 가능한 로또 개수보다 많습니다." }`를 확인할 필요가 있을까요?  `player.addTickets(manualLottoTickets)`을 호출하는 순간 메서드 내부의 유효성 검증에 의해서 똑같은 검증이 수행될 것 같아요. 

LottoBookingSystem은 단순히 수동 로또 갯수만큼 예약( 구입?)하는 것에만 관심을 두면 될 것 같아요. 😃
수도 로또 구입 갯수와 입력한 수동 로또의 갯수가 일치하는지 여부 정도는 여기서 검증을 해야할 수도 있을 것 같네요. 🤔
```suggestion
    fun generateManualTickets(manualCount: Int, ): List<LottoTicket> {
        require (manualCount == lottoTickets.size) { 적절한 예외메시지 }
        return LottoTicketGenerator.generateManualTickets(lottoTickets)
    }
```

2023-11-16 16:10 UTC, Rok93 commented on src/main/kotlin/lotto/business/Player.kt
> +class Player(tickets: List<LottoTicket> = listOf(), purchasableCount: Int) {
지금의 방식이 나쁘다는 의미는 아니지만 player 객체가 자신의 책임을 수행하기 위해서, 완전히 초기화된 뒤에 자신의 역할을 수행해야하는데, 완전히 초기화되지 않은 상태에서 player 객체가 자신의 책임을 수행하게될 수도 있고 이러면 객체가 자신의 책임을 제대로 수행하지 못하는 경우가 발생할 수 있을 것 같아요. 🤔

가급적 객체의 생성자(or 정적 팩토리 메서드)를 통해서 생성자 파라미터를 입력받아 객체가 생성될 때, 객체는 자신의 책임을 수행할 수 있는 완전한 상태인 것이 좋다고 생각해요. 😃

## AS - IS
```kotlin
    fun run() {
        val player = Player(receivedAmount = ReceivedAmount(LottoInputHandler.inputPurchaseAmount()))
        generateTickets(LottoBookingSystem(), player)
        val winningLottoTicket = generateWinningLottoTicket()
        printLotteryStatistics(winningLottoTicket, player)
    }
```

대략적으로 저는  수동 로또와 자동 로또들을 lottoBookingSystem으로 각각 만들고 합한 하나의 `LottoTickets` (일급 컬렉션으로 사용할 수도 있고 List<LottoTIcket> 자체로 사용해도 상관은 없을 것 같습니다. 🤔)으로 `winningLottoTicket` 객체와 협력하여 이후 로또라는 비즈니스를 수행하도록 할 것 같아요. 😃

## TO - BE 
```kotlin
    fun run() {
        val receivedAmount = ReceivedAmount(LottoInputHandler.inputPurchaseAmount())
        // lottoTicketNumbers는 수동 로또, 자동 로또 갯수를 가짐 (네이밍은 그렇게 만족스럽지는 않아서 참고삼아 봐주세요)
        val lottoTicketNumbers = LottoTicketSeller.calculateLottoTicketNumber(receivedAmount, LottoInputHandler.inputManualTicketCount())
        val lottoTickets = generateTickets(lottoTicketNumbers, LottoBookingSystem())
        val winningLottoTicket = generateWinningLottoTicket()
        printLotteryStatistics(winningLottoTicket, lottoTickets, receivedAmount)
    }

    private fun generateTickets(
        lottoTicketNumbers: LottoTicketNumbers,
        lottoBookingSystem: LottoBookingSystem,
    ): List<LottoTicket> {
        val manualLottoTickets = lottoBookingSystem.generateManualTickets(
            manualCount = lottoTicketNumbers.manualLottoNumber,
            lottoTickets = LottoInputHandler.inputManualNumbers()
        )
        val autoLottoTickets = lottoBookingSystem.generateMultipleTickets(lottoTicketNumbers.autoLottoNumber)
        LottoPurchaseSummaryPrinter.print(manualLottoTickets, autoLottoTickets)

        return manualLottoTickets + autoLottoTickets
    }


    
```

2023-11-16 16:23 UTC, Rok93 requested changes
홍광님 피드백 반영 잘해주셨습니다. 👍💯
조금만 더 짚고 넘어가면 좋을 것 같은 부분이 있어서 코멘트 남겨두었습니다. 
이 부분 확인해서 반영해주시면 감사하겠습니다. 🙏

2023-11-17 22:34 UTC, AlbertImKr commented
경록님
피드백 적용했습니다.
리뷰 요청드립니다.

2023-11-18 17:46 UTC, Rok93 requested changes
홍광님 피드백 반영 잘해주셨습니다. 👍
마지막으로 현재 생성한 로또를 출력하는 부분이 미션 요구사항과 다르게 동작하고있는 것 같아요. 👀
이 부분 수정해주시면 감사하겠습니다. 🙏

2023-11-18 17:46 UTC, Rok93 commented on src/main/kotlin/lotto/LottoGameManager.kt
> +        require(lottoTicketCounter.purchasableCount >= manualTicketCount) { throw IllegalArgumentException("더 이상 로또를 구매할 수 없습니다.") }
`lottoTicketCounter` 객체의 **decreasePurchasableCount** 메서드 내에서 이미 동일한 유효성 검증을 진행하고있는 것 같은데, 제거해도 괜찮을 것 같아요. 😃

2023-11-18 17:46 UTC, Rok93 commented on src/main/kotlin/lotto/LottoGameManager.kt
> +        LottoPurchaseSummaryPrinter.print(manualTicketCount, lottoTickets)
미션 요구사항의 출력 내용을 보면, 수동으로 생성된 로또 + 자동으로 생성된 로또를 함께 출력하고있어요. 👀
하지만 현재 자동으로 생성된 로또의 경우에만 출력되고있는 것 같아요. 🤔

<img width="1367" alt="image" src="https://github.com/next-step/kotlin-lotto/assets/47850258/457183f0-0929-456b-8c23-b424668a54a2">

2023-11-19 00:00 UTC, AlbertImKr commented
경록님 안녕하세요!!
출력 부분 수정했습니다. 
이번 미션 동안 수고많아셨습니다. 
감사합니다.

2023-11-19 07:15 UTC, Rok93 approved these changes
홍광님 피드백 반영 잘해주셨습니다. 👍💯
로또 미션 충분히 잘 진행해주신 것 같아서, 로또 미션은 이만 종료하도록하겠습니다. 😃
그동안 고생많으셨고, 남은 미션들도 꼭 완주하셨으면 좋겠습니다. 💪💪💪

2023-11-19 07:15 UTC, merged