Step2 : 로또 게임 구현
next-step/kotlin-lotto pull request #958
Opened 2023-11-18 16:09 UTC by be-student

dm 으로 대화했던 부분이 되게 많이 공감이 되었어요
정말 감사합니다! 🙇

2023-11-18 18:39 UTC, jinyoungchoi95 requested changes
안녕하세요 누누 😄

로또 미션 잘 구현해주셨네요. 몇가지 피드백 코맨트로 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoNumber.kt
> +    fun isEqualTo(other: Int): Boolean {
data class와 마찬가지로 자동으로 equals를 재정의해주기 때문에 해당 값을 사용해도 좋을 것 같아요.
- data class: toString(), equals(), hashcode(), copy(), componentN()
- value class: toString(), equals(), hashcode()

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Lotto.kt
> +    companion object {
[kotlin convention](https://kotlinlang.org/docs/coding-conventions.html#class-layout)에서 `companion object`는 최하단에 위치합니다.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Lotto.kt
> +    }
사용되지 않는 함수인 것 같네요.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Prize.kt
> +enum class Prize(val sameCount: Int, val amount: Amount) {
enum 👍

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Prize.kt
> +    companion object Something {
`companion object`에 클래스 네임을 지정해주신 이유가 있을까요?

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Prize.kt
> +        }
(반영하지 않으셔도 됩니다.) 현재의 방법도 물론 좋지만, `sameCount`라는 명칭은 몇개가 맞았느냐를 뜻해요. 다만 0, 1, 2의 경우 모두 `NONE_PRIZE`에 속하지만 `sameCount`의 단일값이기 때문에 속하지 않게 되고 현재처럼 각 값을 따로 재처리해주어야하는 상황이 발생하는데요.

`sameCounts`라는 복수로 둔다면 list로 0, 1, 2를 모두 판단할 수 있게 되고 해당 list의 contains여부에 따라 find 후 예외처리만 할 수 있도록 만들 수도 있을 것 같아요.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Prize.kt
> +        private val orderedPrize = values().toList().sortedByDescending { it.sameCount }
참고로 현재 미션은 1.8이지만 1.9에서는 [entries](https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function)를 stable하게 지원하고 있습니다.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoNumberGenerator.kt
> +interface LottoNumberGenerator {
랜덤 생성로직 추상화 👍

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/RandomLottoNumberGenerator.kt
> +        private const val MAX_NUMBER = 45
`MIN_NUMBER`와 `MAX_NUMBER`가 혼재되어있는데요. `LottoNumber`를 캐싱하고, 캐싱된 value를 shuffle하여 값을 가져오도록한다면 한군데서 해당 상수를 관리할 수 있을 것 같네요.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoMachine.kt
> +        }
generate할 때 6개를 가져오면 while문을 사용하지 않아도 될 것 같은데 한개만 가져오도록 하신 이유가 있을까요?

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoMachine.kt
> +        return lottos
```suggestion
        return (0 until lottoCount).map { Lotto(generateLottoNumbers()) }
```
와 같은 형태로도 만들 수 있습니다 :)

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoRule.kt
> +    }
`calculateResult`에서만 사용이 되어있어 private로 전환하고 `calculateResult`에 대한 테스트로 변경하면 좋을 것 같아요.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/test/kotlin/lotto/AmountTest.kt
> +        assertDoesNotThrow { Amount(1000) }
junit에 대한 의존성 없이 `shouldNotThrowAny`를 사용할 수 있겠네요.

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/test/kotlin/lotto/LottoNumberTest.kt
> +        LottoNumber(45)
안정적인 생성이 목적이라면 shouldNotThrowAny를 사용하는건 어떨까요?

2023-11-18 18:39 UTC, jinyoungchoi95 commented on src/test/kotlin/lotto/LottoNumberTest.kt
> +            assertThat(LottoNumber(5).isEqualTo(4)).isFalse()
assertThat 혹은 kotest의 should 중 하나로 통일하면 좋을 것 같아요. (이왕이면 kotest를 사용하고 있으니 should로 통일하는건 어떨까요?)

2023-11-19 12:24 UTC, be-student commented on src/main/kotlin/lotto/Amount.kt
> +        require(value >= 0)
아하 추가했습니다! 실무에서  require 를 사용하나요?
항상 커스텀 예외를 정의해서 사용하고, 메시지를 생성자에 넣어주는 방식으로 사용하다보니, require 를 쓸 일이 많지 않을 것 같아서요

2023-11-19 12:24 UTC, be-student commented on src/main/kotlin/lotto/LottoNumber.kt
> +    fun isEqualTo(other: Int): Boolean {
오 그렇네요 감사합니다!

2023-11-19 12:25 UTC, be-student commented on src/main/kotlin/lotto/Prize.kt
> +        }
오 그런 방법도 있겠네요 감사합니다! 훨씬 깔끔해지겠네요

2023-11-19 13:00 UTC, be-student commented on src/main/kotlin/lotto/Prize.kt
> +    companion object Something {
지정이 되는구나 하고서 학습용으로 사용했던 것 같아요

궁금한 점이 지금까디 코딩을 하면서 이름을 붙혀서 사용하는 경우가 있었나요?

2023-11-19 13:14 UTC, be-student commented on src/main/kotlin/lotto/LottoRule.kt
> +    }
복잡한 코드를 사용하다보면, 지금같은 느낌으로, 특정 메서드를 public 으로 열고 테스트하는 케이스가 있을 수 있는데, 보통 그런 경우는 어떻게 해결하시나요?

2023-11-19 13:14 UTC, be-student commented on src/main/kotlin/lotto/Lotto.kt
> +    companion object {
변경하였습니다!

2023-11-19 13:36 UTC, be-student commented on src/main/kotlin/lotto/LottoMachine.kt
> +        return lottos
오 저 부분 되게 신기하네요
감사합니다! 🙇

2023-11-19 13:40 UTC, be-student commented on src/main/kotlin/lotto/LottoMachine.kt
> +        }
고민을 많이 못 했던 것 같네요
현재는 set 으로 가져오도록 해서 간단하게 변경하였습니다!

2023-11-19 14:11 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Amount.kt
> +        require(value >= 0)
`require`를 사용하다가 log 레벨에 맞게 예외를 정의할 일이 있어 require와 같은 형태로 log레벨까지 받을 수 있는 커스텀 validation을 만들어서 사용하고 있어요. 결국 `require`과 형태는 동일한 형태에요.

2023-11-19 14:12 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Prize.kt
> +    companion object Something {
없습니다. 자바로 포팅해서 쓰고 그때 네이밍이 따로 필요하면 지을것 같은데 사실 그럴일은 거의 없죠 :)

2023-11-19 14:27 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoRule.kt
> +    }
복잡한 코드의 기준이 어떨지는 사람마다 다르겠지만, 실무에선 500줄짜리 코드가 있는데 이런 경우에는 어쩔 수 없이 public으로 열고 테스트할 수 밖에 없는 것 같아요.

미션상에서는 테스트가 불가능할 정도로 길게된다면 클래스 분리 진행합니다. 복잡한 상태에서 테스트를 짜기 힘들다는 것은 테스트를 짜서 커버하더라도 조그마한 변경점이 로직 전체를 건든다는 의미가 될 수도 있기 때문에 클래스를 분리하려고 하고 있어요. (미션은 최대한 극단적으로 객체지향을 지켜보는것도 좋은 것 같아요.)

2023-11-19 14:34 UTC, jinyoungchoi95 approved these changes
안녕하세요 누누 😄

피드백 반영 잘 해주셨네요. 다음 단계 넘어가기전에 도움될만한 몇가지 코멘트 남겨두었으니 확인 부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2023-11-19 14:34 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/Main.kt
> +fun main() {
만들어주신 각 class가 어떤 기능을 하는지 기능요구사항을 작성해주면 좋을 것 같네요.

2023-11-19 14:34 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoNumber.kt
> +        val cache = (MIN_NUMBER..MAX_NUMBER).associateWith { LottoNumber(it) }
```suggestion
        val CACHE = (MIN_NUMBER..MAX_NUMBER).associateWith { LottoNumber(it) }
```
상수의 네이밍은 기본적으로 대문자를 사용합니다.

2023-11-19 14:34 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoNumber.kt
> +        fun of(value: Int): LottoNumber {
정적 팩토리 메소드의 네이밍은 관습적으로 파라미터가 1개일때  from을 사용합니다.
- from: 파라미터가 1개일 때
- of: 파리미터가 여러개일 때

2023-11-19 14:34 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/RandomLottoNumberGenerator.kt
> +class RandomLottoNumberGenerator : LottoNumberGenerator {
👍

2023-11-19 14:34 UTC, jinyoungchoi95 commented on src/test/kotlin/lotto/LottoMachineTest.kt
> +        lotto[0].lottoNumbers.size shouldBe Lotto.SIZE
```suggestion
        lotto[0].lottoNumbers shouldHaveSize Lotto.SIZE
```
kotest에서는 size 체크를 제공하고 있습니다.

2023-11-19 14:35 UTC, merged

2023-11-19 14:51 UTC, be-student commented on src/main/kotlin/lotto/LottoNumber.kt
> +        val cache = (MIN_NUMBER..MAX_NUMBER).associateWith { LottoNumber(it) }
앗 맞네요 이 부분을 놓쳤군요

2023-11-19 14:52 UTC, be-student commented on src/main/kotlin/lotto/LottoNumber.kt
> +        fun of(value: Int): LottoNumber {
생각보다 of 로 다 다뤄버리면 편해지는 케이스들이 있더라고요
메서드의 인자를 1개만 받다가 추후에 다른 객체를 같이 받아서 진행해야 하는 일들이 생기고, 그렇게 되면 from 을 of 로 바꾸어야 하는데, 그러다보면 관리가 힘들어지는 것 같아서 of 로 통일해버리는 것은 어떻게 생각하시나요?

2023-11-19 14:52 UTC, be-student commented on src/test/kotlin/lotto/LottoMachineTest.kt
> +        lotto[0].lottoNumbers.size shouldBe Lotto.SIZE
오 저런 함수가 있군요 감사합니다!

2023-11-19 14:52 UTC, be-student commented on src/main/kotlin/lotto/Main.kt
> +fun main() {
앗 넵 감사합니다!

2023-11-19 14:54 UTC, jinyoungchoi95 commented on src/main/kotlin/lotto/LottoNumber.kt
> +        fun of(value: Int): LottoNumber {
관습적으로 사용한다는 이유이지 그렇게 정의내리신다면 괜찮다고 생각합니다 :)