Step3: 로또(2등)
next-step/kotlin-lotto pull request #962
Opened 2023-11-19 11:49 UTC by inhyeokk

안녕하세요 리뷰어님. 3단계 - 로또(2등) 리뷰 요청 드립니다.

### What
- https://github.com/next-step/kotlin-lotto/pull/937 에서 남겨주신 코멘트에 대한 수정사항 반영했습니다.
- 3단계 - 로또(2등) 구현 했습니다.

### How
- LottoMatchCount -> Rank 로 변경
   - 6개 번호 중 5개 일치하는 경우가 2등, 3등으로 추가되어 힌트에 명시된 Rank 와 같이 변경했습니다.
- 2등 추첨을 위해 보너스 번호 추가
- 6개 번호와 보너스 번호를 담고 있는 LastWeekLottoNumber 클래스 추가

### 리뷰 받고 싶은 내용
- '2등 추첨을 위해 보너스 번호 추가' 만 되어서 그런지 로직에 큰 변화가 없었네요. 
이 단계까지의 궁금한 점들은 대부분 해소된 듯 한데 개선이 필요한 부분이 있다면 코멘트 남겨주시면 감사하겠습니다. 🙇

2023-11-20 03:27 UTC, Hyeon9mak requested changes
안녕하세요 인혁님! 3단계도 잘 진행해주셨습니다.
요구사항을 만족하는데 큰 변화가 없었다는 건, 이전 단계에서 유지보수가 용이한 형태로 잘 만들어주셨다는 의미인 것 같아요 😄 👍 
함께 더 고민해보면 좋을 부분 코멘트 남겼습니다.
궁금하신점 코멘트, DM 주세요.

2023-11-20 03:27 UTC, Hyeon9mak commented on src/test/kotlin/lotto/domain/LottoStoreTest.kt
> +
> 로또를 구매할 수 있는 금액이 아닌 경우 구입 금액을 재입력 받을 수 있도록 적용했습니다. 

넵! 코멘트 의도대로 잘 변경해주셨습니다!
꼼꼼한 테스트 코드까지.. 👍

2023-11-20 03:27 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            } while (!LottoStore.isPurchasable(lottoCash))
부정형 질문(`isNotPurchaseable`)을 던진다면 `!` 를 제거할 수 있겠네요 😉

2023-11-20 03:27 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val lastWeekMatchLotto = LastWeekMatchLotto.valueOf(numbers, bonusNumber)
구조분해 활용 👍

2023-11-20 03:27 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val rankList = Rank.values().filter { it.reward > 0 }.sortedBy { it.reward }
랭크를 정렬해서 나타내는 부분이 잘 동작하는지 테스트 코드로 확인해볼 수 있을까요?
테스트 코드 작성이 편해지려면 무언가 변화가 필요할 수 있겠어요.

2023-11-20 03:27 UTC, Hyeon9mak commented on src/main/kotlin/lotto/domain/model/Rank.kt
> +}
이번에는 보너스 여부까지 Rank 의 속성 값으로 가져보는 건 어떨까요? 😉 
코드가 간결해지는 것 뿐만 아니라, `Rank` enum class 를 살펴보는 과정에서
어떤 속성들이 모여 등수라는 지표를 나타내는 건지 알려줄 수 있겠어요.

2023-11-21 10:17 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            } while (!LottoStore.isPurchasable(lottoCash))
수정했습니다. 👍 https://github.com/next-step/kotlin-lotto/pull/962/commits/c66adcf0c460294615b98cca74dd586ab71c4b0e

2023-11-21 10:18 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Rank.kt
> +}
수정했습니다. 훨씬 낫네요 👍 https://github.com/next-step/kotlin-lotto/pull/962/commits/63bb6a7d5a7f3d1330a0bdd350b828dc812e3f96

2023-11-21 10:26 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val rankList = Rank.values().filter { it.reward > 0 }.sortedBy { it.reward }
수정했습니다. https://github.com/next-step/kotlin-lotto/pull/962/commits/bfd68ec946db961a59d2f3a1d29961da9a186e75

그런데 수정하다가 문득 'ResultView 에서 필요한 랭크 목록을 외부에서 전달해주는게 맞을까' 라는 생각이 들었는데요. 도메인 로직으로 볼 수도 있겠지만, 출력에 필요한 값이라 기준을 삼기가 애매한 것 같습니다. 이 부분은 어떻게 보셨는지 궁금합니다.

2023-11-21 10:27 UTC, inhyeokk commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val rankList = Rank.values().filter { it.reward > 0 }.sortedBy { it.reward }
더하여 테스트 코드를 작성하다가 생긴 궁금증인데요, shouldBe 의 expected 에는 로직이 들어가도 되나요? 아니면 직관적인 결과 값 (ex true, false or 어떤 값) 이 들어가는게 나을까요?

상황에 따라 다를 수 있겠지만 로직이 들어갔던 코드는 shouldBe 의 좌측 항에 들어간 코드와 같지만 변환 로직이 직접 들어갔던 것 같아서, 직관적인 값이 들어가는게 맞겠다는 생각이 들었습니다. 🤔 

지금 코드는 혼재 되어 있을거에요;;

2023-11-21 10:28 UTC, inhyeokk commented
안녕하세요 리뷰어님. 이번에도 날카로운 리뷰 감사합니다.

남겨주신 리뷰에 대해 수정 반영해두었으니 시간 되실 때 확인 부탁드릴게요. 🙇

2023-11-21 11:17 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Rank.kt
> +}
수정하고 코드를 보니 오류가 있네요. 다시 수정하고 테스트 코드 추가할게요.

2023-11-21 11:24 UTC, inhyeokk commented on src/main/kotlin/lotto/domain/model/Rank.kt
> +}
수정했습니다. 🙇 https://github.com/next-step/kotlin-lotto/pull/962/commits/b14a19347b04a609bfc65715b2b7ad313157141e

2023-11-22 09:46 UTC, Hyeon9mak approved these changes
안녕하세요 인혁님! 피드백 잘 반영해주셨습니다.
간단한 코멘트 남겼으니 확인해주세요.
다음 단계에서 뵙겠습니다!

2023-11-22 09:46 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val rankList = Rank.values().filterHasReward().sortedByReward()
> 도메인 로직으로 볼 수도 있겠지만, 출력에 필요한 값이라 기준을 삼기가 애매한 것 같습니다. 

공감합니다. 출력에 사용되는 값이라 도메인 로직으로 보는게 맞을지 애매하네요.
제 생각은 (인혁님도 잘 아시겠지만) 케이스 바이 케이스 같아요.
랭크 정렬 방식을 기획 및 정책으로 볼 것인지, 단순히 화면 표현으로 생각할 것인지에 따라 달라질 것 같습니다.

2023-11-22 09:46 UTC, Hyeon9mak commented on src/main/kotlin/lotto/LottoApplication.kt
> +            val rankList = Rank.values().filterHasReward().sortedByReward()
> shouldBe 의 expected 에는 로직이 들어가도 되나요? 아니면 직관적인 결과 값 (ex true, false or 어떤 값) 이 들어가는게 나을까요?

저는 아래 이유로 상수 값(직관적인 값)을 선호합니다.

- 로직이 잘못 되었을 경우 거짓 음성 반응이 나타난다.
- 상수 값이 테스트 코드를 읽을 때 훨씬 직관적이다.

2023-11-22 09:46 UTC, merged