Step3
next-step/kotlin-lotto pull request #967
Opened 2023-11-19 16:08 UTC by kakao-moses-lee

안녕하세요 리뷰어님! 잘 부탁드립니다!

## 이 PR의 유형
- step3

## 필수 리뷰어
@rok93

## 개요 (변경 내역 및 배경)
- 도메인 로직을 재정리 할겸, 처음부터 다시 시작 했습니다.

## 요청 사항 
- 패키지 분리가 이상적인지 
  - presentation 과 domain 의 분리 (`LottoResult` 와 같은 controller 에서 사용하는 객체의 적용이 적합한지?)
  - response / request (dto 객체의 사용이 자연스러운지)
  - view 는 도메인 객체 대신, 원시 타입만 알게 하려고 했는데, 적절한 방법인지

2023-11-20 15:03 UTC, Rok93 requested changes
상후님 3단계도 구현 잘해주셨습니다. 👍
몇몇 코멘트 남겨두었으니 확인해서 반영해주시면 감사하겠습니다. 🙏
잘 이해가 안되거나 어려운 부분이 있으면 언제든지 DM 주세요. 😃

2023-11-20 15:03 UTC, Rok93 commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +    private fun Iterable<RankFrequency>.sum() = RankFrequency.of(sumOf { it.value })
`RankFrequency`는 사실 용도를 잘 모르겠기 때문에 이 확장함수가 적절한지 아닌지 의견을 드리기가 조금 힘든 것 같습니다. 🙄
Rank에서  `일치하는 로또 숫자 수`로 쓰이고 LottoResults에서는 `당첨로또의 갯수`로 쓰이는 것 같아요. 🤔 

두 용도는 전혀 다른 느낌인데 같은 VO를 쓰고있는터라 이 VO 객체는 어떤 의도로 만드신건지가 궁금합니다. 👀

성질이 비슷(= 0이상의 정수)하고 어떤 개념의 갯수를 의미한다고해서 똑같은 VO로 볼 수 있을까요?

2023-11-20 15:03 UTC, Rok93 commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +// TODO-review : LottoResult 는 view <-> domain 사이의 결합을 낮추기 위해 controller 에서 사용하는 객체입니다.
가급적 주석보다는 PR의 코멘트로 남겨주시면 좋을 것 같아요. 🙏

그 외에도 코드의 설명을 위해서 주석을 붙이기보다는 코드 그 자체로 코드의 동작을 표현하도록 도전해보시면 좋을 것 같습니다. 🤗

2023-11-20 23:37 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/PurchaseResponse.kt
> +        fun of(tickets: LottoTickets) = run { PurchaseResponse(tickets.tickets.map { it.numbers }) }
가독성을 위해 scope function 을 사용해봤는데요. 

블록 형태로 명시하는게 더 좋을것 같습니다! 

반영 했습니다!

2023-11-21 00:05 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/PurchaseRequest.kt
> +            require(amount % LOTTO_PRICE == 0) { "구입 금액은 로또 가격의 배수여야 합니다." }
"dto로 View와 Domain 객체가 직접적으로 의존하는 것은 방지" 하기 위해서, 

"dto" 에서 "view" 의 입력값을 "domain" 객체에게 전달 전에 검증 하려고 했습니다! 

저의 의도가 알맞는 접근인지 궁금합니다!

2023-11-21 00:05 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/PurchaseRequest.kt
> +class PurchaseRequest private constructor(
좋습니다! 반영하겠습니다!

2023-11-21 00:13 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +// TODO-review : LottoResult 는 view <-> domain 사이의 결합을 낮추기 위해 controller 에서 사용하는 객체입니다.
넵! 다음 스탭에서 반영하겠습니다!

2023-11-21 00:16 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +    private fun Iterable<RankFrequency>.sum() = RankFrequency.of(sumOf { it.value })
정확한 지적입니다..!

 LottoResult 의 `당첨로또의 갯수` 가 명확한 의도이구요. 

Rank의 `일치하는 로또 숫자 수` 는 별도의 VO 를 선언하도록 하겠습니다!

2023-11-21 00:26 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/vo/RankFrequency.kt
> +value class RankFrequency private constructor(val value: Int) {
되도록 모든 원시 타입을 객체로 포장해서 코드를 더 명확하게 작성해보고 싶었습니다!

2023-11-21 00:29 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +class LottoTickets(val tickets: List<LottoNumber>) {
LottoTickets 의 원소로 있는 각 티켓의 고유성을 고민하다가 나온 결과물(?) 인데요. 

개별 로또 티켓은 그 고유성이 숫자에 있다고 생각해서 LottoNumber 를 LottoTickets 의 원소로 정했습니다! 

하지만 경록님  코멘트 읽어보니, 혼동될 여지가 다분하다고 생각되어 LottoTicket 이 더 좋은 네이밍인것 같습니다! 

반영 했습니다!

2023-11-21 00:33 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/Rank.kt
> +        }
enum class 를 다룰때 마다 실수하는 부분인것 같습니다! 😂

반영완료했습니다!

2023-11-21 00:36 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +    // TODO : 리펙토링, aggregateByRank 이 너무 비대하다. 역할 분배 필요
아! 그렇게 할 수 있겠군요!! 감사합니다!

2023-11-21 01:07 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/LottoTickets.kt
> +    // TODO : 리펙토링, aggregateByRank 이 너무 비대하다. 역할 분배 필요
https://github.com/next-step/kotlin-lotto/pull/967/commits/8f6bb8b8f3e50df877bb65ccc1d3f93db8aa6ff2

2023-11-21 08:39 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoController.kt
> +    var tickets: LottoTickets? = null
말씀 주신 내용처럼, evaluate 메서드의 파리미터로 주입받기 위해. 

tickets 의 상태를 controller 에서 purchase 후, responseDTO 에 저장하고, 

evaluate 에 reqeuestDTO 에 넣어서 최종 결과를 계산하도록 해서, 역할을 분리했습니다!

2023-11-21 08:40 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoController.kt
> +    var tickets: LottoTickets? = null
https://github.com/next-step/kotlin-lotto/pull/967/commits/e3b6a14799e6b0f55edf134d8cc2537f24627c74

2023-11-21 08:48 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +            listOf(matchedCount.value, winningMoney.value, frequency)
Rank, RankFrequency 는 모두 도메인을 담고 있는 값객체이기 때문에,

view 에서 참조되는것이 옳지 않다고 생각했습니다.

말씀 주신대로, List<List> 와 같이 의미를 알기 어려운 타입이 발생하니,

DTO 를 별도 선언해서 view 에 전달해야할것 같습니다!

2023-11-21 09:05 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/presentation/controller/LottoResult.kt
> +            listOf(matchedCount.value, winningMoney.value, frequency)
78ab58c9d7df54350c6494cadb6e47c491f5b571

2023-11-22 14:06 UTC, Rok93 approved these changes
상후님 피드백 반영 잘해주셨네요. 👍
이정도면 3단계는 충분한 것 같아서 이만 머지하도록하겠습니다. 
몇몇 코멘트 남겨두었으니 확인해서 다음 단계 진행하시면서 같이 반영해주세요. 🙏
잘 이해가 안되거나 어려운 부분이 있으면 언제든지 DM 주세요. 😃

2023-11-22 14:07 UTC, merged

2023-11-30 07:26 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/WinningLottoInfo.kt
> +class WinningLottoInfo private constructor(
좋습니다!

2023-11-30 08:23 UTC, kakao-moses-lee commented on src/main/kotlin/lotto/domain/WinningLottoInfo.kt
> +    private val bonusNumber: Int
적용해보겠습니다!