Step4 - 로또 (수동)
next-step/kotlin-lotto pull request #975
Opened 2023-11-21 03:44 UTC by HyoTaek-Jang

안녕하세요, 장효택입니다.

일이 많아서 다음 단계 진행이 늦었습니다.. 죄송합니다.

step4 로또(수동) 미션 리뷰 요청드립니다.

감사합니다!

2023-11-21 14:22 UTC, laco-dev requested changes
4단계 미션 잘 해주셨습니다.
지난 미션까지 해서 어느정도 구조가 잘 만들어진 만큼, 수정이 많지 않았던 것 같습니다.

큰 구조 변경은 없어 보이지만 개선해보면 좋을 만한 내용을 몇가지 남겨보았습니다.

2023-11-21 14:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        require(numbers.all { it.number in LOTTO_NUMBER_MIN..LOTTO_NUMBER_MAX }) { "로또 번호는 1~45 사이의 숫자만 가능합니다." }
numbers가 이미 LottoNumber 타입을 가지고 있으므로 이 검증 로직은 중복이네요!

2023-11-21 14:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/Lotto.kt
> +            return Lotto((LOTTO_NUMBER_MIN..LOTTO_NUMBER_MAX).toList().shuffled().take(LOTTO_NUMBER_SIZE).sorted().map(::LottoNumber))
코드가 한줄로 작성되어 가독성을 많이 떨어트리는 것 같아요.
라인별로 나눠보면 어떨까요?

2023-11-21 14:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +class LottoCount(val autoLottoCount: Int, val manualLottoCount: Int)
조금 ? 더 로또 구매라는 도메인으로 접근 해본다면 로또 주문서(LottoOrder) 같은 네이밍도 괜찮아 보이네요

2023-11-21 14:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +        return manualLottoList + autoLottoList
LottoFactory가 count를 계산하고 로또를 구매하는 것까지 한다면 여러개의 일을 한다고도 볼 수 있지 않을까요?

2023-11-21 14:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun match(lottoList: List<LottoNumber>): Pair<Int, Boolean> {
match() 라는 메소드가 반환하는 `Pair<Int, Boolean>` 타입이 무엇인지 예측이 될까요?

저도 오랜만에 봤지만 실제 코드가 어떻게 동작하는지를 완벽히 이해해야만 반환 타입을 알 수 있을 것 같아요.
만약 승부를 벌이는 것이라면 명확하게 LottoPrize를 반환하도록 할 수도 있지 않을까요?

2023-11-22 15:11 UTC, HyoTaek-Jang commented on src/main/kotlin/lotto/domain/Lotto.kt
> +        require(numbers.all { it.number in LOTTO_NUMBER_MIN..LOTTO_NUMBER_MAX }) { "로또 번호는 1~45 사이의 숫자만 가능합니다." }
아 그러네요 제거하겠습니다!

2023-11-22 15:11 UTC, HyoTaek-Jang commented on src/main/kotlin/lotto/domain/LottoCount.kt
> +class LottoCount(val autoLottoCount: Int, val manualLottoCount: Int)
넵 동의합니다 수정하겠습니다~

2023-11-22 15:16 UTC, HyoTaek-Jang commented on src/main/kotlin/lotto/domain/WinningLotto.kt
> +    fun match(lottoList: List<LottoNumber>): Pair<Int, Boolean> {
저도 오랜만에 보니까 이해가 어렵네요ㅎ.ㅎ....
명확하게 네이밍이 된 객체를 보내는게 더 적합하다고 동의합니닷!

2023-11-22 15:37 UTC, HyoTaek-Jang commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +        return manualLottoList + autoLottoList
이 부분은 조금 어렵게 다가오네요.. `calculateLottoCount`기능을 위해 또 다른 도메인을 만들기엔 너무 도메인의 개수가 많다고 느껴집니다.. 어떤 식으로 해결하면 좋을까요?

2023-11-23 00:22 UTC, laco-dev requested changes
피드백 반영 잘 해주셨습니다.

질문 주신 내용은 답변을 남겨두었습니다.
간단하지만 개선해보면 좋을 내용이 있어서 같이 적어두었어요! 💪🏻 

그 외에 추가로 수정할 부분이 없다면 반영 후 바로 리뷰요청 주시면 되겠습니다.

2023-11-23 00:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +        return manualLottoList + autoLottoList
그렇군요, 제가 어색하다고 느낀 점은 굳이 함수를 두개로 만들 필요가 있었을까? 인데요!

로또 팩토리에게 우리가 요청하는 협력은 아래와 같습니다.
"내가 이만큼의 돈과 로또 번호들을 줄태니, 로또를 만들어 줘"
```kotlin
fun buyLotto(amount: Int, lottoNumbers: List<LottoNumbers>)
```
다만 이렇게 되면 LottoOrder 자체가 불필요하게 됩니다. 조금 다르게 바라본다면
"여기 로또 주문서를 줄태니 로또를 만들어 줘"

```kotlin
class LottoOrder(val autoCount: Int, val manualLottoNumbers: List<LottoNumbers>)
fun buyLotto(order: LottoOrder) { ... }
```
이 경우, 그러면 로또 주문서는 누가 발급하는 것이지?
현실세계에 비유를 해본다면 로또 판매원에게 돈과 번호들을 주고 주문서를 받아올 수도 있습니다.
`돈과 번호들 -> 로또 판매원 -> 로또 주문서 -> 로또 기계 -> 로또 발급`

---

이야기가 길어졌네요.
지금 단계에서는 꼭 이렇게 까지 협력을 나눌 필요는 없다고 생각해요. 오버엔지니어링이 될 수 있으니까요

그렇기에 단순하게 LottoOrder를 계산하는 역할을 LottoOrder 스스로 하도록만 바꿔봐도 좋을 것 같습니다.

```kotlin
LottoOrder.create(price)
```

2023-11-23 00:22 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
작성된 것 처럼 로또 번호는 1부터 45까지의 숫자만을 가지고 있습니다.

그렇다면 같은 로또 번호에 대해서 항상 인스턴스를 만들 필요가 없을 수도 있는데요.
*우리가 Integer(1)을 만들때 같은 것으로 취급하는 것 처럼

캐시등의 방법을 이용해서 로또 번호가 재사용 될 수 있도록 만들어 보면 어떨까요?

2023-11-24 05:56 UTC, HyoTaek-Jang commented on src/main/kotlin/lotto/domain/LottoFactory.kt
> +        return manualLottoList + autoLottoList
맞네요.. 현실세계를 대입하니 훨씬 필요한 도메인의 분리가 명확하게 보입니다.

코멘트 주신대로 우선 LottoOrder가 스스로 계산할 수 있도록 수정했습니다.

2023-11-25 13:49 UTC, laco-dev approved these changes
좋습니다, 여러가지 어려운 요구사항을 드렸던 것 같은데, 잘 마무리 해 주신 것 같습니다.

로또 미션 이후에서도 요구사항은 동일하기 때문에 얻어가신 경험들을 이용해 미션 마지막까지 응원하겠습니다.

2023-11-25 13:49 UTC, laco-dev commented on src/main/kotlin/lotto/domain/LottoOrder.kt
> +        private set
Delegate 는 어떤 목적으로 사용되었는지 모르겠군요!
학습하면서 사용하신 것 같지만, 저도 평소에 사용을 잘 안해서 이부분은 조금 모르겠군요

대신, lazy를 이용한 초기화 방법을 권장하는 편입니다
```kotlin
val autoLottoCount by lazy { ... }
```

2023-11-25 13:49 UTC, merged