[Step4] : 로또(수동) && step3 리뷰 반영
next-step/kotlin-lotto pull request #989
Opened 2023-11-26 00:57 UTC by yoonnyeong

안녕하세요 리뷰어님!
step3 로또(2등)에서 주신 커멘트 반영과 로또(수동) 요구사항을 구현했습니다!
로또(수동)을 구현하면서 기존에 Money로 작성했던 클래스를 Buy 클래스로 수정했습니다!
이번 리뷰도 잘 부탁드립니다! 🫡

2023-11-26 14:54 UTC, catsbi requested changes
윤녕님 어느새 마지막 4단계 이군요!

몇 가지 피드백 남겨드렸으니 확인 후 리뷰 요청 해주세요 !

2023-11-26 14:54 UTC, catsbi commented on src/main/kotlin/lotto/LottoMain.kt
> +    val resultMap = lottos.groupBy { winningLotto.calculatePrize(it) }
현재 service layer와 controller layer가 섞여있는것 같은데 어떻게 생각하시나요?

2023-11-26 14:54 UTC, catsbi commented on src/main/kotlin/lotto/domain/Buy.kt
> +class Buy(val amount: Int, var manualCount: Int) {
Buy는 행위로 보통 클래스 네이밍 컨벤션인 명사로 지어라 라는 지침과는 좀 달라지는 것 같네요 🤔

2023-11-26 14:54 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +            return CACHED_NUMBER[num - 1]
만약 캐싱을 할 때 List가 아닌 Map으로 만들어서 key를 LottoNumber의 value로 만든다면 -1을 할 필요도 없으질 것 같아요 ㅎㅎ

2023-11-26 14:54 UTC, catsbi commented on src/main/kotlin/lotto/domain/LottoPrize.kt
> +    THIRD(1_500_000, { count, bonus -> (count == 5 && bonus == false) }, "5개 일치"),
람다식 활용 👍

2023-11-26 14:54 UTC, catsbi commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getManaulLottos(buy: Buy): List<Lotto> {
UI Layer의 역할은 어디까지일까요?
UI Layer는 테스트 대상이 아니죠. 그런데 UI Layer에 비즈니스로직이 있다면 이는 테스트 대상일까요 아닐까요?

2023-11-26 15:50 UTC, yoonnyeong commented on src/main/kotlin/lotto/domain/Buy.kt
> +class Buy(val amount: Int, var manualCount: Int) {
그러네요..! 원래 Money로 네이밍한게 낫겠습니다! 다시 변경할게요!

2023-11-26 16:29 UTC, yoonnyeong commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +            return CACHED_NUMBER[num - 1]
Map<Int, LottoNumber>로 변경해보겠습니다~

2023-11-26 17:41 UTC, yoonnyeong commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getManaulLottos(buy: Buy): List<Lotto> {
리뷰어님~! 요 부분은 어떤식으로 개선할 수 있을지 좀 고민이 되어서요..!
getManaulLottos는  수동으로 로또를 입력하면  해당 번호를 가지고 리스트를 만들어주는 역할인데 요것도 비즈니스로직에 해당한다고 봐야할까요??

2023-11-26 17:44 UTC, yoonnyeong commented on src/main/kotlin/lotto/LottoMain.kt
> +    val resultMap = lottos.groupBy { winningLotto.calculatePrize(it) }
controller, service 레이어를 추가해서 나름 분리해보았는데..  분리하고 나니 service를 굳이 새로 만들 필요는 없었나 싶기도하고 헷갈리네요! 보시고 의견주시면 감사하겠습니당😄

2023-11-27 09:57 UTC, catsbi approved these changes
윤녕님 피드백 반영 잘 해주셨어요 👍 
계속해서 많은 피드백을 드린게 스트레스가 되진 않으셨을지 걱정이 듭니다만, 포기하지 않고 꾸준히 반영 빠르게 해주셔서 저도 더 열심히 피드백 드렸던 것 같아요 👏

컨트롤러 구조가 좀 고민해보면 좋을 것 같아 피드백 남긴게 있으니 고민해보시면 좋을 것 같아요 ㅎㅎ
하지만 크게 크리티컬한 부분은 없어서 로또 미션은 여기서 마무리하도록 하겠습니다. 미션 진행하시느라 고생하셨고, 다음 미션도 화이팅 하시길 발바니다 👍

2023-11-27 09:57 UTC, catsbi commented on src/main/kotlin/lotto/LottoController.kt
> +    private val purchaseAmount: Money = buyLotto()
음.......생성자 호출시 buyLotto() 함수를 실행시키면서 구매금액을 인스턴스 변수로 할당하는건 문제의 여지가 있어보입니다. 
1. 생성자 호출시 필드 할당을  위해 UI Layer에 의존하는 부분이 있습니다. 
2. 컨트롤러 영역에 인스턴스 변수가 선언되어 있네요. Domain Layer를 제외하고는 별도의 상태를 가지는걸 지양해주세요.

2023-11-27 09:57 UTC, catsbi commented on src/main/kotlin/lotto/domain/Money.kt
> +class Money(val amount: Int, var manualCount: Int) {
돈이라는 정보를 책임지는 일급객체인 Money인데 수동 로또 갯수까지 같이 포함하고 있어요. 적절할까요?!

지금 request/response 객체를 고려해보면 좋을 것 같아요! 
로또를 구매하기 위한 요청정보들이 필요한데 이 요청정보들을 정리해보면
- 돈 (Money)
- 구입하고자 하는 수동 로또 갯수 (Int)
- 구입하고자 하는 수동 로또 번호 목록 (List<Set<Int>>)

그럼 굳이 돈 객체에 정보를 추가할게 아니라 LottoOrderRequest같은 dto를 만들어서 서비스 계층에 전달할 수 있지 않을까요?

2023-11-27 09:57 UTC, merged

2023-11-27 10:13 UTC, yoonnyeong commented
리뷰어님~! 로또리뷰 기간동안 꼼꼼히 봐주셔서 감사합니다. 리뷰어님두 고생하셨습니다! 잘봐주신덕분에 저도 미션을 통해 배워가는 점도 많았던 것 같아요!! 😄 앞으로도 홧팅입니다!!